### ISSUE TITLE
Error "Not a directory"

### ISSUE THREAD

**Issue by kaoz3000** [astrada/google-drive-ocamlfuse#107]
Hello,
maybe this is not a google-drive-ocamlfuse issue but I have a problem.
I mount the google drive with `mount` and I get this result:
`drwxrwxr-x  2 www-data www-data   4096 Jan  3 10:25 google-drive`
with root I have no problems with this directory,
but I can not access this with user `www-data`, and therefor can not access this directory with owncloud for example:
```
root@host:/var/www/# su www-data
sh-4.2$ cd /var/www/google-drive
sh: cd: /var/www/google-drive: Not a directory
```
`www-data` is in the group `fuse`

**Comment by astrada** [comment]
Try using `-o allow_other`, e.g.:

    $ google-drive-ocamlfuse -o allow_other /var/www/google-drive

**Comment by kaoz3000** [comment]
Hi astrada,
thank you again!
Now it works!
