### ISSUE TITLE
Can't Mount My Gooogle Drive

### ISSUE THREAD

**Issue by JaysonWonder** [astrada/google-drive-ocamlfuse#108]
I am getting this error:
/usr/bin/gdfuse: line 2: google-drive-ocamlfuse: command not found

I was trying to get mount automatically on boot. Why is this happening? When I run 
google-drive-ocamlfuse ~/googledrive
things work fine and google drive mounts.

To automount on boot I was using an executable bash scritp file in /usr/bin/gdfuse with the following:
#!/bin/bash
google-drive-ocamlfuse -lable $1 $*
exit 0

And an /etc/fstab entry with this:
#Google Drive
gdfuse#default  /mnt/gdrive     fuse    allow_other     0       0

When I try to mount using"
mount /mnt/gdrive
As mentioned above, I get this error and can't seem to figure out why:
/usr/bin/gdfuse: line 2: google-drive-ocamlfuse: command not found

Any thought as to why this could be happening?

Thanks,

**Comment by PeterDaveHello** [comment]
Try to use `type google-drive-ocamlfuse` to get the full path of it, and use it to replace `google-drive-ocamlfuse` in line 2.

**Comment by JaysonWonder** [comment]
thanks this works!

**Comment by PeterDaveHello** [comment]
There is not a problem of this project, but a path issue of your shell script, you should prepare the search path for it, or you should give the command a full path.

**Comment by JaysonWonder** [comment]
I added the path to my shell. Do you think there was an error with this?
This is what I did:

PATH= $PATH:$HOME/.opam/system/bin export PATH

Is it wrong?

**Comment by PeterDaveHello** [comment]
I think there should not be a space after assign symbol.

**Comment by JaysonWonder** [comment]
No. That was just a typo on my post. I went and verified that it was
correct. I have also confirmed that the path is being set by my .bashrc
correctly so it is another problem.

Still works with the full path to ocamlfuse specified. No big issue just
wondered if this was a bug or user problem. Can't seem to find anything
else wrong.

Also do I need to still have a googledrive directory in my home? Since one
is created now in /mnt?

Thanks

**Comment by astrada** [comment]
PATH=$PATH:$HOME/.opam/system/bin export PATH

Try expanding `$HOME`. If the user running `/usr/bin/gdfuse` is not your user, `$HOME` will not match with your home and the executable will not be found.

**Comment by JaysonWonder** [comment]
Well in actual fact I am running everything as root. Unless I specify  the
full path it won't work. Any other ideas?

**Comment by astrada** [comment]
I think you should modify `/usr/bin/gdfuse` this way:

    #!/bin/bash
    /home/[... your user name ...]/.opam/system/bin/google-drive-ocamlfuse -lable $1 $*
    exit 0

(be sure to replace `[... your user name ...]` with your actual user name).

**Comment by astrada** [comment]
As an alternative, check out this page: https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting

**Comment by cicindel** [comment]
Interestingly if I just run the following line from terminal:
`google-drive-ocamlfuse ~/Gdrive/`
it works ok, but if I put it into autostart apps (with Ubuntu GUI), it won't start. I'll try the full path and report here if it worked after reboot later today (I'm at work).

**Comment by jagrutiboda** [comment]
/bin/bash: google-drive-ocamlfuse: command not found error occur so please solve this error
