### ISSUE TITLE
ods directory listing error

### ISSUE THREAD

**Issue by angrygeek** [astrada/google-drive-ocamlfuse#110]
ods sheets created with the new Google Drive will not show in a directory listing. 

[140.364627] TID=0: getattr /RPGs/RuneQuest Books.ods
Getting metadata from context...valid
Loading resource /RPGs/RuneQuest Books.ods (trashed=false) from db...found
Exception:Option.No_value

I copied an ods made with the older drive and moved it into the directory. Used the web interface to move all the data to the copy. It will now show up in a directory listing.

**Comment by astrada** [comment]
Did you try clearing the cache (with `google-drive-ocamlfuse -cc`)?

**Comment by astrada** [comment]
I think there is some issues with new spreadsheets. It looks like the same problem is experienced by other users:
http://stackoverflow.com/questions/28028031/google-drive-web-api-does-not-return-open-office-export-link-for-new-spreadsheet
https://productforums.google.com/forum/#!topic/docs/S6IkdnuH91E%5B1-25-false%5D
I will try to see if I can download open office formats document anymore.

**Comment by astrada** [comment]
I've opened [issue 3713](https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3713) on Google APIs bug tracker.

**Comment by astrada** [comment]
I've uploaded version 0.5.13 with a workaround that should re-enable .ods download even for new Sheets.
