### ISSUE TITLE
Access photos from Google+ photos

### ISSUE THREAD

**Issue by blueyed** [astrada/google-drive-ocamlfuse#111]
Would it be possible and in the scope of this tool to make media files from Google+ accessible?

(during a quick research I've found http://googlesystem.blogspot.de/2013/08/view-google-drive-photos-in-google.html, which explains how to add photos from Drive to Plus).

**Comment by astrada** [comment]
No, sorry. There is no way to access Google+ content using Google Drive API. And even using Google+ API you won't get access to your private content (just to your published public posts, AFAIK).

**Comment by blueyed** [comment]
Too bad.

Thanks for your support and this tool nevertheless!

**Comment by astrada** [comment]
Now it is possible to [access and organize](https://support.google.com/drive/answer/3259546?p=create_photos_folder&hl=en&rd=1) photos via Drive. If you add photos to your Drive, you will be able to access them via google-drive-ocamlfuse.
