### ISSUE TITLE
cache only retains one file at a time?

### ISSUE THREAD

**Issue by agfung** [astrada/google-drive-ocamlfuse#112]
I take a look at the `~/.gdfuse/default/cache` directory sometimes, and I notice I only ever have 3 files (one of them being `cache.db`).  One of the file is always zero bytes, and the other appears to be whatever file I last modified.

I would have expected the `cache/` directory to contain a lot more files (all the recent files I modified).  I have the `max_cache_size_mb` set quite large, and `stream_large_files` off.

Am I doing something wrong?

**Comment by astrada** [comment]
If you enable verbose logging (with `-debug`), you should see lines like this in your `gdfuse.log`:

    Downloading resource (id=17)...Updating cache size (200) in db...done

Cache is updated downloading resources, writing files, or when a change is detected server side. Note that Google Docs are not cached.
