### ISSUE TITLE
cache eats ALL disk space, during large file upload!

### ISSUE THREAD

**Issue by psmelion** [astrada/google-drive-ocamlfuse#113]
Thanks for the GREAT software! Those Windows commerical-ware all suck!

But, this is simply not working!

Cache eats ALL disk space!

It works for a day then it won't work. After checking this and that, finally found that the cache ate all disk space!

I'm running Ubuntu 14 in VirtualBox. Host is Windows 7. Using the latest official 0.5.12. Since it's a VM, I only made a 8G VDI, as google-drive-ocamlfuse is the only thing I run on the VM, for sharing Google Drive via Samba to the Windows host.

Once I start upload a big file (video clips at several GB and bigger), I watch the cache slowly eat all the disk space. I've a 500Mbps up/down link and up/down to Google Drive is at around 10MB/s in Chrome. After a few minutes, the Ubuntu VM will be at 0% space left and the connection to Google Drive will drop.

On next startup of ocamlfuse, it will complain can not access to the config file (due to no space left!). And I need to setup authorization all over again!

I checked that there is a  stream_large_files=true option but I guess it's for download/playback use. Already had that option at "true" but didn't help my upload problem.

Or maybe I should just setup a 100G VDI for the cache to use whatever it wants?

**Comment by astrada** [comment]
> I checked that there is a stream_large_files=true option but I guess it's for download/playback use. 
> Already had that option at "true" but didn't help my upload problem.

Yes. It's just for download.

> Or maybe I should just setup a 100G VDI for the cache to use whatever it wants?

Unfortunately, Google Drive API doesn't allow to upload files in chunks. So I have to cache the whole file before uploading it. And there is no workaround. So the only option is to have a virtual disk big enough.

**Comment by ddurdle** [comment]
"Unfortunately, Google Drive API doesn't allow to upload files in chunks. So I have to cache the whole file before uploading it. And there is no workaround. So the only option is to have a virtual disk big enough."

News to me.  Google Drive supported chunk transfers (as long as chunks are in multiples of 512 bytes) since Google Docs API.

https://developers.google.com/drive/web/manage-uploads

**Comment by astrada** [comment]
Yes, you are right, and I'm using, in fact, resumable uploads. The problem is that you cannot make partial updates to the byte stream. For example, if I modify only few bytes of a file, I have to re-upload the whole file (even in chunks). I cannot upload just the affected chunk.
