### ISSUE TITLE
google-drive-ocamlfuse command not found during auth in headless mode

### ISSUE THREAD

**Issue by Bertieio** [astrada/google-drive-ocamlfuse#114]
opam says its installed and Ive tried removing it and reinstalling it using opam, Ive tried type google-drive-ocamlfuse and still no luck. 

 A reboot fixed this

**Comment by astrada** [comment]
Do you have these lines in `~/.profile`?

    # OPAM configuration
    . $HOME/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

What's the content of file `~/.opam/opam-init/variables.sh`?

**Comment by Bertieio** [comment]
On ~/.profile im getting file not found 

and the contents of ~/.opam/opam-init/variables.sh is:

CAML_LD_LIBRARY_PATH=/home/Bertie/.opam/4.01.0/lib/stublibs; export CAML_LD_LIBRARY_PATH;
MANPATH=$MANPATH:/home/Bertie/.opam/4.01.0/man; export MANPATH;
MAKELEVEL=; export MAKELEVEL;
MAKEFLAGS=; export MAKEFLAGS;
PERL5LIB=/home/Bertie/.opam/4.01.0/lib/perl5:$PERL5LIB; export PERL5LIB;
OCAML_TOPLEVEL_PATH=/home/Bertie/.opam/4.01.0/lib/toplevel; export OCAML_TOPLEVEL_PATH;
PATH=/home/Bertie/.opam/4.01.0/bin:$PATH; export PATH;

**Comment by astrada** [comment]
Then OPAM will build your executables in `/home/Bertie/.opam/4.01.0/bin`. Check that, in the folder, you find `google-drive-ocamlfuse` executable. Then check that your `$PATH` environment variable contains OPAM bin dir (running `echo $PATH`).

**Comment by Bertieio** [comment]
All of them are in the right places and the $PATH files are correct

**Comment by astrada** [comment]
What's the output of command:

    $ which google-drive-ocamlfuse

**Comment by Bertieio** [comment]
~/.opam/4.01.0/bin/google-drive-ocamlfuse

**Comment by astrada** [comment]
And when you run:

    $ google-drive-ocamlfuse

gives you "command not found"?

**Comment by Bertieio** [comment]
No thats fixed but now its not syncing. Sorry I edited my first post to say a reboot fixed it.

**Comment by astrada** [comment]
Sorry, but what do you mean when you say that it's not syncing?

**Comment by Bertieio** [comment]
I run google-drive-ocamlfuse and nothing happens, It worked originally after a restart but I had to restart again and I stopped being able to access gdrive

**Comment by astrada** [comment]
Have you tried running the command with `-debug` command line option, and then check the log files?
