### ISSUE TITLE
cache keeps growing

### ISSUE THREAD

**Issue by Rick7C2** [astrada/google-drive-ocamlfuse#115]
I have max cache set to 512MB.

I have a VPS with only 30GB SSD drive that I use to transfer files to GDrive.

Since I have small disk space I need to keep the cache as low as possible at all times.

If I upload a 1GB file the cache fills up to 1GB that's fine but once the upload is completed that file is not deleted from cache even tho it keeps it above the max 512MB.

am I doing something wrong?

**Comment by Rick7C2** [comment]
I'm dumb lol.

I had .gdfuse/default/config set at 512MB But I mounted with -label I had the wrong config file edited.

**Comment by astrada** [comment]
OK, no problem.

**Comment by woftor** [comment]
I cannot find the right config file and my cache is growing HUGE overtime... The one in .gdfuse/default/config is set to 512 MB, but my cache was 17 GB after 2 months. Is it somewhere in /etc?

**Comment by astrada** [comment]
> I cannot find the right config file and my cache is growing HUGE overtime... The one in .gdfuse/default/config is set to 512 MB, but my cache was 17 GB after 2 months. Is it somewhere in /etc?

No. If you have just one account, `.gdfuse/default/config` is the only config file used. If you enable logging with `-debug` you should see messages like

    Updating cache size (...) in db...

when cache is evicted. Unless you have very big files (multi GB), cache should not grow too much. In that scenario (when you have very big files) the only way to keep a small cache is to activate file streaming in config (e.g.):

    stream_large_files=true
    large_file_threshold_mb=16

**Comment by woftor** [comment]
I will try that, because I have indeed large files (3GB+).
Is there any drawback in streaming?

Thank you for the response!

**Comment by astrada** [comment]
> Is there any drawback in streaming?

No, unless these files are modified, because when you modify a file it has to be cached anyway. Streaming is mostly useful for media files.

**Comment by woftor** [comment]
Do you mean 'unless the files modified -during- the copy process?' Trying to fully onderstand what is happening. Again thanks, really elaborating.

**Comment by astrada** [comment]
> Do you mean 'unless the files modified -during- the copy process?'

No, any time a file is modified, it has to be downloaded to the cache and then fully uploaded, because Google Drive API does not support partial updates (i.e. even if you modify a single byte of a file, that file must be re-uploaded in its entirety).
