### ISSUE TITLE
Automounting via rc.local

### ISSUE THREAD

**Issue by DennisLfromGA** [astrada/google-drive-ocamlfuse#116]
Would it be possible to automount using the `/etc/rc.local` file instead of adding an `/etc/fstab` entry?

Maybe something as simple as the `gdfuse` contents would work:

  `su $USERNAME -l -c "google-drive-ocamlfuse -label $1 $*"`

substituting `$USERNAME` with the desired `username` and `$1` with either `default` or another label.

-DennisL

P.S. This app works great! I've got it setup as a Bookmark in my file manager so it's readily available.

**Comment by astrada** [comment]
I think it would work. Googling "fuse rc.local" shows that similar scripts are used to mount sshfs at boot, so there should be no problem.
