### ISSUE TITLE
Parallel operations?

### ISSUE THREAD

**Issue by m94mni** [astrada/google-drive-ocamlfuse#117]
I'm trying to rsync a huge drive account (100Gb of various small and larger file), and find myself wanting to download multiple files in parallel, as a single process will pause for several seconds between files.

But after some experimentation I get the definite impression that operations are forced to be serial. Any ideas on how to make requests in parallel?

**Comment by astrada** [comment]
Using `-m` command line option activates multi-threading. Unfortunately the FUSE library I'm using is not very stable with that option turned on.

**Comment by m94mni** [comment]
Thanks! Somewhat hidden option, but perhaps for good reason...

Tried it together with rcoup/rsync_parallel.sh and got a flood of errors and then transport disconnected. 

Lots of rsync lines like

Bilder/2008-08-12--2008-12-06/IMG_3007.JPG
rsync: read errors mapping "/home/mikaeln/gdrive/Bilder/2008-08-12--2008-12-06/IMG_2995.JPG": Device or resource busy (16)

It would be a great option to have stable!

**Comment by astrada** [comment]
Pre-release [0.6.0](https://github.com/astrada/google-drive-ocamlfuse/releases/tag/v0.6.0) should address at least part of this issue. If you are on Ubuntu you can add the [beta PPA](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta), to check out this version.

**Comment by astrada** [comment]
Closing this issue as the new version is out of beta.
