### ISSUE TITLE
-cc option fails with "Error: int_of_string"

### ISSUE THREAD

**Issue by pbx** [astrada/google-drive-ocamlfuse#120]
Trying to force regeneration of exported files after changing `presentation_format` in my config, I ran `google-drive-ocamlfuse -cc`. It failed with *Error: int_of_string*.  I unmounted the drive and passed the flag when I remounted. Same error.

Ubuntu 14.04, google-drive-ocamlfuse v0.5.14

**Comment by astrada** [comment]
Could you send me your config file to alessandro (dot) strada (at) gmail (dot) com, please? It looks like an error in the config file parser (it's the only place where I use `int_of_string`).

**Comment by pbx** [comment]
Thanks for the quick reply. Here's my config: http://dpaste.com/3B4BDSD

**Comment by astrada** [comment]
Should be fixed in v0.5.15
