### ISSUE TITLE
Shared files are moved to trash when changed locally

### ISSUE THREAD

**Issue by fluffman86** [astrada/google-drive-ocamlfuse#122]
I share a KeePass 2 (*.kdbx) database with my wife since we have some shared accounts. We have been using Google Drive to sync the database to our Android phones using the Keepass2Android app and Grive-Tools on Ubuntu, until that recently stopped working with the Drive API changes.

Since then, I've noticed that things aren't syncing correctly on our phones when I make a change on Ubuntu and expect it to sync up via google-drive-ocamlfuse. Tonight I realized that the issue relates to the fact that when I save the Keepass2 database, the old kdbx file is moved to the trash in Google Drive. 

This wouldn't be an issue, but it means that every time I make a change, I have to go back into Google Drive and share the file with my wife again. If it were just me, it would only mean that I have to re-locate the file and re-open the database in Keepass2Android. The big problem comes in with shared files. 

I imagine this will also be an issue other shared files, and whether or not keep_duplicates is set to true or false.

**Comment by astrada** [comment]
I checked the source code of KeePass 2 and I think that what you have experienced is the default behavior when saving the kdbx file. The DB is saved to a new temporary file, then renamed to match your original filename. There should be an option to turn off this behavior: in Tools -> Options -> Advanced there is a checkbox labeled `Use file transactions for writing databases`. You should try unchecking this option.

**Comment by fluffman86** [comment]
Thanks for the help! Changing that option worked. I never changed it when switching from grive to ocamlfuse. Weird, but glad it's working now.
