### ISSUE TITLE
setting created time

### ISSUE THREAD

**Issue by aselvan** [astrada/google-drive-ocamlfuse#124]
When google-drive-ocamlfuse driver uploads a file, how does it set the create time in Google Drive? I have attached a screenshot showing a file modified time as 12/25/2012 (which is actually correct i.e. mtime value). However, the create time set as 5/24/2015 which is the day I uploaded (rsync'ed) this file.

This may be a problem in Google Drive API but wanted to know is there a way to set a create time?

![drive_filecreation_issue](https://cloud.githubusercontent.com/assets/4648662/8020735/e1552508-0c49-11e5-8106-76ed8027aa14.png)

**Comment by gogeccc** [comment]
The same happens when you upload a file using Google Drive web service.
I guess that's the reason why they have 'New' instead of 'Upload' button :-D

**Comment by astrada** [comment]
> This may be a problem in Google Drive API but wanted to know is there a way to set a create time?

I don't think it's possibile. I just did a test using [Google API Explorer](https://developers.google.com/apis-explorer/#p/drive/v2/).

This is the request, where I try to set the creation date:
 
    POST https://www.googleapis.com/drive/v2/files

    {
     "title": "test.txt",
     "createdDate": "2015-01-01T00:00:00.00Z"
    }

And this is the response, but the creation date was overwritten with the date of the request:

    200 OK
     
    {
     "kind": "drive#file",
     ...
     "title": "test.txt",
     "mimeType": "text/plain",
     ...
     "createdDate": "2015-06-07T11:51:56.124Z",
     "modifiedDate": "2015-06-07T11:51:55.846Z",
     "modifiedByMeDate": "2015-06-07T11:51:55.846Z",
     "lastViewedByMeDate": "2015-06-07T11:51:55.846Z",
     "markedViewedByMeDate": "1970-01-01T00:00:00.000Z",
     ...
    }

**Comment by aselvan** [comment]
Thanks @astrada 

As you confirmed, Drive API ignores the "createdDate". This makes all the files clumped into same date (uploaded date) which makes the timeline meaningless (in photos stream) as well as sorting and grouping of old pictures and movies in Drive!

I tried using the API *drives.files.patch* (PATCH verb) and found that it requires a boolean flag **"setModifiedDate=true"** as query parameter to update the modifiedDate field. I wonder if I can pass "setCreatedDate=true" on this call to force it to update the createdDate? Unfortunately, I could not try that since API explorer does not allow editing to add that query parameter.

Request:
```
PATCH https://www.googleapis.com/drive/v2/files/xxxxxxxxxxxxx?fields=originalFilename%2CmodifiedDate%2CcreatedDate&setModifiedDate=true&key={YOUR_API_KEY}
 
{
 "createdDate": "2012-12-25T11:51:56.124Z",
 "modifiedDate": "2012-12-25T11:51:56.124Z"
}
```
Response:
```
200 OK
 
- Show headers -
  
{
 "createdDate": "2015-05-25T01:08:42.361Z",
 "modifiedDate": "2012-12-25T11:51:56.124Z",
 "originalFilename": "IMG_2195.JPG"
}
```

**Comment by astrada** [comment]
No sorry, there is no parameter to set the creation date (https://developers.google.com/drive/v2/reference/files/update).

**Comment by aselvan** [comment]
Thank you for your help. Since this is not an issue with this driver since the problem is with Google Drive API. I am closing this issue.
