### ISSUE TITLE
File listings disappear/don't refresh

### ISSUE THREAD

**Issue by sciencepro** [astrada/google-drive-ocamlfuse#125]
I'm observing a strange behavior as follows: folders will lose their file index, and only be refreshed after running `ls` one or more times.  Applications that only scan directories once often will miss entire folders because they appear empty when they are in fact not.

I've increased the cache size and lowered the refresh time but it doesn't seem to have any impact.

It this a known behavior or is there something wrong with my configuration?

**Comment by astrada** [comment]
No, you should see all the files every time you run `ls`. Have you tried turning on debug log and then check if `~/.gdfuse/default/gdfuse.log` or `~/.gdfuse/default/curl.log` report any error?
