### ISSUE TITLE
Icons for Google Docs/Sheets/Slides etc.

### ISSUE THREAD

**Issue by jjordanthesailor** [astrada/google-drive-ocamlfuse#126]
Wow, I have been searching for this capability for months, thank you so much for building it.  

I believe the most powerful part of your program is the .desktop file generation for the Google Docs formats.  It is awesome that I can double click a Google Sheet in my file manager and Chrome opens with the spreadsheet ready to edit.  The fact that I am editing the file actually stored on Google's servers is even better, no worries about sync errors or other problems.

Because you are building a .desktop file for each document I believe you could add an icon that indicates the file type (basically simulate a mime type icon).  If you included an icon for Docs, Sheets, etc. in the ~/.gdfuse directory then you could add an icon=/home/username/.gdfuse/gdocs.png line to the .desktop file for each item as it is created (just noticed .desktop files refuse to follow the ~ might be better to install the icons to /usr/share/icons).  I would recommend the icons for the various programs but if you feel that might cause copyright problems, I'll gladly build you a set of similar icons with no copyright issues.

Maybe I'll try to build a bash script to implement this for my own use, looks like I can grep for /spreadsheets/ or /document/ and then append the corresponding Icon line to the .desktop file.

Thanks again for the great program!

Regards,
J. Jordan

**Comment by astrada** [comment]
I think I will add a configuration option per file-type (e.g. `spreadsheet_icon`) so that you can specify any icon you want: a system icon or a custom icon (that you can put in `~/.local/share/icons/`...). Hope that works for you.

**Comment by jjordanthesailor** [comment]
Sounds great!

**Comment by astrada** [comment]
Should be available in version 0.5.17. Remember to clear the cache after changing icons in `config` file.

**Comment by jjordanthesailor** [comment]
Wow, Thanks for the quick response.  I'm really lazy and don't have a
system handy with a build environment set up, how often do you usually
update the PPA?

Thanks again,
-j

**Comment by astrada** [comment]
I usually upload the .debs as I publish a new version. I think the PPA should already be updated.

**Comment by jjordanthesailor** [comment]
Yes, it is updated, I should have taken a look before I asked, sorry.

**Comment by astrada** [comment]
Don't worry. No need to apologize. :smile:

**Comment by jjordanthesailor** [comment]
5.17 Love it, beautiful, fantastic!  Got to spread the word on this awesome
software sent a tip to OMG Chrome to do an article on it.  Don't know if
they will.  I have Peppermint 5 on a couple of systems and just started
playing with Chromixium both of those projects should include
google-drive-ocamlfuse in their installations.   This was really all that
was missing to allow a Linux installation to do everything a ChromeBook can
and still have the power of Linux when you want or need it.

Grazie mille. Andare al piano di sotto per abbracciare il mio 1992 Alfa
Romeo Spider Veloce in tuo onore.  (Google translate, my 1 semester of
Italian is pretty much gone.)
-j

**Comment by astrada** [comment]
Thanks! I'm glad you find this project useful.
