### ISSUE TITLE
Allow mount-time options to specify gdfuse user

### ISSUE THREAD

**Issue by bendavis78** [astrada/google-drive-ocamlfuse#130]
Currently, I cannot mount using the mount command or fstab, because gdfuse expects to find the `.gdfuse` in /root. It would be ideal if I could specify a path to this in the options for `mount`.

**Comment by astrada** [comment]
I added mount option `gdfroot` to specify that path. You can use it on the command line with `-o` (e.g. `google-drive-ocamlfuse -o gdfroot=/path/to/dir`) or in `/etc/fstab`, e.g.:

    gdfuse#default  /mnt/gdrive     fuse uid=1000,gid=1000,gdfroot=/path/to/dir     0       0
