### ISSUE TITLE
google-drive-ocamlfuse + ubuntu problem

### ISSUE THREAD

**Issue by m3i58** [astrada/google-drive-ocamlfuse#131]
Hello,

I have installed and authorized google-drive-ocamlfuse to access Google Drive. So far so good. But doing "ls" in mounted directory gives:
> ls: cannot open directory .: Device or resource busy

Of course I tried to learn more from the logs, but there is not much to learn there.

google-drive-ocamlfuse -debug or -verbose goes just that far and stops:
> Starting application setup (label=default).
> Opening log file: /home/user/.gdfuse/default/gdfuse.log

gdfuse.log is empty, unless run without -debug, then it is:
> [0.000452] TID=0: Setting up default filesystem...
> [0.000507] TID=0: Loading configuration from /home/user/.gdfuse/default/config...done
> Saving configuration in /home/user/.gdfuse/default/config...done
> [0.001044] TID=0: Loading application state from /home/user/.gdfuse/default/state...done
> Current version: 0.5.17
> Setting up cache db...done
> Setting up CURL...done
> Refresh token already present.
> [0.003289] TID=0: Starting filesystem /home/user/drive/
> [0.008393] TID=0: init_filesystem
> [11.618456] TID=0: Exiting.
> CURL cleanup...done
> Clearing context...done

curl.log is empty in either case.

I'd very much appreciate help.

**Comment by astrada** [comment]
From the logs it looks like process was stopped after about 11 seconds. Did you stopped it with Ctrl+C? Or with fusermount? What's the state of your mount point? Try running `ls -l /home/user/drive`.

**Comment by m3i58** [comment]
Thank you for your answer. Now I let it run for over 120 minutes, but it still is refreshing database.

> 0.000175] TID=0: Setting up default filesystem...
> [0.000208] TID=0: Loading configuration from /home/user/.gdfuse/default/config...done
> Saving configuration in /home/user/.gdfuse/default/config...done
> [0.000452] TID=0: Loading application state from /home/user/.gdfuse/default/state...done
> Current version: 0.5.17
> Setting up cache db...done
> Setting up CURL...done
> Refresh token already present.
> [0.002733] TID=0: Starting filesystem /home/user/drive
> [0.006386] TID=0: init_filesystem
> [1117.753339] TID=0: getattr /
> Loading metadata from db...not found
> Refreshing metadata...
(still in progress)

Granted the Google Drive content is big (the content is less then 2TB). Still it takes a lot of time...

**Comment by astrada** [comment]
If you used `-debug`, you should find all the requests to Drive API in `curl.log`. If it's getting all the metadata the file should grow quite big. If it's empty there is another problem.

**Comment by m3i58** [comment]
Ahhh, Drive API was off :)
Maybe it woud be a good idea to put it into the guide for less experienced users like myself?

**Comment by astrada** [comment]
OK. I've updated the wiki.
