### ISSUE TITLE
Google-Drive-Ocamlfuse and file explorer on Xubuntu

### ISSUE THREAD

**Issue by Styxe** [astrada/google-drive-ocamlfuse#132]
Hello,
First, sorry for my English and thank you for your work.

I encounter a problem with google-drive-ocamlfuse, let me explain. (I'm on Xubuntu)

I set GDO (Google-Drive-Ocamlfuse) for it to start at boot, I was looking for how to turn the process to save my battery (use at school), wanting to put it out I noticed that my home directory was buggy as I have not revived GDO.
I tested without internet connection and I find the same problem. I can use my file explorer if GDO can not connect to my Gdrive. And the problem is that I almost never have access to the internet while traveling, at school and in the train.

My question is: do you have a solution that does not make GDO bugue my file explorer in these situations?

Thank you for your attention

**Comment by astrada** [comment]
I'm sorry but this application doesn't work offline. You should use another tool (e.g. https://github.com/rakyll/drive) to keep your files even when you are not online.

**Comment by Styxe** [comment]
I will try it, thank you for the reply and the software anyway.
Good luck for the future
