### ISSUE TITLE
Cache control issue

### ISSUE THREAD

**Issue by m3i58** [astrada/google-drive-ocamlfuse#133]
Hello,

I've tried to upload huge video files to GD. The cache grows to enormous sizes and it seems the config setting (16MB in my case) does not work. With this setting my cache size is 77MB at the moment.

I'd like the upload process (local file to Google Drive) wouldn't need big cache. Is there a way around it?

Is it possible to limit cache to the metadata and don't use it for files at all?

**Comment by astrada** [comment]
No, sorry. Google Drive API doesn't support uploading a chunk of a file. You have to fully upload it every time.

**Comment by m3i58** [comment]
Thank you for your reply.

But can't it be uploaded directly from the source file, without caching it?

**Comment by astrada** [comment]
No, FUSE works with file primitives, in this case: `write buffer` where buffer is 132KB long. The FUSE driver doesn't receive the original file, just some bytes of it, so It has to cache it all before uploading. If GDrive API supported uploading a chunk, I could upload just the buffer and I would not need to cache it.

**Comment by m3i58** [comment]
I very much appreciate your reply. Hopefully Google API will progress.
