### ISSUE TITLE
segmentation fault on mount

### ISSUE THREAD

**Issue by oleid** [astrada/google-drive-ocamlfuse#136]
Dear astrada,

I'm trying to run your app on ArchLinux and installed it and it's dependencies via AUR (user repository -- both, version 0.5.15 , which is available there and 0.5.18).

Authorization works fine, but on mounting the app crashes. I cleared the cache and tried to run the app via gdb:

    (gdb) ru -d -debug ~/mnt/google
    Starting program: /usr/bin/google-drive-ocamlfuse -d -debug ~/mnt/google
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    Starting application setup (label=default, base_dir=/home/oleid/.gdfuse).
    Opening log file: /home/oleid/.gdfuse/default/gdfuse.log
    FUSE library version: 2.9.4
    nullpath_ok: 0
    nopath: 0
    utime_omit_ok: 0
    unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
    INIT: 7.23
    flags=0x0003f7fb
    max_readahead=0x00020000
       INIT: 7.19
       flags=0x00000031
       max_readahead=0x00020000
       max_write=0x00020000
       max_background=0
       congestion_threshold=0
       unique: 1, success, outsize: 40
    unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 1492
       unique: 2, error: -38 (Function not implemented), outsize: 16
    unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 1492
    LOOKUP /.Trash
    getattr /.Trash
    [New Thread 0x7ffff46d5700 (LWP 2485)]
    [Thread 0x7ffff46d5700 (LWP 2485) exited]
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00000000005c3587 in caml_absf_mask ()
    (gdb) backtr
    #0  0x00000000005c3587 in caml_absf_mask ()
    Backtrace stopped: Cannot access memory at address 0xf4b160d0
    (gdb) 

This is curl.log:

    [0.023671] curl: info:   Trying 216.58.213.10...
    [0.047328] curl: info: Connected to www.googleapis.com (216.58.213.10) port 443 (#0)
    [0.048258] curl: info: ALPN, offering http/1.1
    [0.048537] curl: info: Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    [0.065566] curl: info: successfully set certificate verify locations:
    [0.065586] curl: info:   CAfile: /etc/ssl/certs/ca-certificates.crt
      CApath: none
    [0.065679] curl: info: TLSv1.2 (OUT), TLS header, Certificate Status (22):

And gdrive.log:

    [0.000262] TID=0: Setting up default filesystem...
    [0.000299] TID=0: Loading configuration from /home/oleid/.gdfuse/default/config...done
    Saving configuration in /home/oleid/.gdfuse/default/config...done
    [0.000591] TID=0: Loading application state from /home/oleid/.gdfuse/default/state...done
    Current version: 0.5.18
    Setting up cache db...done
    Setting up CURL...done
    Refresh token already present.
    [0.004170] TID=0: Starting filesystem /home/oleid/mnt/google
    [0.008530] TID=0: init_filesystem
    [0.010788] TID=0: getattr /.Trash
    Loading metadata from db...not found
    Refreshing metadata...

Any suggestion on where to start digging? I've never did any ocaml programming, thus I'm not sure how to get meaningful backtraces.

By the way: it's 
 * libgcrypt-1.6.4-1
 * libcurl 7.44.0-1

Best,

Olaf

**Comment by astrada** [comment]
Have you tried setting `curl_debug_off` to `true` in config?

**Comment by oleid** [comment]
I'm not at the same machine at the moment,  but I installed google-drive-ocamlfuse there, too. This time, it's a Gentoo based system. There, I have the same problem, but the program dies with SIGILL instead SIGSEGV.

At least on this machine, setting curl_debug_off to true helps!

**Comment by oleid** [comment]
Confirmed, `curl_debug_off = true` helps on ArchLinux, too.

**Comment by astrada** [comment]
OK, thanks for your feedback.
