### ISSUE TITLE
Open Google Docs online

### ISSUE THREAD

**Issue by sebast331** [astrada/google-drive-ocamlfuse#137]
Since Google Documents are read only locally, would it be posssible to add another format (web) that would create a link file so when I open a Google Document file, it opens the browser with that wile opened in Google Drive?

**Comment by astrada** [comment]
You should use `desktop` format for Google Documents you want to access via web. Then you can click on the shortcut from the file explorer to open the browser pointing to your doc.

**Comment by sebast331** [comment]
That works half way. Under Gnome, it would require the file to have a .desktop extension to work properly. Or is it working for everyone else but me?

**Comment by astrada** [comment]
OK, thanks! I'm adding it to the wiki.
