### ISSUE TITLE
Selective files offline

### ISSUE THREAD

**Issue by Immortalin** [astrada/google-drive-ocamlfuse#139]
Is it possible to have an option to configure which files are kept offline using a combination of blacklists and whitelists and let it automatically override/ignore the cache parameter and large file stream options? E.g. to keep all my photos offline I just use gdrive-offline-whitelist=/photos/* etc. In official google drive clients I believe it is available as a check box at the directory level to choose whether to sync it to the computer or not.

**Comment by astrada** [comment]
The official Google Drive client effectively synchronizes files from cloud to pc, while google-drive-ocamlfuse just gives you a view of your cloud filesystem. As there is no physical copy on your pc of your files in the cloud (if you ignore the cache copy that is used just for performance reasons), you wouldn't be able to access "blacklisted" files. If you need a sync tool, maybe you can check out [drive](https://github.com/odeke-em/drive) or [grive2](https://github.com/vitalif/grive2).
