### ISSUE TITLE
stat() system call causes curl download

### ISSUE THREAD

**Issue by lainegholson** [astrada/google-drive-ocamlfuse#140]
This can be problematic if you are offline or impatient to load the above directory.

**Comment by astrada** [comment]
Yes, you are right, but I chose consistency over responsiveness because my main use case is to backup my Drive locally. If you need to access files while offline, maybe you should use a sync tool, e.g. [drive](https://github.com/odeke-em/drive) or [grive2](https://github.com/vitalif/grive2).
