### ISSUE TITLE
Have installed google-drive-ocamlfuse - cannot find the binary

### ISSUE THREAD

**Issue by kraken17** [astrada/google-drive-ocamlfuse#141]
I have resolved all the issues with ocaml - installed google-drive-ocamlfuse but i cannot find the binary on my fedora 22 system. 

Please tell me what i have done wrong.

**Comment by astrada** [comment]
If you are using opam, you should find binaries under `~/.opam/system/bin` or something like that (anyway a subdir of `~/.opam`). Maybe you should run `eval $(opam config env)` to add that directory to the PATH variable.

**Comment by kraken17** [comment]
It does not seem to have compiled into that directory.

**Comment by astrada** [comment]
What is the output of `opam list`?

**Comment by kraken17** [comment]
[WARNING] Running as root is not recommended
# Installed packages for 4.02.1:
base-bigarray                 base  Bigarray library distributed with the OCaml
base-threads                  base  Threads library distributed with the OCaml c
base-unix                     base  Unix library distributed with the OCaml comp
biniou                       1.0.9  Binary data format designed for speed, safet
camlidl                       1.05  Stub code generator for OCaml
camlp4                      4.02+6  Camlp4 is a system for writing extensible pa
cppo                         1.3.1  Equivalent of the C preprocessor for OCaml p
cryptokit                     1.10  Cryptographic primitives library.
easy-format                  1.0.2  High-level and functional interface to the F
extlib                       1.6.1  A complete yet small extension for OCaml sta
gapi-ocaml                   0.2.6  A simple OCaml client for Google Services.
google-drive-ocamlfuse      0.5.18  A FUSE filesystem over Google Drive
ocamlfind                    1.5.5  A library manager for OCaml
ocamlfuse               2.7.1-cvs2  OCaml bindings for FUSE (Filesystem in UserS
ocamlnet                     4.0.4  Internet protocols (http, cgi, email etc.) a
ocurl                        0.7.5  Bindings to libcurl
sqlite3                      4.0.0  sqlite3-ocaml - SQLite3 bindings
xmlm                         1.2.0  Streaming XML codec for OCaml
yojson                       1.2.3  Yojson is an optimized parsing and printing

**Comment by astrada** [comment]
OK, if you installed opam with `sudo`, you should find binaries here: `/root/.opam/4.02.1/bin`. But probably you should reinstall them without `sudo` (with your standard user), so that you will find binaries in `~/.opam/4.02.1/bin`, and you will be able to use them without `sudo`.

**Comment by kraken17** [comment]
Good man - it was in 4.02.1 - in root - as this is a production server (web server) I cannot run it as anything other than root - can i?

**Comment by kraken17** [comment]
ok - another problem - do you want me to open another issue. Can you please publish concise information on how to use the headless system. I cannot get it to authenticate using google apis system from the instructions i have found on the internet.

**Comment by astrada** [comment]
Have you checked [this page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization) on the wiki?

**Comment by kraken17** [comment]
yes - way out of date - in the end had to make a fedora gui vmbox and get the code authenticated that way. We need to find a way to do this cos apparently it only lasts 30 days now.
