### ISSUE TITLE
Client never receives authorization tokens.

### ISSUE THREAD

**Issue by godofgrunts** [astrada/google-drive-ocamlfuse#142]
"The application was successfully granted access. Please wait for the client to retrieve the authorization tokens."

 Firefox just sits there and my terminal just sits there waiting for the tokens. So I  removed the default directory with

rm -r ~/.gdfuse/default

And trying again.  Same result.

After removing Firefox, Chrome opens and google-drive-ocamlfuse is able to access tokens correctly.

Unfortunately, nothing is logged while it sits there and does nothing so I don't have anything to give you.

uname -a
Linux cthulhu 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.5.18

firefox --version
Mozilla Firefox 42.0

google-chrome-stable -version
Google Chrome 46.0.2490.80 

xdg-open --version
xdg-open 1.1.0 rc3

**Comment by astrada** [comment]
If you enable debug logging with `-debug`, you should see the requests to obtain the token in `~/.gdfuse/default/curl.log`. If there is any error, it should be logged there too (or in `~/.gdfuse/default/gdfuse.log`).

**Comment by godofgrunts** [comment]
Okay I'll try that when I get home.

On Wed, Nov 4, 2015 at 2:01 PM, Alessandro Strada <notifications@github.com>
wrote:

> If you enable debug logging with -debug, you should see the requests to
> obtain the token in ~/.gdfuse/default/curl.log. If there is any error, it
> should be logged there too (or in ~/.gdfuse/default/gdfuse.log).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astrada/google-drive-ocamlfuse/issues/142#issuecomment-153831308>
> .
>



-- 
Thank you,
             Ryan Whited
