### ISSUE TITLE
Use default ~/.config folder instead ~/.gdfuse

### ISSUE THREAD

**Issue by eusonlito** [astrada/google-drive-ocamlfuse#144]
I think, as best practices, that config files should be located at `~/.config/gdfuse` folder instead a new custom config folder at user home.

Config files at default location are easy to find and backup.

It's only a suggestion :)

**Comment by astrada** [comment]
In version 0.6.12 you can turn on XDG Base Directory support with `-xdgbd` command line option.

**Comment by kynikos** [comment]
Hi, first of all thank you for this very nice piece of software!
I know I should have noticed this issue before you patched it (by coincidence I'm only a few days late), however I think a more correct implementation of the XDG standard that also keeps backwards compatibility shouldn't require command-line options, something like (pseudocode):
```
define xdgcfgdir, xdgdatadir, xdgcachedir, homedir
if $HOME is defined
    xdgcfgdir = $HOME/.config/gdfuse
    xdgdatadir = $HOME/.local/share/gdfuse
    xdgcachedir = $HOME/.cache/gdfuse
    homedir = $HOME/.gdfuse
if $XDG_CONFIG_HOME is defined
    xdgcfgdir = $XDG_CONFIG_HOME/gdfuse
if $XDG_DATA_HOME is defined
    xdgdatadir = $XDG_DATA_HOME/gdfuse
if $XDG_CACHE_HOME is defined
    xdgcachedir = $XDG_CACHE_HOME/gdfuse

if xdgcfgdir, xdgdatadir, xdgcachedir are assigned and xdgcfgdir already exists in the file system
    if xdgdatadir does not exist in the file system
        create and initialize xdgdatadir
    if xdgcachedir does not exist in the file system
        create xdgcachedir
    read the configuration from xdgcfgdir and use xdgcachedir, xdgdatadir
else if homedir is assigned and already exists in the file system
    read the configuration from homedir and use it for data and cache
else if xdgcfgdir, xdgdatadir, xdgcachedir are assigned
    create and initialize xdgcfgdir
    # The code below is the same as in the first 'if' block, perhaps reuse it
    if xdgdatadir does not exist in the file system
        create and initialize xdgdatadir
    if xdgcachedir does not exist in the file system
        create xdgcachedir
    read the configuration from xdgcfgdir and use xdgcachedir, xdgdatadir
else if homedir is assigned
    create and intialize homedir
else
    return an error (or create .gdfuse in the working directory?)
```

**Comment by astrada** [comment]
The command line option is required only once. The next time you run the application, the configuration file will be loaded from the XDG dir.

**Comment by kynikos** [comment]
I see, thanks, I should have read the updated wiki pages before. However I'm not very good at reading OCaml, and there's one thing that I don't understand from the docs, or maybe I misunderstood: you wrote that `-xdgbd` is needed only once, and then the value is stored in an `xdg_base_directory` option in the configuration file; is this configuration file staying in `~/.gdfuse/default/config` regardless of the `xdg_base_directory` value , or how does the application understand where to find the file before being able to read the `xdg_base_directory` option inside of it?

**Comment by astrada** [comment]
With `-xdgbd`, the old configuration file is not moved, but a new one is created, the old file will remain in the old path (`~/.gdfuse/default/config`), but it's not needed: you can move it to the new XDG config dir, or delete it, or keep it. The next time you start the application, the XDG config dir will be probed before the old one (somewhat like your pseudo-code), so only the new configuration file will be loaded.

**Comment by kynikos** [comment]
A-ha, so basically now the logic to read the configuration is:
```
if `~/.config/gdfuse` already exists
    use it
else if `~/.gdfuse` already exists
    use it
else
    create the config in `~/.gdfuse`
```
I don't want to abuse your patience, however now I don't understand the need for the `xdg_base_directory` option anymore. What happens if it's changed to `false` in `~/.config/gdfuse/default/config`? Does that mean that then the app for example searches the cache folder in `~/.config/gdfuse/default/cache` instead of `~/.cache/gdfuse/`? And if it's changed to `true` (manually, without using the `-xdgbd` flag) in `~/.gdfuse/default/config`? Does it mean that the application uses the XDG paths for everything except for the config file?

Would you accept it if I contributed a "Configuration path priority" section in [Configuration](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) to clarify all this?

**Comment by astrada** [comment]
> I don't want to abuse your patience, however now I don't understand the need for the xdg_base_directory option anymore.

You are right, it's mostly useless. The only use case where it can be of some use is when you specify a custom config file with `-config` and you want to use XDG directories for cache and state.

> What happens if it's changed to false in ~/.config/gdfuse/default/config? Does that mean that then the app for example searches the cache folder in ~/.config/gdfuse/default/cache instead of ~/.cache/gdfuse/? And if it's changed to true (manually, without using the -xdgbd flag) in ~/.gdfuse/default/config? Does it mean that the application uses the XDG paths for everything except for the config file?

Yes, it's like that and it's probably confusing. I'm going to remove it in a future release.

> Would you accept it if I contributed a "Configuration path priority" section in Configuration to clarify all this?

Sure! Thanks!

**Comment by kynikos** [comment]
Awesome, so [this](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration/_compare/514833863eb8897f2c865d42d3c0b363b8fade6b...a27cf412e17002919e1004bb3b6f16972cadf788) is my commit on the wiki, I hope it will make it clearer also for others :)
