### ISSUE TITLE
Cache size larger than config setting

### ISSUE THREAD

**Issue by abarrac1** [astrada/google-drive-ocamlfuse#149]
I am trying to sync a mounted network share to my google drive and noticed that the cache has grown to the maximum capacity of my disk ignoring the max_cache_size_mb configuration.

Is there any way to force this?

**Comment by abarrac1** [comment]
I did a search on previous issues and it looks like I have the same issue as #113.  When choosing the drive size should I allocate for total amount of data being transferred or the largest file being transferred?  Is there a way to clear the cache during an rsync?

**Comment by astrada** [comment]
> When choosing the drive size should I allocate for total amount of data being transferred or the largest file being transferred?

The largest file being transferred. But there is a problem: if your cache is nearly full and you upload a big file, it would get copied anyway, and only when the upload is completed, the cache will be freed.

> Is there a way to clear the cache during an rsync?

No. You can try to delete cached files with a script but afterwards, cache size will not be aligned anymore and this could cause other issues.
