### ISSUE TITLE
must uninstall ocamlfuse in order to use firefox and teamspeak

### ISSUE THREAD

**Issue by AAN3AC** [astrada/google-drive-ocamlfuse#150]
This is very strange.  
When I run Teamspeak it says through the speakers that it has connected, but the window is not displayed.  When I run firefox the firefox window appears for less than a second and then disappears.

Uninstalling ocamlfuse and rebooting fixes the problem.
Installing ocamlfuse again will cause both problems.

Naturally, I like ocamlfuse, but a computer without firefox is not good.

**Comment by astrada** [comment]
I'm working on a new version ([0.6.0](https://github.com/astrada/google-drive-ocamlfuse/tree/multi-threading)) that should support multi-threading. Maybe this will solve your issue.
