### ISSUE TITLE
OAuth call issues "400 Bad Request"

### ISSUE THREAD

**Issue by goodevilgenius** [astrada/google-drive-ocamlfuse#151]
When running `google-drive-ocamlfuse`, after clicking "Allow" on the page which reads "The application gdfuse OAuth2 Endpoint is requesting permission to access your Google Account", the next page says:

> # Error: Bad Request
> ## Your client has issued a malformed or illegal request.

The title on the page is "400 Bad Request".

The client hangs at that point.

**Comment by goodevilgenius** [comment]
running with `-debug` simply outputs 

    Starting application setup (label=default, base_dir=/home/user/.gdfuse).   
    Opening log file: /home/user/.gdfuse/default/gdfuse.log

`/home/user/.gdfuse/default/gdfuse.log` says:

```
Saving application state in /home/drj/.gdfuse/default/state...done
Current version: 0.5.21
Setting up cache db...done
Setting up CURL...done
Saving application state in /home/drj/.gdfuse/default/state...done
Starting web browser with command: xdg-open "https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=uzG4BoGpQxNjRXcmujO0cO%2FfVqnkmnUSclz5PqzILa8"...done
Getting tokens from GAE proxy...not found, retrying
Getting tokens from GAE proxy...not found, retrying
Getting tokens from GAE proxy...not found, retrying
```

**Comment by astrada** [comment]
Please try removing the directory .gdfuse (`rm -r /home/drj/.gdfuse`) and start the authorization procedure again. If the problem persists let me know.

**Comment by goodevilgenius** [comment]
I've done that several times, with no change.

I've got version 0.5.21-0ubuntu1~ubuntu15.04.1.

**Comment by astrada** [comment]
OK, I see. Can you please try the alternative [authorization method](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization)? The problem is that the error you obtain is caused by a page on Google servers that are not under my control, so I don't have logs and it's difficult to understand what went wrong.
