### ISSUE TITLE
Q: It is not clear if this always keeps all files on the device.

### ISSUE THREAD

**Issue by Fuco1** [astrada/google-drive-ocamlfuse#153]
From the readme it is not clear if this always downloads copies to the device or just lists the files and access them on-demand (with caching for already downloaded files).

I have many many things on my drive and I don't want to download all of it to every machine I use.  Is this possible?

**Comment by astrada** [comment]
Yes. You should set `stream_large_files=true` so that files larger than `large_file_threshold_mb` will not be cached.

**Comment by Fuco1** [comment]
Awesome, apparently I was hit by a temporary blindness :)

Thanks for quick reply!
