### ISSUE TITLE
Google Drive API does not allow urn:ietf:wg:oauth:2.0:oob redirect URL (headless auth)

### ISSUE THREAD

**Issue by tlaitinen** [astrada/google-drive-ocamlfuse#154]
<img width="615" alt="screen shot 2016-01-28 at 16 17 16" src="https://cloud.githubusercontent.com/assets/1113883/12646766/a256d3e2-c5da-11e5-8260-6d01a27d70a5.png">

I get "400. That’s an error.

Error: redirect_uri_mismatch" for for OAuth2 request.

A possible enhancement would be to add a parameter to google-drive-ocamlfuse to specify the redirect url of the OAuth2 request.

**Comment by astrada** [comment]
Yes, Google updated the Developers Console UI. I think you should choose "Other" as Application type.
![oauth2](https://cloud.githubusercontent.com/assets/1190416/12647851/9d210b84-c5d7-11e5-9630-598314a85f06.png)

**Comment by tlaitinen** [comment]
Great, now it works, Thanks!
