### ISSUE TITLE
Invisible to Plex

### ISSUE THREAD

**Issue by kevinjpickard** [astrada/google-drive-ocamlfuse#155]
Hello, 

I was hoping to use google drive to store some movies and then stream them through plex since I get unlimited storage while I am a student. I have my own dedicated private server set up running Ubuntu Server 14.04 (headless). I have installed google-drive-ocamlfuse, and it does work as far as letting me access files through an SSH connection. I have also installed Plex on this server, and have been able to stream movies from a local directory just fine. However, when I try to add a library in Plex and guide it to my ocaml-fuse mount point, the folder is not there. As soon as I unmount, Plex can see the folder again and access it just fine. I don't think it is a permissions issue, but it could be. I have added the Plex user to both my user's group and that of fuse as well. I have also tried mounting with different filesystems (i.e. ext3, which then shows up as fuse.ext3) and that did not help. I simply cannot seem to figure this out. Any help is greatly appreciated.

**Comment by cal2195** [comment]
use the `-oallow_other` argument when starting google-drive-ocamlfuse! :)

**Comment by kevinjpickard** [comment]
Thank you! Add a space in between the -o and the allow_other and it works beautifully! :) Thanks again, I've been banging my head against the wall for weeks with this one.

**Comment by AloiSama** [comment]
Sorry for reopening this, but does this still work? I keep reading that PLEX will cause google to ban you for 24 hrs.
