### ISSUE TITLE
Preload Files

### ISSUE THREAD

**Issue by ReneHollander** [astrada/google-drive-ocamlfuse#156]
Thanks for this awesome Google Drive client!

Is there a way to preload the files just like Dropbox does?

**Comment by astrada** [comment]
No, sorry. This application just gives you a local view of a remote file-system. It's not a sync app like Dropbox. If you need to have all files on your local hd to access them when offline, you should use another client (for example, [this one](https://github.com/odeke-em/drive)).

**Comment by ReneHollander** [comment]
Thanks for your answer!
