### ISSUE TITLE
OpenSUSE usage

### ISSUE THREAD

**Issue by pmoreaux** [astrada/google-drive-ocamlfuse#157]
MANY thanks to Alessandro Strada for his google-drive-ocaml-fuse package.
I'm running OpenSUSE 13.2, 64b, and installing the rpm was a breeze.
It runs very well.
Best wishes,
Patrice Moreaux (Professor on Computer Science, Polytech Annecy-Chambéry, University Savoie Mont Blanc, France).

**Comment by astrada** [comment]
Thank you for using my application!
