### ISSUE TITLE
Uploading Video "Unable to process this video"

### ISSUE THREAD

**Issue by canonlp** [astrada/google-drive-ocamlfuse#158]
I am not too sure where the problem lies. I have uploaded several videos and most are processed by Google drive correctly and play fine. However there are couple of videos that are not processing. Is my upload being corrupted somehow? How can I prevent that from happening?

**Comment by astrada** [comment]
>  Is my upload being corrupted somehow?

I don't know. What if you download them from Google Drive web interface? Are they still not playable? Can you reupload those files?

**Comment by Rick7C2** [comment]
I take it you are trying to stream the transcoded version from google drive web? If so it take a bit for google drive to process newly uploaded videos. If it is only new upoads giving you this issue then give it some time.
