### ISSUE TITLE
Slow upload rates, flooded connection

### ISSUE THREAD

**Issue by VE7ZBG** [astrada/google-drive-ocamlfuse#16]
I am experiencing incredibly slow transfer rates when uploading large documents, such as a 16 MB PDF, to my Google Drive.

When I tried to copy several PDF files from local to Google Drive, the small PDF files transferred without issue, but I noticed the larger files, especially the 16 MB one, would take around 10-15 minutes to transfer.  They were transferring at maximum 10 kB/s!  I tried unmounting and remounting the drive after the first couple times, but this didn't help.

I have since updated google-drive-ocamlfuse via the Update Manager on my Linux distro, and am still experiencing painfully slow upload rates for large documents, although they seem to have sped up a little, to about 15 kB/s.

Finally, it also seems that attempting to upload these large documents also causes google-drive-ocamlfuse to flood my Internet connection.  Perhaps this is related to the slow transfers?  During my most recent attempt today, I figured I'd do some online gaming while waiting.  My ping in the game was approaching 1000 ms!  I tried to click the cancel button on the copy dialogue, to stop the upload, but it wouldn't respond.  I ended up just disconnecting the computer from the network.  The instant I disconnected that computer, my ping in the game dropped to a normal less-than-100 ms.

----

`cat /etc/*-release`
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=15
DISTRIB_CODENAME=olivia
DISTRIB_DESCRIPTION="Linux Mint 15 Olivia"
NAME="Ubuntu"
VERSION="13.04, Raring Ringtail"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 13.04"
VERSION_ID="13.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

`uname -a`
Linux Aspire-3620 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:19:42 UTC 2013 i686 i686 i686 GNU/Linux

**Comment by astrada** [comment]
In version 0.5.21, I've added `max_download_speed` and `max_upload_speed` to avoid flooding the connection.

**Comment by moz87** [comment]
I have the same issue, its very slow to put a file.

I run the command "dd" to test the speed and I can't get more than 50kB/s on a **VPS**

```
$ dd if=/dev/zero of=/googleDrive/test bs=1024 count=1k
1024+0 records in
1024+0 records out
1048576 bytes (1,0m MB) cop, 24.2475 s. 43.2kB/s
```
