### ISSUE TITLE
cp fails with error cp: failed to close ‘<filename>’: Device or resource busy

### ISSUE THREAD

**Issue by macemoneta** [astrada/google-drive-ocamlfuse#160]
Running on kernel 4.5.0, copy to Google Drive fails on the close with -1 EBUSY (Device or resource busy).

Strace:

stat("googledrive/", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
stat("<input file>", {st_mode=S_IFREG|0700, st_size=311342, ...}) = 0
stat("googledrive/<output file>", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
open("<input file>", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0700, st_size=311342, ...}) = 0
open("googledrive/<output file>", O_WRONLY|O_TRUNC) = 4
fstat(4, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
mmap(NULL, 139264, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f803d502000
read(3, "\3\331\242\232g\373K\265\1\0\3\0\2\20\0001\301\362\346\277qCP\276X\5!j\374Z\377\3"..., 131072) = 131072
write(4, "\3\331\242\232g\373K\265\1\0\3\0\2\20\0001\301\362\346\277qCP\276X\5!j\374Z\377\3"..., 131072) = 131072
read(3, "\362\21\304D\351\306)\357\246\25\36\306N@'r\260\237\323|\265\212b\356\22\337O\276G\323\325g"..., 131072) = 131072
write(4, "\362\21\304D\351\306)\357\246\25\36\306N@'r\260\237\323|\265\212b\356\22\337O\276G\323\325g"..., 131072) = 131072
read(3, "G\211&\16\260do\254\"\350\243\311\2768\361\215\16\207\224\371\24=\26]W\362\3362\5\364\337\322"..., 131072) = 49198
write(4, "G\211&\16\260do\254\"\350\243\311\2768\361\215\16\207\224\371\24=\26]W\362\3362\5\364\337\322"..., 49198) = 49198
read(3, "", 131072)                     = 0
close(4)                                = -1 EBUSY (Device or resource busy)

$ google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.5.22
Copyright (C) 2012-2016 Alessandro Strada
License MIT

**Comment by astrada** [comment]
Please, use `-debug` and send `curl.log` and `gdfuse.log` (in `./gdfuse/default`) to my email alessandro.strada@gmail.com. Thanks

**Comment by macemoneta** [comment]
Debug logs sent. It looks like it's the same problem as issue #159, File creation date cannot be modified.

**Comment by sandler31** [comment]
Hello @astrada, I've sent you my logs too, I have the same problem.

**Comment by macemoneta** [comment]
Corrected with gapi-ocaml.0.2.9.
