### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by noesisconsultancy** [astrada/google-drive-ocamlfuse#161]
This Started before 4-5 days,
Till then it was working fine, All of sudden when we copy or modify the file it gave this error

while uploading, copying or moving or editing file

"Device Resource is Busy"

And logs shows this

Uploading file (cache path=/root/.gdfuse/backup3/cache/0B3i-cB9JQSysNHFaTENaNV9sbW8, content type=text/plain)...ServiceError
Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"badRequest\",\"message\":\"File creation date cannot be modified.\",\"locationType\":\"other\",\"location\":\"file.created_millis\"}],\"code\":400,\"message\":\"File creation date cannot be modified.\"}}")

-----

Loading resource /gdrivebackups/2016-03-17/govind.tar.gz (trashed=false) from db...found
Writing local file (path=/gdrivebackups/2016-03-17/govind.tar.gz,trashed=false)...done
Updating resource in db (id=5)...done
[467.610864] TID=2311: write /gdrivebackups/2016-03-17/govind.tar.gz buf 73826304 0
Getting metadata from context...valid
Loading resource /gdrivebackups/2016-03-17/govind.tar.gz (trashed=false) from db...found
Writing local file (path=/gdrivebackups/2016-03-17/govind.tar.gz,trashed=false)...done
Updating resource in db (id=5)...done
[467.615303] TID=2312: flush /gdrivebackups/2016-03-17/govind.tar.gz 0
Getting metadata from context...valid
Loading resource /gdrivebackups/2016-03-17/govind.tar.gz (trashed=false) from db...found
Uploading file (cache path=/root/.gdfuse/backup3/cache/0B3i-cB9JQSysMWhFRXhNNXRmUUU, content type=application/octet-stream)...ServiceError
Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"badRequest\",\"message\":\"File creation date cannot be modified.\",\"locationType\":\"other\",\"location\":\"file.created_millis\"}],\"code\":400,\"message\":\"File creation date cannot be modified.\"}}")
Backtrace:
[472.095461] TID=2313: release /gdrivebackups/2016-03-17/govind.tar.gz O_WRONLY
Getting metadata from context...valid
Loading resource /gdrivebackups/2016-03-17/govind.tar.gz (trashed=false) from db...found
Uploading file (cache path=/root/.gdfuse/backup3/cache/0B3i-cB9JQSysMWhFRXhNNXRmUUU, content type=application/octet-stream)...ServiceError
Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"badRequest\",\"message\":\"File creation date cannot be modified.\",\"locationType\":\"other\",\"location\":\"file.created_millis\"}],\"code\":400,\"message\":\"File creation date cannot be modified.\"}}")

Please help how to resolve this

**Comment by jetteim** [comment]
Just confirm I'му got the same issue a week ago

**Comment by noesisconsultancy** [comment]
Seems like Older Version has issue, after upgrading to latest one, issue resolved

**Comment by noesisconsultancy** [comment]
Seems like Older Version has issue, after upgrading to latest one, issue resolved

**Comment by astrada** [comment]
Yes, Google updated its API so that it caused that error. See issues #159 #160.
