### ISSUE TITLE
Device or resource busy @ Linux

### ISSUE THREAD

**Issue by carlosgs83** [astrada/google-drive-ocamlfuse#163]
Hi,

I have been using Google Drive OCALMFuse in headless mode for several weeks with great results, but right I cannot write anything to the mounted point while I'm getting a _Device or resource busy_ error.

I regenerated successfully new tokens a mounted it again with no success. 

Thanks in advance!

**Comment by astrada** [comment]
Can you update to the latest version (with OPAM or the Ubuntu package)? This issue was caused by a change in Drive API. See issue #159 #160.

**Comment by carlosgs83** [comment]
That's right! Thanks!
