### ISSUE TITLE
Zero file size on drive

### ISSUE THREAD

**Issue by Heland** [astrada/google-drive-ocamlfuse#166]
Hello,

I really enjoy this tool and I use it every days, hence I would like first, to thank you for the dev you are doing.
However
Since few days, I had an issue while copying a file to google drive:
-creating a tree folder is working successfully.
-copying a file either with rsync or cp, leads to a corrupted  zero file size on google drive.

Thanks in advance

**Comment by astrada** [comment]
Please update to the latest version. It should fix it. (See issues #159 and #160.)

**Comment by Heland** [comment]
Hi,

You are right!

After removing the rpm, and fixing the cryptokit 1.9 failure
I updated it to the latest version with opam

opam update && opam upgrade. 

Now I have again full accessworking.

Thanks for your quick support

BR
Stéphane
