### ISSUE TITLE
Folder and file names mangled with (1) 

### ISSUE THREAD

**Issue by berni421** [astrada/google-drive-ocamlfuse#168]
I am using google-drive-ocamlfuse, version 0.5.22 to keep a backup of a google drive shared amongst several users. 

The drive is mounted read only using:

google-drive-ocamlfuse -label example 	$HOME/example 	-o ro,allow_root

Some files and folders are presented with "(1)" or "(2)" appended to the names. The "appendages" are not present on the www version of the drive. e.g:

"Folder/Filename.pdf" is presented ocamlfuse mound point as "Folder (1)/Filename(1).pdf"

This does mean my backup can not be restored to an original state.

config:

async_upload=false
client_id=
client_secret=
conflict_resolution=server
connect_timeout_ms=5000
curl_debug_off=false
debug=false
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
force_docs_export=true
form_format=ods
form_icon=
keep_duplicates=false
large_file_threshold_mb=16
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=5120
max_download_speed=0
max_retries=10
max_upload_speed=0
metadata_cache_time=600
new_revision=true
presentation_format=pdf
presentation_icon=
read_only=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=50000
stream_large_files=false
umask=0o002
verification_code=

**Comment by astrada** [comment]
Files are renamed appending a suffix like "(1)", "(2)", if there is more than one file with the same name in the same folder. As there is no way to keep two files with the same name in the same directory on a UNIX file-system (while Google Drive permits), I have to disambiguate them. If you don't want to have those suffixes, be sure to rename the files so that are no duplicates (in the same folder).

**Comment by berni421** [comment]
Much appreciated. However,  in these cases there are no duplicate versions showing on the google drive listing at https://drive.google.com. e.g. I will struggle to fix by renaming because they are not actually ambiguous. :-)

**Comment by berni421** [comment]
Just to add there may well have duplicates at some stage in the past. However, not now.  Is there some kind of extra meta data update needed? -cc does not fix.

**Comment by astrada** [comment]
No, -cc should do. But you can try removing `~/gdfuse/default/cache` with `rm -r`. If it doesn't work yet, please activate debugging output (with -debug), do an `ls -R` of your mount point, and send `gdfuse.log` and `curl.log` to my email (alessandro.strada@gmail.com). Thanks

**Comment by berni421** [comment]
Doh.  Yes -cc fixed. Sorry, I had omitted to use the -label option to point to the correct cache.

**Comment by astrada** [comment]
OK, no problem.
