### ISSUE TITLE
Cache does not recycle correctly

### ISSUE THREAD

**Issue by carlosgs83** [astrada/google-drive-ocamlfuse#170]
In my /.gdfuse/me/cache folder there is a huge list of files with old date. It seems that after failing an upload the cache file is not removed.

I'm using the following version:

root@xxx:~/.gdfuse/me/cache# google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.5.22

Thanks!

**Comment by astrada** [comment]
Should be fixed in the new 0.6.x series.
