### ISSUE TITLE
Can copy file from google-drive-ocamlfuse but not to google-drive-ocamlfuse

### ISSUE THREAD

**Issue by shl198** [astrada/google-drive-ocamlfuse#172]
Hi Astrada,
I can copy file from google drive to other folders. But when I copy file from other folders to google drive, it says 'Device or resource busy'. the error message in gdfuse.log is attached:

[gdfuse.log.txt](https://github.com/astrada/google-drive-ocamlfuse/files/210921/gdfuse.log.txt)

Could you please have a look? thank you very much.

**Comment by roodyster** [comment]
Hi, I am having the same issue.

**Comment by astrada** [comment]
Please update to the latest version. See issues #159 and #160.

**Comment by rccipriani** [comment]
Same issue, running latest version. I can create a file (touch test), but if I try to write to the file with vi I see " E667: Fsync failed.   A "cp" gives me: cp: failed to close ‘/mnt/google/test’: Device or resource busy.

**Comment by astrada** [comment]
Which distribution are you using?

**Comment by rccipriani** [comment]
I'm running CentOS 7.2.1511, kernel is  3.10.0-327.13.1.el7.x86_64

**Comment by astrada** [comment]
Are you compiling google-drive-ocamlfuse with OPAM?

**Comment by rccipriani** [comment]
Yes, using OPAM. It was working at one point, but unfortunately I can't say what changed that might have broken it.  Perhaps Google changed something?

**Comment by astrada** [comment]
Can you please post the output of `opam list gapi-ocaml`?

**Comment by rccipriani** [comment]
# Available packages for system:
gapi-ocaml  0.2.10  A simple OCaml client for Google Services.

**Comment by astrada** [comment]
Have you tried reinstalling it?

    $ opam uninstall gapi-ocaml
    $ opam install google-drive-ocamlfuse

**Comment by rccipriani** [comment]
Same results. :(

**Comment by rccipriani** [comment]
Noticed that, while I can "touch" an empty file, I can't chmod or chown it afterwards.

**Comment by astrada** [comment]
>  I can't chmod or chown it afterwards.

That's because it's not implemented (as there is no easy way to map local users/permissions to Drive users/permissions).

Can you please send your `curl.log` (with the error) to my email (alessandro.strada@gmail.com)?

**Comment by rccipriani** [comment]
Gotcha. Google is weird. I appreciate your efforts :).

I don't have anything in my curl.log, do I need to run as -debug for it to be populated?

**Comment by astrada** [comment]
> do I need to run as -debug for it to be populated?

Yes, exactly.
