### ISSUE TITLE
Access mountpoint not as root possible? How? 

### ISSUE THREAD

**Issue by Spencerh20** [astrada/google-drive-ocamlfuse#173]
I had no problems to mount GDRIVE but I want to access the mountpoint with other users. So I change the permission of the mountpoint to 777. But after mounting only the root has permission to access. Any way to make the mountpoint accessible for all users?

**Comment by astrada** [comment]
You should use `-oallow_other`.

**Comment by Spencerh20** [comment]
Worked.

**Comment by Windywind** [comment]
Same problem, `-o allow_other` worked, but files created by other users are shown as root's files, why this?
