### ISSUE TITLE
Read-only access to the Google Photos directory

### ISSUE THREAD

**Issue by paede81** [astrada/google-drive-ocamlfuse#176]
Hi Alessandro

First: Great application, great work! Thanks!

I have a feature request for your connector: Is it possible to provide read only access to Google Photos? I think Google Photos is part (sub-directory) of Google Drive, so access via api should be possible.
I'm looking for way to easily download all my photos from Google

Regards,
Patrick

**Comment by astrada** [comment]
It should already work as you expect. Have you enabled access to Google Photos via Google Drive (see "Organize photos & videos using Google Drive" https://support.google.com/photos/answer/6156103?hl=en). Then you should be able to access to the Google Photo folder.

**Comment by paede81** [comment]
Perfect thanks! That was the point! It's working now
