### ISSUE TITLE
Access to a drive folder

### ISSUE THREAD

**Issue by ZhukovGreen** [astrada/google-drive-ocamlfuse#177]
Hello,

please help me to resolve further issue. Once I am mounting the drive by the command
```
drive-google-ocamlfuse /home/azh/GoogleDrive/
```
I am able to do that only on root@AZH
After that, I am not able to reach my folder under AZH rights.

I was trying to change permission but, the system shows that it is already ok (see the screenshot)
![screenshot from 2016-05-12 10-39-19](https://cloud.githubusercontent.com/assets/10520003/15208878/5efc21dc-182e-11e6-9953-d6d18d5fb653.png)
Please help to resolve the problem

Thank you

**Comment by astrada** [comment]
You should use `-oallow_other`.

**Comment by ZhukovGreen** [comment]
Hello Allesandro,
may you please provide a little bit more instructions?
I was trying ```/root@AZH:~# /home/azh/GoogleDrive/~ -o allow_other``` but it gives me
```No such file or directory```

**Comment by astrada** [comment]
Try with:

    # drive-google-ocamlfuse -oallow_other /home/azh/GoogleDrive/

**Comment by ZhukovGreen** [comment]
Yes, I tried this, but the result is
```google-drive-ocamlfuse: unknown option '-oallow_other'```

**Comment by astrada** [comment]
Sorry, it should be:

    # drive-google-ocamlfuse -o allow_other /home/azh/GoogleDrive/

**Comment by ZhukovGreen** [comment]
Yes, now it works. thank you
