### ISSUE TITLE
What happens when I rename a file?

### ISSUE THREAD

**Issue by Rick7C2** [astrada/google-drive-ocamlfuse#178]
What happens when I rename a file?

Does it download the file, raname, then re-upload?

Or does it call the drive api and rename the file directly on google drive? if not is there any way to make it work this way?

I have about 15TB of movies and tv shows that I decided to I want to change the naming scheme. It has taken forever for me to upload the content to begin with.  Not about to do it again but would much rather have the new naming scheme.

**Comment by astrada** [comment]
> Does it download the file, raname, then re-upload?

No, it shouldn't, unless it is a Google Doc. Let me know if it doesn't work as you expect.

**Comment by Rick7C2** [comment]
Thanks for confirming @astrada I just tested a small batch of files and it is indeed renaming them serverside. About to edit my script and batch rename all of the files.
