### ISSUE TITLE
Cache is stored on different disk than mount point

### ISSUE THREAD

**Issue by seymour1** [astrada/google-drive-ocamlfuse#179]
I'm mounting my google drive on a 2TB drive, but the OS is mounted on a 32GB SSD. The cache is being used on the disk with the OS, which ends up bloating and killing all the space I have on the disk.

Sample du -h output:
11G     /home/seymour1/.gdfuse/default/cache

Is there any way to force the cache to be stored somewhere else?

**Comment by Rick7C2** [comment]
Not sure if there is a way to configure google-drive-ocamlfuse but you could symlink the directory.

ln -s /DirectoryOnYour2TBPartituon/cache /home/seymour1/.gdfuse/default/cache

Make sure to stop google-drive-ocamlfuse first.

Move the original cache directly where ever you want it on your 2TB partition. Make sure the original cache dir is gone before running the above command. If not the symlink will not work.

This will alow the actual data to be stored on the partition you want while still being found in the other. Basically it's a shortcut.

**Comment by seymour1** [comment]
Ah, you know, that's not a bad idea! I'll keep that in mind for the future. It's probably overkill to add directly to google-drive-ocamlfuse.

The upload I was trying repeatedly failed for this reason, but I didn't see any output stating why (the why being that the cache was out of space to write). Maybe the documentation or logging could be better in that respect? Otherwise, this issue can be closed.

**Comment by astrada** [comment]
In version 0.6.12, I've added `cache_directory` config option to specify a custom cache path.
