### ISSUE TITLE
Drive FUSE Implementation doesn't support symbolic links.

### ISSUE THREAD

**Issue by jos3k4** [astrada/google-drive-ocamlfuse#182]
First of all, really nice implementation of Google Drive as filesystem is just what I was looking for.

I've tried to create a symbolic link inside the Google drive folder but I received the following error.

```
jperez@test-box ~/gdrive-fuse/test $ ln -s /home/jperez/stuff/ stuff
ln: failed to create symbolic link ‘stuff’: Function not implemented
```

It will be nice if the FUSE Implementation for Google drive support this.

**Comment by astrada** [comment]
I created a new [PPA](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta) with a new version ([0.6.0](https://github.com/astrada/google-drive-ocamlfuse/releases/tag/v0.6.0)) of my application that should support symbolic links. You should consider this a beta version. If you don't use Ubuntu, let me know, so I can give you instructions on how to install it.

**Comment by hotice** [comment]
Symlinks to either files or folders end up as 0 byte binaries in my Google Drive. Am I supposed to configure something regarding this?

**Comment by astrada** [comment]
No, that's the way they are implemented. Those are placeholders (kept in Drive) that are used to store the link name and metadata (the path the link points to). This way, you can clear your cache without losing the symlinks.

**Comment by hotice** [comment]
Oh so the actual file the link points to is never uploaded. Got it, thanks! Though that's a bit weird since pretty much everywhere "symlink support" usually means it uploads the actual contents, so you may want to clarify that in the description so you don't get useless comments/bug reports like mine :)

**Comment by astrada** [comment]
> Oh so the actual file the link points to is never uploaded. Got it, thanks!

No, if it's out of the mounted directory.

> Though that's a bit weird since pretty much everywhere "symlink support" usually means it uploads the actual contents

Well, a symbolic link (in a Unix file system) is just a file that stores a path.

> so you may want to clarify that in the description

OK, thanks for your feedback

**Comment by aliefe04** [comment]
so I cant add any kind of link to hold data ?
