### ISSUE TITLE
Use without local storage

### ISSUE THREAD

**Issue by mateussaggin** [astrada/google-drive-ocamlfuse#183]
Hi,

First I would like to apologize, my question can be ridiculous . I would like to use google-drive-ocamlfuse only to send and access the files in the cloud, without saving them locally. Is it possible to do that?

I'm making a storage system for internal use on my company. I'm using OwnCloud and I would like to use google drive for storing files instead of storing on my server.

Thanks,

**Comment by ittus** [comment]
I think you can set `stream_large_files=true` and `large_file_threshold_mb=1`. So it will stream all the files which are larger than 1MB.

**Comment by mateussaggin** [comment]
Thank you Ittus for your quick response, I will try this right now! I'll return to post the result.

**Comment by mateussaggin** [comment]
Thank you so much Ittus I did everything work properly. I have only one question. Doing that I will have my files stored on my server or just on google? 

I have a very limited space locally. Currently I'm using something around 500TB in the cloud. The files that are already on Gdrive will be synchronized locally?

Thank you so much. If anyone needs help with this, for sure, I will be available to help, just contact me.

**Comment by astrada** [comment]
With `stream_large_files=true` files are stored locally only if you have to upload them. Otherwise, they will not be downloaded in the local cache.

**Comment by mateussaggin** [comment]
Hi astrada thank for your quick response. Understand that. But will the files be temporarily allocated in my local disk when uploading files?

**Comment by astrada** [comment]
Yes, correct. As Google Drive only accepts the entire file during an upload, there is no way to upload single chunks individually. I have to store the whole file in the local cache before being able to start the upload.

**Comment by mateussaggin** [comment]
Thank you again astrada. All my question where answered. I will make this work. If anyone needs help, please contact me.

**Comment by JohNan** [comment]
Hi. I have a similar case as @mateussaggin and I am wondering if there's a local copy stored if I move from a local folder /tmp/file1.bin to the mounted folder? The reason I want to use it is to free space locally by uploading to Drive. Do I need to set `stream_large_files=true` for this to work as I want?

thanks!

**Comment by astrada** [comment]
No, sorry. Uploading requires copying the entire file to the cache, streaming options work only when downloading resources.

**Comment by JohNan** [comment]
Thanks for your reply. 
But will the cache be emptied once the file is uploaded (it's fine for me to temporarily keep the file)

**Comment by astrada** [comment]
If `max_cache_size_mb` is below the file size, the next time you upload/download a file, the bigger file should get evicted from cache (if it doesn't do so, it's a bug).

**Comment by jiangjiangflies** [comment]
@astrada 

> No, sorry. Uploading requires copying the entire file to the cache, streaming options work only when downloading resources.

I'm downloading files to mounted google drive. Is it possible not to save files to local cache?

**Comment by astrada** [comment]
Yes, you should set `stream_large_files` to `true` in config. If a file is bigger than `large_file_threshold_mb`, it will be streamed instead of fully downloaded to the local cache.

**Comment by jiangjiangflies** [comment]
> Yes, you should set stream_large_files to true in config. If a file is bigger than large_file_threshold_mb, it will be streamed instead of fully downloaded to the local cache.
I set stream_large_files to true and large_file_threshold_mb to 1. Then the size of the downloaded file in google drive is the same as the local cache.  Why?

**Comment by astrada** [comment]
After modifying the configuration, you should restart the application.

**Comment by jiangjiangflies** [comment]
Sorry again. How should I restart the application? should I mount it again?

**Comment by astrada** [comment]
Yes, correct.

**Comment by jiangjiangflies** [comment]
Again. The cache file size (0B5F-rbY1D1XCWU5VcEZsWklFcXc) is the same as my downloaded file in google drive. Did I do something wrong?

**Comment by astrada** [comment]
Previously cached files won't be removed, if you want you can remount with `-cc` to clear the local cache.

**Comment by jiangjiangflies** [comment]
I cleaned the cache, and remount again but  local cache is still generated when I download files.

**Comment by astrada** [comment]
Some files will still be downloaded: files smaller than 1MB and Google Docs

**Comment by jiangjiangflies** [comment]
I download YouTube videos with youtube-dl to mounted google drive. The cache file size is the same as the downloaded video. Maybe you can have a try.

**Comment by astrada** [comment]
Ah, I see. You are *uploading* files to Google Drive. So, no, I'm sorry, it's not possible to upload files without caching them on disk first.

**Comment by jiangjiangflies** [comment]
What a pity.... Thanks, anyway. If so, this application is almost the same as gdrive.
