### ISSUE TITLE
Use file immediately before it's uploaded completely to Google Drive

### ISSUE THREAD

**Issue by ittus** [astrada/google-drive-ocamlfuse#184]
Hello,
We are using google-drive-ocamlfuse with workflow:
1. Download a large file from Internet (~2GB) to google-drive-ocalmfuse mount folder
2. After download finished, use Python code to upload this file immediately to Youtube. We upload by chunk **16*1024** bytes
3. We observed that uploading speed ~100KB/s. If we downloading to local disk and then upload, upload speed ~1MB/s. Future more, not all parts of file are uploaded to Youtube, it seems that some parts are lost and some parts are duplicate.

Our configuration is 

```
conflict_resolution=server
connect_timeout_ms=5000
curl_debug_off=false
debug=false
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
force_docs_export=true
form_format=ods
form_icon=
keep_duplicates=false
large_file_threshold_mb=16
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=5120
max_download_speed=0
max_retries=10
max_upload_speed=0
metadata_cache_time=72000
new_revision=true
presentation_format=pdf
presentation_icon=
read_only=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
umask=0o022
```

We aren't not sure what happens when use that downloaded file immediately. If we download to google-drive mount folder, is it actually downloaded to cache folder? When we use that file immediately after download, is it uploaded to Google Drive and downloaded again?

**Comment by astrada** [comment]
> If we download to google-drive mount folder, is it actually downloaded to cache folder?

Yes, and when the download is completed (the file is closed by the OS), the file is (starting to be) uploaded to Google Drive servers.

> When we use that file immediately after download, is it uploaded to Google Drive and downloaded again?

If you access the file before the upload is completed, yes, the file is probably going to be downloaded again. You can turn on verbose logging with `-debug`, then check the log files to see what's happening.

**Comment by ittus** [comment]
That means if I use the file immediately before it's fully uploaded to Google Drive, there is a chance that I will only access a part (not whole) of that file. Because this file is downloaded again, and normally download speed is faster than upload speed. 

Is there any way to know when file is completely uploaded to Google Drive?

**Comment by astrada** [comment]
No, sorry.
