### ISSUE TITLE
Cache details

### ISSUE THREAD

**Issue by jivank** [astrada/google-drive-ocamlfuse#186]
Can you describe how the cache works?
When you move a file onto the fuse mount, how long does the file sit locally?

Would it be possible to have some sort of expiry on files (by the last time the OS accessed them)? So a file that is often read, will always stay in cache (read 1 time in a certain period).
And if a large file is being streamed, it also gets copied into the cache, so the second time its read, its already local.

Is something like this already happening when you reach the cache size limit (delete the oldest file in cache until under the cache size limit)?

**Comment by astrada** [comment]
> When you move a file onto the fuse mount, how long does the file sit locally?

As long as Drive API returns that the file (or one of the folders that contains it) is modified.

> Is something like this already happening when you reach the cache size limit (delete the oldest file in cache until under the cache size limit)?

Yes, it should work like that.
