### ISSUE TITLE
code.google.com points to console.developers.google.com

### ISSUE THREAD

**Issue by madorian** [astrada/google-drive-ocamlfuse#188]
I'm trying to install on a headless server, but I can't find what the documentation describes. 

It says: 
Click "Services" in the left-hand pane (will take you to https://code.google.com/apis/console/?pli=1#:services). Turn on the service "Drive API".

First of all, that code.google.com redirects to console.developers.google.com and there is no select API access thing to click on. Can you please update this documentation?

**Comment by astrada** [comment]
From the hamburger menu, you should select API Manager, then Library -> Drive API, then ENABLE. This link has some screenshots: http://www.iperiusbackup.net/en/how-to-enable-google-drive-api-and-get-client-credentials/

**Comment by madorian** [comment]
I figured it out;) Thanks.
