### ISSUE TITLE
fuse: mount failed: No such device (openVZ)

### ISSUE THREAD

**Issue by madorian** [astrada/google-drive-ocamlfuse#189]
I've got a problem running google-drive-ocamlfuse in a hosted openVZ.

I've successfully run the application on normal GNU/Linux distributions, but I can't manage to run it here. 

I get: 

b0ef@famadorian:~$ sudo google-drive-ocamlfuse -label me -debug gdrive/
Starting application setup (label=me, base_dir=/home/b0ef/.gdfuse).
Opening log file: /home/b0ef/.gdfuse/me/gdfuse.log
fuse: mount failed: No such device

Any pointers as to how I can troubleshoot this?

**Comment by astrada** [comment]
It looks like you don't have setup FUSE inside the container. Look at this link: https://openvz.org/FUSE

**Comment by madorian** [comment]
This is the reply I have gotten from my Bytesized provider: 

"I have confirmed that the kernel module is loaded and i´ve made sure that your container now has the neccesary permisions. Could you try again now and let us know."

Is there any way I can test fuse in openvz to let them understand that they've set it up wrong?

**Comment by astrada** [comment]
Try with:

    $ ls -l /dev/fuse

you should get something like:

    crw-rw-rw- 1 root root 10, 229 Jan 19 13:53 /dev/fuse

**Comment by madorian** [comment]
Ok, I get the exact same with sshfs:

`
b0ef@famadorian:~$ sudo apt-get install sshfs
[sudo] password for b0ef: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  sshfs
0 upgraded, 1 newly installed, 0 to remove and 37 not upgraded.
Need to get 41.7 kB of archives.
After this operation, 138 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/universe amd64 sshfs amd64 2.5-1ubuntu1 [41.7 kB]
Fetched 41.7 kB in 0s (748 kB/s) 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "nb_NO.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package sshfs.
(Reading database ... 26837 files and directories currently installed.)
Preparing to unpack .../sshfs_2.5-1ubuntu1_amd64.deb ...
Unpacking sshfs (2.5-1ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up sshfs (2.5-1ubuntu1) ...
b0ef@famadorian:~$ ls
gdrive  wtf.log
b0ef@famadorian:~$ # sshfs root@foo.org:/root /mnt/foo.org.root
b0ef@famadorian:~$ mkdir sshfs
b0ef@famadorian:~$ sshfs root@foo.org:/root sshfs/
fuse: failed to open /dev/fuse: Permission denied
b0ef@famadorian:~$ sudo sshfs root@foo.org:/root sshfs/
fuse: mount failed: No such device
b0ef@famadorian:~$ 


`

**Comment by madorian** [comment]
b0ef@famadorian:~$ ls -lh /dev/fuse 
crw-r--r-- 1 root root 10, 229 Jul 25 06:12 /dev/fuse

**Comment by astrada** [comment]
OK, you user doesn't have the write permission on the device. Check this link: http://superuser.com/a/800016

**Comment by madorian** [comment]
Hmm, I did: 

chmod a+rw /dev/fuse

Now I have: 

b0ef@famadorian:~$ ls -lh /dev/fuse 
crw-rw-rw- 1 root root 10, 229 Jul 25 06:12 /dev/fuse
b0ef@famadorian:~$ sudo google-drive-ocamlfuse -label me -debug gdrive/
Starting application setup (label=me, base_dir=/home/b0ef/.gdfuse).
Opening log file: /home/b0ef/.gdfuse/me/gdfuse.log
fuse: mount failed: No such device
b0ef@famadorian:~$ 

, so still the same

**Comment by astrada** [comment]
Probably you have to restart your VE (see https://forum.openvz.org/index.php?t=msg&goto=11793& and http://realtechtalk.com/OpenVZVirtuozzo_Enable_Fuse_in_Container-139-articles).

**Comment by madorian** [comment]
Right, I'll let them know: 

cat /proc/filesystems 
nodev   cgroup
nodev   devpts
nodev   mqueue
        ext3
        ext4
nodev   nfs
nodev   nfs4
nodev   delayfs
nodev   devtmpfs
nodev   sysfs
nodev   proc
nodev   tmpfs
nodev   binfmt_misc

**Comment by madorian** [comment]
Excellent;) Working now, thanks a lot.
