### ISSUE TITLE
Mount Read Only

### ISSUE THREAD

**Issue by madorian** [astrada/google-drive-ocamlfuse#190]
Is it possible to mount the google drive read only?

**Comment by astrada** [comment]
Yes. Modify the configuration file putting `read_only=true`.

**Comment by madorian** [comment]
Ok, found the read_only=true flag. Sorry for the noise. I looked in man.

**Comment by madorian** [comment]
It is mounted read only, but it still displays: 

google-drive-ocamlfuse on /home/b0ef/gdrive type fuse.google-drive-ocamlfuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

I can't write to it, so everything is great; just mentioning;)

**Comment by Orbixx** [comment]
It would be helpful if the application gave the option of requesting a read-only token from Google. A malicious attacker that compromises the credentials could destroy an entire Google Drive account and even a Google Photos account too if configured to show on GDrive.

**Comment by Orbixx** [comment]
To anybody who wants similar behaviour and don't mind compiling, edit line containing: "let scope = [GapiDriveV2Service.Scope.drive]" in oauth2.ml to: "let scope = [GapiDriveV2Service.Scope.drive_readonly]"
