### ISSUE TITLE
Using EncFS/EcryptFS is very slow

### ISSUE THREAD

**Issue by ALinuxNinja** [astrada/google-drive-ocamlfuse#192]
Hi,

I've been testing the usage of encfs/ecryptfs directly on ocamlfuse, but I have been encountering extremely low speeds. Most of the rsync transfers into the encrypted container go at ~150kbps, where I can get around 4MB/s if using rsync directly into ocamlfuse.

Will be happy to provide whatever is necessary to help the debug process :)

**Comment by astrada** [comment]
AFAIK encfs uses FUSE, so you have a double FUSE layer. This could explain the slowness. Probably you should use another tool to upload your encrypted filesystem to the cloud (e.g. https://github.com/odeke-em/drive).

**Comment by Thinkscape** [comment]
Experiencing the same problem. It doesn't occur with other fuse mounts (i.e. gdfs). Raw write speed is 10x-50x faster than via encfs.

**Comment by blitz313** [comment]
I had the same problem back in June as well - I was in the process of switch from acd_cli to Google Drive equivalent.  I originally was attempting to make my implementation work with google-drive-ocamlfuse, however I had to switch over to gdfs for this same reason.  The ENCFS volume never mounts.  I'd like to switch over to google-drive-ocaml-fuse b/c gdfs hasn't had a commit in over a year - and honestly I have issues with Plex playback.  So, any help with resolving the ENCFS loading would be greatly appreciated.
