### ISSUE TITLE
Not work the automount

### ISSUE THREAD

**Issue by htschannerl** [astrada/google-drive-ocamlfuse#194]
Hello,

I did the configuration to automount link this tutorial https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting using the the FSTAB on the CentOS 7 but when I restart the computer not mount.
If I use the mount -a command it works.
Someone know how I fix?

**Comment by ittus** [comment]
1 solution is add mount command to crontab configuration. 

> @reboot google-drive-ocamlfuse -label default /path/to/mount
