### ISSUE TITLE
Exec permissions

### ISSUE THREAD

**Issue by tomgoldsmith** [astrada/google-drive-ocamlfuse#195]
I appear to be having issues setting exec permissions for any scripts stored on my Google Drive.  I have attempted to set permissions, the command does not fail but the permissions are not set. Is there a way to fix this?

**Comment by astrada** [comment]
No, because Google Drive doesn't have a UNIX-like permission model. I'm thinking about adding metadata to Drive files, but it's a long term enhancement, so I cannot give you an ETA.

**Comment by tomgoldsmith** [comment]
Ahh I see yes that makes sense. Totally understand about the ETA.

Just for info my use case here is that I want to store a set of scripts that I can use on multiple machines without having to store them in a git repository and have to pull them when changes are made and so I can quickly reinstate them on a clean build. 

Very much appreciate the work so far! Thank you!

**Comment by astrada** [comment]
I created a new [PPA](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta) with a new version ([0.6.0](https://github.com/astrada/google-drive-ocamlfuse/releases/tag/v0.6.0)) of my application that should support permissions. You should consider this a beta version. If you don't use Ubuntu, let me know, so I can give you instructions on how to install it.
