### ISSUE TITLE
Add parameter to sync specific folder(s) only

### ISSUE THREAD

**Issue by nicolae-46-2** [astrada/google-drive-ocamlfuse#197]
The project is great !

From being the ultimate implementation for google drive it lacks the support to specify what folder(s) to sync only into the mount-point.

Imagine this use case: I pay for the drive to have more than the free space given by google.
If the tool will potentially sync 1TB+ of data this is not fun. I won't have any space left on my 256GB SSD :)

I can join forces to help with the coding/testing if needed. To me this feature is a deal breaker.

**Comment by astrada** [comment]
Files are just cached locally (and not stored), and if you don't access them, they won't be downloaded. Cache size is also limited (check the configuration file), although if you upload very big files, that limit can be exceeded. If you need a sync tool, you can check out other projects (e.g.: https://github.com/odeke-em/drive).
