### ISSUE TITLE
INSTALLAZIONE E AUTENTICAZIONE SERVER SENZA GUI

### ISSUE THREAD

**Issue by filippo2658** [astrada/google-drive-ocamlfuse#199]
Salve,
Anzitutto mi volevo congratulare per il progetto, poter montare su una macchina linux un drive esterno in cluod come se fosse in locale e' gran cosa.
Il mio problema e' che il file server che ho realizzato (Debian 8.5) e' senza GUI ovvero e' solo terminale,quindi nessun problema per l'installazione ,ma quando arrivo a dover autenticare l'utente ovviamente mi crea problemi non avendo nessun browser installato.
Ho qualche opzione??
Grazie in anticipo per l'aiuto

P:S Con una macchina esterna ho gia' provato

**Comment by astrada** [comment]
Sì, è possibile. In questa [pagina](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization) ci sono le istruzioni per procedere. La macchina esterna con il browser serve comunque.

**Comment by idvoretskyi** [comment]
@filippo2658 @astrada as an end-user of the utility, I'd like to see the GitHub conversations in English.

**Comment by filippo2658** [comment]
Grazie mille!!!!




----Messaggio originale----

Da: "Alessandro Strada" <notifications@github.com>

Data: 23/08/2016 12.21

A: "astrada/google-drive-ocamlfuse"<google-drive-ocamlfuse@noreply.github.com>

Cc: "filippo2658"<filippodaddi@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [astrada/google-drive-ocamlfuse] INSTALLAZIONE E AUTENTICAZIONE SERVER SENZA GUI (#199)




Sì, è possibile. In questa pagina ci sono le istruzioni per procedere. La macchina esterna con il browser serve comunque.

**Comment by brancomat** [comment]
@idvoretskyi, translated recap:

"is it possible to use this in a debian server without GUI / X server?"
"yes it is, see [Headless Usage & Authentication](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization), but you'll still need a graphical browser in some other machine"
