### ISSUE TITLE
Prevents my DE from loading when internet is unavailable. 

### ISSUE THREAD

**Issue by leetwanker** [astrada/google-drive-ocamlfuse#201]
I'm on Mint 17.3 Cinnamon

For some reason when I don't have internet Cinnamon won't load. I ended up having to uninstall.

**Comment by matiasw** [comment]
Google-drive-ocamlfuse should be made to fail gracefully when offline. There's more info about this at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846367 , but basically the mount point is "busy", and makes my file manager, your desktop environment hang.

**Comment by Schisco94** [comment]
I'm having a similar issue. I'm using the new Mint 18 on KDE. Every time I disconnect from the Internet, I can navigate in dolphin no problem, except when I try to view /home/%User%/. My entire home folder hangs, and I can't access any documents. I tried to do an ls, and came up with the same result. As long as I have an Internet connection, I can access my home folder, but I'm running a lab that forces me to disconnect from the Internet to do properly.
