### ISSUE TITLE
Precise repository broken?

### ISSUE THREAD

**Issue by bs27975** [astrada/google-drive-ocamlfuse#204]
As per https://github.com/astrada/google-drive-ocamlfuse I have:
add-apt-repository ppa:alessandro-strada/ppa
apt-get update

On my trusty machines, aptitude search google-drive-ocamlfuse
reveals the expected.

On precise, aptitude search google-drive-ocamlfuse
the output is blank.

Is the precise repository broken? Or what might I be doing wrong?

**Comment by astrada** [comment]
Precise is not supported anymore because it doesn't have updated enough dependencies, so if you cannot update your distro, you should use OPAM to install this app.

**Comment by bs27975** [comment]
Thanks. OPAM install seems to have worked just fine.
