### ISSUE TITLE
Ubuntu 16.10: No 'Release' file + 404 Not Found

### ISSUE THREAD

**Issue by shlomitsadok** [astrada/google-drive-ocamlfuse#208]
On Ubuntu 16.10, running 'apt-get update' after adding ppa, results in this error:

W: The repository 'http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu/dists/yakkety/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by astrada** [comment]
I've uploaded packages for yakkety

**Comment by shlomitsadok** [comment]
Seems to be working. Thanks!
