### ISSUE TITLE
question: upload progress

### ISSUE THREAD

**Issue by alexandrevicenzi** [astrada/google-drive-ocamlfuse#210]
Hi,

Is the gdrive upload progress related to the copy/paste progress from Nautilus?

Showing and copying/pasting from a mounted gdrive is very slow. Not sure if it's slow because fetch some data from gdrive.

**Comment by astrada** [comment]
> Is the gdrive upload progress related to the copy/paste progress from Nautilus?

Not really, it's shown while copying the file to upload to the local cache. The actual upload is done when this copy is completed, so it's not tracked by the progress bar.

**Comment by Moulick** [comment]
So that means If I copy a 1GB file from my home dir to the drive, it'll first cache it ?

**Comment by astrada** [comment]
@Moulick yes, correct.

**Comment by Moulick** [comment]
And why is this caching necessary? When copying from my local drive to
Google drive, the file is already in a sense cached?

**Comment by astrada** [comment]
Because FUSE writes are chunked, but Drive API doesn't support uploading a single chunk of a file.
