### ISSUE TITLE
Error: Integer literal exceeds the range of representable integers of type int

### ISSUE THREAD

**Issue by sionie** [astrada/google-drive-ocamlfuse#212]
Hi,
I got following errors while installing google-drive-ocamlfuse on raspberry pi 3 (w/ jessie lite) according to 
[How-to-install-from-source-on-Debian-Jessie](https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie)

Anyone can help me to fix it?

    pi@raspberrypi:~ $ opam install google-drive-ocamlfuse
    The following actions will be performed:
     - install   google-drive-ocamlfuse.0.5.23
    === 1 to install ===
    
    =-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    
    =-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    Building google-drive-ocamlfuse.0.5.23:
      ocaml setup.ml -configure --prefix /home/pi/.opam/system
      ocaml setup.ml -build
      ocaml setup.ml -install
    [ERROR] The compilation of google-drive-ocamlfuse.0.5.23 failed.
    Removing google-drive-ocamlfuse.0.5.23.
      Nothing to do.
    
    
    #=== ERROR while installing google-drive-ocamlfuse.0.5.23 =====================#
    # opam-version 1.2.0
    # os           linux
    # command      ocaml setup.ml -build
    # path         /home/pi/.opam/system/build/google-drive-ocamlfuse.0.5.23
    # compiler     system (4.01.0)
    # exit-code    1
    # env-file     /home/pi/.opam/system/build/google-drive-ocamlfuse.0.5.23/google-drive-ocamlfuse-    19209-c61e7b.env
    # stdout-file  /home/pi/.opam/system/build/google-drive-ocamlfuse.0.5.23/google-drive-ocamlfuse-19209-c61e7b.out
    # stderr-file  /home/pi/.opam/system/build/google-drive-ocamlfuse.0.5.23/google-drive-ocamlfuse-19209-c61e7b.err
    ### stdout ###
    # ...[truncated]
    # /usr/bin/ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
    # /home/pi/.opam/system/bin/ocamlfind ocamldep -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -modules src/gdfuse.ml > src/gdfuse.ml.depends
    # /home/pi/.opam/system/bin/ocamlfind ocamldep -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -modules src/appDir.ml > src/appDir.ml.depends
    # /home/pi/.opam/system/bin/ocamlfind ocamldep -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -modules src/cache.ml > src/cache.ml.depends
    # /home/pi/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -thread -w -d-58 -I src -o src/appDir.cmo src/appDir.ml
    # /home/pi/.opam/system/bin/ocamlfind ocamldep -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -modules src/config.ml > src/config.ml.depends
    # + /home/pi/.opam/system/bin/ocamlfind ocamldep -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -modules src/config.ml > src/config.ml.depends
    # File "src/config.ml", line 316, characters 26-39:
    # Error: Integer literal exceeds the range of representable integers of type int
    # Command exited with code 2.
    ### stderr ###
    # E: Failure("Command ''/usr/bin/ocamlbuild' src/gdfuse.native -tag debug' terminated with error code 10")

in src/config.ml
(int) max_upload_chunk_size = 1099511627776;
seems too big.......

    pi@raspberrypi:~ $ ocaml
            OCaml version 4.01.0
    
    # max_int;;
    - : int = 1073741823

**Comment by astrada** [comment]
Yes, there was a problem with 32-bit architectures. Should be fixed in 0.5.25 (as soon as the package is published to the official repository).

**Comment by sionie** [comment]
0.5.25 works! thanks :)

**Comment by tulasinandan** [comment]
Hi I'm having the same problem installing on Debian 9 - 32 bit:

# Makefile:50: recipe for target 'IO.cmo' failed
# make[1]: Leaving directory '/home/tulasi/.opam/system/build/extlib.1.7.4/src'
# Makefile:14: recipe for target 'build' failed
### stderr ###
# fatal: Not a git repository: '.git'
# File "IO.ml", line 577, characters 10-21:
# Error: Integer literal exceeds the range of representable integers of type int
# make[1]: *** [IO.cmo] Error 2
# make: *** [build] Error 2
=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install gapi-ocaml             0.3.6 
  ∗  install google-drive-ocamlfuse 0.6.23
The following actions failed
  ∗  install extlib 1.7.4
No changes have been performed

Any suggestions on fixing it? Thanks!

**Comment by astrada** [comment]
It looks like latest version of extlib doesn't compile on 32-bit systems. You can try with `opam pin add extlib 1.7.2`.

**Comment by tulasinandan** [comment]
That worked. Thanks!
