### ISSUE TITLE
Add ARM packages to your repository

### ISSUE THREAD

**Issue by XJDHDR** [astrada/google-drive-ocamlfuse#213]
I have an Odroid with Ubuntu ARM installed on it. I would love to be able to use this program on it. Unfortunately, your PPA only has i386 and amd64 packages available. At this point, this means that my only options are to either run the i386 version through QEMU's emulation, which is slow and I'm not convinced is 100% reliable, or compile it, which I'm not comforable enough to do.

Would it be possible to compile ARM packagess and make them available alongside the i386 and amd64 versions?

**Comment by astrada** [comment]
I think you can try installing OCaml (https://github.com/jrcharney/rigel/wiki/OCAML) and then install google-drive-ocamlfuse with OPAM.

**Comment by XJDHDR** [comment]
I have one question though: How much effort would be required to add ARM binaries to your PPA repository? The reason I ask is because I would much rather use Ubuntu's built-in package manager to manage my software rather than installing another software manager just to install yours.

Otherwise, I could certainly try it. I do however notice that the installation instructions for OCAML has the words "TODO: REDO THE INSTALLATION INSTRUCTIONS!" at the top so I'm already worried. Furthermore, they state that building OPAM and OCAML will take a very long time (hours, judging by the suggestions provided for what to do in the meantime).

**Comment by astrada** [comment]
I didn't know you can enable ARM compiling from PPA settings (http://askubuntu.com/questions/371339/how-to-make-packages-for-arm-in-launchpad/765149#765149). I can enable these targets:

* ARM ARMv8 (arm64)
* ARM ARMv7 Soft Float (armel)
* ARM ARMv7 Hard Float (armhf)

Which one do you need?

**Comment by XJDHDR** [comment]
That's good to hear. Anyway, the Samsung Exynos 5 SOC used by the Odroid XU3 uses the armhf architecture.

**Comment by astrada** [comment]
OK, I published arm packages for Ubuntu 16.04. Let me know if you need packages for another version.

**Comment by XJDHDR** [comment]
I can't believe it's been a month already. 

I just managed to install your program on my Odroid and it seems to be working very well. Thank you! I am having one small issue but I'll create a seperate ticket for that.

As for the other two ARM architectures:
I'm not aware of any computer that requires armel and, from what I've read, armel is slower and older than armhf. I don't think you need to worry about this unless someone requests it.
ARMv7 is still the most popular architecture for ARM computers though as time goes by, ARMv8 is only going to become more popular. In this list, I count 7 computers that can use arm64 binaries:
https://en.wikipedia.org/wiki/Comparison_of_single-board_computers#CPU.2C_GPU.2C_memory

**Comment by astrada** [comment]
Well, thanks! So I'm going to select arm64 too.

**Comment by babam86** [comment]
Can you to provide a static binary for ARMv7, I will use it on Android.

Thanks.
