### ISSUE TITLE
cpu maxing out when using gdo

### ISSUE THREAD

**Issue by Symbiot78** [astrada/google-drive-ocamlfuse#216]
Hi

I just started testing gdo and I got gdrive mounted and all is good.

but when transferring a file between server & google drive my cpu is maxing out.

I tried adding a bunch of files to my gdrive and then had plex media server scan the folder and it's scanning extremely slow and again maxing out CPU.

is this expected behaviour?

**Comment by Symbiot78** [comment]
I tried adding -headless.. will check tomorrow..

the plex scan is still EXTREMELY slow.. but haven't tried playing anything yet..

**Comment by astrada** [comment]
Should be (at least partially) resolved in the new 0.6.x versions.
