### ISSUE TITLE
Google Photos

### ISSUE THREAD

**Issue by marlarius** [astrada/google-drive-ocamlfuse#218]
Google Photos are not shown in the mounted folder. But they are in the web version of Google Drive.

Would it be possible to extend the tool to include Google Photos?

**Comment by astrada** [comment]
You should be able to access Google Photos directory, if you select "Create Google Photos folder" in Drive settings: https://support.google.com/photos/answer/6156103?co=GENIE.Platform%3DDesktop&hl=en&oco=0 (Organize photos & videos using Google Drive)

**Comment by marlarius** [comment]
Thanks. It works!
