### ISSUE TITLE
[Suggestion] Show extra google processed video files (1080p, 720p, 480p, 360p)

### ISSUE THREAD

**Issue by karbowiak** [astrada/google-drive-ocamlfuse#219]
Hi there!

Just started using gdfuse for GDrive fuse mounting, and it is fast with the new 0.6 beta - very fast! :)
Anyway, i was looking at the folder that it mounts, and had a small brain fart, i know that Google processes all videos that are uploaded (if not encrypted obv.) and generates several smaller variants of them as well.

Wouldn't it be a cool idea to have gdfuse show those extra encodes like so
```
Video Name - Original.mkv (Could be mp4, avi etc..)
Video Name - 1080p.mp4
Video Name - 720p.mp4
Video Name - 480p.mp4
Video Name - 360p.mp4
Video Name - ......
```

No idea if it's available in the APIs that are out there right now, but then again, i haven't messed much with the GDrive APIs.

**Comment by astrada** [comment]
No, sorry, the API doesn't support that feature (http://stackoverflow.com/questions/25772174/api-access-to-different-video-formats-and-resolutions/25815541#25815541).

**Comment by karbowiak** [comment]
Oh damn, and here i was hoping it would be :(

Ah well, i'll close this up again then :)
Keep up the good work! :)
