### ISSUE TITLE
already approved access on different machine

### ISSUE THREAD

**Issue by shakworks** [astrada/google-drive-ocamlfuse#223]
I wish to use same googledrive on two computer running linux mint. its access is already approved on one machine but for the second one it just open web browser google page but no app access approval comes up. I think because google has already approved the access that is why that window is not showing up. how i go around this problem.
Many thanks,

**Comment by astrada** [comment]
You should copy `./gdfuse/default/state` (and `./gdfuse/default/config` if you are using your own client id/secret) on the other machine. Then you should be able to mount your Drive without reauthorizing the app.
