### ISSUE TITLE
mv'ing files within Gdrive

### ISSUE THREAD

**Issue by apesofhove** [astrada/google-drive-ocamlfuse#225]
Hello, should I be able to "mv" files between folders within Gdrive.

When I try I get:

mv: cannot move 'file.jpg' to '../snapArchive/2016-12/file.jpg': Input/output error

At the moment I am working round it by copying locally then back to Gdrive.

**Comment by astrada** [comment]
Yes, it was caused by a breaking change in Drive API v3. It should be fixed in version 0.6.6

**Comment by apesofhove** [comment]
Hi, many thanks for the fantastically quick response. I was almost going to report that it had not worked after installing from the beta repository but then realised I hadn't remounted :-)

MUCH quicker than the 0.6.4 version with cp/rm script that I had been using (3x + faster)

Many thanks again.
