### ISSUE TITLE
openoffice documents converted at drive.google.com are accessed read-only

### ISSUE THREAD

**Issue by serhatcevikel** [astrada/google-drive-ocamlfuse#227]
*.ods and *.odt files that are created at drive.google.com as a result of conversion of original documents by Google Docs/Sheets are accessed read-only at the mountpoint. All other files are rw so it is not an issue about how the fs is mounted or fuse.

If this file is copied at the mountpoint to create a new openoffice document, it is rw permitted. However, whenever the same file is converted at drive.google.com by Google Docs (and a new file is created), this new file is also read-only.

**Comment by astrada** [comment]
It's by design. That's because you cannot download Google Docs/Sheets in native format through the API, you can only export them to some other format, and layout (for example) is not always preserved. So, to avoid messing with original docs, I decided to make them read-only.

**Comment by serhatcevikel** [comment]
Thanks. By the way, that's a great application.
