### ISSUE TITLE
can no longer list root of Google Drive

### ISSUE THREAD

**Issue by R-Chandra** [astrada/google-drive-ocamlfuse#228]
Not sure how many updates ago this stopped working, because I do not list it often, but when I try ls(1) (or presumably anything else that does readdir(3)) I get "input/output error."  Although I have not extensively tested, all other operations (create a file, write a file, read a file, list (ls) a subdirectory of GD) seem to work OK.  In previous releases, this has worked OK, not sure if it was the one this past week which caused this not to work.  This is on a Xubuntu 16.04 system updated at least once per day (so, up to date), the 4.4.0-53-generic x86_64 kernel on an HP dx2400 (a Core 2 Duo system).  The installation is from the PPA.  I don't think it makes any difference, but I have set up my own developer account and created a project in order to obtain the security/access token(s).  The other thing I did in the last month is enabling RFC6238 authentication, but it doesn't make sense that everything else is accessible, just not the "root."  I also have the "drive" program installed, its token also obtained before turning on MFA, and running "drive list" does list the "root."

Not super-critical to me, because everything else looks like it's working, but I thought you might like to know there could be a problem.

**Comment by R-Chandra** [comment]
I just fetched google-drive-ocamlfuse_0.6.4-0ubuntu1~ubuntu14.04.1_amd64.deb from the PPA and installed it (with gdebi-gtk; complained a newer version was available, but did it anyway), and it works OK, lists the "root" just fine.

**Comment by astrada** [comment]
Should be fixed in versione 0.6.8. See issue #232.

**Comment by R-Chandra** [comment]
Hey, thanks, dude.  I'll have to give that new version a try.

**Comment by jyn514** [comment]
This is not working for me with version `0.7.1`, I get 'Input/Output error' when I run `ls -l` on the mounted directory. I tried both with and without `-cc`.

```
google-drive-ocamlfuse -d -cc gdrive/ gdrive/
Clearing cache...done
FUSE library version: 2.9.7
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.26
flags=0x001ffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000031
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: ACCESS (34), nodeid: 1, insize: 48, pid: 22726
   unique: 2, error: -38 (Function not implemented), outsize: 16
unique: 3, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 14093
LOOKUP /.xdg-volume-info
getattr /.xdg-volume-info
unique: 4, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 3948
opendir flags: 0x18800 /
   unique: 3, error: -5 (Input/output error), outsize: 16
unique: 5, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 14092
```

**Comment by jyn514** [comment]
I deleted the config file in `~/.gdfuse/default/config` and it seems to be working again. Not sure what happened.
