### ISSUE TITLE
Access to directory mounted at startup

### ISSUE THREAD

**Issue by StefanoGITA** [astrada/google-drive-ocamlfuse#229]
Hi,
i followed the steps showned here http://www.tecmint.com/mount-google-drive-in-linux-using-google-drive-ocamlfuse-client/3/
to mount gdrive at startup of my PC, but i have a problem, i can access at mount directory only by root.
Why?
Down You can check my configuration, can You tell me if I had make something wrong?
Thanks

Stefano G,

stefano@nb-StefanoG:~$ id
uid=1000(stefano) gid=1000(stefano) gruppi=1000(stefano),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare)

stefano@nb-StefanoG:~$ sudo ls -l /mnt
[sudo] password di stefano: 
totale 4
drwxr-xr-x 2 stefano stefano 4096 dic  5 15:25 gdrive

stefano@nb-StefanoG:~$ LC_ALL=c ls -l /mnt
ls: cannot access '/mnt/gdrive': Permission denied
total 0
d????????? ? ? ? ?            ? gdrive

stefano@nb-StefanoG:~$ sudo ls -l /usr/bin/gdfuse 
-rwxr-xr-x 1 root root 77 dic  5 15:23 /usr/bin/gdfuse

stefano@nb-StefanoG:~$ more /usr/bin/gdfuse
#!/bin/bash
su $USERNAME -l -c "google-drive-ocamlfuse -label $1 $*" 
exit 0

stefano@nb-StefanoG:~$ more  /etc/fstab | grep fuse
gdfuse#default	 				/mnt/gdrive 	fuse 	uid=1000,gid=1000 0 	0

stefano@nb-StefanoG:~$ sudo ls -l /mnt/gdrive 
totale 54
drwxr-xr-x 2 stefano stefano 4096 dic  2 09:17 Appoggio
drwxr-xr-x 2 stefano stefano 4096 dic  5 15:10 Auto
drwxr-xr-x 2 stefano stefano 4096 nov 29 09:06 Casa
...
...
...
-r--r--r-- 1 stefano stefano 9946 dic 16 00:11 Ore FormaMentis.ods
drwxr-xr-x 2 stefano stefano 4096 nov 29 10:05 PEDIBUS
drwxr-xr-x 2 stefano stefano 4096 nov 25 09:39 Suonerie

stefano@nb-StefanoG:~$

**Comment by astrada** [comment]
You should add `allow_other` to mount options:

    gdfuse#default	/mnt/gdrive fuse uid=1000,gid=1000,allow_other 0 0

**Comment by StefanoGITA** [comment]
But this is a risk:
http://unix.stackexchange.com/questions/205383/mounting-google-drive-with-google-drive-ocamlfuse

other ideas?

Stefano G.

2016-12-19 10:48 GMT+01:00 Alessandro Strada <notifications@github.com>:

**Comment by astrada** [comment]
The checklist you used is not updated, you should check out this version: https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting
