### ISSUE TITLE
Cannot create files inside GDRIVE FOLDER? "File creation date cannot be modified."

### ISSUE THREAD

**Issue by supercalhotas** [astrada/google-drive-ocamlfuse#231]
Hello there,

I'm having the "File creation date cannot be modified.", when copying/saving files to GDrive with 0.6.7 version of google-drive-ocamlfuse. 
I've read the other issues closed with this problem, but i cannot figure out if the problem is in the newer versions, or it just relates something wrong with the Drive API changes, somewhere between v2/v3 or something....

Thank you for your attention!
Regards!

**CURL LOG (w/ debug enabled)**
>  "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "File creation date cannot be modified.",
    "locationType": "other",
    "location": "file.created_millis"
   }
  ],
  "code": 400,
  "message": "File creation date cannot be modified."
 }

**OPAM show output**
> package: google-drive-ocamlfuse
             version: 0.6.7
          repository: default
        upstream-url: https://forge.ocamlcore.org/frs/download.php/1674/google-drive-ocamlfuse-0.6.7.tar.gz
       upstream-kind: http
   upstream-checksum: e5110d1d1cdae5e5a4053e2771ea12a2
            homepage: http://gdfuse.forge.ocamlcore.org/
         bug-reports: https://github.com/astrada/google-drive-ocamlfuse/issues
            dev-repo: https://github.com/astrada/google-drive-ocamlfuse.git
              author: Alessandro Strada
             license: MIT
             depends: base-threads & camlidl & gapi-ocaml >= 0.2.14 & ocamlbuild & ocamlfind & ocamlfuse & sqlite3
   installed-version: 0.6.7 [system]
  available-versions: 0.2.1, 0.3, 0.3.1, 0.3.2, 0.3.4, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.8, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.8, 0.5.9, 0.5.10, 0.5.11, 0.5.12, 0.5.13, 0.5.14, 0.5.15, 0.5.16, 0.5.17, 0.5.18, 0.5.19, 0.5.20, 0.5.21, 0.5.22, 0.5.23, 0.5.25, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7
         description: A FUSE filesystem over Google Drive
google-drive-ocamlfuse is a FUSE-based file system backed by Google
Drive, written in OCaml.

**Comment by astrada** [comment]
Can you please send the whole curl.log and gdfuse.log to my personal email (alessandro.strada@gmail.com)? Thanks!

**Comment by supercalhotas** [comment]
Closed, some weird OPAM setting, pinned the installation to **0.5.22**, and output **0.6.7** to opam show google-drive-ocamlfuse.

After fix it, did a few tests, working like charm with **0.6.7** now :)
Thanks!
