### ISSUE TITLE
mountpoint ownership and permissions destroyed

### ISSUE THREAD

**Issue by fhteagle** [astrada/google-drive-ocamlfuse#234]
I am unsure of the steps to reproduce, but this has happened twice in about three weeks now. 

'ls -ald' for the mountpoint returns d?????????? for permissions and ? ? ? ? for owner, group, size, and modtime. g-d-o command fails silently (no relevant log entries even with -debug) when the mountpoint is in this state. First time it happened I was able to recover normal functionality by sudo chown and chmod of the mountpoint, but now I get "Input/Output Error" or "Permission Denied" trying to ch or rm -r the mountpoint.

I am using the last automount method suggestion from the Wiki inside of a shell script to accomplish mounting.

Let me know what else you might need for troubleshooting / differential for this ... thanks...

**Comment by fhteagle** [comment]
I am closing this for now as it is "working" at the moment. When I originally posted the bug, "mount" did not show the g-d-o mountpoint as mounted. Checked again just because, and sure enough g-d-o mountpoint was on the list. I umounted, rm'd the g-d-o config dir, and went through the authorization steps again and it is working for now. Will update if I have something more solid later.

**Comment by astrada** [comment]
Something like that happens when you are offline (this should explain why it happens sporadically). In theory, when you get online again, you should be able to access your files. If this doesn't happen, you should remount the file system.

**Comment by fhteagle** [comment]
So the g-d-o fuse entry will not show in the output of the mount command when I am offline?

**Comment by astrada** [comment]
Yes, correct.
