### ISSUE TITLE
question about troubleshooting long transactions

### ISSUE THREAD

**Issue by brancomat** [astrada/google-drive-ocamlfuse#235]
Short version:
are there some quick diagnostics that one can run to see if the mountpoint is working correctly when the `debug` option is not activated?

Long version:
I'm using regularly google-drive-ocalmfuse to backup rather large quantities of data on three unlimited accounts (about 30TB so far).
Every now and then the transition (rsync) stalls and the copy mountpoints hang. Since this happens every 2 to 7 days, I never enabled `debug` to avoid dealing with huge logfiles since it's a rather small server (I know, pure laziness, I should fix this).

Before upgrading to 0.6.x launching `df` with the user mounting the paths showed the google drive mountpoints and I used it basically to see if rsync was actually doing something or if the mountpoints have hanged (in this case, `df` would hang too).
Now I have upgraded to the last version and the mountpoints no longer show launching a `df` so I'm wondering if there's some other quick/correct way to check/monitor the mountpoints status 

thank you

**Comment by astrada** [comment]
Fixed in astrada/gapi-ocaml#13.
