### ISSUE TITLE
"Input/output error" after mount 

### ISSUE THREAD

**Issue by Windywind** [astrada/google-drive-ocamlfuse#237]
Hi,

I am kind of frustrated, after authentication and mount, I got nothing wrong feedback. When I was trying to access the mount point, I got a prompt:

```
[root@centos-512mb-sfo1-01 mnt]# ll
ls: cannot access google-drive: Input/output error
total 0
d????????? ? ? ? ?            ? google-drive
```

The mount point is "/mnt/google-drive/", when I "ll" under "/mnt/", I got some Input/output error, and the folder's properties are unavailable.

Anybody tell me what's wrong?

**Comment by fenixjr** [comment]
looks like what happens when i've got permission issues with fuse mounts. try mounting with -o allow_other and see if you can view files then.

**Comment by Windywind** [comment]
NO luck, still the same.

I mounted as root, accessed as why should I use "allow_other"?

**Comment by vlna** [comment]
Similar issue here, I had to move out Form (Google document type) from Drive root to subfolder. The subfolder with the one file is not accessible now.

**Comment by astrada** [comment]
@Windywind: can you please rerun with `-debug` and send gdfuse.log and curl.log (in ~/.gdfuse/default) to alessandro.strada@gmail.com?
@vlna: can you do the same?
Thanks!

**Comment by Windywind** [comment]
@astrada OK, I will do it now

**Comment by Windywind** [comment]
caused by disabled Google project, problem solved.
