### ISSUE TITLE
fuse: device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by maltokyo** [astrada/google-drive-ocamlfuse#240]
Hello, I received the following when trying to mount for the first time, I cant workout what is wrong.

Kindly help if I miss something!

```
root@server:~# google-drive-ocamlfuse -label email@gmail.com /media/email\@gmail.com
fuse: device not found, try 'modprobe fuse' first
root@server:~# modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab117.16/modules.builtin.bin'
modprobe: FATAL: Module fuse not found in directory /lib/modules/2.6.32-042stab117.16
```

**Comment by astrada** [comment]
Did you updated your kernel without rebooting? If so, a reboot could probably fix it. Otherwise try with `depmod -a`.

**Comment by sbouhnik** [comment]
Hi,

I have ran depmod -a and I got the following error:
root@mp3:~# depmod -a
depmod: WARNING: could not open /lib/modules/2.6.32-042stab127.2/modules.order: No such file or directory
depmod: WARNING: could not open /lib/modules/2.6.32-042stab127.2/modules.builtin: No such file or directory

Can you help ?

Regards,

Shmuel

**Comment by orf53975** [comment]
+1
