### ISSUE TITLE
Ubuntu 16.04 Mount Issue

### ISSUE THREAD

**Issue by jstraw4663** [astrada/google-drive-ocamlfuse#241]
I am having an issue getting google-drive ocamlfuse to mount correctly.

So I'm not really sure what's going on... so if I try to get the size for just the folder, it just sits and "calculates" and never completes (I let it sit for almost 2 mins).

http://imgur.com/ocIrUWs

Also, I noticed that when I check my mount points (using 'df') it is not showing up like it says it should in this guide:
http://www.tecmint.com/mount-google-drive-in-linux-using-google-drive-ocamlfuse-client/3/

http://imgur.com/wXHiY5V

I'm not sure if I'm not mounting it properly or what my issue is.. It is somewhat mounting properly because I can navigate the folders through terminal and see everything on my drive and if I create a new folder/file it is writing to the folder and uploading to drive which shows in the web gui of my google drive but when I try to use it with other applications I get errors (mainly a  `Unable to get free space and unmapped folders for root folder: /home/plex/google-drive/TvShows/: Value was either too large or too small for an Int64. ` error in Sonarr)

**Comment by astrada** [comment]
Can you please remount with `-debug`, run `df` and then send gdfuse.log and curl.log to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by jstraw4663** [comment]
Thank you, attached are the logs, let me know if there is anything that would help.

[Logs.zip](https://github.com/astrada/google-drive-ocamlfuse/files/709351/drive-download-20170116T203643Z.zip)

**Comment by jstraw4663** [comment]
Sent
