### ISSUE TITLE
Space won't release

### ISSUE THREAD

**Issue by Windywind** [astrada/google-drive-ocamlfuse#242]
I used my Google Drive to download some movies, and deleted after got a warning of free space less than 1 GB. However, the space won't release.

I checked from both sides, the machine mounted onto, and the Google Drive page, see nothing from both of them. I believe I have removed all the files and folders.

Any idea? Is this a fuse problem?

**Comment by astrada** [comment]
It shouldn't be a fuse problem. Have you checked your trash? Is it empty?

**Comment by Windywind** [comment]
I didn't even know this (maybe because I cannot see the 'trash' from the mount point. Problem solved, but can you add some features to do with the trash? I removed a file, that means I don' need it any more, not "in trash"...Or maybe just make "rm" from a mounted google drive means "permanent delete"?

**Comment by astrada** [comment]
Trash is mapped in `./.Trash` subdirectory. If you enable `delete_forever_in_trash_folder`, when you remove files in trash, they will be removed permanently. If you use the `-skiptrash` switch, the files will not be trashed.

**Comment by Windywind** [comment]
OK, thanks very much
