### ISSUE TITLE
Can I access google-drive-ocamlfuse via FTP?

### ISSUE THREAD

**Issue by Windywind** [astrada/google-drive-ocamlfuse#243]
This is sort of not a issue, but a question.

I tried to bind mount the google-drive mount point onto `/var/ftp`, which is my anonymous FTP folder. But I can list nothing yet a blank directory.

I don' know what's wrong, anybody has any idea?

**Comment by astrada** [comment]
Looks like user vvcares was able to export his folder via FTP (see issue #245). Maybe you could ask him exactly how he did it.

**Comment by Windywind** [comment]
Well, actually, I kind of solved the problem.

All you need to notice is, remember to mount with the fuse option "-o allow_other".

Very kind of astrada~ :D

Thanks again.
