### ISSUE TITLE
standalone Google Apps Script files

### ISSUE THREAD

**Issue by peter-kehl** [astrada/google-drive-ocamlfuse#244]
Hi Alessandro,

would it be possible to support "standalone Google Apps Script" files from Google drive, please? Those are server-side javascripts created and run at https://script.google.com.

They show up at https://drive.google.com/drive/u/0/search?q=type:script. Google provides limited API to the source of those scripts.

To complicate,
1. each such script ("project") contains of one or more scripts with extension ".gs" (as listed at https://script.google.com).
2. Those ".gs" scripts don't show up as separate files via Google API. Only the parent ("project") shows up.
3. Since those scripts don't count towards user's size quota, the parent shows up with size 0.

See also
http://stackoverflow.com/questions/18445863/how-to-download-google-apps-script
https://developers.google.com/apps-script/import-export#export_projects_from_drive

**Comment by astrada** [comment]
Actually, since version 0.6.7, Apps Scripts should be exported as a json files that contain the full project.

**Comment by peter-kehl** [comment]
Alessandro,

Unfortunately, version 0.6.15 gets an Apps Script as an empty file.  (Potentially related to the fact that Google API shows them with size 0, as they don't count towards user's quota.)

Output from `google-drive-ocamlfuse -debug <mountpoint>` seems to give normal.

https://github.com/astrada/google-drive-ocamlfuse/wiki/Troubleshooting > clearing the cache seems impossible:

```
google-drive-ocamlfuse -cc <mountpoint>
Clearing cache...done
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option

google-drive-ocamlfuse -cc -nonempty <mountpoint>
google-drive-ocamlfuse: unknown option '-nonempty'.
```

How can users install from GitHub source (to experiment)?

Please, advise on the above: clearing the cache and installing from GitHub.

**Comment by astrada** [comment]
Yes, you are right, there is a bug that prevents apps script downloading.

Is the mount point non empty because it is still mounted? If so, I advise you to unmount it first (`fusermount -u <mountpoint>`). Anyway to mount on a non-empty directory you can use `-o nonempty`. To test the github version, and you are using opam, you can use `opam pin` like this:

    opam pin add google-drive-ocamlfuse https://github.com/astrada/google-drive-ocamlfuse.git#master

**Comment by astrada** [comment]
Should be fixed in 0.6.16, that's now on [beta PPA](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta).

**Comment by peter-kehl** [comment]
Thank you for the fix and explanation.

That matches the JSON representation from Google Drive. However, Google Apps Script (https://script.google.com) shows those parts of JSON as separate files.

Ideally, google-drive-ocamlfuse would split one .json file from G. Drive into separate .js (or .gs) local files (and then join them when pushing back to G. Drive). How feasible would it be?

**Comment by astrada** [comment]
No, sorry, it's too complicated. It would require implementing a new virtual file system backed by the json project file. You should probably go for an external editor, e.g.: http://stackoverflow.com/questions/24739294/external-editor-support-for-google-apps-script
