### ISSUE TITLE
Ubuntu with No-GUI - stucked on Gdrive auth

### ISSUE THREAD

**Issue by vvcares** [astrada/google-drive-ocamlfuse#245]
Hi.
Im using digitalocean / ubuntu VPS.
My vps dont have ubuntu GUI.
so once i type 'google-drive-ocamlfuse' , it is looking for a browser to do the google auth.
Is there anyway to do this.?

**Comment by astrada** [comment]
Have you checked [this wiki page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization)?

**Comment by vvcares** [comment]
Hi Astrada. Thank you for your guidance & YES, successfully done.

(Sorry - if my question may out of your topic)
I can see my gdrive folder inside my home/public_html folder. But is this folder can make use of as public access web folder.?
I tried to change the folder permissions to web user name, but seems failed. Via my normal FTP user access, i cant see my folder there.

**Comment by vvcares** [comment]
Seems i got it.
I have to runt the ocamlfuse command as a 'user account'. So now i can use my drive as my hosting space..
