### ISSUE TITLE
Sys_error No such file or directory after first install

### ISSUE THREAD

**Issue by mosteo** [astrada/google-drive-ocamlfuse#246]
Using Ubuntu 16.04.1 amd64 up to date here. I just installed gdo through PPA.

I was next following the Usage page instructions, but with the first 
`$ google-drive-ocamlfuse`
without parameters I get the error:
`Error: Sys_error("/home/user/.gdfuse/default/config: No such file or directory")`

I have tried creating the .gdfuse and .gdfuse/default folders manually, and also touching the config file, but the error persists. The authorization web page doesn't open either.

I could finally workaround the issue with (godo is my alias for the command)
`$ godo -config .gdfuse/default/config`

**Comment by astrada** [comment]
Should be fixed in 0.6.15
