### ISSUE TITLE
unable to delete

### ISSUE THREAD

**Issue by narayana1043** [astrada/google-drive-ocamlfuse#251]
I installed gdrive and now I uninstalled it. However I unable to get rid of the gdrive folder. I even deleted the ~/.gdfuse folder

**Comment by astrada** [comment]
I'm sorry, but what gdrive folder are you referring to?

**Comment by narayana1043** [comment]
Sorry for the confusion.
This is the folder.
/home/$USERNAME/gdrive

Initially I couldn't get rid of this folder, However I managed to login as root immediately after booting and deleted it from there.

The problem I noticed was that the folder permissions are
dr-x------
