### ISSUE TITLE
question about "Shared with me" permissions

### ISSUE THREAD

**Issue by brancomat** [astrada/google-drive-ocamlfuse#253]
I tried the `shared_with_me=true` option (using version 0.6.15) and I can see the `.shared` dir in the mountpoint.
Despite having read/write permissions I can't seem to delete files in a shared directory, but if I use the "add to my Drive" function (via browser) and access the shared directory from the new path created (so not in the `.shared` subdir) I can successfully delete the same files.

Long story short: is the `.shared` directory read only?

**Comment by astrada** [comment]
> Long story short: is the .shared directory read only?

Yes, correct. It's just a view of your shared files.

**Comment by brancomat** [comment]
Thanks, I took the liberty to add the "read-only" bit to the [configuration](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) page in wiki.

**Comment by jmage619** [comment]
Hi, sorry for commenting on an old thread, but are there any plans to allow the shared_with_me files to be writeable if you were granted write access?

**Comment by astrada** [comment]
No, sorry, but you can always add the shared file to your Drive, so it gets writable (if you have permission). https://support.google.com/drive/answer/2375057?co=GENIE.Platform%3DDesktop&hl=en
