### ISSUE TITLE
Use particular GDrive folder instead / of whole drive

### ISSUE THREAD

**Issue by vvcares** [astrada/google-drive-ocamlfuse#255]
Hi team,
We so happy to use this script with our ubuntu droplet.
Is there any possibility to map a particular folder of the Gdrive instead of mapping the wholde drive account?

**Comment by astrada** [comment]
No, sorry. Since this is not an application that syncs your local filesystem with GDrive, remote files are not downloaded unless you access their content (except for Google Docs). So I don't see any advantage in limiting the file-system view to a subdirectory.
