### ISSUE TITLE
Version Installation

### ISSUE THREAD

**Issue by dany20mh** [astrada/google-drive-ocamlfuse#256]
Hi, 

I'm new user to this, and I started using this a few days ago, and I have MacOS 10.12.4, which the only way I could install this was using OPAM, but after the installation it's telling me that I have 0.6.15 and here show the latest version is 0.6.17, I know not much is changed, but I'm not sure if the OPAM didn't get the update, or I'm doing something wrong.

I would appreciate it if someone lead me to right direction.

**Comment by astrada** [comment]
You are right, I've not yet uploaded 0.6.17 to the OPAM repository, but there are no big differences between 0.6.15 and 0.6.17 (just a fix for Google Apps Scripts json files and a useless option removed).

**Comment by dany20mh** [comment]
Thanks :)
