### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by Stayingfalse** [astrada/google-drive-ocamlfuse#259]
This seems to work flawlessly 75% of the time but when using with Plex and trying to stream a file get about 30% of the way then it stops working. When / If I then try and access the mounted folder I get the following error.

ls: cannot access '/Media/Google': Transport endpoint is not connected

If I umount /Media/Google then run google-drive-ocamlfuse -o allow_other /Media/Google again it starts working again but will continue to repeat.

**Comment by astrada** [comment]
If you can use `-debug` to mount your Drive and then send me `gdfuse.log` and `curl.log` (you will find in `~/.gdfuse/default/`) to alessandro.strada@gmail.com, after you get the error it would help me investigate the issue. Thanks.

**Comment by Stayingfalse** [comment]
Enabling Stream Large Files in config has eradicated this issue though with it disabled it seemed to repeat consistently. I assume it was some form of memory/cache issue as some of the files were 5GB+ in size

**Comment by astrada** [comment]
OK, thanks for your feedback.

**Comment by YipYup** [comment]
@astrada Is it possible to pass the -debug parameter when mounting in /etc/fstab ?

Here is what I currently have in my fstab.

`gdfuse#UserLabelHere      /mnt/gdrive  fuse    rw,allow_other  0       0`

**Comment by astrada** [comment]
You could use a wrapper shell script (like the one for [automounting](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting)) and add `-debug` inside that script.

**Comment by animosity22** [comment]
Hmm. I'm getting the same thing once every day or so. I'll setup debug for the next time as it does work superb minus the odd crash.
```
[26258.646605] google-drive-oc[10266]: segfault at 7f1171ff9000 ip 00000000005eea70 sp 00007f114dffa5c0 error 4 in google-drive-ocamlfuse[400000+286000]
```

I setup debug to see if I can capture the next one as

**Comment by animosity22** [comment]
I gzipped up my logs as I got it to happen again. Quite a bit log as almost 40GB uncompressed. I'll email them over.

**Comment by maltokyo** [comment]
What was the resolution for this, I get this error and crash now every 10 min

**Comment by mail2jitu** [comment]
Terminate the session by going to : Runtime -> Manage Sessions, then Click on terminate for the required session. Then you can re-mount the drive. This will resolve the issue.

**Comment by progressify** [comment]
Same problem here with Plex!
How have you resolved it?

**Comment by progressify** [comment]
Same problem here with Plex!
How have you resolved it?
