### ISSUE TITLE
unable to debug

### ISSUE THREAD

**Issue by DragonDon** [astrada/google-drive-ocamlfuse#263]
When I run "sudo google-drive-ocamlfuse -debug ~/google-drive"

I get

"google-drive-ocamlfuse -debug ~/google-driveError: Mountpoint /home/dragondon/google-drive should be an existing directory."

but that IS the directory.

My initial mount command is:

"google-drive-ocamlfuse ~/google-drive"

I'm running this on ChromeOS under Crouton.

I am having syncing issues(as in it ocamlfuse grabs the GDrive initially fine but suddenly it won't update/sync.  I've made changes in Google Drive elsewhere but it's not reflecting any of those updates, despite them being synced between my ChromeBox and Google Drive).  I went to enable the debug option to check but ran into a debug problem(go figure...).

I can view new GDrive folders without any issues but it seems to only do this once and will update GDrive if I create a new folder but it's not grabbing anything after that.

I've restarted the system but it still isn't syncing.

**Comment by astrada** [comment]
It looks like an issue similar to [this one](https://github.com/dnschneid/crouton/issues/891). You should check that your `dragondon` has the same idenitity inside and outside the chroot.

**Comment by DragonDon** [comment]
Seems that it was a permissions thing as "See #624 for a fix: first sudo enter-chroot, then sudo chown -R 1000:1000 "$HOME"." solved the issue.

Thanks!
