### ISSUE TITLE
How to use in Centos?

### ISSUE THREAD

**Issue by lzhqweq1** [astrada/google-drive-ocamlfuse#264]
How to use in Centos? Tkanks~

**Comment by astrada** [comment]
Try with [opam](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#installing-with-opam).

**Comment by lzhqweq1** [comment]
Thank you for you help



tdrobiei@mail.ccsf.edu
 
From: Alessandro Strada
Date: 2017-03-05 00:40
To: astrada/google-drive-ocamlfuse
CC: lzhqweq1; Manual
Subject: Re: [astrada/google-drive-ocamlfuse] How to use in Centos? (#264)
Try with opam.
