### ISSUE TITLE
Using with encrypter drive

### ISSUE THREAD

**Issue by memnos** [astrada/google-drive-ocamlfuse#268]
I have a question.
If my gdrive is encrypted, can i use google-drive-ocamlfuse to mount my gdrive and have my files unencrypted in my local pc?
Obviously i have my password and pass phrase.
Tnx

**Comment by astrada** [comment]
google-drive-ocamlfuse will get your encrypted files as they are on Drive. So you have to decrypt them locally in another directory, otherwise the decrypted files will be uploaded as well.

**Comment by memnos** [comment]
OK, tnx.
Got it.
