### ISSUE TITLE
Possible typo in Jessie docs. 

### ISSUE THREAD

**Issue by nycdubliner** [astrada/google-drive-ocamlfuse#269]
Hi, 

I'm attempting to follow:
https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

It includes the line:
sudo chown root.fuser /dev/fuse

Is there a chance 'root.fuser' is a typo? I'm not usually a debian user, and I'm installing on a Pi3 which I'm new to, so I could be wrong, but that looks wrong.

From a mention here:
https://sourceforge.net/p/fuse/mailman/message/1605376/

Maybe it should be 'root.fuse'.

Thanks.
T.

**Comment by astrada** [comment]
You are right. Fixed. Thanks!
