### ISSUE TITLE
Mount Permissions

### ISSUE THREAD

**Issue by qazero** [astrada/google-drive-ocamlfuse#277]
I mounted gdrive with read only option disabled and i am able to access the contents of drive from all users which is great. However, I am unable to upload/write to gdrive without using the root user account due to permission issues. When trying to edit the permissions of the gdrive mount dir I get the following errors as seen below. Any ideas?

```
root@ix-0475:/mnt# ls -l
drwxr-xr-x 2 root root 4096 Feb 16 22:21 gdrive
rtorrent@ix-0475:/mnt/gdrive$ touch test.txt
touch: cannot touch 'test.txt': Permission denied
root@ix-0475:/mnt# chown rtorrent gdrive
chown: changing ownership of 'gdrive': Input/output error
root@ix-0475:/mnt# chmod 777 gdrive
chmod: changing permissions of 'gdrive': Input/output error

```

**Comment by astrada** [comment]
Have you tried with `-o allow_other`?

**Comment by qazero** [comment]
Yes, no luck.

**Comment by astrada** [comment]
Can you please mount with `-debug` and after you get the `Input/output error` send the log files to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by batgau71** [comment]
Hello ! 

Any news for the question of qazero ? I'm also not able to chmod any file or directory ..

Thanks a lot

**Comment by astrada** [comment]
@batgau71: Could you remount with -debug and (after you get the Input/output error) send the log files (gdfuse.log and curl.log) to alessandro.strada@gmail.com? Thanks!

**Comment by foats** [comment]
@astrada: Do I need to do the same to get an answer?  I'm trying to chmod 755 my files and I get "chmod: changing permissions of '<filename>' : Value too large for defined data type.  I've tried several different mounting options with no luck

**Comment by astrada** [comment]
@foats: yes, please

**Comment by bkayes** [comment]
I just ran into this same issue, and using `-o allow_other` fixed it for me.
