### ISSUE TITLE
incorrect umask/file permissions

### ISSUE THREAD

**Issue by DTrace001** [astrada/google-drive-ocamlfuse#278]
When mounting via google-drive-ocamlfuse file permissions are being set to` -r--r--r--` however other tools such as rclone mounts it with proper permissions based on mask 002  `-rw-rw-r--`.

Expected behavior:
`The default umask of 002 should have default directory permissions of 775 and default file permissions of 664`

Environment:
google-drive-ocamlfuse 0.6.17
Centos 7
system umask 0002
gdfuse config `umask=0o002`
mount `google-drive-ocamlfuse -f -cc -o allow_other,atomic_o_trunc,large_read,default_permissions`

Note:
If you set -o umask=XXX as a mount option it changes both file/dir to be that specific umask option. ie -o umask=002 sets both file and dir as `-rwxrwxr-x`
If you remove the umask entry via the gdfuse config file it changes it back to the default `umask=0o002`
If you change the umask via the gdfuse config it only changes the directory but not the file ie `umask=0o022` will change dir to `drwxr-xr-x` which is correct but file will still be ` -r--r--r--` which is incorrect.

**Comment by DTrace001** [comment]
Updated to 0.6.18 and the same issue occurs as above

**Comment by DTrace001** [comment]
Am I doing something wrong ? Is there a way to have it produce the actual umask necessary or is this a bug ?

**Comment by astrada** [comment]
Sorry, but I cannot reproduce your issue. Anyway, note that Google Docs, Sheets and Slides are read-only by default because they are exported and Google doesn't give access to their native format. So if you only have those kind of files, you cannot get the write permission whichever umask you choose.

**Comment by DTrace001** [comment]
These are mostly video files. Are you unable to reproduce all of the issues or just the umask part ? We could do a screen share if that would help.

**Comment by astrada** [comment]
Files are read-only if one of these conditions apply:
* File is a Google Document
* GDrive API returns field canEdit=false
* `stream_large_files=true` and `large_file_read_only=true`

**Comment by DTrace001** [comment]
Thanks for the info will double check the configs when I can to see if that last condition are both true.
