### ISSUE TITLE
Debian install issue

### ISSUE THREAD

**Issue by DocML** [astrada/google-drive-ocamlfuse#280]
Hello,
unfortunately the provided information how to install this on Debian does not work.
Here is the error:
$ opam depext google-drive-ocamlfuse
opam: unknown command `depext'
Usage: opam COMMAND ...
Try `opam --help' for more information.

That basically means that the following files are not installed (checked via  opam list --rec --required-by google-drive-ocamlfuse):
conf-libcurl 
extlib   
gapi-ocaml  
ocurl  
sqlite3  

Any advise how to install the missing packages on a Debian system?
Thank you!

**Comment by astrada** [comment]
Have you installed the depext plugin with `opam install depext`?

**Comment by DocML** [comment]
Yes, of course I installed opam install depext. But it did not installed all dependencies for Debian Jessie.
I found a description that said to run: sudo apt-get install m4 libcurl4-gnutls-dev libfuse-dev libsqlite3-dev
This installed the missing packages and and I could follow the rest of the instructions.
Thank you!
