### ISSUE TITLE
Shared with me content

### ISSUE THREAD

**Issue by atleta** [astrada/google-drive-ocamlfuse#282]
Hi,

How do I make the files & dirs from 'shared with me' appear in my mount? If it's not supported at the moment, is it something that would be complicated to implement?

**Comment by astrada** [comment]
From the web interface, there is an "Add to My Drive" button (in "Shared with me" section, or in the context menu). Otherwise, you can set `shared_with_me=true` in the config file to have read-only access to all your "Shared with me" files under `./.shared`.

**Comment by avatar-lavventura** [comment]
In which config file does `shared_with_me=true` option exists? @astrada

**Comment by avatar-lavventura** [comment]
I observe that it takes few minutes for shared folder/file to show up under `.shared` folder, is it normal? Why it does not show up right away?

**Comment by rmenes** [comment]
Hi, when I used the method <"Add to My Drive" button> through the drive GUI, I could add a shortcut to the Google Drive, but when I enter the share directory it shows Input/Output error. Also the prorperties of the directory is ???

In this case I was trying to add a folder...

Below the output.

`ubuntu@localhost:~/menes.gdrive$ ls -la |grep Transfer
ls: cannot access 'Transfer': Input/output error
??????????  ? ?      ?             ?            ? Transfer
ubuntu@localhost:~/menes.gdrive$ cd Transfer
-bash: cd: Transfer: Input/output error
ubuntu@localhost:~/menes.gdrive$
`

**Comment by astrada** [comment]
Which version are you using?

**Comment by rmenes** [comment]
> Which version are you using?

google-drive-ocamlfuse, version 0.7.22
Copyright (C) 2012-2020 Alessandro Strada
License MIT

This is a ARM64 system. I am running on my Pine64, running ubuntu

**Comment by astrada** [comment]
Can you please remount with `-debug` and after you get the error, send the log files to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by maximebrunet** [comment]
Same issue here.

**Comment by gussmith** [comment]
> Otherwise, you can set `shared_with_me=true` in the config file to have read-only access to all your "Shared with me" files under `./.shared`.

The config file is rewritten when google-drive-ocamlfuse is called. 
How do you avoid config to be written over? 
doing: 
`google-drive-ocamlfuse -cc `
before to clear cache, does not help. 
Should the file `state` be deleted and keep config before calling google-drive-ocamlfuse?

**Comment by astrada** [comment]
Now the `shared_with_me` is on by default (and it's been removed from the config file).
