### ISSUE TITLE
How to access this by NGINX？

### ISSUE THREAD

**Issue by liwanglin12** [astrada/google-drive-ocamlfuse#284]
I got a 403 error when I trying to access file by nginx

**Comment by simonsmh** [comment]
permission error?
Maybe try to run it as www-data, or run nginx as root.

**Comment by astrada** [comment]
Mount-point permission is set when mounting. But be warned that uid/gid are only persisted for backup purposes. They are not enforced, so any user who can access the mount-point can access any file.

**Comment by liwanglin12** [comment]
thanks. Please close this :-)

2017年4月11日星期二，Alessandro Strada <notifications@github.com> 写道：
