### ISSUE TITLE
Help getting setup

### ISSUE THREAD

**Issue by justinglock40** [astrada/google-drive-ocamlfuse#285]
I cannot get this to run in headless mode for my ubuntu server. Anyone think they could point me in the right direction?

**Comment by gts24** [comment]
https://www.linode.com/docs/applications/cloud-storage/access-google-drive-linode  this should assist. (this may also assist with the install process as well http://www.webupd8.org/2013/09/mount-google-drive-in-linux-with-google.html )

**Comment by astrada** [comment]
@justinglock40: have you checked the [wiki page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization) about headless mode?

**Comment by justinglock40** [comment]
Yea I got through all that stuff but I don't see the files

**Comment by justinglock40** [comment]
So I got the drive mounted however now my applications like Sonarr, Radarr, SABnzd. can't see the mountpoint I create, but in terminal I can see the mount and the files inside. Any idea how I can fix this?

**Comment by dany20mh** [comment]
Make sure you use the allow_other in your mount command and that let others to use the mount point.

**Comment by justinglock40** [comment]
What's the allow other command? if this works by showing as a drive. Will I need rclone for anything or will this take care of everything?

**Comment by justinglock40** [comment]
As far as uploading is concerned?

**Comment by dany20mh** [comment]
So you can use it like this :

google-drive-ocamlfuse -o allow_other ./mountpoint

As far as uploading, I don’t do any upload with any of them so you have to try and see which one is work better for you, but make sure don’t use rclone mount, because than cause ban with google.
