### ISSUE TITLE
Caching Question

### ISSUE THREAD

**Issue by dany20mh** [astrada/google-drive-ocamlfuse#286]
Hi,

I just have quick question about how the caching is working?

So inside the config file there is cache folder section, which if I set it or not, it will only carry a cache.db file that won’t go high that much in size (maybe 15-20 mb), and -cc command will clear that.

And then we have max memory cache, which if I set it to 10Gb, it will exactly use 10Gb of my memory and stay there.

So I’m not sure how the cache handling here, do we only keep the cache inside the memory and when ever the drive unmount or anything else, the cache is gone, or do we have option to cache the stuff inside a folder (on hard drive) too?

I would rater to have the second option too and have a specific storage on the hard for cache.

**Comment by astrada** [comment]
> So inside the config file there is cache folder section, which if I set it or not, it will only carry a cache.db file that won’t go high that much in size (maybe 15-20 mb), and -cc command will clear that.

> And then we have max memory cache, which if I set it to 10Gb, it will exactly use 10Gb of my memory and stay there.

That's if you set `stream_large_files=true`.

> So I’m not sure how the cache handling here, do we only keep the cache inside the memory and when ever the drive unmount or anything else, the cache is gone, or do we have option to cache the stuff inside a folder (on hard drive) too?

Memory cache is just for streaming. If you set `stream_large_files=false`, accessed files will be (fully) downloaded to the persistent disk cache. But be warned that if you have very big files (e.g. videos) those will be fully downloaded to the disk cache before you can access the first byte of the file (so it can be very laggy).

**Comment by dany20mh** [comment]
Thanks for the answer.

For the second part, if we disable the stream, can the file download in the chunk instead of whole file and it save in chunk by chunk ?

**Comment by astrada** [comment]
No, sorry.
