### ISSUE TITLE
upload video photo via command line

### ISSUE THREAD

**Issue by RobertusIT** [astrada/google-drive-ocamlfuse#287]
hi, i possible?

on raspberry pi3 is very slow upload files, like photo with drag and drop. very very slow, a lot of mins only for a picture, and i have a fiber.

**Comment by astrada** [comment]
Is it slow even from the shell (using `cp` for example)?

**Comment by RobertusIT** [comment]
Sei anche tu italiano ma scrivo in inglese per far comprendere a tutti ;)

I'm trying now to use: cp -R
On my Rpi3, i hope to solve with it, because i have a lot of pics and videos, and i want to synch in my google photos without lost my time at pc.
I will inform you about result ;)

Thanks a lot for the support and for this amazing job.

**Comment by RobertusIT** [comment]
With:
cp -R * /home/pi/GDRIVE/Google\ Foto/2016 and i trying to upload video .mp4.

but stay always in process, are uploaded, but stay always in process to elaborate by google.

Instead i upload them from my phone, are available in a couple of mins.

Could be gdrive the reason?

**Comment by hbakhtiyor** [comment]
Hi @RobertusIT, how did you resolve the issue?

**Comment by RobertusIT** [comment]
Upload my photos with this method isn't good because use quota, and you
can't do nothing for that. Is Google that do it when you upload in this
way. But if you upload from web or phone,  no problem.


Il 11 mag 2017 18:13, "Abd ar-Rahman Hamidi" <notifications@github.com> ha
scritto:
