### ISSUE TITLE
Offline usage

### ISSUE THREAD

**Issue by tolgahantunc** [astrada/google-drive-ocamlfuse#289]
Hi,
First of all, thank you for all your efforts to develop this application.
I have been using ocamlfuse for a long time but there is something I am curious about. Can we use this application without the Internet? I cannot access to my drive account, unless I connect the Internet.

**Comment by astrada** [comment]
No, sorry, there is no offline mode. If you need to keep a local copy of your files, you should install a sync app (e.g. https://github.com/odeke-em/drive).

**Comment by tolgahantunc** [comment]
Thank you for answer and suggestion.
