### ISSUE TITLE
Fix documentation: wiki/How-to-install-from-source-on-Debian-Jessie

### ISSUE THREAD

**Issue by achoy** [astrada/google-drive-ocamlfuse#290]
@astrada just want to mention that when I followed the steps on:

https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

you need the step (backquoted opam config env):
eval `opam config env`
before:
`opam depext google-drive-ocamlfuse`

or it doesn't understand: opam depext ..

I was going to add it into that document, but thought I should let you know instead.

**Comment by astrada** [comment]
Feel free to update the docs. Thanks!

**Comment by animosity22** [comment]
I made the change on the on the page as I hit the same issue.
