### ISSUE TITLE
Upload cache status

### ISSUE THREAD

**Issue by gzohop** [astrada/google-drive-ocamlfuse#291]
Hi

I have question about upload cache, how does it work?
When I upload big files it seems that they get copied in to the cache(cache directory is growing) and then uploaded in the background, because when cp command is finished then i see outgoing traffic started and the file is visible on the google drive with size 0, and when background upload stops(outgoing traffic stops) then the file is fully accessible. During the background upload I,m able to clear the cache with -cc command and upload continues so I don't know if it's using the cache or original file.

Is there way to check progress of this background upload process, or to disable it so cp command would be done synchronously with the actual upload?

Regards

**Comment by astrada** [comment]
> Is there way to check progress of this background upload process, or to disable it so cp command would be done synchronously with the actual upload?

Yes, you can set `async_upload=false` in the config file.

**Comment by gzohop** [comment]
Don't know how I missed that options in the config file :)
Thanks :+1:

**Comment by gzohop** [comment]
OK, I've Checked that option but it's no good.
Copy progress works as before and during that time file gets copied to cache I presume. After that actual upload starts and copy operation "hungs" on 100% until upload is finished.
Overall speed is lower because during copy to cache there is no actual upload.
I's faster to use async mode because then after copy to cache upload starts and another file gets copied to cache.

So is there any way to check status of this background upload process?

**Comment by astrada** [comment]
> So is there any way to check status of this background upload process?

No, sorry (FUSE API was not really designed with remote file systems in mind). If you need more control, you should switch to another app (e.g. https://github.com/odeke-em/drive).

**Comment by gzohop** [comment]
Ok, thanks
