### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by neon64** [astrada/google-drive-ocamlfuse#292]
```
Finished, 0 targets (0 cached) in 00:00:00.
File "_tags", line 32, characters 22-31:
Warning: the tag "pkg_oUnit" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
File "_tags", line 35, characters 18-27:
Warning: the tag "pkg_oUnit" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
+ /usr/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package Fuse -package camlidl -package gapi-ocaml -package sqlite3 -package threads -thread -w -d-58 -I src -o src/config.cmo src/config.ml
File "src/config.ml", line 1:
Error: The files src/utils.cmi and /usr/lib/ocaml/curl/curl.cmi
       make inconsistent assumptions over interface Curl
Command exited with code 2.
Compilation unsuccessful after building 6 targets (5 cached) in 00:00:00.
E: Failure("Command ''/usr/bin/ocamlbuild' src/gdfuse.native -tag debug' terminated with error code 10")
```

I have little experience in how OCaml handles packaging, but it seems like my system is has an out of date `/usr/lib/ocaml/curl/curl.cmi` (I'm running Arch and have updated recently)

**Comment by astrada** [comment]
How are you building the app? With opam?

**Comment by neon64** [comment]
I just ran exactly what it described in the README:

```
ocaml setup.ml -configure
ocaml setup.ml -build
```

**Comment by neon64** [comment]
Okay I really have no idea what I'm doing with OCaml, but I made sure the environment variables for opam were set correctly and I ran those two commands again.. This time it is `src/utils.cmi` and `/usr/lib/ocaml/gapi-ocaml/gapiCurl.cmi` that conflict

**Comment by astrada** [comment]
Have you tried following [these steps](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#installing-with-opam)?

**Comment by neon64** [comment]
Okay I apologise - I never saw those instruction initially. They worked like a charm.. Now I suppose the question is, why do the `ocaml setup.ml` commands not work? I'm guessing its because some of the dependencies are missing. That they also means that the ArchLinux PKGBUILDs are missing something, because they didn't build for me either.

**Comment by astrada** [comment]
That's probably caused (as you suspected) by ocurl version mismatch (opam ocurl is newer than arch's one).

**Comment by neon64** [comment]
Okay does that mean that there is a bug in the Arch package? Should I report it?

**Comment by neon64** [comment]
Thank you very much for your help by the way

**Comment by astrada** [comment]
> Okay does that mean that there is a bug in the Arch package? Should I report it?

Sorry, but I don't know enough about Arch packaging to answer. Probably that package doesn't work with opam installed (but it's just a guess).
