### ISSUE TITLE
Mount keeps dropping. Included -debug information below. 

### ISSUE THREAD

**Issue by ml3000** [astrada/google-drive-ocamlfuse#294]
If I do a Plex library scan I can get it to crash instantly. Otherwise 10 minutes into an episode the mount will crash. 

-debug shows the following
```

Thread 9144 killed on uncaught exception Invalid_argument("fill_and_blit")
Thread 9143 killed on uncaught exception Invalid_argument("fill_and_blit")
Thread 9146 killed on uncaught exception Invalid_argument("fill_and_blit")
Thread 9147 killed on uncaught exception Invalid_argument("fill_and_blit")
Thread 9145 killed on uncaught exception Invalid_argument("fill_and_blit")
Fatal error: out of memory.
```
This is a brand new installation as of a couple days ago. I can not seem to get it working well. 

Here is my config file:

```
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=
client_secret=
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=1073741824
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=10485760
metadata_cache_time=60
presentation_format=pdf
presentation_icon=
read_ahead_buffers=5
read_only=false
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=true
umask=0o002
verification_code=
```

Here is what I am using to mount.

`google-drive-ocamlfuse -debug -o allow_other,atomic_o_trunc,large_read,default_permissions /home/msrlrocket/PlexO`

Help would be greatly appreciated. Thank you.

**Comment by astrada** [comment]
Can you please send your gdfuse.log to my email (alessandro.strada@gmail.com)? Thanks

**Comment by saitoh183** [comment]
im having a similar issue after over a month of stability.
Using ubuntu 16.10 server and I was force to remove large_read or else I get fuse: invalid argument but I worked the first time I ran it.

here is the message i found in the dmesg:

```
[106639.227651] google-drive-oc[20671]: segfault at 6597bb933000 ip 00000bb73589ea96 sp 00006597a8b842c0 error 4 in google-drive-ocamlfuse[bb73559a000+3a1000]
[106639.227668] grsec: From 24.202.151.170: Segmentation fault occurred at 00006597bb933000 in /usr/bin/google-drive-ocamlfuse[google-drive-oc:20671] uid/euid:0/0 gid/egid:0/0, parent 
/lib/systemd/systemd[systemd:1] uid/euid:0/0 gid/egid:0/0
```
There was nothing in the gfuse.log file

**Comment by astrada** [comment]
@saitoh183: next time can you send me your core dump (enable it with `ulimit -c unlimited`)? Thanks!

**Comment by saitoh183** [comment]
@astrada what is the exact command you want me to run.. Sorry I'm not very versed in Linux debugging. Someone suggested that I run dmesg and post the output here.

**Comment by astrada** [comment]
@saitoh183: `ulimit -c unlimited` enables processes to produce a core file when they segfaults (see http://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-when-a-process-gets-a-segmentation-fault). So if you run that command before google-drive-ocamlfuse segfaults, you will get a `core` file that you can send me for further analysis.

**Comment by saitoh183** [comment]
Ok, I will

**Comment by saitoh183** [comment]
is it space intensive because when i added verbose or debug to ocamlfuse, the file grew so fast that i had to stop it before it eat up all the disk space

**Comment by saitoh183** [comment]
@astrada sorry for not replying sooner but the mount hasn't dropped since my last post. So when it does, I will
