### ISSUE TITLE
Huge Data Usage

### ISSUE THREAD

**Issue by shadowsbane0** [astrada/google-drive-ocamlfuse#296]
I'm running your software on an Ubuntu AWS server. I'm experiencing huge data usage and the only explanation is my mounted Google Drive. I'm blowing TB of data a day. I'm going to currently have to stop using your product because right now I'm at over $500 in data overage fees. I'm not synchronizing my Google Drive locally and I'm only adding a few GB of data to it in a given day. So what is going on behind the scenes that is blowing up to data out in the TB of data. I will say that my Google Drive account is a business account that has around 15TB of data. The data was already there before I started using your product.

**Comment by animosity22** [comment]
Can you see what's accessing those files? The product really doesn't "do" anything unless you have something accessing the data that is mounted.

**Comment by hjone72** [comment]
@shadowsbane0 do you have streaming enabled?

See here: https://github.com/astrada/google-drive-ocamlfuse/issues/248

**Comment by shadowsbane0** [comment]
@animosity22 - Folder or file access from Google Drive wouldn't be an issue because it would be considered inbound data which Amazon doesn't charge for.

@hjone72 - Negative on the streaming. 


As I mentioned I have a Google Apps account with about 15TB of data. On a given day I add a few GB to that total through the mount point. I should only see the amount of usage for the data that I put to the various folders within the mount point. 

In the past three days my server blew through 10TB of outbound data. I can assure you I did not transfer that amount of data to my Google Drive folders. In that time span I only had one large data transfer to my Google Drive of 54GB of which I killed it at 52 percent once I was alerted to the insane outbound data rate. I added 10 files of less than 2GB each and about 20 files of less than 300mb each. None of that adds up to 10TB of data. This server is solely used to put data to my Google Drive account. 

I've installed NTOP on my server in hopes of getting a clear picture of where so much data is going. Unfortunately, so far it only shows me that data is outbound to the internal interface on the AWS server. I cannot see the NAT'ing that is going on or the external interface to monitor how much and where that traffic is going. NTOP is a new app to me so I may have to do some tweaking of it to get the results I want. I went with the AWS Lightsail because it was supposed to save me money - that didn't really work out.

**Comment by shadowsbane0** [comment]
@animosity22 - BTW I do run Plex but I run Plex Cloud and it connects directly to my Google Drive through it's own API outside of my Amazon AWS instance.

**Comment by animosity22** [comment]
@shadowsbane0 - turn on -verbose on your mounts options and you can see what files are being accessed. You can also run "lsof "</MOUNTPOINT" as root to see what files are currently being used. You have some processing that's doing something causing the outbound data as it's not the mount directly.

**Comment by shadowsbane0** [comment]
@animosity22 - I'll do that. I've also got a junk laptop that I'm going to setup to mirror my AWS server. I can use it on my main ISP without any extra cost to see if I can replicate and nail down the issue. I can't do it on my AWS server right now because ANYTHING I do on it right now is costing me an extra $100 a day until the billing cycle rolls over. I currently have it stopped so the bleeding of my cash flow will end.

**Comment by mikeferr** [comment]
This happens to me to. Followed @animosity22 post on rclone forum [https://forum.rclone.org/t/403-forbidden-with-google-drive-impossible-to-use-rclone-mount/1955/4?](url). As soon as I initiated a library scan in a fresh Emby install. It starts downloading gigabytes and gigabytes of data. So I went back to scanning using a straight up rclone mount and that works fine.

**Comment by animosity22** [comment]
@mikeferr - Emby does a 'ffprobe' of each file on first scan and it depends on how the mount handles opening up the file. You can run rclone with -vv to see the difference or run this with debug or verbose. It only does that probe one time unless the mod time on the file changes. You would really need @astrada to comment on how seeking of a file works or if it grabs a full file.

If you ever lose your mount and rescan, you have to re-ffprobe the file again as it doesn't retain the info. Plex handles that via 'do not delete on scan' or something along those lines. 

To me, that's really understanding how the tool works and using it for the proper use-case. Emby with ffprobe doesn't play nice with this, but rclone does. Rclone doesn't play nice with Plex, but this really does.

**Comment by astrada** [comment]
> You would really need @astrada to comment on how seeking of a file works or if it grabs a full file.

It depends: if `stream_large_files=true`, it downloads only the chunk containing the requested bytes (2 chunks if the requested segment crosses chunk boundary). Otherwise, it will download the full file unless there is a valid copy in the cache.

**Comment by animosity22** [comment]
That seems to be ok when I did some testing with ffprobe as it works as I expected.

@mikeferr  - did you have sream_large_files=true setup? I ran a ffprobe with that and it seems to work properly:

```
felix@plex:/media/TV/NCIS$ time ffprobe NCIS.S13E19.HDTV-1080p.mkv
ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from 'NCIS.S13E19.HDTV-1080p.mkv':
  Metadata:
    encoder         : libebml v1.3.1 + libmatroska v1.4.2
    creation_time   : 2016-03-22 20:45:47
  Duration: 00:43:27.98, start: 0.000000, bitrate: 12898 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 11386481
      BPS-eng         : 11386481
      DURATION        : 00:43:27.939000000
      DURATION-eng    : 00:43:27.939000000
      NUMBER_OF_FRAMES: 62528
      NUMBER_OF_FRAMES-eng: 62528
      NUMBER_OF_BYTES : 3711906229
      NUMBER_OF_BYTES-eng: 3711906229
      _STATISTICS_WRITING_APP: mkvmerge v8.4.0 ('A better way to fly') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.4.0 ('A better way to fly') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-03-22 20:45:47
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-03-22 20:45:47
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1: Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s (default)
    Metadata:
      BPS             : 1509749
      BPS-eng         : 1509749
      DURATION        : 00:43:27.979000000
      DURATION-eng    : 00:43:27.979000000
      NUMBER_OF_FRAMES: 244498
      NUMBER_OF_FRAMES-eng: 244498
      NUMBER_OF_BYTES : 492174474
      NUMBER_OF_BYTES-eng: 492174474
      _STATISTICS_WRITING_APP: mkvmerge v8.4.0 ('A better way to fly') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v8.4.0 ('A better way to fly') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-03-22 20:45:47
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-03-22 20:45:47
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

real	0m2.031s
user	0m0.020s
sys	0m0.004s
```

Roughly 2 seconds for a 4G file is pretty fast.

**Comment by mikeferr** [comment]
@animosity22 nope, I didn't have stream_large_files=true, I might try setting it up again this weekend. Got a "download quota reached" on google drive when I scanned my library though the rclone mount.

**Comment by animosity22** [comment]
@mikeferr - that would download every single file on the plex scan. Also, ACD doesn't support mod times and gogle does. So if, you may have to re-analyze if you change from ACD to GD in Plex, which is time consuming and annoying.

**Comment by shadowsbane0** [comment]
So, I finally finish rebuilding a local test server...wow! I installed EtherApe on it and I see the issue and it's a big one. Currently, there are seven different connection to Google Servers each consuming around 35-50 Mbps because I'm using qBittorrent directly to my folders. Average file size is around 850 bytes but the amount of data being transferred is incredibly more than what I'm putting into the folders. I've only added 1GB of data to my Google Drive folders but I've transferred 18.39GB on one connection 16.06 on another, and on it goes for each connection. All told in only a three hour period I've hit the Google servers for 62GB of data out for the 1GB of data in actual file space.


________________________________

**Comment by animosity22** [comment]
A torrent use case is not really a good one for cloud storage since it has to read entire files and such. I'd recommend using local storage for that over a cloud one as the IOPs needed for torrenting would be painful.
