### ISSUE TITLE
More of a question.

### ISSUE THREAD

**Issue by Dark-Witcher** [astrada/google-drive-ocamlfuse#297]
I have used this for my Linux Mint for some time now. I was wondering is there a way to use it (the way it connects to drive and mounts it as a network drive) in Windows? I know that this isn't the place to ask, but I didn't find any definitive answer on the web.

**Comment by astrada** [comment]
No, I don't think so. Not yet, at least, until Microsoft implements [this feature](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13522845-add-fuse-filesystem-in-userspace-support-in-wsl).

**Comment by Dark-Witcher** [comment]
Thank you for the response.
