### ISSUE TITLE
metadata question

### ISSUE THREAD

**Issue by animosity22** [astrada/google-drive-ocamlfuse#299]
I was trying to make sure I had the right setting in terms of keeping the "metadata" cache up longer.

I normally move files to my cloud storage at very planned intervals and can refresh my mount if needed to update the cache by remounting it.

If I run a few ls commands, I usually do that to prime up the cache, but I'm not sure what is keeping the state of it in the config and how long it normally does that by default:

```
felix@plex:/TV$ time ls -alR | wc -l
14936

real	0m0.508s
user	0m0.040s
sys	0m0.052s
felix@plex:/TV$ time ls -alR | wc -l
14936

real	0m1.268s
user	0m0.044s
sys	0m0.056s
felix@plex:/TV$
felix@plex:/TV$
felix@plex:/TV$ time ls -alR | wc -l
14936

real	0m1.567s
user	0m0.040s
sys	0m0.068s
felix@plex:/TV$ time ls -alR | wc -l
14936

real	0m1.667s
user	0m0.044s
sys	0m0.060s
```

My first one takes roughly 30 seconds, but the next few come back insanely fast. I wasn't sure if that was a function of the ocamlfuse that I can config or it was auto_cache doing it's thing so I figured I'd just ask to make sure I had it properly.

**Comment by astrada** [comment]
Metadata are cached in a sqlite3 DB, and changes are pulled from the API every `metadata_cache_time` (in the config file) seconds.

**Comment by animosity22** [comment]
Ok. I'm just trying to figure this out:

/GD -my ocamlfuse mount
/TV - my ocamlfuse and local storage unionfs-fuse mount 

The /GD always takes 10 seconds to list out which doesn't seem bad.
My /TV mount takes 30 - 60 seconds the first time, but is instant after that.

```
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
15317

real	0m11.174s
user	0m0.264s
sys	0m0.564s
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
15317

real	0m10.796s
user	0m0.156s
sys	0m0.520s
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
15317

real	0m10.756s
user	0m0.224s
sys	0m0.488s
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR /TV | wc -l
14936

real	0m1.551s
user	0m0.040s
sys	0m0.060s
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR /TV | wc -l
14936

real	0m0.498s
user	0m0.048s
sys	0m0.044s
felix@plex:/GD/media/smu5ej34ujbdoip1cm3mlk92q4$ time ls -alR | wc -l
15317

real	0m10.860s
user	0m0.212s
```
I'm not sure what is causing my unionfs mount to respond so much faster than the other mount.

```
/usr/bin/unionfs-fuse -o cow,allow_other,direct_io,auto_cache,sync_read /local/tv=RW:/media/TV=RO /TV
```

My GD mount:
```
/usr/bin/google-drive-ocamlfuse /GD -o allow_other,auto_cache -verbose >> /home/felix/.gdfuse/default/mount.log 2>&1 &
```

Any thoughts?

**Comment by animosity22** [comment]
Seems like when I do a ls -alR on the mount, it does check every file form the db:

```
[1484.495524] TID=210828: BEGIN: Loading resource /media/smu5ej34ujbdoip1cm3mlk92q4/vvph2hckkfr210fkn0ev5m6lp9lfvj7m49v3flr7v144h523h9c0/1ads5a714a6e696rq278kvdpuht9rrvri6775uhe39totv930h34c0sfmh9f015ftvbljgvho68b0 (trashed=false) from db
[1484.495683] TID=210828: END: Loading resource /media/smu5ej34ujbdoip1cm3mlk92q4/vvph2hckkfr210fkn0ev5m6lp9lfvj7m49v3flr7v144h523h9c0/1ads5a714a6e696rq278kvdpuht9rrvri6775uhe39totv930h34c0sfmh9f015ftvbljgvho68b0 (trashed=false) from db: Found (id=14857, state=ToDownload)
```

but on my fuse mount, it seems to never go back to /GD until a ~5 minutes or so go by and it rechecks.

**Comment by astrada** [comment]
Probably unionfs does some caching on its own (probably in memory).

**Comment by animosity22** [comment]
Cool. Thanks for the info.
