### ISSUE TITLE
Streaming Question

### ISSUE THREAD

**Issue by animosity22** [astrada/google-drive-ocamlfuse#300]
I'm just trying to make sure I'm not really using double memory so I wanted to make sure I got how the streaming memory settings work. I use ocamlfuse mount with rclone encrypt. I turned off the 1G buffer I had with rclone currently.

I run with
```
max_cache_size_mb=100000
max_memory_cache_size=8000000000
max_retries=8
memory_buffer_size=536870912
metadata_cache_time=600
read_ahead_buffers=5
read_only=false
stream_large_files=true
```

So my theory was for each file I'm streaming, I will cache min ~500M as it seems to grab that in the beginning from my bandwidth consumption and it seems to work as I would expect it. At that point, i have a ~8GB cap so in theory, I should be able to hit ~16 streams at 500x16=~8GB of memory.

I bumped read_ahead to 5 from the default of 3 as I saw that in a different post, but I'm not really sure if 3 to 5 really impacts much.

I've toyed with some various 'min' settings from 10M all the way up to 1G as the goal for me would be to buffer up as much as I can to ensure that no playback issues occur. I used to do that with a rclone mount with the 1G buffer so each file opened would buffer up to 1G. 

Hope that make sense and if my assumptions were correct.

**Comment by astrada** [comment]
With that setup, you get 14 blocks of 512MB. When you access the first byte of a file, it starts downloading the first block (of 512MB), then it spawns 5 threads to download the next 2.5GB of the same file. If you access another file, it does the same, starting to download 3GB (in 6 parallel threads). There are still 2 free blocks (you used 2 blocks for streaming and 10 blocks for read-ahead), so if you access a third file, you start downloading 3GB of this new file: you download the first GB, but then you need 4 more blocks. The oldest 4 blocks (sorted by last access) will be reused and overwritten by the content of this new file.

**Comment by animosity22** [comment]
That helps a bit. So I'm configured bigger than I wanted and I can tweak my config to do what I want. Thanks for the detailed reply.

I'm going to drop down to 50M so I get around 250M with the 5 threads in my buffer. That should be plenty.
