### ISSUE TITLE
Mount Not Updating

### ISSUE THREAD

**Issue by sbcrumb** [astrada/google-drive-ocamlfuse#302]
For Some reason my mount is not updating. Not showing what is most recent in my google drive.
I see the changes on the web some from yesterday, that today don't reflect on my linux mount. What would be the reason for this?

**Comment by YipYup** [comment]
Have you tried clearing the cache, or checking your caching settings?

**Comment by sbcrumb** [comment]
Yes just did a cache clear and my cache settings are the default of 60. Still is not updating.

**Comment by YipYup** [comment]
Can you confirm your mount is still active? I do something like:
`df -h`

**Comment by sbcrumb** [comment]
Yes it is still active. I see some files still just not all. Also just rebooted and remounted it..

**Comment by astrada** [comment]
Should be fixed in v0.7.0+.
