### ISSUE TITLE
cannot access 'googledrive': Input/output error

### ISSUE THREAD

**Issue by XanderStrike** [astrada/google-drive-ocamlfuse#304]
I see there are other similar issues but they're all closed with solutions that don't make sense in my context.

I authenticated headlessly if that matters, using the same drive account that https://github.com/prasmussen/gdrive has no trouble accessing, so I know the API is enabled and working.

Mounting appears to succeed, but when trying to access the folder I get this error every time:

```
root@prox:~# google-drive-ocamlfuse googledrive
root@prox:~# ls googledrive
ls: cannot access 'googledrive': Input/output error
```

When running with `-debug`, it hangs forever here:

```
root@prox:~# google-drive-ocamlfuse -debug googledrive
Starting application setup (label=default, base_dir=).
[0.000243] TID=0: Loading configuration from /root/.gdfuse/default/config...done
Opening log file: /root/.gdfuse/default/gdfuse.log
```

After waiting a few minutes, I kill it with Ctrl+C. The log file mentioned in the above contains the following:

```
[0.000551] TID=0: Setting up default filesystem...
[0.000578] TID=0: BEGIN: Saving configuration in /root/.gdfuse/default/config
[0.000724] TID=0: END: Saving configuration in /root/.gdfuse/default/config
[0.000761] TID=0: Loading application state from /root/.gdfuse/default/state...done
Current version: 0.6.17
Setting up cache db...done
Setting up CURL...done
Refresh token already present.
[0.001427] TID=0: Starting filesystem googledrive
[0.004797] TID=1: init_filesystem
[99.844196] TID=0: Exiting.
Waiting for pending upload threads (0)...done
CURL cleanup...done
Clearing context...done
```

And finally the contents of my configuration. I haven't modified it manually and the client_id/secret are correct:

```
root@prox:~# cat .gdfuse/default/config
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=<redacted>
client_secret=<redacted>
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
presentation_format=pdf
presentation_icon=
read_ahead_buffers=3
read_only=false
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
umask=0o022
verification_code=
```

I'm not sure where the problem would come from, I know the credentials are correct and the API is working. My drive may be unusually large (15tb in 16,000 files) but the root directory only has a handful of folders in it.

**Comment by astrada** [comment]
> When running with -debug, it hangs forever here:

With `-debug` the process remains in foreground, so you should open another shell to access your mountpoint. Then, when you get an input/output error, you can check the log files (and in curl.log you should see if Drive returns some kind of auth error).

**Comment by XanderStrike** [comment]
Ah thank you, didn't realize I needed to access the drive to get debug information. I was getting the drive disabled error, which is bizarre because it was definitely enabled (as gdrive works).

Disabling it and re-enabling it appears to have worked.
