### ISSUE TITLE
Unable to locate package google-drive-ocamlfuse

### ISSUE THREAD

**Issue by davidcmag** [astrada/google-drive-ocamlfuse#307]
Every time I try to install google-drive-ocamlfuse It gives me the message that it's unable to locate the package.  Any help?

thanks.

sudo apt-get install google-drive-ocamlfuse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package google-drive-ocamlfuse

**Comment by astrada** [comment]
Have you added my PPA to your repositories?

    sudo add-apt-repository ppa:alessandro-strada/ppa
    sudo apt-get update

**Comment by davidcmag** [comment]
Yes.  I finally got it to load, however, because it's a headless ubuntu
server, I don't know how to finish the setup.  there is no browser on the
headless server.

Can you possibly help?

Thanks


On Sun, May 21, 2017 at 3:33 PM, Alessandro Strada <notifications@github.com

**Comment by davidcmag** [comment]
I don't have admin access to my google drive account, so I can't create a new project to get the id and the secret for the command line.   Any help would be appreciated.  thanks

**Comment by astrada** [comment]
If you have another box with a browser, you can authorize the application on that PC, and then copy `~/.gdfuse/default/state` to your headless box.

**Comment by fjen** [comment]
It's not necessary that the application id and secret come from the same google account as the gdrive. Just use another one.

**Comment by davidcmag** [comment]
ok.  I've authorized the app from a browser on my mac, and successfully got the "The application was successfully granted access. Please wait for the client to retrieve the authorization tokens." message.  However, where do I find ~/.gdfuse/default/stat to copy and paste?

thanks for your help!!

**Comment by astrada** [comment]
No, that file would be present if you ran the application on your mac. If you run the application from the headless box, copy the link on your mac and authorize it, it should be enough to wait for the application to fetch the refresh token. If it timeouts, you should retry.

**Comment by jsjcjsjc** [comment]
I have the sam problem, it looks there is problem on your PPA?

```
W: Failed to fetch http://ppa.launchpad.net/alessandro-strada/google-drive-ocamlfuse-beta/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by astrada** [comment]
@jsjcjsjc: I'm sorry but jessie is not an Ubuntu distribution. Packages are available for artful, zesty, xenial, and trusty.

**Comment by sneha-gathani** [comment]
I am facing this problem.
According to your answer, i added
"sudo add-apt-repository ppa:alessandro-strada/ppa"
"sudo apt-get update"
but i still face the same problem -


sudo apt-get install google-drive-ocamlfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package google-drive-ocamlfuse

**Comment by astrada** [comment]
If you are using colab (that uses an obsolete Ubuntu version), please check this workaround: https://github.com/astrada/google-drive-ocamlfuse/issues/493#issuecomment-422380636
