### ISSUE TITLE
Cannot mount drive

### ISSUE THREAD

**Issue by tjustice86** [astrada/google-drive-ocamlfuse#309]
I am trying to mount my drive on a headless ubunbtu server. After installaing and authorizing I try to mount the drive and I get this:
 `fuse: device not found, try 'modprobe fuse' first
`

I run modprobe fuse and get this:
`modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab120.16/modules.builtin.bin'`

**Comment by astrada** [comment]
Looks like you are using an old kernel (see https://askubuntu.com/questions/687369/could-not-open-builtin-file-modules-builtin-bin).

**Comment by fjen** [comment]
It's not only an old kernel but also an openvz container. Fuse be enabled on the provider side.

**Comment by tjustice86** [comment]
Once I have the provider enable fuse, will I be able to mount the drive?
