### ISSUE TITLE
Input/output error after mounting

### ISSUE THREAD

**Issue by halolordkiller3** [astrada/google-drive-ocamlfuse#310]
Not sure why but after I issue the command google-drive-ocamlfuse -label me ~/google/ (even running as root) I get a cannot access 'google': Input/output error when I do a ls. I have even tried allow_other for permissions and still nothing.

Ubuntu Server 16.04 4.11 kernel and I'm on the latest beta 6.19

**Comment by astrada** [comment]
You should remount with `-debug` and then (after running ls in the mountpoint) check `~/.gdfuse/[label]/curl.log` to find what kind of error you are getting from Drive API.

**Comment by halolordkiller3** [comment]
it seems to be stuck at opening log file (unless its because it thinks its trying to open a gui

**Comment by astrada** [comment]
After mounting you have to reproduce the Input/output error, then you should check curl.log.

**Comment by halolordkiller3** [comment]
is there a way to do this headless? it seems it just wants to get stuck at opening log file

**Comment by astrada** [comment]
With `-debug` the process remains in foreground, you should open another shell (or add an `&` to the mount command).

**Comment by halolordkiller3** [comment]
[https://i.gyazo.com/b61a9e985cc556309bf5458b6cea22f7.png](url)

**Comment by halolordkiller3** [comment]
I'm an idiot forgot to enable gdrive api lol you can close this
