### ISSUE TITLE
Got no Tokens

### ISSUE THREAD

**Issue by Wigberg** [astrada/google-drive-ocamlfuse#311]
Hello, i got the issue that i get no tokens from google. 
I tryed both, login via google, and via oauth, but there is no tokens for me, what can i do?

**Comment by astrada** [comment]
You should enable logging with `-debug`, then check the logs to see if you are getting timeout errors (or cannot connect errors if you are behind a proxy).

**Comment by Wigberg** [comment]
ok, it seems my libcurl3-amd64 and libcurl3-gnutls is to new for this, after downgrade to an older libcurl*  i got the tokens, after upgrade it i dont get tokens just a timeout and the message 
[23.143984] TID=0: Retrying (1/8)
[24.948649] TID=0: Error during request: Code: 35, Description: CURLE_SSL_CONNECT_ERROR, ErrorBuffer: gnutls_handshake() failed: Public key signature verification has failed.

**Comment by astrada** [comment]
OK, thanks for your feedback!
