### ISSUE TITLE
Caching is not working properly

### ISSUE THREAD

**Issue by Nodens-** [astrada/google-drive-ocamlfuse#312]
Specifically while a file is still in cache and uploading, any file read operations are not pointing to the cache but to what looks like a 0 byte stub file.
This breaks functionality of every backup software that is trying to perform any kind of "file written" verification after it finishes writing.
Disabling async upload is a workaround that works but
a) It slows the filesystem to a crawl
b) Does not help when there's additional caching or asynchronous transfers from elsewhere (eg samba aio).

Please see here for complete information on my investigation and perhaps you can shed some more light on what is going on: https://github.com/rfjakob/gocryptfs/issues/112

**Comment by astrada** [comment]
Should be fixed in version 0.6.21 (beta channel).

**Comment by Nodens-** [comment]
Confirmed. Behavior on 0.6.21 looks normal now.
