### ISSUE TITLE
Streaming Large Files: The download quota for this file has been exceeded.

### ISSUE THREAD

**Issue by tcf909** [astrada/google-drive-ocamlfuse#315]
When the following conditions are met:
1) -verbose or -debug are used
2) large files are set to stream
3) a file has exceeded its download quota
4) The file that has exceeded its download quota is opened.

Result:
The log fils up with what I believe to be string encoded binary data.

version: 0.6.19 (built with opam)

**Comment by astrada** [comment]
Should be fixed in 0.6.20 (beta channel).
