### ISSUE TITLE
First run does not open a web page

### ISSUE THREAD

**Issue by LinuxClassicist** [astrada/google-drive-ocamlfuse#318]
As the terminal copy / paste below shows, I run a (plain vanilla) Ubuntu Linux 17.04. I do  a daily distribution-upgrade.

My problem is that google-drive-ocamlfuse has never called a webpage to authorize access to my Google account.

[code]
bruce@CatoMinor:~$ uname -a
Linux CatoMinor 4.10.0-23-generic #25-Ubuntu SMP Fri Jun 9 09:39:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
bruce@CatoMinor:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
bruce@CatoMinor:~$ cat .gdfuse/default/config
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=
client_secret=
connect_timeout_ms=60000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
presentation_format=pdf
presentation_icon=
read_ahead_buffers=3
read_only=false
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
umask=0o022
verification_code=
bruce@CatoMinor:~$ google-drive-ocamlfuse 
Cannot get token. Quitting.
bruce@CatoMinor:~$ 
[/code]

**Comment by astrada** [comment]
Your should restart it with `-debug`, then check gdfuse.log and curl.log (in ~/.gdfuse/default/) to see what kind of error you are getting (it looks like you cannot access the authorization endpoint).

**Comment by joma74** [comment]
Similar has happened to me on Ubuntu 16.04. Never called a webpage to authorize access to my Google account. But did not quit either.
What worked is to set Firefox as the default browser via Ubuntu Details/Default Applications. On restarting `google-drive-ocamlfuse` the authorization worked again seamless. Note that Chromium has been set as the default browser before.
