### ISSUE TITLE
High i/o wait on one core

### ISSUE THREAD

**Issue by ro345** [astrada/google-drive-ocamlfuse#319]
First, thanks for this great software.

I am seeing a situation where every few days or sometimes hours, i/o wait on one core will spike to 100%.  If I kill google-drive-ocaml process the i/o wait goes back down to zero.  It generally just happens on one core, and it seems to happen when very little is being done on the google-drive.  I can run iotop and see that no traffic is being processed through the drive.  The next time it happens, I will look in the logfile to see if there is any issue there.  Normally, I just kill the process and it starts over.  Normally, I wouldn't care too much, but the high io wait causes my plex transcode process to not kick off, due to the high load (even though I'm not processing on the google-drive, just a local drive).  Rclone crypt is layered over top of google-drive.  Below is the output from my top:

```
top - 06:32:21 up 29 days, 22:33,  1 user,  load average: 1.00, 1.00, 1.00
Tasks: 199 total,   1 running, 198 sleeping,   0 stopped,   0 zombie
%Cpu0  :  0.3 us,  0.0 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu1  :  1.0 us,  0.0 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu2  :  1.7 us,  0.0 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  :  2.4 us,  0.3 sy,  0.0 ni,  0.0 id, 97.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem : 12303700 total,   233288 free,  2069696 used, 10000716 buff/cache
KiB Swap:  1048572 total,   866316 free,   182256 used.  9806772 avail Mem
```

Notice CPU 3 is 97% wait, load is exactly 1.

**Comment by astrada** [comment]
Which version are you running?
