### ISSUE TITLE
Feature request: endering directories by ID (including from shared links)

### ISSUE THREAD

**Issue by vi** [astrada/google-drive-ocamlfuse#321]
google-drive-ocamlfuse shows only my Google Drive content.

I want to be able to enter arbitrary folders shared with me. It can be implemented as a special directory like `.by-id`.

Bonus if anonymous access (mounting shared link to google drive without logging in) will work.

If this is not possible it should be mentioned in README.

**Comment by astrada** [comment]
> google-drive-ocamlfuse shows only my Google Drive content.

You can access shared files that are not in your drive `shared_with_me=true`. They will be available in the special directory `.shared`.

> Bonus if anonymous access (mounting shared link to google drive without logging in) will work.

Drive API doesn't allow anonymous access.

**Comment by vi** [comment]
This should be mentioned in README or some documentation linked from README.

How do input ID from sharable link to the google-drive-ocamlfuse without going though browser? Just `cd` into `.shared/<ID>` doesn't work.

Idea: supporting entering URI-named directories, like `cd 'https://drive.google.com/open?id=ABCDE0987...21'`.

**Comment by vi** [comment]
Added a bullet point for this in README in #322.

**Comment by astrada** [comment]
That option is already documented in the [configuration page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) of the [wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki). The wiki is already referenced by README.
