### ISSUE TITLE
A lot of files have been renamed

### ISSUE THREAD

**Issue by PSOHart** [astrada/google-drive-ocamlfuse#323]
![gdriveocalm](https://user-images.githubusercontent.com/29763723/27664034-a6844562-5c65-11e7-9145-bf537d9716a6.jpg)
As you can see in the picture, some folders and files have been renamed, but only in the mount point (right is the same folder on Windows) and everything looks fine on the web.

Recreate the mount and reboot does not solve the problem.
It's rather problematic because I was planning to sync with a Seafile folder and the names must be the same.
Thanks in advance.

**Comment by astrada** [comment]
Folders/files get renamed if there is more than one file/folder with the same name.

**Comment by PSOHart** [comment]
That's what I thought and I double check but there is no duplicate on the Drive.
Is there a way to clear the cache or something ?
Maybe clean and reinstall ?

**Comment by astrada** [comment]
> Is there a way to clear the cache or something ?

The `-cc` command line option clears the cache before mounting.

**Comment by PSOHart** [comment]
Perfect
Unmount, clear the cache, remount, the folders and files have the correct names.
Thank you
