### ISSUE TITLE
opam update gives [ERROR] <snip> Unsupported protocol git+https

### ISSUE THREAD

**Issue by berni421** [astrada/google-drive-ocamlfuse#324]
Having googled the error - I am none the wiser, suggesting something in git needs a fix. 

Can anyone re-assure these errors from opam wont affect the installation of google-drive-ocamlfuse...

$ opam update
[default] Downloading https://opam.ocaml.org/1.2.0/urls.txt
Updating ~/.opam/repo/compiler-index ...
Updating ~/.opam/compilers/ ...
Updating ~/.opam/repo/package-index ...
Updating ~/.opam/packages/ ...
[ERROR] At ~/.opam/repo/default/packages/i3ipc/i3ipc.0.1.1/opam:8:52:
  Unsupported protocol git+https
[ERROR] At ~/.opam/repo/default/packages/secp256k1/secp256k1.0.2.5/opam:10:51:
  Unsupported protocol git+https

I am following the procedures here, on an up to date jessie system: https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

Huge thanks,

Bernie

PS: So far the install seems to work for me. I am guessing the two borked packages are not used or the particular versions are ignored. But experience tells me an ERROR is not something to leave unexplained.

**Comment by astrada** [comment]
> Can anyone re-assure these errors from opam wont affect the installation of google-drive-ocamlfuse...

Yes, those errors are caused by unrelated packages.

**Comment by kurdtpage** [comment]
I have the exact same error on Debian Jessie (fresh install). Running `opam update` (or any other opam command) after this gives:
`Please run 'opam init' first to initialize the state of OPAM.`
