### ISSUE TITLE
Not able to build with opam

### ISSUE THREAD

**Issue by sk2212** [astrada/google-drive-ocamlfuse#325]
sandro@sandro-mint ~/Git $ opam install depext
The following actions will be performed:
  ∗  install ocaml-variants 4.06.0+trunk+safe-string  [required by ocaml]
  ∗  install ocaml          4.06.0                    [required by depext]
  ∗  install depext         1.0.4                   
===== ∗  3 =====
Do you want to continue ? [Y/n] Y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-variants.4.06.0+trunk+safe-string
        (This might be due to outdated metadata, in this case run 'opam update')

What is wrong here? Of course I have run 'opam update' before.

**Comment by astrada** [comment]
It looks like opam cannot find a compiler and it tries to install the latest experimental one. Maybe you have to run `eval $(opam config env)` or you have to re-init opam with `opam init --comp 4.04.2`.
