### ISSUE TITLE
Expects camlidl files at wrong location

### ISSUE THREAD

**Issue by jollyrogers88** [astrada/google-drive-ocamlfuse#326]
google-drive-ocamlfuse expects com.a, com.cma, com.cmi and com.cmxa to be at /usr/lib/ocaml/comlidl
but they are at /usr/lib/ocaml/

See also https://aur.archlinux.org/packages/google-drive-ocamlfuse-git/

**Comment by astrada** [comment]
Please, try installing with OPAM (https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#installing-with-opam). And be sure to use version 4.04.2 of the compiler.
