### ISSUE TITLE
delete google trash folder

### ISSUE THREAD

**Issue by snoopy0815** [astrada/google-drive-ocamlfuse#328]
Thank you for your perfect program and for sharing with us.

Is it possible to delete the content of the Trash folder with it?

cheers.

**Comment by snoopy0815** [comment]
To make it more concrete :
I get an error message telling me that I have not enough rights to delete files or folders inside the trash folder. 
Everything else works like a charm...

**Comment by astrada** [comment]
> Is it possible to delete the content of the Trash folder with it?

You should set `delete_forever_in_trash_folder=true` in config.

**Comment by snoopy0815** [comment]
Hello astrada,

Thank you very much for your quickhelp!!
After changing this setting this to `true` - and un-mounting / re-mounting the drive it works perfectly fine :)
THANK YOU :)
Cheers.
