### ISSUE TITLE
Automount at rc.local

### ISSUE THREAD

**Issue by jiangjiangflies** [astrada/google-drive-ocamlfuse#329]
Hi, 
I tried to automount by adding this command `/usr/bin/google-drive-ocamlfuse -label me /gdrive` in /etc/rc.local but it doesn't work. I think this way is much easier but I don't know what's the problem.

**Comment by krusic22** [comment]
Try using full path at /gdrive.
I personally use a cronjob @reboot

**Comment by xxx31fr** [comment]
Follow the tuto for automount and change gdfuse with sed command 
I william sens youthe full command to pass when i'm at home
