### ISSUE TITLE
Problems with cache?

### ISSUE THREAD

**Issue by jrpelegrina** [astrada/google-drive-ocamlfuse#330]
Hello

I'm using google-drive-ocalmfuse (Ubuntu xenial 16.04) and when I drop a document on the google-drive web, the document only appears in my "local" folder (mounted with google-drive-ocalmfuse) only if I clear the cache Or if in the "local" folder I modify an existing document or add a new file.

If I add a document to the "local" folder, it immediately appears on the google-drive web

Is this normal?

a greeting

**Comment by astrada** [comment]
The local mountpoint is updated only every `metadata_cache_time` seconds (default is 60 seconds). So it's normal not to see the added document immediately after adding it to you Drive from the web interface.

**Comment by jrpelegrina** [comment]
First of all thanks for the quick response ...

The problem is that after the metadata_cache_time the document is not displayed. I launched the debug log and do not see the cache update after that time ....

**Comment by astrada** [comment]
The update is not automatic, you need to run some command to refresh the mountpoint (e.g., `ls`).

**Comment by jrpelegrina** [comment]
OK
On another computer works perfectly may be due (as I read in other issues) to the amount of google docs that has the google-drive account, which causes it not to cache correctly

Thank you
