### ISSUE TITLE
Slow streaming speeds

### ISSUE THREAD

**Issue by xxtensazenxx** [astrada/google-drive-ocamlfuse#332]
When streaming video (plex) or pulling files from my google drive in general I only get about 30mbit/s consistantly, making the streaming of large files impossible. My server definitely has the bandwith, and I get full speed when downloading files from chrome in my browser (550mbit/s at least). Is there any settings I can change to improve this or is it a bottleneck that can't be avoided?
Thanks!

**Comment by astrada** [comment]
You can try modifying this config options: max_memory_cache_size, memory_buffer_size, read_ahead_buffers (see the [wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) to know what those parameters are used for).

**Comment by xxtensazenxx** [comment]
After messing with settings I (kind of ) got it. But the downloads always start off really slow and crawl up to my max download speed eventually, making it take long for streams, due to the download speed not starting at a good speed. is there any other settings? 

Thanks again for your help

**Comment by astrada** [comment]
> is there any other settings?

No, sorry.
