### ISSUE TITLE
fail to build on Fedora 26 

### ISSUE THREAD

**Issue by sergiomb2** [astrada/google-drive-ocamlfuse#333]
Hi, 
I got some solicitations to build google-drive-ocamlfuse on Fedora 26 , but all versions that I tested  doesn't build. The last one almost build, pass configuration ... but fails on compilation, you may check the logs here [1] 
Thanks

[1]
 https://copr-be.cloud.fedoraproject.org/results/sergiomb/google-drive-ocamlfuse/fedora-26-x86_64/00582597-google-drive-ocamlfuse/build.log.gz
https://copr-be.cloud.fedoraproject.org/results/sergiomb/google-drive-ocamlfuse/fedora-26-x86_64/00582597-google-drive-ocamlfuse/
https://copr.fedorainfracloud.org/coprs/sergiomb/google-drive-ocamlfuse/build/582597/

**Comment by astrada** [comment]
From the logs, it looks like there is some problem with ocamlnet package in Fedora 26 (netsys library is provided by ocamlnet).

    Error: Files /usr/lib64/ocaml/netsys/netsys_oothr_mt.cmxa
       and /usr/lib64/ocaml/threads/threads.cmxa
       make inconsistent assumptions over implementation Thread

**Comment by sergiomb2** [comment]
Thanks for the feedback we are fixing it now [1]

[1]
https://bugzilla.redhat.com/show_bug.cgi?id=1474762
