### ISSUE TITLE
Speed limit setting ? 

### ISSUE THREAD

**Issue by MasterCATZ** [astrada/google-drive-ocamlfuse#334]
Uploading to Google always kills our internet, I believe this is from our ISP throttling our upload 
 the connection becomes completely unstable and unusable until upload finishes
( after many disconnections ) 

would it be possible to set our maximum upload/download speeds? 

unfortunately, our QoS does not work because it's not manually configurable and thinks there is plenty of bandwidth free while our ISP throttles at 50% bandwidth

**Comment by astrada** [comment]
Yes, you can specify `max_download_speed` and `max_upload_speed` (check the [wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) for further info).

**Comment by krusic22** [comment]
I don't want to open another issue just for one question so I'm just going to as it here.
Why is the upload so slow. I have a server with a 200Mbps/200Mbps connection. When you try to download a file it waits for 5 seconds then slowly starts ramping up the download speed till it hits somewhere around 10Mbps. But uploading... it never goes above 1Mbps. When I try to upload via the normal drive interface (Inside Chrome)  it downloads and uploads instantly.

**Comment by astrada** [comment]
That's is caused by limitations in Drive API combined with FUSE. If you need maximum upload/download speed, try other Drive clients: e.g. https://github.com/odeke-em/drive or https://github.com/ncw/rclone.
