### ISSUE TITLE
Upload failed for large files in 32 bit OS

### ISSUE THREAD

**Issue by pedrom71** [astrada/google-drive-ocamlfuse#335]
I have installed google-drive-ocamlfuse in Raspbian (Raspberry Pi), which is 32-bit. When I copy a large file (> 512 mb aprox), the app throw an error and don't upload the file. In debug mode, throw this error:

Thread 16396 killed on uncaught exception Sys_error("Value too large for defined data type")

Is there any way for upload large files in a 32-bit OS? I tried in config with max_upload_chunk_size=805306368 and with max_upload_chunk_size=536870912, with the same result.

**Comment by astrada** [comment]
Can you please send your log files to my email (alessandro.strada@gmail.com), after getting the error? Thanks!

**Comment by pedrom71** [comment]
I sent you the email

**Comment by astrada** [comment]
OK, thanks. It looks like an error similar to [this one](http://caml-list.inria.narkive.com/cSnYm3FW/error-opening-large-file#post5). Maybe you can try to recompile the OCaml compiler with `-D_FILE_OFFSET_BITS=64`.

**Comment by pedrom71** [comment]
The generated file `setup.data` after command `ocaml setup.ml -configure` contains this lines:
```
architecture="arm"
ccomp_type="cc"
ocaml_version="4.01.0"
standard_library_default="/usr/lib/ocaml"
standard_library="/usr/lib/ocaml"
standard_runtime="/usr/bin/ocamlrun"
bytecomp_c_compiler="gcc -fno-defer-pop -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC"
native_c_compiler="gcc -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT"
```

In bytecomp compiler and native compiler already contains the flag `-D_FILE_OFFSET_BITS=64`. So is already compiled with that flag, I guess. I don't know any other way to compile it with ocaml.

**Comment by astrada** [comment]
Maybe you can try installing google-drive-ocamlfuse with OPAM (see https://blog.danny-willems.be/ocaml-raspberry-pi/, but instead of ocaml 4.03.0, that's quite old, you can install ocaml 4.04.2). See also [this link](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#installing-with-opam) for installing instructions with OPAM.

**Comment by pedrom71** [comment]
The error is still ocurring. I installed OPAM and ocaml 4.04.2, and then installed google-drive-ocamlfuse with opam. The error is the same, when I copy a 1Gb file, throws the same error.

I also tried installing google-drive-ocamlfuse from source with last version of ocaml (4.05.0), but ocurs the same error.

**Comment by astrada** [comment]
I see, sorry. When I have some spare time, I will try to reproduce the issue on a virtual machine.

**Comment by pedrom71** [comment]
Have you found a solution for that problem?

**Comment by astrada** [comment]
No, sorry. I'm on vacation and I don't have a stable connection. Feel free to try another Drive client (e.g.: https://github.com/odeke-em/drive or https://github.com/ncw/rclone).
