### ISSUE TITLE
How to install in Arch?

### ISSUE THREAD

**Issue by fliegentoeter** [astrada/google-drive-ocamlfuse#336]
Hello,

how do you install this package in Arch Linux?

The version from the AUR seems to be outdated and cannot be build. Comments in the AUR regarding this issue are from month back.

Using OPAM to install from source also fails:
"The following dependencies couldn't be met:
  - google-drive-ocamlfuse -> gapi-ocaml (< 0.2.14 | >= 0.2.1) -> ocamlnet >= 3.5.1
Your request can't be satisfied:
  - ocamlnet is not available because your system doesn't comply with ocaml-version >= "4.00.0" & ocaml-version < "4.05.0" & compiler != "4.04.0+flambda".
  - ocamlnet>=3.5.1 is not available because your system doesn't comply with ocaml-version >= "4.00.0" & ocaml-version < "4.05.0" & compiler != "4.04.0+flambda".

No solution found, exiting"

I am really looking for an solution to mount my google drive folder in Arch...

**Comment by astrada** [comment]
You can try with version 4.04.2 of the compiler:
    opam switch 4.04.2
    eval `opam config env`

Then you should be able to install ocamlnet.
