### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by xzl2021** [astrada/google-drive-ocamlfuse#338]
Hello, author.
When I use `aria2c`(a download tool) to download a large file directly to my mounted google drive, there always occur error: 
`Transport endpoint is not connected.`
This error always occured when the download processed about 50%.
After that, I must remount google drive, and download restart.
But when download processed about 50%, the error occured again.
I have sent log files to your gmail:  alessandro.strada@gmail.com
So, are there anything advice for me? Thanks a lot.

**Comment by astrada** [comment]
Closing as the problem seems to be in aria2.
