### ISSUE TITLE
[Feature request]: Mount your TeamDrives

### ISSUE THREAD

**Issue by rmartin-rp** [astrada/google-drive-ocamlfuse#339]
Since Team Drives has been released I would love to be able to mount a Team Drive in my file system.
Do you think that can be a big problem to implement?

Thanks for all this!

**Comment by astrada** [comment]
The problem is that this feature it's only available as part of G Suite, and I don't have a G Suite account.

**Comment by astrada** [comment]
Closing as duplicate of #288.
