### ISSUE TITLE
Translated directory names don't work

### ISSUE THREAD

**Issue by coderforlife** [astrada/google-drive-ocamlfuse#340]
Google Drive supports some characters in the online interface (e.g. /) that are automatically translated to underscores when mounted due to difficulties in using them in path names (this happens on Windows as well as with this FUSE driver). However with this FUSE driver it gets confused by the files while the Windows program handles them nicely.

If I do an `ls` in a directory containing directories whose names have a `/` which has been replaced by `_` I get errors and I cannot descend into or even `ls` those directories. Here is the output from an `ls`:

```
$ ls Google\ Drive/Google\ Photos
ls: cannot access 'Google Drive/Google Photos/2002-07 Scouts_Album 1': No such file or directory
ls: cannot access 'Google Drive/Google Photos/1999 Scouts_Album 2': No such file or directory
ls: cannot access 'Google Drive/Google Photos/2005-12 Scouts_Album 3': No such file or directory
'1999 Scouts_Album 1'     '2014-08 Album 1'
'2001-2005 Album 2'       '2014-08 Album 3'
'2002-07 Scouts_Album 2'  '2014-09 Album 4'
'2005-12 Scouts_Album 3'  '2015-07 Album 5'
...
```

(note that the inaccessible directories show up in red when listed instead of blue).

**Comment by astrada** [comment]
I'm sorry but I cannot reproduce your problem (I don't get album names under Google Photos directory). Can you please remount with `-debug` and after reproducing the error, send the log files (curl.log and gdfuse.log in ~/.gdfuse/default) to my email (alessandro.strada@gmail.com)? Thanks!

**Comment by coderforlife** [comment]
Shortly after submitting this bug I renamed those folder and since I have tried quite a few things to reproduce this myself, but I have failed to reproduce it. If I ever come across it again I will send more information.
