### ISSUE TITLE
after mounting the second time, nothing shows up

### ISSUE THREAD

**Issue by ryo204** [astrada/google-drive-ocamlfuse#342]
The first time I mount with the command
    $ google-drive-ocamlfuse -label label [mountpoint]
it works.

After a reboot, no other mounting attempts were fruitful. Sometimes, using the command above will open the authorization grant page, sometimes it won't start anything. But even if the token has been successfully received, running ls on the mounting drive doesn't show any files in gdrive.

**Comment by mediapinta** [comment]
Hi, I have a similar problem and I solved it removing the content of ~/.gdfuse/default directory (as pointed [here](https://github.com/astrada/google-drive-ocamlfuse/issues/327#issuecomment-313847352) by astrada).

I hope it helps you.

Greetings,
ifrit
