### ISSUE TITLE
automount during startup

### ISSUE THREAD

**Issue by xxx31fr** [astrada/google-drive-ocamlfuse#345]
Hello, 
I tried to follow the dedicated wiki about automouut, i always fail to automount google-drive-ocamlfuse....

I need to run at startup this command:

`google-drive-ocamlfuse -debug -label gdrive /mnt -o allow_other,atomic_o_trunc,default_permissions,nonempty`

I tried to add it in /etc/rc.local directly, but itfails.
I tryied to create de gdfuse in /usr/bin and and add the referer into fstab...but it fails too.
Maybe, the wiki is not enough clear with me.

Can you, please, help me with a detailled step by step for setup automount google-drive-ocamlfuse.
I'm running ubuntu 16.04
Thank you.

**Comment by xxx31fr** [comment]
found the solution

**Comment by thebitbrine** [comment]
@xxx31fr Please share it with us.

**Comment by nrajasekharan** [comment]
Get it to work by changing the mount command in Startup Applications to the following:

google-drive-ocamlfuse "/home/thebitbrine/gdrive"
