### ISSUE TITLE
Problems in the first run

### ISSUE THREAD

**Issue by Coalijes** [astrada/google-drive-ocamlfuse#349]
I just finished the installation on ubuntu14x64bit

But I am unable to start using ocamlfuse. See below my code and the error I am getting.

`root@ubuntu:/# google-drive-ocamlfuse`
`/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found`
`/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found`
`/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found`

Could you please help me?

**Comment by astrada** [comment]
If you are using a headless host, you should follow these [instructions](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-%26-Authorization).

**Comment by Coalijes** [comment]
Great,

I followed the instructions and it worked perfectly

Thanks a lot and keep up the good work!
