### ISSUE TITLE
Install just doesn't work for me

### ISSUE THREAD

**Issue by Danny02** [astrada/google-drive-ocamlfuse#35]
Hi I just found out about your project and wanted to give it a try. I'm a complete ocaml noob, so it is totally possible that I did something wrong.

So I did the following:
$ wget http://www.ocamlpro.com/pub/opam_installer.sh
$ sh ./opam_installer.sh /usr/local/bin
$ opam init
$ eval 'opam config env'
$ opam install google-drive-ocamlfuse

then at "installing xmlm.1.1.1" I get:
W: Field 'ocamldoc' is not set
E: Cannot find external tool 'ocamldoc'

any help would be greatly appreciated.

**Comment by JohnathanMarkSmith** [comment]
I am still getting this error:

[ERROR] No package named google-drive-ocamlfuse found

**Comment by astrada** [comment]
Try running `opam update` before `opam install google-drive-ocamlfuse`.
