### ISSUE TITLE
Text file interpreted as "binary" by Google after writing

### ISSUE THREAD

**Issue by tonebender** [astrada/google-drive-ocamlfuse#353]
Not sure if this is google-drive-ocamlfuse's fault.
But, after editing a text file located in my (mounted) Drive and saving it with the text editor, Google Drive (in browser) will no longer preview it when double-clicking. It turns out it thinks it's a binary file. Before editing and saving, it was interpreted as "text" by Google and I could easily view it.
The text editor is Geany in linux and I've never had any issues with it. Opening the text file, after editing, it looks perfect.
Any idea why this happens?

Thanks in advance!

**Comment by tonebender** [comment]
I might add -- saving the txt file locally and then copying it to Drive (with cp in linux terminal) will make it show up as txt (not binary) in Drive in browser.

**Comment by astrada** [comment]
When you upload a file, the extension determines its MIME type. Unfortunately that info is not modifiable once the file is created, so if your editor creates a temporary file without extension and then renames it to `.txt`, your file on Drive will still have `application/octet-stream` as MIME type.

**Comment by tonebender** [comment]
Ah, that makes sense! I guess I could fix it by saving everything to a temporary spool directory or so, which I then copy to gdrive.
Thanks for the quick reply!
