### ISSUE TITLE
ocamlfuse on Ubuntu 14.04 uploads are very slow

### ISSUE THREAD

**Issue by kellnerp** [astrada/google-drive-ocamlfuse#358]
For a 638MB upload more than 2 hours was predicted. 
The connection is fast > 10mb/s
The indicated upload speed is ~68kB/sec
ocamlfuse was run in a terminal with debug on to watch the behavior.
ocamlfuse seems to be rewriting files that it has already written (they can be opened in a Navigator window.)
ocamlfuse seems to be getting a report back from google drive (error -2)  that a file doesn't exist when it does and then proceeds to re-upload the file. This will change the icon from a preview to a clock for a file that was previously uploaded.
error -61 comes up a lot assiciated with GETXATTR
For example this snapshot of debug output was taken when the last file uploaded was DSC00094.JPG
```
 opcodeunique: 223031, opcode: WRITE (16), nodeid: 337, insize: 4176, pid: 6577
write[0] 4096 bytes to 1449984 flags: 0x8001
   write[0] 4096 bytes to 1449984
   unique: 223031, success, outsize: 24
unique: 223032, opcode: GETXATTR (22), nodeid: 337, insize: 68, pid: 6577
getxattr /17.10.04-소요산/SONY/DSC00073.JPG security.capability 0
   unique: 223032, error: -61 (No data available), outsize: 16
unique: 223033, opcode: WRITE (16), nodeid: 337, insize: 4176, pid: 6577
write[0] 4096 bytes to 1454080 flags: 0x8001
   write[0] 4096 bytes to 1454080
   unique: 223033, success, outsize: 24
unique: 223034, opcode: GETXATTR (22), nodeid: 337, insize: 68, pid: 6577
getxattr /17.10.04-소요산/SONY/DSC00073.JPG security.capability 0
   read[0] 131072 bytes from 2998272
   unique: 222311, success, outsize: 131088
unique: 223035, opcode: READ (15), nodeid: 332, insize: 80, pid: 10014
read[0] 131072 bytes from 3260416 flags: 0x48000
unique: 223036, opcode: READ (15), nodeid: 332, ins

```

**Comment by astrada** [comment]
If you need maximum upload speed, consider using https://github.com/odeke-em/drive or https://github.com/ncw/rclone.

**Comment by kellnerp** [comment]
I was aware of those. But is this program not supported anymore?

**Comment by kellnerp** [comment]
I was aware of those. But is this program not supported anymore?

**Comment by astrada** [comment]
Sure it is. But slow uploads are caused by FUSE + Drive API. So if you need fast uploads, feel free to use another client.

**Comment by kellnerp** [comment]
Thanks. What I needed to know.

**Comment by kellnerp** [comment]
Thanks. What I needed to know.

At least as far as fuse is concerned have you filed a bug report? I have no idea what to tell them if I do it.

**Comment by astrada** [comment]
> At least as far as fuse is concerned have you filed a bug report? I have no idea what to tell them if I do it.

No, it's not a bug. The problem is that FUSE is not designed to serve remote filesystems.
