### ISSUE TITLE
Installation on Debian Jessie failed - ERROR while installing zarith.1.6

### ISSUE THREAD

**Issue by snoopy0815** [astrada/google-drive-ocamlfuse#361]
Unfortunately my system on a Raspberry Pi had to be reinstalled from scratch (google-drive-ocamlfuse has been working perfectly before).
I've followed again this instruction https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie but this time I've got the following errors after this command:

  **opam install google-drive-ocamlfuse**

results in the error-message:
   **[ERROR] The compilation of zarith failed at "make".**

Does anybody has experienced this failure before? What can I do?
Thanks for any hints.

---------------------------------
**This is the full text-output after command "opam install google-drive-ocamlfuse"::**

```bash
The following actions will be performed:
  ∗  install zarith                 1.6       [required by cryptokit]
  ∗  install cryptokit              1.12      [required by gapi-ocaml]
  ∗  install gapi-ocaml             0.3.4     [required by google-drive-ocamlfuse]
  ∗  install google-drive-ocamlfuse 0.6.21
===== ∗  4 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[cryptokit] Archive in cache
[gapi-ocaml] Archive in cache
[google-drive-ocamlfuse] Archive in cache
[zarith] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of zarith failed at "make".
Processing  1/4: [zarith: ocamlfind remove]
#=== ERROR while installing zarith.1.6 ========================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/pi/.opam/system/build/zarith.1.6
# compiler     system (4.02.3)
# exit-code    2
# env-file     /home/pi/.opam/system/build/zarith.1.6/zarith-2822-ad8886.env
# stdout-file  /home/pi/.opam/system/build/zarith.1.6/zarith-2822-ad8886.out
# stderr-file  /home/pi/.opam/system/build/zarith.1.6/zarith-2822-ad8886.err
### stdout ###
# [...]
# ocamldep -native  z.ml q.ml big_int_Z.ml z.mli q.mli big_int_Z.mli > depend
# ocamlc   -c z.mli
# ocamlc   -c z.ml
# ocamlc   -c q.mli
# ocamlc   -c q.ml
# ocamlc   -c big_int_Z.mli
# ocamlc   -c big_int_Z.ml
# ocamlmklib -failsafe -o zarith z.cmo q.cmo big_int_Z.cmo -lgmp
# gcc -DZ_OCAML_HASH -DZ_OCAML_COMPARE_EXT -DHAS_GMP     -c -o caml_z_arm.o caml_z_arm.S
# <eingebaut>: die Regel für Ziel „caml_z_arm.o“ scheiterte
### stderr ###
# project.mak:138: depend: Datei oder Verzeichnis nicht gefunden
# Name "main::extra" used only once: possible typo at ./z_pp.pl line 29.
# caml_z_arm.S: Assembler messages:
# caml_z_arm.S:25: Error: junk at end of line, first unrecognized character is `,'
# make: *** [caml_z_arm.o] Fehler 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
  ∗  install cryptokit              1.12
  ∗  install gapi-ocaml             0.3.4
  ∗  install google-drive-ocamlfuse 0.6.21
The following actions failed
  ∗  install zarith 1.6
No changes have been performed

```

**Comment by snoopy0815** [comment]
additional: I've digged a little deeper in Zarith 1.6 where an update of **caml_z_arm.S** took place a month ago.
the following lines of code seemed to be the problem.

```bash
/* makes the stack non-executable. */
        .section .note.GNU-stack,"",@progbits
```

if I comment-out the .section   at least I'm able to install Zarith on its own following the installation guideline on https://github.com/ocaml/Zarith

but how can I do this in the context of google-drive-ocamlfuse - cause by following the installation guide there, the file **caml_z_arm.S** gets overwritten again - including the unwanted additional line of code...

Does anybody have any ideas?  - or maybe I'm in a totally wrong direction?

cheers...

**Comment by astrada** [comment]
You can try downgrading zarith to 1.5:

    opam pin add zarith 1.5

**Comment by snoopy0815** [comment]
Hi astrada,

perfect hint - I was not aware of this command.
It worked like a charm for me and google-drive-ocamlfuse is up and running since a few minutes again :)

I've added a pull request @ Zarith - https://github.com/ocaml/Zarith/issues/14
  based on a hint by bschommer how the real issue can be fixed.

Thank you so much for your help!
cheers.
