### ISSUE TITLE
How can I force sync using a command?

### ISSUE THREAD

**Issue by Jimster121** [astrada/google-drive-ocamlfuse#364]
Hello,

I would like to know if there is a command telling your software to sync with Google Drive. Also, can I use this on a launcher? I am using XFCE 4.12 as my desktop environment.

Thanks

**Comment by astrada** [comment]
I'm sorry, but this is not a sync tool. It just lets you mount your Google Drive as a local filesystem, but you have to be online as there is no offline mode. Consider using https://github.com/odeke-em/drive or https://github.com/ncw/rclone.

**Comment by Jimster121** [comment]
Thank you for your fast response! I would like to add that it actually syncs the changes I made to a file, I just had to open the Google Drive folder.
