### ISSUE TITLE
Access to Folder shared by link

### ISSUE THREAD

**Issue by cfra** [astrada/google-drive-ocamlfuse#369]
Sorry if this has been documented or should be obvious, I did not find it and am not too familiar with Google's products.

I received files by someone sending me a link to a google drive and I would like to access those. They are currently accessible by "Owner" and "anyone with the link (can view)".

How can I tell google-drive-ocamlfuse to mount that folder?

**Comment by astrada** [comment]
If you [add them to your Drive](https://support.google.com/drive/answer/2375057?co=GENIE.Platform%3DDesktop&hl=en), those files will be available as standard files.

**Comment by cfra** [comment]
Okay, that solves the issue for me, thank you. Just out of curiosity, I am trying to download huge uncompressable files and right now the `cp` is "hanging" after having `open`ed the first file of the output, but having written 0 bytes.

I assume this is because Google insists on wasting their CPU time "compressing" stuff and then sending them after that is complete so that the transfer cannot be streamed in a sensible way?

**Comment by astrada** [comment]
> I assume this is because Google insists on wasting their CPU time "compressing" stuff and then sending them after that is complete so that the transfer cannot be streamed in a sensible way?

No, if you don't enable streaming, files are downloaded to the cache before being accessible. But note that if you enable streaming, large files are made read-only by default.

**Comment by cfra** [comment]
Ah, I found it, and you replied even faster than that. Just for reference if anybody should stumble across this being in the same situation as me:

I have put the following into `.gdfuse/default/config`
<pre>large_file_read_only=true
large_file_threshold_mb=16
stream_large_files=true</pre>
Now it seems to work reasonably well. 

@astrada thank you for writing this excellent piece of software. I was beginning to fear I would never get those 200GB of video footage scattered out of Google Drive without being driven insane. Your software actually made it usable. If we should ever meet in a bar, drinks are definitely on me.
