### ISSUE TITLE
Burns cycles doing MD5 checksums on files I've never accessed

### ISSUE THREAD

**Issue by gunslingerfry** [astrada/google-drive-ocamlfuse#370]
I lost my logs so I can't post them here but what I was seeing was a CPU core getting eaten up by gdfuse doing md5 checksums on cache entries for files I've never navigated to. Large video files. 

Those files don't really need to be accessible nor cached so I added the stream large files option and I've moved my directory structure around and used the new root folder option to only include data I care about so this may not happen again. If it does, I'll post here. Is there a scheduled task to generate md5 sums and it was just taking a really long time?

**Comment by astrada** [comment]
> Is there a scheduled task to generate md5 sums and it was just taking a really long time?

No, md5 checksum is recalculated only before downloading, to check if the cached copy is still synchronized. Maybe the Drive API was returning that those files have been modified (maybe just metadata) and that triggered downloading those files again.

**Comment by gunslingerfry** [comment]
Ok. So there's still problems. My curl log is 11G overnight gdfuse.log is 124M overnight. I'm going to turn off the curl logging. It also allocated 1.1GB of virt memory and filled my swap. I'm going to restart this and start logging the gdfuse.log growth to see if I can identify if it correlates with any access I'm doing. 

Sorry for the running commentary. I'll try and catch it while it's being naughty and post some of the logs.

**Comment by gunslingerfry** [comment]
I solved this by using the setting the root folder as shown in the wiki: https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration
