### ISSUE TITLE
Download forbidden of uploaded file

### ISSUE THREAD

**Issue by lcssanches** [astrada/google-drive-ocamlfuse#371]
I have configured a server to backup some data every day and the upload works very well until now, the problem is that I cannot download the files with my own account, unless I share to "anyone with the link" and open on incognito tab.

According Google help:

"**Forbidden**
This error means you don't have permission to download this file from the server.

To fix, go to the website where the file is hosted. Check if you need to sign in (or provide some other authentication). If you can't sign in, contact the website or server owner, or try finding the file on a different site."
[source](https://support.google.com/chrome/answer/2898334?p=ui_download_errors&hl=en&ctx=36&visit_id=1-636456122623038295-3951012590&rd=1)

I don't know if I am missing some configs.

**Comment by astrada** [comment]
>  I cannot download the files with my own account, unless I share to "anyone with the link" and open on incognito tab.

So, you can download it via google-drive-ocamlfuse but not via web interface?

It that's the case, have you tried reauthorizing the app?

**Comment by lcssanches** [comment]
@astrada thanks for your reply. This is an amazing project!

I don't know if I understand what do you mean by "download via google-drive-ocamlfuse". But if I upload a file through my desktop, the file just appears on my server few seconds after that.

I'm using Ubuntu Server, so I had to do the headlesss authorization.

I think it's worth to mention that only download is been forbidden, if I open the Google Drive page and select a file to preview, it's shown perfectly.

**Comment by astrada** [comment]
> I don't know if I understand what do you mean by "download via google-drive-ocamlfuse".
 
If you mount your Drive, can you access that file (e.g. copy it to another local directory)?

**Comment by lcssanches** [comment]
Yes, I can.

**Comment by astrada** [comment]
Even after clearing the cache? If so, I would try reauthorizing the app (removing everything under `~/.gdfuse/default` and starting over).

**Comment by lcssanches** [comment]
Yes.

I will try to reauthorizing the app, but what's the relation between the cache and download from Google Drive web page?

**Comment by astrada** [comment]
If your file is already cached (it's cached before uploading), you will always be able to access it without accessing Drive API, so any error that would be returned by the API won't be triggered without clearing the cache.

**Comment by lcssanches** [comment]
Got the same error after reauthorize.

I don't know if this make sense, but maybe the file created by the Google Drive API is only accessible by the API? Though I can download through the link share.

**Comment by astrada** [comment]
No, it should be accessible (I never experienced your issue). If I go to the web interface and check the details of every file uploaded with google-drive-ocamlfuse I get "Viewers can download".

**Comment by astrada** [comment]
Maybe it's an issue of the session in your web browser:
https://productforums.google.com/forum/#!topic/drive/BwruvJYKzWU
https://productforums.google.com/forum/#!topic/drive/yTMj7Icwm3U

**Comment by lcssanches** [comment]
OK, I found something interisting here.

I uploaded a file via browser and I cannot download either. I fave created a GoogleDoc file and was just fine.
![image](https://user-images.githubusercontent.com/3931027/32494155-b11ee2e4-c3a7-11e7-926b-2f5a5c731818.png)

This was uploaded by google-drive-ocamlfuse
![image](https://user-images.githubusercontent.com/3931027/32494172-c314c946-c3a7-11e7-806e-58a61cad7cad.png)


I will try to figure out what's going on.

**Comment by lcssanches** [comment]
From the second link you get

> "This usually happens if you have multiple signed in accounts in your browser.
> 
> Account 1 is attempting to download the file
> Account 2 ends up doing the request to download the file
> since account 2 doesn't have access to the said file, you will get the forbidden message
> 
> clearing the cache/cookies can fix this but you can also try downloading the files while in incognito mode to ensure that you only have one account signed in."

I have 4 active accounts on my browser.


Was that.

Thanks for your help!
