### ISSUE TITLE
Long pause on file save before upload even starts

### ISSUE THREAD

**Issue by anthonybilinski** [astrada/google-drive-ocamlfuse#372]
Ubuntu 17.10, freshly installed google-drive-ocamlfuse, all default settings.

Saving a file from an application in my mounted dir freezes the application for 45s. Once the application unblocks, my computer starts uploading about 2 seconds later, which lasts for 15 seconds.

Since the application unblocks before the upload has finished (or even started), is there any reason why it's blocking for so long? Is there any way I can mitigate this (possibly even to 0s since write appears to be async?)

**Comment by astrada** [comment]
> Since the application unblocks before the upload has finished (or even started), is there any reason why it's blocking for so long?

That's because the application needs to copy the file to the local cache before uploading.

> Is there any way I can mitigate this (possibly even to 0s since write appears to be async?)

No, sorry, I don't think so.

**Comment by anthonybilinski** [comment]
The file is only around 2 MB and I'm running off an SSD with low load, surely copying to local cache should take under a second, instead of the 45s I'm seeing? I can't imagine the time I'm seeing is due to I/O limitations.

**Comment by astrada** [comment]
You can enable verbose logging (with `-verbose`), then check `~/.gdfuse/default/gdfuse.log`. It reports timestamps for each operation. `mknod` is called when creating a new file, e.g.:

    [267.602869] TID=293: mknod /mp3/test.mp3 100600

Then you should see a series of `write` calls:

    [269.549571] TID=296: write /mp3/test.mp3 [131072 bytes] 0 0
    [270.377098] TID=298: write /mp3/test.mp3 [131072 bytes] 131072 0
    [270.848342] TID=300: write /mp3/test.mp3 [131072 bytes] 262144 0
    ...
    [275.794260] TID=326: write /mp3/test.mp3 [48605 bytes] 1966080 0

And finally a `flush`:

    [276.051459] TID=327: flush /mp3/test.mp3 0

And that starts the upload:

    [276.278254] TID=328: BEGIN: Uploading file (id=76, path=/mp3/test.mp3, cache path=/home/alex/.gdfuse/default/cache/1GNtRaShfc8Pzu7uSkxm85bvNZCPkkiGv, content type=audio/mpeg, content_length=2014685).
    ...
    [280.473024] TID=328: END: Uploading file (id=76, path=/mp3/test.mp3, cache path=/home/alex/.gdfuse/default/cache/1GNtRaShfc8Pzu7uSkxm85bvNZCPkkiGv, content type=audio/mpeg).

During this test, I copied a 2MB file to my Drive: 9 secs for copying the file to the cache (on a 5400rpm HD), and 4 secs for uploading to Drive (on a 4G connection).

**Comment by anthonybilinski** [comment]
Thanks. I ran it with -verbose and got the following data:

The testfile is 7.5MB.
```
[92.872092] TID=625: mknod /testdir/testfile 100644
...
[133.088217] TID=8248: flush /testdir/testfile 0
```
so the saving application is blocked for 40s waiting for the local cache copy.

For comparison, copying the same file to /tmp (storage-backed, not tmpfs):
```
$ time cp /media/gdrive/testdir/testfile /tmp/

real	0m0.078s
user	0m0.000s
sys 	0m0.009s
```
So the local cache copy used by google-drive-ocamlfuse is taking over 500x longer than a raw cp. I get that there's some metadata overhead needed to track the file in the cache.. but this seems like way too much.

Here's the log from mknod until flush.
[test-save.log](https://github.com/astrada/google-drive-ocamlfuse/files/1469603/test-save.log)

I think the grand majority of the time isn't spent on any hardware limitation, but on the huge number of db accesses to copy the file. For example, the file is loaded from db 7624 times in this small save:
```
$ grep "BEGIN: Loading resource.*from db" test-save.log | wc -l
7624
````

**Comment by astrada** [comment]
Your issue is caused by the fact that FUSE is using the default 4kb block size:

    write /testdir/testfile [4096 bytes] 0 0

In theory `big_writes` should be turned on by default and you should see 128kb blocks. Are you on an old kernel (https://sourceforge.net/p/fuse/mailman/message/20806709/)?

**Comment by anthonybilinski** [comment]
I'm not convinced it's a general FUSE limitation, because using sshfs (also FUSE) on loopback, which should have much higher overhead with ssh protocol, encryption, compression, network stack etc, sending /dev/urandom which is incompressible, I still get 103 MB/s write speed and 147 MB/s read speed compared to the 0.1875 MB/s with google-drive-ocamlfuse from my 7.5 MB over 40s which is just copying to local disk, without all of the added ssh overhead overhead.

My kernel is 4.13.0-16-generic.

**Comment by astrada** [comment]
> I'm not convinced it's a general FUSE limitation

No, not really. It's a combination of FUSE+Drive API. But the real issue is why `big_writes` doesn't work for you.

**Comment by anthonybilinski** [comment]
How does Google Drive API have anything to do with copying to local cache? Isn't this purely the google-drive-ocamlfuse implementation, which should be tailored for FUSE since that's what it's built for?

As for why big_writes isn't working, I tried remounting with `google-drive-ocamlfuse -o big_writes -verbose` and I see writes in the log all alternating between 3584 bytes and 512 bytes. 

`cat /sys/kernel/mm/transparent_hugepage/enabled` gives
always [madvise] never
which should enable when requested, apparently.

I then did a test with a 1GB file instead of the 7MB one I was using, and saw writes of 131072 bytes, must be using the big_blocks. This increases my write time to 6MB/s, from the 0.1875 MB/s I was seeing before. Definitely an improvement, but still extremely slow for local access.

I can't see a way to force this use of bigger blocks on small files, maybe Linux is making the decision because of the small file size, I'm not sure.

I still don't see any reason why copying to cache should be slower than any other FUSE, regardless of block size. Increasing block size may mitigate the slowness somewhat by decreasing the number of transactions, but the root cause must be the slow handling of each block.

**Comment by astrada** [comment]
> How does Google Drive API have anything to do with copying to local cache?

FUSE writes are block by block, but Drive API doesn't support uploading a single block, you have to upload the whole file. That's why files need to be cached and also why it's slower than sshfuse (because SSH supports chunk uploads).

**Comment by Nodens-** [comment]
Indeed this sounds like an implementation problem. Writing to cache is irrelevant to the drive api and should be as fast as any other fuse fs when writing on local storage. The only condition where a delay is logical is when cache is full at which point it would block until upload finished (assuming slower upstream than disk i/o).
Any processing related to the drive api should happen after the transfer to cache has finished. Is this not the case right now? If it is, then there must be a bug somewhere on cache handling..

**Comment by BungeeCloud** [comment]
Hey, I can confirm here the problem on nvme:

https://cdn.bungeecloud.org/i/151133158200141.jpg

and still on it. Testing it here with Ubuntu 17:10

**Comment by astrada** [comment]
If you need to max out your upload bandwith, consider using https://github.com/odeke-em/drive (not based on FUSE) or https://github.com/ncw/rclone (that IIRC caches everything in memory).

**Comment by anthonybilinski** [comment]
This isn't about upload bandwidth, it's about local cache. google-drive-ocamlfuse maxes my upload bandwidth no problem once the file is copied into cache.

The problem is that copying into cache is the more critical part, since it blocks applications, and is extremely slow with no reason, since it should only be limited by disk write speed and cache implementation.

**Comment by BungeeCloud** [comment]
Hi,

I found a part of the solution. It is working fine under a ram disk till that is full.


@anthonybilinski
mount -t tmpfs none /root/.gdfuse/default/cache

https://cdn.bungeecloud.org/i/151229449800117.jpg
(Here in a upload from a other server. Screen on the target server with the mounted FS as temp FS!)

But that is not  a so great solution as I do not have 100+GB ram for moving files ;)

I have a nvme in raid 1. So why is that with the normal file system so extream slow!


Regards,

Paul

**Comment by astrada** [comment]
And in version 0.7.10, I've added `async_upload_queue` config option to start async uploads.
