### ISSUE TITLE
installation failed with gapi-ocaml

### ISSUE THREAD

**Issue by leighsjo** [astrada/google-drive-ocamlfuse#374]
Because of the failure in installing gapi-ocaml 0.3.4, I was unable to install google-drive-ocamlfuse 0.6.21 on my Mac. 
The error message that I got is given as follows:
=== ERROR while installing gapi-ocaml.0.3.4 ==================================#
 opam-version 1.2.2
 os           darwin
command      ocaml setup.ml -build
path         /Users/username/.opam/system/build/gapi-ocaml.0.3.4
compiler     system (4.06.0)
exit-code    1
env-file     /Users/username/.opam/system/build/gapi-ocaml.0.3.4/gapi-ocaml-28860-865888.env
stdout-file  /Users/username/.opam/system/build/gapi-ocaml.0.3.4/gapi-ocaml-28860-865888.out
stderr-file  /Users/username/.opam/system/build/gapi-ocaml.0.3.4/gapi-ocaml-28860-865888.err
stdout ###
Error: This expression has type
[...]
            < close_out : unit -> unit; flush : unit -> unit;
              output : string -> int -> int -> int >
        but an expression was expected of type
          Netchannels.rec_out_channel =
            < close_out : unit -> unit; flush : unit -> unit;
              output : Bytes.t -> int -> int -> int >
        Type string is not compatible with type Bytes.t = bytes 
        Types for method output are incompatible
 Command exited with code 2.
stderr ###
 E: Failure("Command ''/Users/username/.opam/system/bin/ocamlbuild' src/gapi/gapi-ocaml.cma src/gapi/gapi-ocaml.cmxa src/gapi/gapi-ocaml.a src/gapi/gapi-ocaml.cmxs src/gdata/gdata.cma src/gdata/gdata.cmxa src/gdata/gdata.a src/gdata/gdata.cmxs -tag debug' terminated with error code 10")
Does anybody know how can I solve the problem? Many thanks!

**Comment by astrada** [comment]
I'm working on this issue. The new compiler (4.06.0) uses a special flag that causes that error. If you are in a hurry please switch to 4.05.0.

**Comment by leighsjo** [comment]
Thanks, astrada.  It solves the problem.

**Comment by astrada** [comment]
Should be fixed in version 0.6.22 (with gapi-ocaml 0.3.5).
