### ISSUE TITLE
retrieve the authorization tokens  not working on my Gapps email address.  Cursor blinks

### ISSUE THREAD

**Issue by manjusr81** [astrada/google-drive-ocamlfuse#376]
ocamlfuse Not able to authenticate on my Gapps email address.  Pls help
![selection_228](https://user-images.githubusercontent.com/9315238/33198506-87cef6e6-d111-11e7-87c6-7b9d4eafe408.png)

**Comment by astrada** [comment]
You should enable debug logging with `-debug`, then check `~/.gdfuse/default/curl.log` where you can find if you are experiencing timeouts or other errors during connection with the auth proxy.

**Comment by thardbarger** [comment]
Same problem here.  Curl.log is blank.

**Comment by astrada** [comment]
What about gdfuse.log?

**Comment by thardbarger** [comment]
Am running Raspbian Jessie.  I set up google-drive-ocamlfuse three months ago with no problems.  Just moved from London to Washington DC and encountered error when booting for first time after I arrived.  Have tried changing locale options.

[0.001417] TID=0: Setting up default filesystem...
[0.001535] TID=0: BEGIN: Saving configuration in /home/pi/.gdfuse/default/config
[0.002245] TID=0: END: Saving configuration in /home/pi/.gdfuse/default/config
[0.002358] TID=0: Loading application state from /home/pi/.gdfuse/default/state...done
Current version: 0.6.17
Setting up cache db...done
Setting up CURL...done

**Comment by thardbarger** [comment]
Left it running over night and found “hostname not found in DNS cache” in curl log.  Did not realise log is written over when restarting the process so letting it run again to get the full copy.  Thanks

**Comment by thardbarger** [comment]
I found that I need to have a web browser (have tried Chromium and Midori) open before the program will proceed.  I get the following repeatedly in the curl log.  Clearing browser cache makes no difference.

[60.911664] curl: info: Hostname was NOT found in DNS cache
[66.426945] curl: info: Resolving timed out after 5515 milliseconds
[66.427220] curl: info: Closing connection 0

**Comment by astrada** [comment]
If your DNS is slow you can raise connect_timeout_ms in config.

**Comment by thardbarger** [comment]
Had an incorrect dns server in dhcpcd.conf.  Changed and all working fine now.  Many thanks! - Tom
