### ISSUE TITLE
empty file

### ISSUE THREAD

**Issue by lcssanches** [astrada/google-drive-ocamlfuse#378]
I am uploading some files, between 200mb and 2000mb.

Sometimes some files are just not uploaded, but are created on Google Drive with 0 bytes.

I am using `dd` to copy the file to google drive folder.

This is the one who failed.
```
dd if=/tmp/backup-201711281125.tar.gz of=/google-drive/servers/backup/backup-201711281125.tar.gz bs=4MB
68+1 records in
68+1 records out
273115550 bytes (273 MB, 260 MiB) copied, 8.06905 s, 33.8 MB/s
```

I manually re-upload the file and it works fine.
```
dd if=/tmp/backup-201711281125.tar.gz of=/google-drive/servers/backup/backup-201711281125-2.tar.gz bs=4MB
68+1 records in
68+1 records out
273115550 bytes (273 MB, 260 MiB) copied, 7.15541 s, 38.2 MB/s
```

How can I investigate this issue?

**Comment by astrada** [comment]
You should enable debug logging with `-debug`, then check `gdfuse.log` and `curl.log` in `~/.gdfuse/default` and look for errors.

**Comment by lcssanches** [comment]
Should I remount the drive or there's a way to activate the debug without remounting?

Also, does the `-cc` clear the logs?

**Comment by astrada** [comment]
> Should I remount the drive or there's a way to activate the debug without remounting?

No, sorry, you have to remount.

> Also, does the -cc clear the logs?

No, logs are overwritten every time you remount.

**Comment by lcssanches** [comment]
Here is the output. I got one exception and one file was not uploaded correctly.
```
root@backup:/# google-drive-ocamlfuse -debug /google-drive
Starting application setup (label=default, base_dir=).
[0.000154] TID=0: Loading configuration from /root/.gdfuse/default/config...done
Opening log file: /root/.gdfuse/default/gdfuse.log

Thread 6730 killed on uncaught exception Sys_error("/root/.gdfuse/default/cache/1oZJgCWYaFiS_L_yqQBYko7xxQenjrDql: No such file or directory")
```

I have a script to backup all my containers, one of those containers is named "backup", who has the google drive. This container is also backuped. That's the reason I have the `-cc`, if not it will become bigger and bigger.


Theses lines may interest you.
```
lxc exec backup -- google-drive-ocamlfuse -cc
lxc exec backup -- mkdir -p /google-drive/servers/$CONTAINER_NAME
[...]
lxc file push $IMAGE_NAME.tar.gz backup/tmp/
lxc exec backup -- dd if=/tmp/$IMAGE_NAME.tar.gz of=/google-drive/servers/$CONTAINER_NAME/$IMAGE_NAME.tar.gz bs=4MB
```


The failed file was the second one, with 565MB. The first one has 235MB.

**Comment by astrada** [comment]
> Thread 6730 killed on uncaught exception Sys_error("/root/.gdfuse/default/cache/1oZJgCWYaFiS_L_yqQBYko7xxQenjrDql: No such file or directory")

It looks like the cached copy of the file was deleted before the upload was completed.

**Comment by lcssanches** [comment]
Hi astrada. I changed my script, to avoid always cleaning cache .

Let's see if it work!

Thank you!

**Comment by lcssanches** [comment]
I'm closing this because after the changes on my script, based on your reply, the error does not occurs anymore.

Thanks!
