### ISSUE TITLE
d????????? ? ? ? ?            ? gdrive

### ISSUE THREAD

**Issue by da0ist** [astrada/google-drive-ocamlfuse#379]
Everything was working great since I installed it last week, but this morning, my /media/gdrive directory has seriously strange permissions. I am unable to move or delete the directory. Any ideas?

System:    Host: X250 Kernel: 4.13.0-17-generic x86_64 bits: 64
           Desktop: Gnome 3.26.1 Distro: Ubuntu 17.10

**Comment by astrada** [comment]
You should remount (with `-cc` if it does still not work).

**Comment by da0ist** [comment]
jamesward@X250:~$ ls -l /media
ls: cannot access '/media/gdrive': Transport endpoint is not connected
total 0
d????????? ? ? ? ?            ? gdrive
jamesward@X250:~$ google-drive-ocamlfuse -cc /media/gdrive
Error: Mountpoint /media/gdrive should be an existing directory.

**Comment by astrada** [comment]
If the process is still running you should kill it. Then you should unmount with `fusermount -u mountpoint` and then remount.

**Comment by da0ist** [comment]
Rebooting seems to have fixed it eventually. I found Ubuntu 17.10 too unstable to do my work, so I've installed Debian this morning. Thanks for your help!

**Comment by aapthorp** [comment]
Had the same issue today. Added ,_netdev after 'user' to my fstab entry for gdrive. e.g. user,_netdev This seemed to fix it.
