### ISSUE TITLE
404 ERROR

### ISSUE THREAD

**Issue by HuLian21** [astrada/google-drive-ocamlfuse#381]
W: Failed to fetch http://ppa.launchpad.net/alessandro-strada/google-drive-ocamlfuse-beta/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

**Comment by astrada** [comment]
It looks like you are fetching packages for Debian Jessie, but the PPA contains packages only for Ubuntu (xenial, zesty, ecc.).

**Comment by HuLian21** [comment]
![snipaste20171219_095017](https://user-images.githubusercontent.com/21038789/34136714-40cf253c-e4a2-11e7-964a-6e961722e3d0.png)
![snipaste20171219_095230](https://user-images.githubusercontent.com/21038789/34136730-5907e562-e4a2-11e7-8c2f-0130618502b2.png)
I don't know why, but it's looks locked. Than I try chmod a+rw command, but it's looks not very useful.
I used OPENVZ/Ubuntu16.04/Linux 2.6.32-042stab123.9

**Comment by astrada** [comment]
If you want you can enable debug output (with `-debug`) and check the log files (`gdfuse.log` and `curl.log`) in `./gdfuse/googledrive` to see what it's doing.

**Comment by HuLian21** [comment]
I was tryed your command, and it still can't work. 
```
google-drive-ocamlfuse -label googledrive ~/googledrive -o nonempty -debug
Starting application setup (label=googledrive, base_dir=).
[0.001636] TID=0: Loading configuration from /root/.gdfuse/googledrive/config...done
Opening log file: /root/.gdfuse/googledrive/gdfuse.log
```

I used chmod a+wr for curl.log and gdfuse.log

**Comment by astrada** [comment]
With `-debug` the process remain in foreground. You should check the content of the log files to see what's going on.

**Comment by HuLian21** [comment]
Thank you for your patience, I tried, there is no write in the curl.log file, but gdfuse.log has
```
[0.005311] TID=0: Setting up googledrive filesystem...
[0.005341] TID=0: BEGIN: Saving configuration in /root/.gdfuse/googledrive/config
[0.005516] TID=0: END: Saving configuration in /root/.gdfuse/googledrive/config
[0.006408] TID=0: Loading application state from /root/.gdfuse/googledrive/state...done
Current version: 0.6.21
Setting up cache db...done
Setting up CURL...done

```

Nothing else in there.

**Comment by astrada** [comment]
I think the problem is that when you initialized the application with `google-drive-ocamlfuse -headled -id...` you didn't specify a label (so `default` label is used), then when you tried to mount the filesystem you specified `-label googledrive`. You should specify the same label when authorizing and when mounting.
