### ISSUE TITLE
Different authorization scope https://www.googleapis.com/auth/drive.file	

### ISSUE THREAD

**Issue by workmonitored** [astrada/google-drive-ocamlfuse#382]
Rather than giving full access, I want to set up google-drive-ocamlfuse as a drop point where people drop files into my drive/folder without giving them full access. Is this possible? The drop will be done using sftp and will give an anon access to the user.

**Comment by astrada** [comment]
I don't think so (file permissions are not enforced). I think your best option would be to put user files in a staging area then periodically push them with something like [drive](https://github.com/odeke-em/drive).
