### ISSUE TITLE
Can't send photos to Google Photos

### ISSUE THREAD

**Issue by ludovicrl** [astrada/google-drive-ocamlfuse#383]
In Google Backup & Sync on Windows I have the option to include photos in Google Photos. Now I upload jpg photos with ocaml without problems but they only end up on Google Drive, I don't see them in Google Photos. Is there an option that could be added to add the pictures to Google Photos automatically?

Thanks

![image](https://user-images.githubusercontent.com/34710674/34204431-9046f89c-e54c-11e7-99d9-6187f1c567e2.png)

**Comment by astrada** [comment]
If you [enable](https://support.google.com/drive/answer/6156103) Google Photos in you Drive, you should see a `Google Photo` folder in your Drive that you can access with google-drive-ocamlfuse.

**Comment by KenSharp** [comment]
You can download from Google Photos, but uploading does not work. At least not the way intended.

**Comment by KenSharp** [comment]
I guess you're not interested.

**Comment by astrada** [comment]
I'm sorry but I think that it's not possible to upload photos to Google Photos via the Drive API. You can only upload files.
