### ISSUE TITLE
failed to launch GPU process.

### ISSUE THREAD

**Issue by panxl6** [astrada/google-drive-ocamlfuse#385]
Using ubuntu 16.04 amd 64bit.
Chrome Version 63.0.3239.108 (Official Build) (64-bit)

When i login google account, this problem occur:
[5973:6013:1226/202608.092897:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.

I had try several times to confirm, the problem is the same.
Need help!

**Comment by astrada** [comment]
That error is returned by Google Chrome, and you may ignore it safely. You can reproduce it starting Chrome from bash:

    alex:~$ google-chrome-stable 
    [19866:19905:1226/140823.290855:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to 
    launch GPU process.
    Created new window in existing browser session.

**Comment by KenSharp** [comment]
What does this have to do with the project?
