### ISSUE TITLE
Location for for ocaml sqlite3 has moved

### ISSUE THREAD

**Issue by pmetzger** [astrada/google-drive-ocamlfuse#386]
The readme points at bitbucket, but the actual location is now
https://mmottl.github.io/sqlite3-ocaml/

**Comment by astrada** [comment]
OK, thanks!

**Comment by pmetzger** [comment]
Weird. Even though you fixed it, the README.md doesn't have it. Did you commit it to the wrong branch?

**Comment by pmetzger** [comment]
Yah, you committed it on the gh-pages branch.
