### ISSUE TITLE
chown sets wrong uid/gid when omitted

### ISSUE THREAD

**Issue by ArminXG** [astrada/google-drive-ocamlfuse#389]
When using chown, the omitted value is set to nobody/nogroup, but it should be left unchanged.
Examples:
`chown user1.group1` : works
`chown user1` : sets to user1.nogroup
`chgrp group1`  : set to nobody.group1

uid and gid should be checked for value -1 which means to omit changing that value.

Armin

**Comment by astrada** [comment]
Should be fixed in 0.6.24 (beta channel).

**Comment by ArminXG** [comment]
Works now, thank you!
