### ISSUE TITLE
Google doc file not existent until directory is read

### ISSUE THREAD

**Issue by ArminXG** [astrada/google-drive-ocamlfuse#392]
When I try to read or stat a google doc file (e.g. as odt/ods) before the directory entries are read
with a command like `ls`, an error `No such file or directory` is shown.
Then, a `ls` shows the file with
`?????????? ? ?     ?                 ?            ?`
and the file cannot be read until I remount with cleared cache.

It works without error when I do `ls` before I try to access/stat the file.

You can reproduce that by creating a google doc file, mount the drive with clear cache and
do a `stat <filename>.odt` before any `ls`.

**Comment by astrada** [comment]
Should be fixed in 0.6.25 (beta channel).
