### ISSUE TITLE
Very slow when edit files from other software

### ISSUE THREAD

**Issue by Queequeg92** [astrada/google-drive-ocamlfuse#393]
I store some of my code in google drive. When I edit my code in some IDEs, such as pycharm, the IDEs become very slow. In addition, most of the operations on the files in google drive folder are much slower compared to the official google drive clients of Windows and Mac. I was wondering is there anything wrong with my configuration? The following is my configuration file. Thank you for your time!
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=
client_secret=
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=15000
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=20
presentation_format=pdf
presentation_icon=
read_ahead_buffers=3
read_only=false
root_folder=
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=true
team_drive_id=
umask=0o002
verification_code=

**Comment by cpassos** [comment]
This happens with me as well, and I'm using the default configuration.

**Comment by astrada** [comment]
> the IDEs become very slow. In addition, most of the operations on the files in google drive folder are much slower compared to the official google drive clients of Windows and Mac.

That's because Windows and Mac clients are not a FUSE file-system. You work on your file-system, and those client keep it in sync with the remote version. If you need similar functionality you should try [grive](https://github.com/Grive/grive) or [drive](https://github.com/odeke-em/drive).

**Comment by Queequeg92** [comment]
@cpassos Dude. I recommend pcloud to you. It's fabulous. You can refer to my link to register. https://www.pcloud.com/welcome-to-pcloud/?discountcode=9DoCgsm7cRysu1zLHryDqzZV

**Comment by Queequeg92** [comment]
@astrada Thank you for your awesome work:gift::gift::gift:. But I often edit my code in google drive. I really need a faster sync tool. I find pcloud, which has official clients for win, mac and linux.

**Comment by matjazmav** [comment]
Yes it's too slow to be used on daily bases. I'm using Ubuntu 18.04. And when saving plain text files it take like up to 10 seconds for file to saved and program to be responsive. I'm editing in vim. 

Can I do anything? Like async save? I'm on version 0.7.0

**Comment by astrada** [comment]
No, sorry, I had to remove the async upload option because it increased the probability of losing data.
