### ISSUE TITLE
How activate root folder in config

### ISSUE THREAD

**Issue by agilebean** [astrada/google-drive-ocamlfuse#398]
Hi,

setting the root folder would be enormously valuable but I can't get it activated.
I tried to set a root folder in the config by:
`root_folder=dir2`
or
`root_folder=/dir2`

my folder structure is simply:
GoogleDrive/
GoogleDrive/dir1
GoogleDrive/dir2
...

1. How do I correctly specify the root_folder?
2. How do I activate reading the config file without going through unmounting and mounting the drive again?

Help would be really appreciated!!!

**Comment by astrada** [comment]
> How do I correctly specify the root_folder?

It should be right as you are doing. Alternatively you could specify folder id that you can get from the web interface (it's the id in the url after https://drive.google.com/drive/folders/). Remember remount with `-cc` after you change the root folder.

> How do I activate reading the config file without going through unmounting and mounting the drive again?

There is no way. If you need to have more than one root folder, you should use different labels.

**Comment by agilebean** [comment]
thank you very much, alessandro!
with the folder id, it worked right away!
strangely, the folder name doesn't work.

**Comment by valoricDe** [comment]
Ahh thank you for mentioning `-cc` I just unmounted with `fusermount -u /drive` and remounted with `google-drive-ocamlfuse /drive` but it needed the `-cc` option as well
