### ISSUE TITLE
permissions for synced directory changed to unknown

### ISSUE THREAD

**Issue by agilebean** [astrada/google-drive-ocamlfuse#399]
Hello,
I have a really strange but interesting error when starting the sync:
After starting ocamlfuse,
the permissions change from
`drwxr-xr-x  5 rstudio googledrive 4096 Feb  6 09:46 rstudio`
to
`d?????????  ? ?       ?              ?            ? 06 Machine Learning`

How can I avoid this happening??

Here's my little script which triggers it:
```
# create local folder
mkdir /home/rstudio/'06 Machine Learning'

# make clouddrive directory available to rstudio user via clouddrive group
sudo chown -h rstudio:rstudio /home/rstudio/'06 Machine Learning'

# selective sync only for folder "06 Machine Learning"
sed -i 's,^\(root_folder=\).*,\1'1ja01aeTBzPq_CWVNeGJqsRRKL5pb6o3r',' ~/.gdfuse/default/config

# start syncing
google-drive-ocamlfuse /home/rstudio/'06 Machine Learning'
```
Any help much appreciated!

**Comment by astrada** [comment]
After changing `root_folder` you should clear the cache:

    google-drive-ocamlfuse -cc /home/rstudio/'06 Machine Learning'

But your problem is caused by some error that's occurring during mount. You should be able to get the exception from log files. It's probably due to user permissions of rstudio.

**Comment by agilebean** [comment]
Thanks a lot! 
Clearing the cache indeed solved the issue, now I get the permissions set.
The syncing process also works correctly in ubuntu file system, but in Rstudio Server, the directory and files disappear.
That must be some other reason unrelated to ocamlfuse maybe...
