### ISSUE TITLE
Team Drive can't see directories

### ISSUE THREAD

**Issue by xinity** [astrada/google-drive-ocamlfuse#401]
Hey there,

Many thanks for this awesome tool i was trying to use teamdrive, but i only see files in the root of my TeamDrive. i can't see any "directories".

Searching the wiki and issues i haven't found any hint about that. Is here anything i can do ?

Cheers,

**Comment by astrada** [comment]
Sorry, but I'm not able to reproduce it. (I see the subfolders in my Team Drive.)

**Comment by Disctanger** [comment]
@xinity 
If you have a lots of files in your subfolder, then it will take some time to load/show folders. Sometimes waiting for some time and reloading is the solution of this problem. For example I have two team drives one has around 10 folders and second team drive has around  30 folders in the subfolder.

TEAM DRIVE 1 =======|1 folder =======|30 folders =======|etc.
TEAM DRIVE 2 =======|10 folders =======|etc.

**Comment by xinity** [comment]
Thanks a lot guys!

I'll try again this morning and let you know how it goes after waiting a bit :blush:

**Comment by xinity** [comment]
tested it again today, still no team drive directories and a very very slow sync (behind a 100mbits fiber though)
