### ISSUE TITLE
How to uninstall and delete google-drive

### ISSUE THREAD

**Issue by alexgmuir** [astrada/google-drive-ocamlfuse#403]
Greetings,

I've installed the application and apt install, mounted a google drive and then unistalled using apt remove.

However I'm not able to delete the google drive left over with rm -rf

Could you kindly add instructions for how to safely remove all traces of this application and the mounted drive.

Regards
Alex

**Comment by astrada** [comment]
You should unmount your drive (`fusermount -u MOUNTPOINT`), before uninstalling.
