### ISSUE TITLE
Feature Request: CLI usage using Links or another CLI-based web browser

### ISSUE THREAD

**Issue by themurph2k** [astrada/google-drive-ocamlfuse#407]
For users that don't use X / Desktop.

**Comment by astrada** [comment]
You can use any browser that can login to your google account and authorize an app, but I don't know any CLI-based browser that can do that.

**Comment by themurph2k** [comment]
I believe elinks can be compiled with Javascript support

**Comment by astrada** [comment]
If you manage to successfully access to your Google Account with elinks, you can just set it as your default browser (https://askubuntu.com/questions/788043/where-to-change-how-xdg-open-opens-urls-sync-with-kde-open), and it will be opened to authorize the application.

**Comment by themurph2k** [comment]
Thanks much, I will give it a try! I was hoping to avoid installing a desktop environment completely, though :(

**Comment by astrada** [comment]
If you want you can authorize the application using another device (e.g., a smartphone or a tablet). Check the wiki (https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization).

**Comment by chaimleib** [comment]
I tried this out, but I ran into trouble.
```
$ google-drive-ocamlfuse -headless -id `jq .installed.client_id ~/gdrive-ocamlfuse-secrets.json` -secret `jq .installed.client_secret ~/gdrive-ocamlfuse-secrets.json`                                                                                                                                      
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=%22xxxxxxxxxxxxxx.apps.googleusercontent.com%22&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: 
```
When I opened the link from the CLI in Chrome, I got a 401:
> 401. That’s an error.
> 
> Error: invalid_client
> 
> The OAuth client was not found.
> 
> Request Details
> client_id="xxxxxxxxxxxxxx.apps.googleusercontent.com"
> redirect_uri=urn:ietf:wg:oauth:2.0:oob
> scope=https://www.googleapis.com/auth/drive
> response_type=code
> access_type=offline
> approval_prompt=force

I have the Google Drive API added to my project's library. Not sure what is wrong.
