### ISSUE TITLE
[Feature Request] A refresh access token option

### ISSUE THREAD

**Issue by dragonator4** [astrada/google-drive-ocamlfuse#408]
Currently, I delete the folder in `~/.gdfuse/` and recreate it using the `google-drive-ocamlfuse -label label mountpoint` command (like in the README).

Perhaps we could have a simple thing like `google-drive-ocamlfuse --refresh-access -label label` to just re-request the access tokens for the connection label. The good thing is that I have a backup of my config file, so I can simply replace the custom settings. Had I not had the backup, it would have been difficult to recover the settings after deleting the entire folder.

Also, is it possible to just delete `state` in `~/.gdfuse/label` to refresh the access tokens?

**Comment by astrada** [comment]
> Also, is it possible to just delete `state` in `~/.gdfuse/label` to refresh the access tokens?

Yes you can do that.
