### ISSUE TITLE
Must remount after reboot

### ISSUE THREAD

**Issue by JacobEFO** [astrada/google-drive-ocamlfuse#409]
Dear ocamlfuse devs.

I am happy I have found you solution to mount google drive on Linux. However whenever I shut down, I must remount the drive. Is there any way, I don't have to do this every time?

Best regards Jacob

**Comment by astrada** [comment]
Check the wiki: https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting

**Comment by JacobEFO** [comment]
Helle Astrada

Thank you very much for your link, I am sorry I did not find it myself. However I tried doing the script thingie, and it did not automount on start-up, and now I am unfortunately stuck with a folder named "Google_Drive" which I cannot mount to or delete.

Even if i try "sudo rm -rf Google_Drive" it says "rm: cannot remove 'Google_Drive': is a directory". I have no idea, what to do with it. 

Do you have any suggestions? 

Best regards Jacob

**Comment by astrada** [comment]
If you can't remove it, it's probably still mounted. So before deleting, you should try to unmount it with `fusermount -u MOUNTPOINT`. Then, you should check if you still have some process named `google-drive-ocamlfuse` and kill it.

**Comment by JacobEFO** [comment]
Hello Astrada

That worked splendidly.

Now in order to use the automount function, should I use ocamlfuse (the first guide) and set the mount point before I follow the automount guide?

Best regards Jacob

**Comment by astrada** [comment]
You don't need to mount before following automount guide (you mount your Drive as the last step of the guide).

**Comment by lssong99** [comment]
I think it's difficult to clarify all those path issue, so I just automount the drive with cron:

add following line in your crontab (use your user's cron job, NOT su...)

`crontab -e`

add following line anywhere in crontab

`@reboot sleep 100 && . /home/$USER/.opam/opam-init/init.sh && google-drive-ocamlfuse -label $LABEL ~/$MOUNTPOINT`

don't forget change $USER to your username, $LABEL to your label and $MOUNTPOINT to your mount path

The sleep 100 is not mandatory but it works for me.
