### ISSUE TITLE
Issues on Mac OS X (OSXFUSE)

### ISSUE THREAD

**Issue by sorin-ionescu** [astrada/google-drive-ocamlfuse#41]
I have tried to mount Google Drive and received the following output.

```
/bin/sh: xdg-open: command not found
Access token retrieved correctly.
fuse: unknown option `big_writes'
```

There is no `xdg-open` on Mac OS X. The command is `open`. `[[ "$OSTYPE" == darwin* ]] && open "$@"`.

Somehow, it still opened Firefox, which is not the default browser. It redirected me to Google where I approved access. Then it complained about `big_writes`. I am not sure if this is an google-drive-ocamlfuse error or an ocamlfuse error. I did not specify `-obig_writes` on the command line.

**Comment by astrada** [comment]
You can now install my app on MacOS using opam.
