### ISSUE TITLE
Drive not synced after update on another computer

### ISSUE THREAD

**Issue by usawa** [astrada/google-drive-ocamlfuse#410]
Hi, 

I'm using google-drive-ocamlfuse 0.6.21 on Ubuntu 17.10.1 using your PPA. Everything went fine (token, setup, automount using xfce startup line, ...). However I've an issue. If on another computer (mac, windows) I create folders and files, they don't appear in my google drive folder on linux. 

To make them appear, I've to create a file in google drive mountpoint (for example a single touch dummy), and after a few seconds, this new file appears on Mac/Windows folder, then files and folders created on Mac/windows appears in my mountpoint.

I launched in debug mode. I can see the lines, not the good behavior I think.

```
TID=393: BEGIN: Getting changes from server
TID=393: END: Getting metadata: No need to update resource cache

```
A "-cc" does the trick too, but shouldn't it be automatic ? I also tried to reduce metadata_cache_time to 30. No success.

**Comment by astrada** [comment]
Yes, it's a bug that should be fixed in version 0.6.25. It's on the [beta ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta).

**Comment by usawa** [comment]
beta ppa doesn't include a build for Ubuntu 17.10 artful...

**Comment by astrada** [comment]
Yes, unfortunately the artful OCaml packages are broken. You can try to download the bionic `.deb` and install it manually.

**Comment by usawa** [comment]
I manually donwloaded and installed the 0.6.25 from bionic to artful and it's ok. Thanks. To close.
