### ISSUE TITLE
 fuse: failed to exec fusermount: No such file or directory

### ISSUE THREAD

**Issue by beijiaoff** [astrada/google-drive-ocamlfuse#411]
It's a google VM running debian. The google-drive-ocamlfuse was installed and the token was retrieved correctly.
But this is a trouble in mounting. I am sure the /data directory exist.

$ google-drive-ocamlfuse /data  
 fuse: failed to exec fusermount: No such file or directory

Actually, if there is some files in data folder, there will be another error information. 
"fuse: mountpoint is not empty"

Please help me.

**Comment by astrada** [comment]
If fusermount is not installed, try to install `fuse-utils`.

> Actually, if there is some files in data folder, there will be another error information.
"fuse: mountpoint is not empty"

If you want to force mount even if your mountpoint is not empty you can use `-o nonempty`. Although your files in that directory will not be available until you unmount your google drive.

**Comment by JonasUliana** [comment]
worked well with `fuse` dependency (in Debian), maybe this can be considered a closed issue?
