### ISSUE TITLE
sth does not work

### ISSUE THREAD

**Issue by xvtstephen** [astrada/google-drive-ocamlfuse#413]
installed without any issues. the first call to the app connected with google and reported that some token was successfully downloaded.
then mounted to a folder ~/gdrive without any warnings or errors
~/gdrive is not readable

stephen@stephen-AO725:~$ ls -l | grep gd
ls: cannot access 'gdrive': Permission denied
d????????? ? ?       ?             ?            ? gdrive

**Comment by astrada** [comment]
Probably your user cannot access fuse drives (maybe it doesn't belong to fuse group).

**Comment by hyperpress** [comment]
Well, it's a permissions issue on the folder. So, I'd check ownership/perms on the folder and also verify that your fstab user uid/gid is correct.
