### ISSUE TITLE
Disable cacheing

### ISSUE THREAD

**Issue by ryanmjacobs** [astrada/google-drive-ocamlfuse#416]
Is it possible to disable caching entirely?

I'm reading large (~20 GB) files that often change remotely. Is it possible to disable caching entirely? Maybe with a flag or something.

I would like to avoid trashing my disk with extra writes.

**Comment by ryanmjacobs** [comment]
Okay, I saw this line in the config file: `max_cache_size_mb=512`. But maybe it isn't being considered?

![cache directory](https://user-images.githubusercontent.com/4251257/37850328-e8faa512-2e97-11e8-89f9-20c43966e435.png)

**Comment by astrada** [comment]
The max cache size is ignore during uploads (because Drive API doesn't offer a method to upload only a portion of a file). If you are sure you are not modifying those big files locally, you could turn on `stream_large_files` and set an appropriate `large_file_threshold_mb`.

**Comment by rkkoszewski** [comment]
Hi, how is it looking g with this? I have a 2gb partition where I'm running this and it keeps running out of memory due to this cache.

Is there any way to disable it yet?

I'm using:
max_cache_size_mb=0
stream_large_files=true
large_file_threshold_mb=0


I tried also with large_file_threshold_mb=1 and different combinations. The cache is still using gigabytes of space till the whole partition is full and the whole system freezes. Any way to disable completely cache? I'm using rsync to sync my files to the Google drive.

**Comment by MartinX3** [comment]
I want to download 8GB on my external HDD.
I made the mount point on my HDD and copied the files via file explorer on the same partition on my external hdd.

But it want to cache every downloaded file first on my too small home partition.
Hanging my system, consuming 100% on one cpu thread and freezing.

**Comment by astrada** [comment]
@MartinX3 if you don't need to upload big files, you can enable streaming with `stream_large_files=true`, reducing `large_file_threshold_mb` if you have lots of small files.

**Comment by MartinX3** [comment]
Thank you very much for your fast response!

At the moment, I don't need to upload files, only download up to 2.2 GB large files.

But I don't know if I want to upload files in the future with your tool.
Which disadvantages will `stream_large_files=true` gives me?

Is it possible to move the cache into the RAM?

**Comment by astrada** [comment]
> Which disadvantages will stream_large_files=true gives me?
It works for download only. Uploading still requires disk cache.

> Is it possible to move the cache into the RAM?
Nope, sorry (unless you setup a ramdisk).

**Comment by MartinX3** [comment]
I will try it, thank you. :)
