### ISSUE TITLE
Request: google-drive-ocamlfuse static binaries for Android (ARMv7)

### ISSUE THREAD

**Issue by babam86** [astrada/google-drive-ocamlfuse#417]
Can you to provide static binaries for Android (ARMv7), I will use it on Android (Rooted).

Thanks.

**Comment by astrada** [comment]
No, sorry. Check [this comment](https://github.com/astrada/google-drive-ocamlfuse/issues/224#issuecomment-266554160).

**Comment by babam86** [comment]
Okay, thanks.
