### ISSUE TITLE
Multiple Root Folders 

### ISSUE THREAD

**Issue by josiahls** [astrada/google-drive-ocamlfuse#418]
Hi,

Is there a way to have multiple root folders? 

I am trying to have it so it only downloads some of the folders not all of them. Maybe work around this with "multiple accounts" but have them as the same account but with different roots? It would be nice to have a more elegant approach. Also, side question: When you say mount, does it download the files locally, or are they all online? Basically, is there an offline option or function?

**Comment by josiahls** [comment]
^^ I am assuming online, but I saw talk

**Comment by astrada** [comment]
>Maybe work around this with "multiple accounts" but have them as the same account but with different roots?

Yes, that's the way to go. Each label/account can have its own independent configuration.

>  Basically, is there an offline option or function?

No, there is no offline option (as this is not a sync tool).
