### ISSUE TITLE
Error installing with Opam on OS X MacBook

### ISSUE THREAD

**Issue by ebeeman** [astrada/google-drive-ocamlfuse#423]
On my MacBook OS X Sierra, I encountered an error while following instructions on this page:
https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation

I encountered an error at the point where you check dependencies for google-drive-ocamlfuse

$ opam depext google-drive-ocamlfuse

Resulted in:
Fatal error: exception # opam-version    1.2.2
os              darwin
opam: "execvpe" failed on opam-depext: No such file or directory

**Comment by ebeeman** [comment]
I attempted to figure out how opam learns about dependencies and this allowed me to solve this issue.

I found another depext issue from Debian and tried to apply the findings.

Ran this command to find out if the dependencies were able to be listed:

          $ opam list --rec --required-by google-drive-ocamlfuse

# Available packages recursively required by google-drive-ocamlfuse.0.6.23 for system:
<...........truncated as too many to list.........>

Since that worked OK, I figured I would try the app name version found via above "google-drive-ocamlfuse.0.6.23" directly into the depext command that was causing the error:

            $ opam depext google-drive-ocamlfuse.0.6.23

# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - Caskroom/cask/osxfuse
#  - gmp
#  - lzlib
#  - pkg-config
#  - sqlite3
Updating Homebrew...

That allowed the software to install.  Not sure why the difference in results between using google-drive-ocamlfuse.0.6.23 vs google-drive-ocamlfuse

**Comment by astrada** [comment]
Thanks for your feedback.
