### ISSUE TITLE
Provide Gitter chat room for discussion

### ISSUE THREAD

**Issue by bittner** [astrada/google-drive-ocamlfuse#424]
I like clean nature of this project. It has a [clear README](https://github.com/astrada/google-drive-ocamlfuse#fuse-filesystem-over-google-drive), a [website](https://astrada.github.io/google-drive-ocamlfuse/) with and even clearer message, and a [comprehensive Wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki).

Yet still I'm missing a place where I can ask a quick question without disturbing too much -- given the fact that there are well 100 issues already open.

Would it be possible to create a [chat room on Gitter](https://gitter.im/) and add a badge to it on top of the README?

**Comment by astrada** [comment]
Done. Thanks for your suggestion.
