### ISSUE TITLE
Support for docker 

### ISSUE THREAD

**Issue by Guilty-King** [astrada/google-drive-ocamlfuse#427]
Can this be using in an unprivileged docker containers?
I  tired with debian stretch and ubuntu 16.04 container but got errors related to fuse device
I know I could run a --privileged flag ,install fuse on host machine then pass --device /dev/fuse 
But it's would take away the portability and making it difficult or not possible to deploy on public cloud like openshift , heroku , sloppy.io, GCP

**Comment by astrada** [comment]
It looks like it's still experimental: http://www.forshee.me/2016/02/22/container-mounts-in-ubuntu-1604.html

Anyway, if you can run any FUSE implementation in your container, you should be able to run google-drive-ocamlfuse without problems.

**Comment by Guilty-King** [comment]
@astrada thank you for the helpful link. As the post is from 2016 lxc is now replaced by docker ? 
I just started using docker and don't know anything about linux containers / ofc
Have you tried the method in above post?

**Comment by astrada** [comment]
Sorry, I don't really know much about containerization technologies. What about https://stackoverflow.com/a/49021109/2860133 ?

**Comment by Guilty-King** [comment]
The stackoverflow answer doesn't help as it needs to run the container in privileged mode and attach fuse device from host and so the container is dependent on host and porting the container to another host won't work. But thank you for your answer I will do some more research
