### ISSUE TITLE
i/o Error: cannot read  'file name.ods'

### ISSUE THREAD

**Issue by ix4** [astrada/google-drive-ocamlfuse#429]
Directory won't load.
```
ls: cannot access 'Property Search.ods': Input/output error
ls: cannot access 'Contact Information.ods': Input/output error
```
![screenshot from 2018-04-18 09-59-21](https://user-images.githubusercontent.com/38112035/38937238-bb1b783e-42f0-11e8-8c98-2f12a0498feb.png)
![screenshot from 2018-04-18 10-07-47](https://user-images.githubusercontent.com/38112035/38937239-bb280252-42f0-11e8-81cb-2b06a4a5110a.png)

**Comment by astrada** [comment]
You should enable debugging log to see what kind of error are you getting (https://github.com/astrada/google-drive-ocamlfuse#troubleshooting).
