### ISSUE TITLE
Feature request: Remove files from trash on delete

### ISSUE THREAD

**Issue by scriby** [astrada/google-drive-ocamlfuse#43]
I was a little surprised that the rm command left a copy of the file in the trash on Google Drive. It would at least be nice to have a setting to indicate that removing the file should also remove it from trash.

**Comment by ptokponnon** [comment]
How to delete files from trash "on purpose"?
This keeps me coming to empty the trash manually every 2 days (on the web interface), and it begins to be annoying...
