### ISSUE TITLE
Error with my Odroid XU4 with dietpi

### ISSUE THREAD

**Issue by ripoyet** [astrada/google-drive-ocamlfuse#432]
Hi astrada. I've a problem with my Odroid XU4 with **dietpi**. I've update google-drive-ocamlfuse and only install version 0.6.23. This version only give me this permissions (drwxr-xr-x) but in my ubuntu, I can install the version 0.6.24 and give me this permissions (drwxrwxr-x). I need the permissions of the version 0.6.24. I hope that you can help me. Thanks.

**Comment by astrada** [comment]
Check `umask` in `config`, that configuration key determines the default permissions.

**Comment by ripoyet** [comment]
Thank you very much. Other thing that I wanted to know. I've changed the permissions and now I have all of them, but if want to enter inside with my rtorrent client, the folder didn't exist. Thanks in advance.

**Comment by astrada** [comment]
I don't think I understood your issue, but I would advise against using a torrent client on a Drive FUSE-mount. That causes lots of unnecessary uploads/downloads. You'd better run rtorrent on a local directory and then upload them copying the files to Drive.
