### ISSUE TITLE
HDD become full 

### ISSUE THREAD

**Issue by babasa** [astrada/google-drive-ocamlfuse#433]
Hi if i am right, this software should not sync ? but why my hdd grow till full ? my google drive have more than 1 TB files and install gdfuse on VPS. i can delete manual in cacche, but is there someway to make it never happen again? while still have capability to read and write on my google drive??

this is my config

```
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=
client_secret=
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
presentation_format=pdf
presentation_icon=
read_ahead_buffers=3
read_only=false
root_folder=
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
umask=0o002
verification_code=
```

Yes i upload something but not bigger than 50 MB , but the cache eat more than 5 GB and i think will eat many more if i am not force unmount it

thats all thank you

**Comment by astrada** [comment]
If you don't need to upload big files, but you have big files you want to read (video, music, etc.) you can enable streaming with `stream_large_files=true`, so you don't have to download them before access.
