### ISSUE TITLE
access for google drive mounted folder from apache2

### ISSUE THREAD

**Issue by Themex** [astrada/google-drive-ocamlfuse#437]
Hi!
In docker project I'm trying to mount a "/var/www/html/user-media" folder to google drive. So I suppose, that this folder can be accessed with php script. But apache2 logs: 
> AH00035: access to /user-media/ denied (filesystem path '/var/www/html/user-media') because search permissions are missing on a component of the path

When I mount a folder I use user_allow_other option that I think takes no effect.

Google Drive credentials are ok, I can access folder from terminal

How to solve this?

**Comment by astrada** [comment]
It's probably a permission issue (like [this one](https://superuser.com/a/1081599) for example).

**Comment by Themex** [comment]
Thx for the answer!
I've tried another method. Apache2 uses www-data user, so I've found out it's gid and uid in terminal. 
`id www-data`
I used them as args on mounting. 
`google-drive-ocamlfuse /var/www/html/user-media -f -o uid=33, gid=33, allow_other`
So that I can access files on gdrive from apache2

**Comment by Themex** [comment]
I've got one more little question

Is it possible to apply root_folder on mount?

For instance,
`google-drive-ocamlfuse /var/www/html/user-media -f -o uid=33, gid=33, allow_other, root_folder=my_folder_id_or_path_whatever`

**Comment by astrada** [comment]
No, it's not possible. It works only in configuration.
