### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by thwaller** [astrada/google-drive-ocamlfuse#447]
Ubuntu 18.04 MATE
Kernel Linux 4.16.11-041611-generic x86_64
google-drive-ocamlfuse, version 0.6.24
Google Chrome 67.0.3396.56 beta

When I try to authenticate using:
`$ google-drive-ocamlfuse`
I get the following in my browser:
`500. That’s an error.
There was an error. Please try again later. That’s all we know.`
the URL it is at when this displays is:
`https://accounts.google.com/signin/oauth?client_id=........`

Have you experienced this before? I will keep trying, as this may be an issue on Google's end, but I wanted to start this process in case it is not. I have tried deleting the .gdfuse folder to ensure it is a fresh start as well, results do not change. This is a fresh install of google-drive-ocamlfuse. It has never been installed on this computer before. I have however used this on prior installs without problems. I have not before run this on 18.04 though. I believe the last time I used it was on a 17.04 install.

**Comment by thwaller** [comment]
I have authenticated using my own OAuth2 client ID, using the method above is still not working with same results.

**Comment by eightwt** [comment]
When I try to authenticate using:
$ google-drive-ocamlfuse
I get nothing. The browser does not launch, however the .gfuse directory is created.

**Comment by thwaller** [comment]
This was closed as it was fixed? There is no comment as to what has happened.

**Comment by astrada** [comment]
No, the 500 error is returned by Google, so it's not an issue of the application. If you want, you can try to logout from all your accounts on the browser that is opening and try again (or clean all the cookies). But there is no way I can fix this.

**Comment by sk75** [comment]
i am using ubuntu 22.04, when i enter google-drive-ocamlfuse, the browser does not open for authentication. the .gdfuse/default/gdfuse.log is empty

**Comment by imontesino** [comment]
Had the same issue, solved it by adding my email as a  test user under `Audience`
