### ISSUE TITLE
Cache grows larger than max_cache_size

### ISSUE THREAD

**Issue by tjcrone** [astrada/google-drive-ocamlfuse#448]
I am on 0.6.24, and I notice that the cache continues to grow beyond what is set in max_cache_size. Setting stream_large_file=true and setting large_file_threshold_mb=0 appears to disable caching completely, and that would be fine, but transfer rates when streaming appear to be about 5-6x slower than with the cache on (yes, when the files are not already in the cache). Any thoughts on what might be going on?

**Comment by grasmanek94** [comment]
same here..

```
root@SERVER:/home/insync# google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.6.24
Copyright (C) 2012-2018 Alessandro Strada
License MIT
```

config:
```
apps_script_format=json
apps_script_icon=
async_upload=true
cache_directory=
client_id=****************************************************************************************
client_secret=*******************************
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
form_format=zip
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=128
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=1638
max_download_speed=0
max_memory_cache_size=1073741824
max_retries=8
max_upload_chunk_size=10995116277
max_upload_speed=0
memory_buffer_size=107374182
metadata_cache_time=7200
presentation_format=pdf
presentation_icon=
read_ahead_buffers=3
read_only=false
root_folder=
shared_with_me=false
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=30000
stream_large_files=true
team_drive_id=
umask=0o022
verification_code=
```

the interesting parts:
```
large_file_threshold_mb=128
max_cache_size_mb=1638
max_memory_cache_size=1073741824
max_upload_chunk_size=10995116277
memory_buffer_size=107374182
read_ahead_buffers=3
```
which would mean.. 128 MiB, 1638 MiB, 1074 MiB, 11GiB, 107 MiB.. and if we take the biggest and multiply that by 3 we get 33 GB.. yet:

```
root@SERVER:/home/sync/.gdfuse/default# du cache -h
241G    cache
```
How can I prevent this from happening?

**Comment by brancomat** [comment]
> you can safely add a cron job to purge files in `~/.gdfuse/default/cache` and keep only `cache.db`

Does this mean that it's actually safe to remove any file in the cache directory (keeping only cache.db) when the path is mounted? What if there's an ongoing upload? (I suppose it's avoidable by removing only older files, the question is only to understand the scenario)

**Comment by astrada** [comment]
In unix and derivatives, when you delete a file, you don't actually remove it until there are open file descriptors (https://unix.stackexchange.com/questions/237817/delete-file-while-it-is-in-use), so if the upload completes without errors you should have no problems. But it's true that if you delete a file during an upload and the upload fails, it cannot be retried.
