### ISSUE TITLE
File corruption

### ISSUE THREAD

**Issue by jfhenriques** [astrada/google-drive-ocamlfuse#45]
Hey.. I'm trying to use this tool to upload some backups to my drive, but if they are large ~ 400MB they get corrupted. The files are sent in tar.gz file.

**Comment by astrada** [comment]
I'm closing this issue because there was no follow-up.

**Comment by cubixhost** [comment]
Hey @astrada , can you tell me is there an exact way to tell, from this gdfuse.log, whether there was or not something corrupted?

Also... is it possible to make some kind of error-only or corrupt-only verbosity to that log? Because it's so verbose it consumes megabytes in minutes.

Thank you!
