### ISSUE TITLE
Exception: userRateLimitExceeded

### ISSUE THREAD

**Issue by tcf909** [astrada/google-drive-ocamlfuse#453]
```
Thread 35768 killed on uncaught exception Failure("Error: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "userRateLimitExceeded",
    "message": "User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expect
```

Getting a lot of uncaught exceptions when rate limiting. Are the threads ok to die like that, or should these errors be caught and handled better?

**Comment by astrada** [comment]
> Are the threads ok to die like that, or should these errors be caught and handled better?

No, the app should retry the request when receiving that error. If you can reproduce while logging with `-verbose`, would you send me your `gdfuse.log` (my email is alessandro.strada@gmail.com)? I don't need the whole file. It should be enough to get about 50 lines around the line where you should find the string `ServiceError`. Thanks!
