### ISSUE TITLE
fuse: failed to open /dev/fuse: Operation not permitted

### ISSUE THREAD

**Issue by taozitaozi** [astrada/google-drive-ocamlfuse#454]
debian.
According to [this page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation) the installation was successful，but the last step failed。

```
google-drive-ocamlfuse -label googledrive  /googledrive
fuse: failed to open /dev/fuse: Operation not permitted
```

**Comment by astrada** [comment]
Have you tried mounting with `-o allow_other`?

**Comment by rkkoszewski** [comment]
Are you mounting in an lxc container?

**Comment by taozitaozi** [comment]
> Are you mounting in an lxc container?

OpenVZ  Server.Debian GNU/Linux 7.9 (wheezy).
Can't mounting？
Thanks

**Comment by rkkoszewski** [comment]
I did manage to make to make google-drive-ocamlfuse work in an LXC container. But you need to configure AppArmor and OpenVZ to allow access to /dev/fuse.
