### ISSUE TITLE
Allow setting acknowledgeAbuse to true

### ISSUE THREAD

**Issue by Masterxilo** [astrada/google-drive-ocamlfuse#458]
I have some executable files in my drive which google thinks contain a virus. I want to download these files like any others.

Right now, I cannot copy these files through my mounted Google Drive - I have to go to their website and download it from there, ignoring the virus warning.

It seems the google drive api allows doing this without manual confirmation using the extra parameter acknowledgeAbuse=true ( https://developers.google.com/drive/api/v3/manage-downloads#using_altmedia )

It would be very helpful if you could extend your tool to allow setting this option so that I can work with all of my files through it.

Thank you!

**Comment by Masterxilo** [comment]
Yes man astrada, fantastic job. I am pretty sure this makes this mounter the first to implement that, thanks so much.

One could of course encrypt the files but I like them indexing the stuff for me.

**Comment by astrada** [comment]
Actually, [rclone](https://github.com/ncw/rclone) handles `acknowledgeAbuse`. I checked their implementation because I don't have such a file (I tried to report some random file but it was not enough).
