### ISSUE TITLE
label containing hyphens ("-") works unexpectedly for Team Drives

### ISSUE THREAD

**Issue by vfinotti** [astrada/google-drive-ocamlfuse#459]
Hello,

I was trying to create a label for my Team Drive, and decided to call it "sprace-eng":
```
google-drive-ocamlfuse -label sprace-eng /home/vfinotti/gdrive-sprace-eng
```
I should mention that I added the ``team_drive_id`` correctly as mentioned on the [tutorial](https://github.com/astrada/google-drive-ocamlfuse/wiki/Team-Drives), before mounting it. However, the synchronized files were the ones from my drive, not the Team Drive. 

Creating a label without the hyphen successfully synchronized the Team Drive:
```
google-drive-ocamlfuse -label engineering /home/vfinotti/gdrive-sprace-eng
```

**Comment by astrada** [comment]
If your label contains `-`, you can use quotes, e.g.:

    google-drive-ocamlfuse -label "sprace-eng" /home/vfinotti/gdrive-sprace-eng
