### ISSUE TITLE
How to edit config?

### ISSUE THREAD

**Issue by Nate872711** [astrada/google-drive-ocamlfuse#460]
Sorry if this is in the wrong place.

I've searched everywhere and haven't found an answer on how to edit the config file.  All it shows is a list of the contents, but nowhere does it explain the commands you use to change them.

Are they just added after typing google-drive-ocamlfuse and before the drive path or is it something else?  If so, then how do you enter multiple?

Thanks for any help.

**Comment by hyperpress** [comment]
https://help.ubuntu.com/lts/serverguide/lxd.html.en#lxd-container-config as a starting point.

ex: lxc config set.something
