### ISSUE TITLE
Configuring TeamDrive correctly

### ISSUE THREAD

**Issue by bigdoods** [astrada/google-drive-ocamlfuse#466]
Hi,

Firstly, awesome tool. Thank you. Downloaded and got started with myDrive almost immediately.

I am having trouble mounting my team drive. I have added TEAM_DRIVE_ID in config and created a new label for the account (which is the same as the one used for myDrive) then mounted at mountpath but I can still only see the files in myDrive.

Steps to reproduce:
1. Add valid TEAM_DRIVE_ID to config
2. google-drive-ocamlfuse -label myTeamDrive
3. Auth - OK
4. mkdir gDriveTeam
5. google-drive-ocamlfuse -label myTeamDrive gDriveTeam/

I can identify that there is no step in here to select the team drive. My desired result would be that I have two directories in my home folder with respective contents from google drive, as follows:
a) gDrive
b) gDriveTeam

Thanks in advance.

John

**Comment by astrada** [comment]
Have you tried remounting with ‘-cc‘ too clear the cache?

**Comment by jellisii** [comment]
I'm having a similar problem here:  After I alter the config to add `team_drive_id=[MYID]` and mount, the config entry for `team_drive_id` gets removed from the config file and I only get my personal drive, even when using the `-cc` option.  

Version info:
```text
jellisii@mybox:~$ google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.6.21
Copyright (C) 2012-2017 Alessandro Strada
License MIT
```
Using PPA:
```text
jellisii@mybox:~$ cat /etc/apt/sources.list.d/alessandro-strada-ubuntu-google-drive-ocamlfuse-beta-artful.list
deb http://ppa.launchpad.net/alessandro-strada/google-drive-ocamlfuse-beta/ubuntu artful main
# deb-src http://ppa.launchpad.net/alessandro-strada/google-drive-ocamlfuse-beta/ubuntu artful main
```
OS info
```text
jellisii@mybox:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by astrada** [comment]
v0.6.21 doesn't support TeamDrives. Note that Ubuntu 17.10 has reached end of life, so I cannot upload updated packages. Try installing the bionic one if you cannot upgrade your distro.
