### ISSUE TITLE
C version?

### ISSUE THREAD

**Issue by themaddoctor** [astrada/google-drive-ocamlfuse#467]
Can you make a C version?

Building with OCaml requires ocaml-sqlite3 and ocaml-ppx-monadic or whatever, and none of these can be build without jbuilder. But jbuilder is now dune, and dune cannot be build without dune. Yes, dune cannot be build without dune. So, can you make a C version for those of use who use linux?

**Comment by themaddoctor** [comment]
ocaml-sqlite requires ocaml-base, which does not compile.

base-0.11.0 # jbuilder build
      ocamlc src/.base.objs/base__Formatter.{cmi,cmti} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/.base.objs -I /usr/lib64/ocaml/site-lib/sexplib0 -I compiler-stdlib/src/.caml.objs -I shadow-stdlib/src/.shadow_stdlib.objs -no-alias-deps -open Base__ -o src/.base.objs/base__Formatter.cmi -c -intf src/formatter.mli)
File "src/formatter.mli", line 9, characters 9-30:
Error: Unbound module Caml.Format
      ocamlc src/.base.objs/base__Import0.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I src/.base.objs -I /usr/lib64/ocaml/site-lib/sexplib0 -I compiler-stdlib/src/.caml.objs -I shadow-stdlib/src/.shadow_stdlib.objs -no-alias-deps -open Base__ -o src/.base.objs/base__Import0.cmo -c -impl src/import0.ml)
File "src/import0.ml", line 7, characters 6-394:
Error: The signature constrained by `with' has no component named Pervasives
base-0.11.0 # dune build
      ocamlc src/.base.objs/base__Import0.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I src/.base.objs -I /usr/lib64/ocaml/site-lib/sexplib0 -I compiler-stdlib/src/.caml.objs -I shadow-stdlib/src/.shadow_stdlib.objs -no-alias-deps -open Base__ -o src/.base.objs/base__Import0.cmo -c -impl src/import0.ml)
File "src/import0.ml", line 7, characters 6-394:
Error: The signature constrained by `with' has no component named Pervasives
      ocamlc src/.base.objs/base__Formatter.{cmi,cmti} (exit 2)
(cd _build/default && /usr/bin/ocamlc.opt -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -safe-string -g -bin-annot -I src/.base.objs -I /usr/lib64/ocaml/site-lib/sexplib0 -I compiler-stdlib/src/.caml.objs -I shadow-stdlib/src/.shadow_stdlib.objs -no-alias-deps -open Base__ -o src/.base.objs/base__Formatter.cmi -c -intf src/formatter.mli)
File "src/formatter.mli", line 9, characters 9-30:
Error: Unbound module Caml.Format

**Comment by themaddoctor** [comment]
No, not really. Building opam requires some things that require opam. Anyway, i got the damn thing built, but get this error:
```
401. That’s an error.

Error: invalid_client

The OAuth client was not found.
Request Details

    client_id=thomas.a.XXXXXXX
    redirect_uri=urn:ietf:wg:oauth:2.0:oob
    scope=https://www.googleapis.com/auth/drive
    response_type=code
    access_type=offline
    approval_prompt=force

That’s all we know.
```

**Comment by themaddoctor** [comment]
Failure("Code: 60, Description: CURLE_SSL_CACERT, ErrorBuffer: SSL certificate problem: unable to get local issuer certificate\n")

**Comment by astrada** [comment]
It looks like you have problems with the certificate store. What is the output of `curl -v https://www.googleapis.com`?

**Comment by astrada** [comment]
Have you tried getting an updated bundle (https://serverfault.com/a/293474)?

**Comment by themaddoctor** [comment]
Updating libcurl fixed it, even without a new cert bundle. Thanks for your time.

I can access stuff on the GD from the command line, but something about it is causing Konqueror (my file manager) to freeze up. Should I open an issue for that?
