### ISSUE TITLE
Changes on the gdrive are not consistently reflected when looking at the mountpoint

### ISSUE THREAD

**Issue by Kabouik** [astrada/google-drive-ocamlfuse#470]
# System
Debian Jessie VPS, `google-drive-ocamlfuse` installed using the [how-to in the wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie).
`google-drive-ocamlfuse` was installed using a new user (airsonic). This user owns `/home/airsonic/.gdfuse` as well as the mount point, `/home/airsonic/googledrive/gdrivemus1`.
I have set `metadata_cache_time=10` in the `/home/airsonic/.gdfuse/gdrivemus1/config`.

# Issue
When I add or remove some folders or files using the Google Drive interface, they may or may not (far more often not) show up in `ls -la /home/airsonic/googledrive/gdrivemus1`, even hours later (so it is not just a refresh time issue).

Some folders and their content did show up initially for my tests, but then when I wanted to continue adding some, I noticed the changes were not appearing in the mountpoint. I thought maybe there was an error with the authentication or mount, or just that I needed to manually refresh the drive to trigger the changes, so I tried the following:

```bash
fusermount -u /home/airsonic/googledrive/gdrivemus1 
google-drive-ocamlfuse -label gdrivemus1 /home/airsonic/googledrive/gdrivemus1
```
It didn't fix the issue, nor did `google-drive-ocamlfuse -cc`.

I also tried `touch /home/airsonic/googledrive/gdrivemus1/test`, and `test` appeared immediately on Google Drive UI meaning the computer has no issue writing on it. I could see `test` showing up in the terminal as well, and could delete it from there (which did remove it from the Google Drive UI).

It seems it's not an issue to write to the Google Drive, but reading from it is inconsistent and unreliable. Is that a known issue? Is there a fix?

![screenshot from 2018-08-01 20 55 00](https://user-images.githubusercontent.com/7107523/43542422-36628be8-95cd-11e8-9544-e60ead69555e.png)
![screenshot from 2018-08-01 20 56 01](https://user-images.githubusercontent.com/7107523/43542453-51039172-95cd-11e8-86e6-ae25505ef24f.png)

Six folders on Google Drive, five in the mount point. These images show only recent folders, but this is with a new installation of `google-drive-ocamlfuse` from scratch. I had the exact same issue yesterday and the files/folder were still invisible to the server after hours, or after remounting.

**Comment by Kabouik** [comment]
Note than I am having trouble getting [Airsonic](https://github.com/airsonic/airsonic) to see my files in the mount point, but I am not sure whether it is 100% related to the above issue. The [issue](https://github.com/airsonic/airsonic/issues/772) I have with Airsonic is some files that **do** show up in terminal are not scanned in the Airsonic library. Those that do not show up in terminal, of course, are not scanned either.

Now could it be that files that don't show up in terminal and files that do but are not seen by Airsonic are caused by the same thing? No idea, but I created an issue on both Github projects so we can see how interrelated they are.

**Comment by Kabouik** [comment]
Two hours later, the folder `Public broadcasting service` was still not listed in the mount point. I did the following again:

```
touch /home/airsonic/googledrive/gdrivemus1/toto.txt
rm /home/airsonic/googledrive/gdrivemus1/toto.txt
```

And the folder suddenly appeared. It is important to remember that the same manipulation two hours ago had no effect though, despite the fact that the folder was successfully added to Google Drive 30 minutes earlier.

**Comment by lfxc** [comment]
was this ever resolved?  I create files on google drve using the web interface, and they don't show up on the server via the mount point

**Comment by astrada** [comment]
Should be fixed in the latest versions.
