### ISSUE TITLE
Authorization with Service Accounts

### ISSUE THREAD

**Issue by stevenmccord** [astrada/google-drive-ocamlfuse#471]
I see that you have an alternative way to authorize accounts in a headless environment, but that still requires interactivity.  Is there a way to utilize service accounts instead?  

Thanks!

**Comment by josuearisty** [comment]
Hi, where can I find that alternative way? It never open the browser.

So I have never used this app before.

**Comment by karahan** [comment]
Is it possible to utilize server accounts? @stevenmccord @astrada

**Comment by astrada** [comment]
No, sorry, but it looks like [rclone](https://rclone.org/drive/#service-account-support) supports them.
