### ISSUE TITLE
Manpage doesn't follow Unix conventions

### ISSUE THREAD

**Issue by strugee** [astrada/google-drive-ocamlfuse#476]
Some examples I noticed right away:

* It's overall pretty verbose
* The OPTIONS section is missing
* `[*mountpoint*]` should have a space before it and shouldn't have `*`s

etc. I couldn't find the manpage in this repository, but if it was checked in I could probably send a PR.

Thanks for maintaining this; it's super useful. I'm using it for Borg backup to write to and it's been _awesome_ so far.

**Comment by astrada** [comment]
I've pushed the debian packaging directory in the debian branch. You can find the man page template here: https://github.com/astrada/google-drive-ocamlfuse/blob/debian/debian/google-drive-ocamlfuse.mkd
