### ISSUE TITLE
Mounting without manually clicking a link and copying the token on colab.

### ISSUE THREAD

**Issue by Tvde1** [astrada/google-drive-ocamlfuse#482]
I'm on google colab and every time I run my notebook, I have to manually auth to mount my drive.
I have the client id and client secret. Is there a way to make it authenticate by itself so I don't have to do manual clicking and copypasting?

**Comment by ra312** [comment]
Hi @Tvde1! Thanks for the great question! I would be also interested to accomplish token-less mount. Have you managed to mount without the secret ?  @astrada

**Comment by ra312** [comment]
Does this repo https://github.com/astrada/gd-ocaml-auth automate the authentication ?

**Comment by astrada** [comment]
That site provides an authentication proxy that uses a fixed client_id. It provides a way to authenticate via a web page, but it cannot be used with a personal client_id/client_secret.

**Comment by ra312** [comment]
Hi, @astrada. Thanks for getting back!
