### ISSUE TITLE
The OAuth client was not found.

### ISSUE THREAD

**Issue by glennamarshall** [astrada/google-drive-ocamlfuse#484]
Hi
I've been using this on Google Colab with no problems for the last week.  But it has suddenly stopped working with this error.

`401. That’s an error.

Error: invalid_client

The OAuth client was not found.

Request Details
client_id={creds.client_id}
redirect_uri=urn:ietf:wg:oauth:2.0:oob
scope=https://www.googleapis.com/auth/drive
response_type=code
access_type=offline
approval_prompt=force
That’s all we know.`

I don't what I may have done to make it stop working.
P.s. I'm using multiple google accounts at the same time - not sure if this is related - but didn't cause me problems before.
Thanks for any help.

**Comment by JoelParke** [comment]
I too have this issue.  What is even stranger is that when I connect to my development machine at 'localhost' all works as expected.  Yet when I attempt to connect on my server at xxxx.com, I get 401.  Even stranger, by github, gitlab, and facebook connections through passport, all work properly.  Only google has an issue.  It almost feels like one of my package.json changes is the problem... 
We will see.... But I hate this sort of regression.  When I figure it out, I will report back.
