### ISSUE TITLE
Mount once; use by many

### ISSUE THREAD

**Issue by bwbasheer** [astrada/google-drive-ocamlfuse#485]
Is it possible to issue one mount to a mount point that can be accessed by any logged in  user or executing process?

**Comment by astrada** [comment]
Have you tried mounti with `-o allow_other`?

**Comment by bwbasheer** [comment]
No, but I will do that.  That rings a bell from earlier reading.  Need to take better lab notes.  Thanks much.

**Comment by nonfatalexec** [comment]
> Have you tried mounting with `-o allow_other`?

Works for me
