### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by loicbisiere** [astrada/google-drive-ocamlfuse#49]
Hi,

I made some upload speed test with the last release (#47), and my average speed is 160ko/s. My server has a 100MB symmetric connection and when I test the Google Drive Client (Or directcly from the web interface - chrome) from a Windows Virtual Machine hosted on this server, my download / upload speed are > 10Mo/s.
Have you an idea why there is a such difference ?

Thank you.

**Comment by miriampl** [comment]
Hi I have same problem with upload
Network speed 100/100 MB
Upload a iso file 400MB in speed of 134 kB/s

I have changed metadata_cache_time - this has no effect.

don't know what the... by such speed it's not usable. In upload by browser i is 100MB for that folder with the same file

**Comment by astrada** [comment]
Unfortunately Drive API + FUSE is not an ideal combination when you need fast uploads. Maybe you can try this other project: https://github.com/odeke-em/drive (doesn't use FUSE, so maybe has faster uploads).
