### ISSUE TITLE
Error 400: invalid_scope

### ISSUE THREAD

**Issue by veqtor** [astrada/google-drive-ocamlfuse#491]
Has been working perfectly for a long time and now I get:

```
Error 400: invalid_scope
Some requested scopes cannot be shown: [https://www.googleapis.com/auth/drive, https://www.googleapis.com/auth/compute, https://www.googleapis.com/auth/appengine.admin, https://www.googleapis.com/auth/cloud-platform]
Request Details
redirect_uri=urn:ietf:wg:oauth:2.0:oob
prompt=select_account
response_type=code
client_id=32555940559.apps.googleusercontent.com
access_type=offline
display=page
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/appengine.admin https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/accounts.reauth https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/plus.me
```

**Comment by astrada** [comment]
I don't find `https://www.googleapis.com/auth/accounts.reauth` among the accepted scopes: https://developers.google.com/identity/protocols/googlescopes. Maybe that's the one causing the issue.

**Comment by JEF1056** [comment]
I also discovered that the last line,
```apt-get -y install -qq google-drive-ocamlfuse fuse```

results in
```E: Unable to locate package google-drive-ocamlfuse```

even though the repository has been added. Maybe this could be the cause of the issue?

![image](https://user-images.githubusercontent.com/22546776/45652577-e29c9a80-ba89-11e8-9995-51f99d3fd194.png)

**Comment by darylfung96** [comment]
I am also having this issues today

**Comment by astrada** [comment]
@JEF1056 @darylfung96: Which version of Ubuntu are you on? (You can get it running: `lsb_release -a`). I've removed the package for Ubuntu versions that reached end of life (zesty and artful).

**Comment by andrewkhimichuk** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by astrada** [comment]
@andrewkhimichuk: if you cannot upgrade to bionic, can you try downloading the package ([amd64](https://launchpad.net/~alessandro-strada/+archive/ubuntu/ppa/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1~ubuntu18.04.1_amd64.deb)) from bionic and install it with `sudo dpkg --install`?

**Comment by DonPex** [comment]
@astrada: I tried to install the package with `sudo dpkg --install` but it says that another package is needed:
` Preparing to unpack google-drive-ocamlfuse_0.7.0-0ubuntu1_ubuntu18.04.1_amd64.deb ...
Unpacking google-drive-ocamlfuse (0.7.0-0ubuntu1 ~ ubuntu18.04.1) over (0.7.0-0ubuntu1 ~ ubuntu18.04.1) ...
dpkg: dependency problems prevent configuration of google-drive-ocamlfuse:
 google-drive-ocamlfuse depends on libfuse2 (>= 2.8); however:
  Package libfuse2 is not installed.`

`dpkg: error processing package google-drive-ocamlfuse (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 google-drive-ocamlfuse `

**Comment by astrada** [comment]
Please have a look at https://github.com/astrada/google-drive-ocamlfuse/issues/493#issuecomment-422385109. Thanks to @daniel-leonard-robinson

**Comment by JEF1056** [comment]
@DonPex Changing my code to this:

```
# Install a Drive FUSE wrapper.
# https://github.com/astrada/google-drive-ocamlfuse
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!wget https://launchpad.net/~alessandro-strada/+archive/ubuntu/ppa/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1~ubuntu18.04.1_amd64.deb
!apt-get install libfuse2
!dpkg --install google-drive-ocamlfuse_0.7.0-0ubuntu1~ubuntu18.04.1_amd64.deb
#!apt-get -y install -qq google-drive-ocamlfuse fuse
```

Based off astrata's answer seemed to fix the issue.
