### ISSUE TITLE
E: Unable to locate package google-drive-ocamlfuse

### ISSUE THREAD

**Issue by mahmoudSalim** [astrada/google-drive-ocamlfuse#492]
!apt-get -y install -qq google-drive-ocamlfuse fuse

E: Unable to locate package google-drive-ocamlfuse

**Comment by darylfung96** [comment]
I am getting the same issue today

**Comment by Tvde1** [comment]
Same for me today. With code that has been running for a month every day.

**Comment by pjsudharshan** [comment]
I am facing the same issue! What's happening???? I am trying to install this from yesterday

**Comment by astrada** [comment]
I just uploaded version 0.7.0. Have you tried running `apt-get update` again?

**Comment by Tvde1** [comment]
I have a python notebook that runs this every day:
```
# Install a Drive FUSE wrapper.
# https://github.com/astrada/google-drive-ocamlfuse
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools > /dev/null
!add-apt-repository -y ppa:alessandro-strada/ppa > /dev/null
!apt-get update -qq > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse > /dev/null
```
And it strarted failing today. Do I need to check now?

**Comment by astrada** [comment]
Which version of Ubuntu are you on?

**Comment by Tvde1** [comment]
I'm using colab notebooks so I don't know. How can I check?

**Comment by KKeishiro** [comment]
I've got the same issue on Google colab notebook.

**Comment by yisonglee** [comment]
Warning: apt-key output should not be parsed (stdout is not a terminal)
E: Unable to locate package google-drive-ocamlfuse
I just encountered the same problem when i run keras in colaboratory.

**Comment by mahmoudSalim** [comment]
The solution is this using colab library
Thanks to Craig Citro
https://github.com/googlecolab/colabtools/issues/276

Solution : 
from google.colab import drive
drive.mount('/content/drive')

**Comment by Tvde1** [comment]
That is not a solution to the problem

**Comment by astrada** [comment]
To find out which version of Ubuntu you are running, you can use this command: `lsb_release -a`

**Comment by pjsudharshan** [comment]
What is it failing since yesterday which kept working for months???

**Comment by astrada** [comment]
Because I removed packages for zesty and artful, since they have reached end of life (https://wiki.ubuntu.com/Releases). If you cannot upgrade to bionic, you should download the package from the ppa (e.g. [amd64](https://launchpad.net/~alessandro-strada/+archive/ubuntu/ppa/+files/google-drive-ocamlfuse_0.7.0-0ubuntu1~ubuntu18.04.1_amd64.deb)) and install it with `dpkg --install`.

**Comment by jayjtao** [comment]
@astrada  need help - steps/details to do this on colab?

**Comment by astrada** [comment]
Have a look at this script: https://stackoverflow.com/questions/52385655/unable-to-locate-package-google-drive-ocamlfuse-suddenly-stopped-working/52387195#52387195

But you can also use the builtin FUSE driver: https://github.com/googlecolab/colabtools/issues/276#issuecomment-422199546

**Comment by rushic24** [comment]
> Solution:
> 
> ```
> from google.colab import drive
> drive.mount('/content/drive')
> ```
> For example,If you want to find your file:
> 
> ```
> import os
> os.chdir("drive/My Drive/Colab/AIC")
> ```

This worked for 2 days for me ,now that is also not working :|

**Comment by linxid** [comment]
> > Solution:
> > ```
> > from google.colab import drive
> > drive.mount('/content/drive')
> > ```
> > For example,If you want to find your file:
> > ```
> > import os
> > os.chdir("drive/My Drive/Colab/AIC")
> > ```
> 
> This worked for 2 days for me ,now that is also not working :|

This still worked for me,I am using Colab training NN model.

**Comment by RecepCil** [comment]
> 
> 
> The solution is this using colab library
> Thanks to Craig Citro
> [googlecolab/colabtools#276](https://github.com/googlecolab/colabtools/issues/276)
> 
> Solution :
> from google.colab import drive
> drive.mount('/content/drive')

I've got the same issue. I am new to Google Colab so this is a bit confusing for me. I tried your solution but it doesn't work for me. Have I done something wrong?



`from google.colab import drive`
`drive.mount('/content/drive')`

`!apt-get install -y -qq software-properties-common python-software-properties module-init-tools`
`!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null`
`!apt-get update -qq 2>&1 > /dev/null`
`!apt-get -y install -qq google-drive-ocamlfuse fuse`
`from google.colab import auth`
`auth.authenticate_user()`
`from oauth2client.client import GoogleCredentials`
`creds = GoogleCredentials.get_application_default()`
`import getpass`
`!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL`
`vcode = getpass.getpass()`
`!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}`

**Comment by SoleSensei** [comment]
You should choose **just one** mounting method.

### 1. Using build-in Fuse
```py
! echo 'Mounting...'
from google.colab import drive
drive.mount('/content/drive/')
! ls 'content/drive/My Drive'
! echo 'Mounted'
```
### 2. Using `google-drive-ocamlfuse` Fuse Driver
```py
! echo 'Installing required software'
! apt-get install -y -qq software-properties-common -y -qq module-init-tools
! echo 'Add apt-repository with Google.Drive Fuse'
! add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
! echo 'Updating packages...'
! apt-get update -y -qq
! echo 'Installing google-drive-ocamlfuse fuse...'
! apt-get install -y -qq google-drive-ocamlfuse fuse
! echo 'Authenticate Fuse in Google.Drive...'
from google.colab import auth
from oauth2client.client import GoogleCredentials
import getpass
auth.authenticate_user()
creds = GoogleCredentials.get_application_default()
! google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
! echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
! echo 'Authenticated!'
! echo 'Creating mount directory'
! mkdir ./drive2
! echo 'Mounting...'
! google-drive-ocamlfuse ./drive2
! ls ./drive2
! echo 'Mounted!'
```
