### ISSUE TITLE
Add option to overwrite file instead of trashing when using mv

### ISSUE THREAD

**Issue by kabili207** [astrada/google-drive-ocamlfuse#494]
The current behavior when using `mv` will trash the existing file and create a new file. This causes problems with files that are mapped to multiple folders in Google Drive (done using `Shift+Z` on the website). I suspect this also causes issues with files that are shared with other people, however I haven't tested that scenario. There is also the minor annoyance that the Activity history of the file on the website is wiped out. 

Looking at the current options, `keep_duplicates` seems to only create another file with the same name. Can we get a config option to overwrite the existing file *without* trashing it?

**Comment by kabili207** [comment]
After a bit of use, I realized this was really only happening in KeePassXC. Digging around the [source code](https://github.com/keepassxreboot/keepassxc/blob/cb3c4893dce571c9cbfb7f32ee4580f24bb05108/src/core/Database.cpp#L243), it's explicitly deleting and re-creating the file. I haven't been able to recreate my initial test with `mv`, so I feel safe saying this is an issue with KeePassXC.

**Comment by astrada** [comment]
Thanks for your feedback!

**Comment by Tschebbischeff** [comment]
I'm afraid I have to get back to this. While it is true, that I am also just happened to have this problem on KeePassXC so far, I have done tests with manually moving files.

The file will also be sent to the trash bin, when using mv from terminal to move files on the same filesystem itself (mounted drive to another folder on the same mounted drive) and from the host filesystem to the mounted drive.

So I am quite convinced this might not be an issue with only KeePassXC.

The correct behavior should be to "update" the file like it does when copying the file, which will result in a new "version" of the file.

So I would propose the same @kabili207 did before. To add an option that overwrites the existing file when doing an mv without trashing it from google drives perspective.

**Comment by noahajac** [comment]
Can confirm this is not an issue solely with KeePassXC.

Creating a text file and editing with gedit results in the same behavior: the creation of a new file.

Honestly this is more than a simple enhancement and is a pretty decent issue. One of the main uses of syncing Google Drive to Desktop is being able to sync and share files with other computers/software. This behavior breaks this functionality for many programs.

**Comment by astrada** [comment]
In version 0.7.9, I've added config option `mv_keep_target`. If you set it to `true` you should get the expected behavior.
