### ISSUE TITLE
Limit permission to current user with Fuse

### ISSUE THREAD

**Issue by klemy** [astrada/google-drive-ocamlfuse#497]
Hello, I currently use "pam_mount" in order to mount my Google Drive folder.

## The problem

I want to limit the permissions to the current user in order to use my SSH keys stocked on my Google Account. But the currents rights is `755`.

How can I se the permissions to `700` ?

### `~/.pam_mount.conf.xml`
```
<pam_mount>
    <volume fstype="fuse" path="gdfuse#[ABC]" mountpoint="~/Cloud/Google/[ABC]" options="nosuid,nodev" />
</pam_mount>
```

### `~/.gdfuse/[ABC]/config`
```
...
umask=0o700
...
```

### `/etc/security/pam_mount.conf.xml`
``` 
<pam_mount>
    <debug enable="0" />

    <luserconf name=".pam_mount.conf.xml" />

    <mntoptions allow="nosuid,nodev,loop,encryption,fsck,nonempty,allow_root,allow_other" />
    <mntoptions require="nosuid,nodev" />

    <logout wait="0" hup="no" term="no" kill="no" />

    <mkmountpoint enable="1" remove="true" /> 
</pam_mount>
```

Regards,

**Comment by klemy** [comment]
Thanks for responding me.

I have removed the `allow_others` option from `mntoptions allow` in `/etc/security/pam_mount.conf.xml` and added the `allow_root` in `~/.pam_mount.conf.xml
`.

I now have this error :
```
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:72): umount messages:
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:76): fusermount: failed to unmount /home/clesne/Cloud/Google/clementlesne.cl@gmail.com: Invalid argument
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:892): unmount of gdfuse#clementlesne_cl_gmail_com failed
```

**Comment by klemy** [comment]
Thanks for responding me.

I have removed the `allow_others` option from `mntoptions allow` in `/etc/security/pam_mount.conf.xml` and added the `allow_root` in `~/.pam_mount.conf.xml
`.

I now have this error :
```
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:72): umount messages:
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:76): fusermount: failed to unmount /home/clesne/Cloud/Google/[ABC]: Invalid argument
Oct  5 11:21:00 LESNE-XPS13 gdm-session-worker[22792]: (mount.c:892): unmount of gdfuse#[ABC] failed
```

**Comment by klemy** [comment]
Thanks for responding me.

I have removed the `allow_others` option from `mntoptions allow` in `/etc/security/pam_mount.conf.xml` and added the `allow_root` in `~/.pam_mount.conf.xml
`.

I now have this error :
```
gdm-session-worker[22792]: (mount.c:72): umount messages:
gdm-session-worker[22792]: (mount.c:76): fusermount: failed to unmount /home/[USER]/Cloud/Google/[ABC]: Invalid argument
gdm-session-worker[22792]: (mount.c:892): unmount of gdfuse#[ABC] failed
```

**Comment by astrada** [comment]
It looks like the error occurred during unmount. Have you tried remounting?
