### ISSUE TITLE
Sambashare google drive (Ubuntu server 18.04)

### ISSUE THREAD

**Issue by LoYungSum** [astrada/google-drive-ocamlfuse#498]
I've mounted my google drive account in /home/user/GoogleDrive. 
While now I want to sambashare the folder. 
But when I set the "GoogleDrive" as the root directory of sambashare. 
I got "you do not have permission to access this server". 
I have checked the ownership of the "GoogleDrive" folder, which is "root:root".
I try to set it to "user:user" which is my account name. 
But I got "chmod: invalid mode: ‘user:user’ Try 'chmod --help' for more information."
What should I do?

**Comment by LoYungSum** [comment]
Also, I don't know why I cannot config the automount correctly.

/usr/bin/gdfuse
`
#!/bin/bash

su user -l -c "google-drive-ocamlfuse /home/user/GoogleDrive -label user"
exit 0`

/etc/fstab
`gdfuse`

**Comment by m-rufflesmcghie** [comment]
Are "root" & "user" in the samba group ?? I'm working on auto mount myself at the moment 1st attempt failed :-(

**Comment by maravento** [comment]
Similar problem: https://askubuntu.com/questions/1090964/share-folder-into-google-drive-with-samba

**Comment by maravento** [comment]
@LoYungSum Read this: [Share Google Drive with Samba (using google-drive-ocamlfuse)](https://www.maravento.com/2018/11/compartir-google-drive-con-samba.html)

Thanks to this project
