### ISSUE TITLE
Shared_with_me, it takes 3-5 minutes for shared folder to show up in the .shared folder

### ISSUE THREAD

**Issue by avatar-lavventura** [astrada/google-drive-ocamlfuse#499]
I have followed [guide](https://github.com/astrada/google-drive-ocamlfuse/issues/282#issuecomment-289311164) to have `.shared` folder under the google drive's mounted folder.

I observe that it takes 3-5 minutes for shared folder/file to show up under `.shared` folder.

- Why the share files/folders does not show up on the `.shared` folder right away?
- Is it normal that it takes 3-5 minutes for `.shared` folder to fetch them? Is there a optimal time to fetch shared folder/files? If yes, can we make it faster?

**Comment by astrada** [comment]
That's depend on how many Google Docs you have shared. Since Google Docs cannot be downloaded lazily, you have to wait until all the docs are cached. If you don't care about Google Docs, you can set `download_docs=false` in the config, and this should speed things up.
