### ISSUE TITLE
async_upload=false not working or not persistent?

### ISSUE THREAD

**Issue by sagaciouskjb** [astrada/google-drive-ocamlfuse#500]
I'm attempting a borg backup with google-drive-ocamlfuse.  I have read in other tickets that setting async_upload=false might help, but what I have noticed is that the line disappears from the config file after I've set it.

Not sure if this is a bug or if I just don't understand the proper usage.  I can't find anything about async_upload being deprecated, and it's still listed as an option in the [Configuration](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration) documentation.

I thought maybe my edits just weren't being saved for some other reason, but it definitely seems like google-drive-ocamlfuse is being overwritten.

(Could not figure out how to get markdown to not put this all on one line, sorry)
https://pastebin.com/V6N3vEuc

**Comment by astrada** [comment]
Sorry, I forgot to mention that I removed that option in version 0.7.0 (I've just updated the wiki).

**Comment by sagaciouskjb** [comment]
Okay, thanks for speedy reply!
