### ISSUE TITLE
Config being overwritten

### ISSUE THREAD

**Issue by qazero** [astrada/google-drive-ocamlfuse#501]
There seems to be a bug when using the -c parameter to specify your own location for a customized config file. The file keeps being overwritten each time the drive is remounted. Why is that?

**Comment by astrada** [comment]
The configuration file is rebuilt every time you remount your drive. That's the strategy I use to migrate configuration when you upgrade the application to new versions (so you get the new options).

**Comment by qazero** [comment]
There seems to be a bug because each time the drive is remounted the configuration file is overwritten with the default template. I understand that the configuration file is rebuilt every time but should't the tweaks to the original template be migrated to the rebuilt config each time the drive is remounted? If not, then this is a huge logic issue.

For example, in the original template, the "stream_large_files" setting is set to false but in my tweaked config I have this set to true as well as many other tweaks to other settings as well. I have a script which I run on cron to check if google-drive-ocamlfuse is still mounted and if it isn't then I remount it. The problem arises when the drive is remounted because the modified config I am using gets overwritten. Therefore, once the drive is remounted the performance is horrible making it unable for my needs. But when I am using my tweaked modified config file the performance is excellent.

That being said, what would you recommend to fix this? Am I doing something wrong? Settings in the config file shouldn't need to be re-entered each time the drive is remounted, they should be persistent. Please advise, thanks.

**Comment by astrada** [comment]
> There seems to be a bug because each time the drive is remounted the configuration file is overwritten with the default template.

This should not happen. The `config` file is regenerated from default values only if the file is not present, otherwise previous values should be preserved.

**Comment by qazero** [comment]
Why would the original config get overwritten? I can assure you the file is/was present but every so often I find the values get overwritten. It doesn't happen every time the drive is re-mounted but it does happen every so often for some reason...

**Comment by astrada** [comment]
> Why would the original config get overwritten?

It is overwritten, because if I add new config options, you get them for free with their default values after the upgrade.
