### ISSUE TITLE
[question] full access to docs and slides

### ISSUE THREAD

**Issue by kirk86** [astrada/google-drive-ocamlfuse#503]
Hi, thanks for creating and sharing this, I was just wondering if there are any plans on adding full read/write access to `Read-only access to Google Docs, Sheets, and Slides`.
Thanks!

**Comment by astrada** [comment]
No, sorry. The reason for this behavior is that this kind of documents cannot be downloaded directly in their native format, but have to be exported in another format (LibreOffice format for example). I've tried to edit this kind of documents and re-import them on Drive, but usually the document layout gets messed, so I've decided to keep these file read-only to avoid unexpected modifications. As a workaround you can configure those files to open directly in the web browser, if you are not on a headless server (https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration#document-export-formats).

**Comment by kirk86** [comment]
@astrada thanks for the prompt response, appreciate the info.
Closing, to keep things clear.
