### ISSUE TITLE
errror upon installation

### ISSUE THREAD

**Issue by kirk86** [astrada/google-drive-ocamlfuse#504]
@astrada I keep getting this on installation
```
/tmp/tmp-user/aur-ocaml-sqlite3/src/sqlite3-ocaml-4.4.0
[ERROR] No switch is currently set. Please use 'opam switch' to set or install a switch
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build ocaml-sqlite3.
```
I think it requires switching to another compiler? Any ideas?

**Comment by didipluto** [comment]
I try installing compiler :

opam switch install ocaml-base-compiler

The sqlite3 can be installed but it gets the error in :

Error: /usr/lib/ocaml/sqlite3/sqlite3.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.

**Comment by astrada** [comment]
Why don't you try removing opam and install the package in AUR: https://aur.archlinux.org/packages/google-drive-ocamlfuse?

**Comment by os369510** [comment]
I was same problem here and I upgrade the ocaml-sqlite3 to version 4.4.1-1.
It works for me.

Reference:
https://aur.archlinux.org/packages/ocaml-sqlite3/
