### ISSUE TITLE
HTTP/2 uploading problems: New files not readable and have 0 size

### ISSUE THREAD

**Issue by rqi14** [astrada/google-drive-ocamlfuse#508]
Hi

I am using google-drive ocamlfuse 0.7.0 on Debian 9 Jessie. Recently I found that new files uploaded to my google drive through other ways (mountain duck or expandrive) have zero size in google-drive-ocamlfuse mounted drive. This issue can only be solved by doing umount and mount again. Is there any settings I did wrong? I do not think this issue exists before.

My settings are:
`
acknowledge_abuse=false

apps_script_format=json

apps_script_icon=

cache_directory=

client_id=

client_secret=

connect_timeout_ms=5000

curl_debug_off=false

data_directory=

delete_forever_in_trash_folder=false

desktop_entry_exec=

docs_file_extension=true

document_format=odt

document_icon=

download_docs=true

drawing_format=png

drawing_icon=

form_format=zip

form_icon=

fusion_table_format=desktop

fusion_table_icon=

keep_duplicates=false

large_file_read_only=true

large_file_threshold_mb=64

log_directory=

lost_and_found=false

low_speed_limit=0

low_speed_time=0

map_format=desktop

map_icon=

max_cache_size_mb=1024

max_download_speed=0

max_memory_cache_size=10485760

max_retries=8

max_upload_chunk_size=1099511627776

max_upload_speed=0

memory_buffer_size=1048576

metadata_cache_time=60

metadata_memory_cache=true

metadata_memory_cache_saving_interval=30

presentation_format=pdf

presentation_icon=

read_ahead_buffers=3

read_only=false

root_folder=

shared_with_me=false

spreadsheet_format=ods

spreadsheet_icon=

sqlite3_busy_timeout=5000

stream_large_files=true

team_drive_id=

umask=0o022

verification_code=

`

**Comment by astrada** [comment]
Do you experience the same problem if you upload a new file using Google Drive's web interface?

**Comment by rqi14** [comment]
> Do you experience the same problem if you upload a new file using Google Drive's web interface?

Hi. I think they are the same. I uploaded using Mountain Duck and I can see it via both Mountain Duck and Expandrive but not with google-drive-ocamlfuse. 

I cannot test anymore because it seems deleting the default folder and authorizing again solved the problem. Thanks anyway.

**Comment by rqi14** [comment]
> Do you experience the same problem if you upload a new file using Google Drive's web interface?

Hi. It appeared again so I did more testing. It turned out that this happens only when I upload files using Mountain Duck but it is normal when I upload with web interface or expandrive. However, it is weird that the file size appears to be correct in both Expandrive and google drive web interface but not in google-drive-ocamlfuse. Do you have any idea why?

**Comment by astrada** [comment]
I don't know. Maybe Mountain Duck creates a 0-length file and then uploads the content?

**Comment by canardos** [comment]
I am not sure if it is the same issue, but am experiencing the following 0-length issue, resulting in data loss:

- Mount drive
- Create a new file in LibreOffice Calc, add content, save to mounted location.
- At this point, the local file system shows the file as having positive size, but Google Drive (via web/phone interface) shows file present, but with 0-size.
- Close file, exit LibreOffice
- Unmount drive
- The file on Google Drive is still 0-length

If the drive is remounted immediately, then the local file system will show the positive size file. (presumably writes are not being flushed and the local cache is still valid?). But if I wait a day, then after remounting I see the 0-length file only (local cache expired?) and the original data is lost.

**Comment by astrada** [comment]
@canardos can you reproduce your issue mounting with `-debug` and send `gdfuse.log` and `curl.log` to me (alessandro.strada@gmail.com), please?

**Comment by dnapier** [comment]
I'm experiencing the same as canardos.  

I'm not sure if this is related, but I use 3 gdrives, 1 default and 2 using the -label flag.  Of the two using the label flag, the third is a team drive.  I use a script to run through all 3 after network connection is established.  The two drives using the -label flag mount, but do not show as drives on the desktop nor in the 'Places' panel menu.

I'll do the same as requested of canardos, and email you the -debug/gdfuse.log/curl.log.

**Comment by astrada** [comment]
@dnapier: I'm sorry but it's not the same issue, and I don't see any error in the log files you sent me. If you want you can append an `&` after your mount command to keep them in background (`google-drive-ocamlfuse -debug ~/gdrive &`).

**Comment by astrada** [comment]
Should be fixed by astrada/gapi-ocaml@0dd1d4e released with gapi-ocaml 0.3.8.
