### ISSUE TITLE
How to setup streaming uploading?

### ISSUE THREAD

**Issue by petrohiv** [astrada/google-drive-ocamlfuse#509]
I have a following scenario: I want to capture video stream and write it to my mounted gdrive. I use default configuration of ocamlfuse. The thing is that the machine doing capture has not so big HDD so it's important to upload recordings as fast as possible, without letting hard drive be full. 
Can you please suggest any config modifications or options that can help in my case?

**Comment by astrada** [comment]
Unfortunately Google Drive's API only supports uploading whole files so there are no options you can use to enable streaming for uploads.

**Comment by petrohiv** [comment]
I see. Thanks a lot for your answer! But can you reveal caching strategy then? Does ocamlfuse remove from cache storage any files that are not in downloading or uploading at the moment?

**Comment by astrada** [comment]
It should remove cached files as soon as the upload ends if the total size of cache is above `max_cache_size_mb`.
