### ISSUE TITLE
one of the mount occasionally crash

### ISSUE THREAD

**Issue by ilovetosharing** [astrada/google-drive-ocamlfuse#510]
i'm using bash script to run mount at startup : 
#!/bin/bash  
google-drive-ocamlfuse -o allow_other -label storage01 /var/www/web1/media/videos/
google-drive-ocamlfuse -o allow_other -label storage02 /var/www/web2/media/videos/

but occasionally one of the mount crash after 2-3 hours while new video been uploading

i make cronjob to check every 5 minute 
*/5 * * * * /usr/local/bin/checkstorage01.sh
*/5 * * * * /usr/local/bin/checkstorage02.sh

but cronjob cant restart my server, the bash script checkstorage01.sh :
#!/bin/bash  
if [ ! $(find /var/www/web1/media/videos | wc -l) -gt 1 ]; then  
    reboot  
fi  

my question is : 
Do you know the easy way to remount automatically if one of the drive crash when mounting?

**Comment by astrada** [comment]
If the google-drive-ocaml process hangs, you should kill it with -9, then run `fusermount -u [mountpoint]`.

**Comment by ilovetosharing** [comment]
i'm sorry but can you give me example how to mount 2 drive at once using fusermount -u [mountpoint] and how to make it function like this : 
google-drive-ocamlfuse -o allow_other -label storage01 /var/www/web1/media/videos/
google-drive-ocamlfuse -o allow_other -label storage02 /var/www/web2/media/videos/

please help.
