### ISSUE TITLE
Mounted directory eat local harddisk space

### ISSUE THREAD

**Issue by Medow** [astrada/google-drive-ocamlfuse#513]
Hello:
I am using google-drive-ocamlfuse installed from apt on Ubuntu 18.04.1 .
I mount it on directory /var/www/html/drive
My local harddisk have 20GB space and i have other network HD with 200 GB which i use to store my data before transfer it to google drive.
My localdrive have a 17 GB free space.
The problem is:

- I am not able to move more than that 17 GB to the mounted directory .
- When i move those 17 GB to the mounted directory the `df -h`  show that the local hardisk is 100% full.
- I try to unmount google drive directory but `df -h`   still show that my harddsik is 100% full.
- I have to reboot my PC to have `df -h`   show the correct space.

Is this problem for your own side or it is related to Ubuntu OS?

Thanks

**Comment by astrada** [comment]
There was a bug (#512) that should be solved in the latest beta version, that caused a similar behavior. File were not closed correctly after upload, so disk space could not be reclaimed until you unmounted your Drive. You can test if the fix solves this issue for you pointing to the beta [ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta).

**Comment by Medow** [comment]
I can confirm that using this beta is solving the issue.
Thanks.

**Comment by astrada** [comment]
Thanks for your feedback.
