### ISSUE TITLE
dyld: Library not loaded [Unable to start using the utility]

### ISSUE THREAD

**Issue by sunandosamaddar** [astrada/google-drive-ocamlfuse#516]
**After `opam install google-drive-ocamlfuse`**
```
$ google-drive-ocamlfuse -version
dyld: Library not loaded: /usr/local/lib/libssh2.1.dylib
  Referenced from: /Users/sunandosamaddar/.opam/SWITCH/bin/google-drive-ocamlfuse
  Reason: image not found
Abort trap: 6
```
Resolved by installing libssh2.
```
$ google-drive-ocamlfuse -version
dyld: Library not loaded: /usr/local/lib/libssl.1.1.dylib
  Referenced from: /Users/sunandosamaddar/.opam/SWITCH/bin/google-drive-ocamlfuse
  Reason: image not found
Abort trap: 6
```
Resolved by installing openssl 1.1, then something like below turns up.
```
$ google-drive-ocamlfuse -version
dyld: Library not loaded: /usr/local/lib/libgssapi_krb5.2.2.dylib
  Referenced from: /Users/sunandosamaddar/.opam/SWITCH/bin/google-drive-ocamlfuse
  Reason: image not found
Abort trap: 6
``` 
Tried installing`gss` using `port install` but no effect. What is happening is when one dylib file requirement is satisfied another dylib requirement comes up. I installed libssh2, openssl1.0.2, and openssl1.1.1 by downloading source files and then following the INSTALL plus available online documentations. No issues with dependencies during this process, I managed to do it as instructed.

**Comment by astrada** [comment]
It looks like you need `krb5` (kerberos).

**Comment by sunandosamaddar** [comment]
You're a genius! I can now see `-version`:-D.
