### ISSUE TITLE
Failing to mount but returning successful

### ISSUE THREAD

**Issue by JP-Ellis** [astrada/google-drive-ocamlfuse#52]
Hi,

I'm currently writing a script to automatically mount Google drive, sync relevant files, and then dismount Google drive (or leaving it mounted if it was already).  I do not like leaving Google drive mounted because it causes the parent folder to load very slowly (and any process which access information of the mounted file system, such as the system monitor), but that could be a separate issue.

The issue here is that I'd like to ensure that google-drive-ocamlfuse has successfully mounted Google drive and to check that, I thought I'd just look at the exit code; however, it sometimes exits with 0 even if it failed to mount Google drive.  In particular, I have noticed this happening if the folder being mounted to is non-empty.

In the mean time, I can parse `mount -l` to check that it has been mounted, but google-drive-ocamlfuse should probably not exit with 0 if it failed.  This would also allow the use of `&&` and `||`.

Cheers

**Comment by arifmahmudrana** [comment]
But what I always want to mount it on start up like ```Dropbox linux client```, it also will show the error I guess.

I have a google account that I mounted & that is not empty after syncing now I added ```google-drive-ocamlfuse ~/gdrive``` in my start up application but it doesn't mount & when running ```google-drive-ocamlfuse ~/gdrive``` it prints this error.

Now if I run command as you mentioned ```google-drive-ocamlfuse -o ~/gdrive``` it will hide the files already synced & again download the files I guess.

**Comment by astrada** [comment]
Sorry, but this is not a sync app like the Dropbox one. When you unmount your Drive, you cannot access your files anymore.

**Comment by arifmahmudrana** [comment]
@astrada so do I have to again delete the folder then again using access token again sync all the file

**Comment by astrada** [comment]
google-drive-ocamlfuse gives you a view of your Drive. It doesn't download your files locally. If you need to copy your remote files you could use rsync from the mountpoint to a local directory. Or you can switch to a sync app (e.g.: https://github.com/Grive/grive).
