### ISSUE TITLE
Google One?

### ISSUE THREAD

**Issue by fgilbert68** [astrada/google-drive-ocamlfuse#520]
Hi,
Sorry as this is not an issue and this may be a FAQ, but a reasonable search didn't bring anything to me.
My question is, does google-drive-ocamlfuse allow to mount the new Google One cloud space offered by Google, and to which Google Drive paying subscribers are to be moved onto sooner or later?
Thank you.

**Comment by astrada** [comment]
I think that Google One is just a new name for Google Drive. I think the current API will work with the new service.

**Comment by fgilbert68** [comment]
Thanks for your reply, let's cross fingers.

**Comment by quamis** [comment]
I'm using google-drive-ocamlfuse to backup & download my photos from gdrive to my local computer. Recently I've started using Google One. The backup process I've setup with google-drive-ocamlfuse works without any changes, so I'd say that it uses the same API.

This issue should be closed

**Comment by astrada** [comment]
Thanks for your feedback!
