### ISSUE TITLE
files added through browser from another computer do not show up via the linux mount point for quite a while

### ISSUE THREAD

**Issue by lfxc** [astrada/google-drive-ocamlfuse#523]
already have a mount point to my google drive files, can see everything, upload a file via the browser and do not see it for quite a while, not sure how long because I haven't times it, but should show up within seconds.  I've reduced the cash setting to 10 seconds but doesn't do anything.   This is a major issue for users that share folders/files with one another and need to collaborate in real time.

thanks

**Comment by astrada** [comment]
Which version are you using? How do you check if there is a new file? (with a GUI? with the command shell?)

**Comment by lfxc** [comment]
not sure how to check the version, but I just installed 2 days ago on debian 9 using these instructions:  https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

let me know how to check the version and I will do so.

In terms of checking for the file I had Thunar open - I'm using xfce4, and I also checked through a shell thinking it may have been Thunar, but it didn't show up through a shell either.

Should be very easy to recreate:
1) Mount google drive in Linux desktop
2) open file manager (Thunar in my case), and go to folder where you will upload file to
3) upload file through the google drive browser interface using another machine.

In my case though, I used the same account for the google drive mount as well as for the upload from another machine, if that makes any difference.

thanks

**Comment by lfxc** [comment]
Version:
google-drive-ocamlfuse, version 0.6.23
Copyright (C) 2012-2017 Alessandro Strada
License MIT

That is the problem.  I do an "ls" from a terminal window and the file doesn't show up.  I just uploaded another test file and I'm still not seeing it after doing "ls" commands from a terminal for over 12 minutes.

One interesting thing I just noticed which may provide a clue is that the GoogleDrive mount was performed by a regular user but when I log in as root and try to "cd" to that mount point I get "permission denied"

**Comment by astrada** [comment]
> google-drive-ocamlfuse, version 0.6.23

OK, that version had the issue you are reporting. If you upgrade to the latest version (0.7.1) you should resolve your problem.

**Comment by lfxc** [comment]
that's good news.  given that I use the installation instructions here:
https://github.com/astrada/google-drive-ocamlfuse/wiki/How-to-install-from-source-on-Debian-Jessie

How can I update to 7.1?  Not sure how to do that

thanks

**Comment by astrada** [comment]
Debian Jessie ships with an old version of the OCaml compiler, so you have to update it. You can do this with:

    opam switch create 4.07.1
    eval $(opam env)

And then, reinstall google-drive-ocamlfuse:

    opam install google-drive-ocamlfuse

**Comment by lfxc** [comment]
hmm. not working.  

I run
     opam siwtch create 4.07.1
and get:
     opam: Invalid switch subcommand "create"
     Usage: opam switch [OPTION]... [COMMAND] [ARG]...
     Try `opam switch --help' or `opam --help' for more information.

**Comment by lfxc** [comment]
may be easier to just do the install using the latest version.  Here are the commands I use to install.  WHat would need to be changed to use the latest version?  thanks


        apt-get -y install m4 libcurl4-gnutls-dev libfuse-dev libsqlite3-dev opam ocaml make fuse camlp4-extra build-essential pkg-config zlib1g zlib1g-dev

       #!/bin/bash
        USER=SomePerson
        groupadd fuse
        adduser ${USER} fuse
        chown root:fuse /dev/fuse
        chmod 660 /dev/fuse
        #as user
        sudo su - ${USER} -c 'opam init'
        sudo su - ${USER} -c 'opam update'
        sudo su - ${USER} -c 'opam install google-drive-ocamlfuse'

**Comment by astrada** [comment]
Unfortunately the opam package included in jessie is old too and you have to update it too. The latest version is 2.0.3. You can upgrade with (see http://opam.ocaml.org/doc/Install.html):

    sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)

Then after:

    sudo su - ${USER} -c 'opam init'

You should add:

    sudo su - ${USER} -c 'opam switch create 4.07.1'
    sudo su - ${USER} -c 'eval $(opam env)'

**Comment by lfxc** [comment]
I'm getting the errors at the end of this message running "google-drive-ocamlfuse ~/GoogleDrive", but it did connect to GoogleDrive.

I'm still not seeing updates on the desktop for files uploaded through the web.  In fact it's been about 4 hours now and nothing has updated, running ls commands or otherwise.



Errors running "google-drive-ocamlfuse ~/GoogleDrive":

[7721:7721:0206/142339.331153:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[7721:7721:0206/142339.335369:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[7721:7721:0206/142339.391668:ERROR:viz_main_impl.cc(184)] Exiting GPU process due to errors during initialization
Gkr-Message: secret service operation failed: Failed to execute program org.freedesktop.secrets: No such file or directory
[7:14:0206/142340.365806:ERROR:command_buffer_proxy_impl.cc(105)] ContextResult::kTransientFailure: Shared memory region is not valid
Gkr-Message: secret service operation failed: Failed to execute program org.freedesktop.secrets: No such file or directory
Access token retrieved correctly.

**Comment by astrada** [comment]
`google-drive-ocamlfuse -version` is returning 0.7.1?

**Comment by lfxc** [comment]
yes.   its' funny because if I delete something from the web interface, that change shows on the mount point.  But if I add something, then nothing shows up on the mount point.

the errors in previous post are actually related to Google Chrome.  It doesn't seem to have an effect on your app

**Comment by astrada** [comment]
Would you please send me your log files (to my personal email alessandro.strada@gmail.com)?

Mount with `-debug -cc`, do an `ls` in your GDrive root, add a file from the web interface, wait for a couple of `metadata_cache_time` intervals, do another `ls`, then send me `gdfuse.log` and `curl.log`. Thanks!

**Comment by lfxc** [comment]
sent email
