### ISSUE TITLE
Auto Mount Issue

### ISSUE THREAD

**Issue by ithinkmatt** [astrada/google-drive-ocamlfuse#527]
I run a script at startup that will automatically mount the Google Drive on my Linux tower.

I also have a Linux laptop. I am unable to successfully run the same script that runs on the tower.

Automatically running the script at startup causes the mount directory (/home/m/google-drive-mount) to disappear.

If I remove the script from running at start up. Then, reboot my laptop the /google-drive-mount directory is shown (/home/m/google-drive-mount.

I can then successfully mount the folder by runing google-drive-ocamlfuse /home/m/google-drive-mount in terminal. This issue only occurs on the laptop. The desktop has no issues running the script.

The script I am running is just:
- file name: google-drive-mount.sh
- google-drive-ocamlfuse /home/m/google-drive-mount
- Allow executing file as program is checked
- Permissions for the script file and /home/m/google-drive-mount directory are the same on the tower and laptop.

Any help would be very much appreciated!

Thanks,

Matt

**Comment by ithinkmatt** [comment]
I just changed the script to mount to /home/m/google-drive (instead of /google-drive-mount). Same issue the directory just disappears. But, the directory reappears after boot (with the start up script disabled).

Thanks,

Matt

**Comment by ithinkmatt** [comment]
I figured the issue out. For some reason, only on my laptop, I had to add the mount to FSTab. Then, set .sh to run at startup. Now * google-drive-ocamlfuse /home/m/google-drive-mount successfully mounts every time the machine boots.

**Comment by gabefair** [comment]
Congratulations on getting it working.
When you are ready, don't forget to also close your ticket.
