### ISSUE TITLE
"available Offline" option like in the GUI mac and windows versions

### ISSUE THREAD

**Issue by Hydramus** [astrada/google-drive-ocamlfuse#528]
Hi,

Can we get the "right click and select "available Offline" option like in the GUI mac and windows versions but the option to set this via the command line? 

I want to be able to set available offline in a headless environment.

Can we set this? I don't see it currently in the documentation.

Thanks,
Josh

**Comment by astrada** [comment]
No, sorry, this isn't a sync application. If you need to access files offline, please check this others apps: https://github.com/odeke-em/drive, https://github.com/ncw/rclone, https://github.com/vitalif/grive2

**Comment by Hydramus** [comment]
Thanks for the choices, would you have a personal recommendation out of the three?

**Comment by astrada** [comment]
Nope, sorry.
