### ISSUE TITLE
Linux - multiple files in /tmp of the form tmppt6u_pjs&cache=shared

### ISSUE THREAD

**Issue by alexsharaz** [astrada/google-drive-ocamlfuse#532]
Seem to have a stable Ubuntu version of this running now. However, there are a lot of files of the form tmppt6u_pjs&cache=shared appearing in /tmp when applications are accessing my google drive. Just trying to find out if its google-drive-ocamlfuse or my plex server thats generating them 

Is this file name format associated with this ?
Rgds
Alex

**Comment by astrada** [comment]
> Is this file name format associated with this ?

No, files are created only under `~/.gdfuse/`.
