### ISSUE TITLE
df showing only 15 Gb Size on unlimited Teams

### ISSUE THREAD

**Issue by JonAnder83** [astrada/google-drive-ocamlfuse#535]
Well, that's pretty much the issue.
On Arch LINUX ARM on a raspberry pi 3B+. I managed to se emy teams folder but df still shows it as a 15 Gb drive.
Will be happy to help debug this.

**Comment by astrada** [comment]
I don't think you can get the storage quota for team drives. Do you see that info in the web interface somewhere?

**Comment by JonAnder83** [comment]
You're right: These unlimited storages don't show you any size.
Although, some windows clients show you astronomic amounts of free space like "6 Eb" or stuff like that.

Forget about it... i can live with it , even though would've been nice to have some way of knowing the used space.

Cheers!
