### ISSUE TITLE
0 bytes files when drive is mounted.

### ISSUE THREAD

**Issue by barra51** [astrada/google-drive-ocamlfuse#537]
Hi and thanks to all in advance!

I have mounted my google drive with this command:

MacBook-Air-de-Miguel-Hernandez:Documents Miguel$ google-drive-ocamlfuse ./DriveUDG/ -cc -debug &

Everithing went fine with mount. When I tried to open a file, error -36 is showed and files are with 0 bytes.

If I try directly from google drive web interface, its working as expected.

**Comment by astrada** [comment]
Can you send your log files to my personal email (alessandro.strada@gmail.com)? Thanks

**Comment by barra51** [comment]
Hi @astrada 
Thanks for your help, I will send you this night, I don't have my macbook with me at this moment.

Regards
