### ISSUE TITLE
rsync shows files are being uploaded but after a while, it dies and only a bunch did truely upload

### ISSUE THREAD

**Issue by JonAnder83** [astrada/google-drive-ocamlfuse#538]
Well, I have a ton of files from various sizes and types to be uploaded to my google teams drive.
I tweaked the config file like this:

```
acknowledge_abuse=true
connect_timeout_ms=50000
max_cache_size_mb=10240
metadata_cache_time=36000
```

I launch rsync like so:

`rsync -rlvW --delete --stats --inplace --progress --size-only /media/origin/ /home/myuser/mounted_drive/destination/`

The speeds seem consistent, the cache file gets huuge and after some time (some times hours) I receive an IO error and rsync just crashes.
If rsync reports 100 files have been uploaded, perhaps only the first 20 did: It's really inconsistent.

Care to help me debug this issue? i'm open to suggestions/tests

**Comment by astrada** [comment]
If you remount with `-verbose` you should see some kind of error in `gdfuse.log`. If you want, send it to my personal email (alessandro.strada@gmail.com).

**Comment by astrada** [comment]
Should be fixed in the [beta PPA](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta).

**Comment by JonAnder83** [comment]
Actually, setting max_upload_chunk_size=1099511627776 did the trick for now.... when updating to the newer version, should I still leave this setting on this value?

Thanks for your great work!

**Comment by astrada** [comment]
> when updating to the newer version, should I still leave this setting on this value?

Nope. That value (1099511627776=1TB) is fine for 64-bit machines. The lower value is needed only for 32-bit machines.
