### ISSUE TITLE
Suggestion: get credentials on a server without gui

### ISSUE THREAD

**Issue by Zibri** [astrada/google-drive-ocamlfuse#539]
Instead of opening a browser on the server were is running the software,
it would be nice just to print the url for verification.
So I can open it on another computer and get the credentials and then put them in the app.

**Comment by Zibri** [comment]
gdrive works perfectly... can you do as gdrive does?

**Comment by Zibri** [comment]
https://github.com/gdrive-org/gdrive

**Comment by JonAnder83** [comment]
You already can do it:

https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization

Use the -headless option

**Comment by Zibri** [comment]
Yes, but is badly implemented.
gdrive is straight forward, just pits out the url and then waits for the token.
That's how it should be.
(IMHO)

**Comment by ewnjtgouierg** [comment]
simple workaround:

create `/usr/local/bin/google-chrome` script which prints first argument to stderr
and `chmod +x /usr/local/bin/google-chrome`

example in php:

`#!/usr/local/bin/php
<?php

$fp = fopen('php://stderr', 'w');
fwrite($fp, "\n\n".$_SERVER['argv'][1]."\n\n");
`

**Comment by BiatuAutMiahn** [comment]
on older versions, when it failed to open the url, it would wait for a token, id open a browser elsewhere, authenticate, and it was a toss as to whether or not gd-ocaml would take it. but @ewnjtgouierg's solution is awesome

**Comment by astrada** [comment]
Service accounts are now supported (as of v0.7.11).
