### ISSUE TITLE
Question: Using duplicity with google-drive-ocamlfuse

### ISSUE THREAD

**Issue by JonAnder83** [astrada/google-drive-ocamlfuse#541]
I'm using duplicity to backup some stuff to my google teams folder.
The advantage of duplicity against any other solution is that the data is both transported and stored fully encrypted with a GPG key.
duplicity supports different backends, so you can store the backups either locally (file://) or remotely (gdrive://, sftp://, etc...)
I'm currently using it with google-drive-ocamlfuse with the file:// backend: I mount my drive folder as usual and set the directory as destination for duplicity: So far it seems to be working (just started some minutes ago with the process)
However, I was wondering if integration between this app and google-drive-ocalmlfuse could be possible: Some dvantages could be (i guess) improved stability and full integration with the backup tool, so we can use features like backup progress indicators (that don't work with the file:// protocol)

I wonder if anyone can give feedback on using this tool with google-drive-ocamlfuse or wether integration would be feasible/worth it-

Thanks!

**Comment by astrada** [comment]
Sorry, but why are you not using the gdrive backend of duplicity?

**Comment by JonAnder83** [comment]
Well, it's not properly working on my distro (arch)

I'm trying to find a solution for it.

**Comment by JonAnder83** [comment]
Ok, It actually does work, however, I can't figure out how to make it work with team drives, and the dependencies for pydrive are a total mess. Nevermind, I thought I could use your solution as alternative backend.

Cheers.

**Comment by techsy730** [comment]
Just from personal experience, while google-drive-ocamlfuse isn't exactly the fastest thing around, I have found that the Drive backend for duplicity (and Drive/Gnome integration in general) to be even slower and more unreliable still. So I am continuing to use a google-drive-ocamlfuse mount for my backups. Maybe this has changed recently, but this is why I am still using google-drive-ocamlfuse for my duplicity backups.
