### ISSUE TITLE
Problem with build on raspberry pi3b+

### ISSUE THREAD

**Issue by fan3k** [astrada/google-drive-ocamlfuse#542]
Look in picture. How to resolve?
![Screenshot_20190414-204438_JuiceSSH](https://user-images.githubusercontent.com/46594950/56097821-97504a80-5ef9-11e9-9436-d19981f3e437.jpg)

**Comment by astrada** [comment]
Latest version of `ocamlfuse` is `2.7.1-cvs6`. You should run `opam update && opam upgrade` to get the latest version.
