### ISSUE TITLE
Issue re configuring ocamlfuse

### ISSUE THREAD

**Issue by swatwithmk3** [astrada/google-drive-ocamlfuse#546]
Hai Fams,

I installed the app to my POP OS installation which uses Debian 19.04 and the initial setup went to the browser for authentication but nothing was mounted. Then when I tried mounting again it would give me an error while trying to open the browser. I'll paste the output here: [12568:12568:0427/194226.812955:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[12578:12578:0427/194226.837180:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/swatwithmk3 which is owned by swatwithmk3.)
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: chromium-browser: not found
[12608:12608:0427/194226.883621:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=r8acnK0bxDoCu5uYj1bpQAwsIb0ecU2ho6ovcK5M9eg'
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/swatwithmk3 which is owned by swatwithmk3.)
[12634:12634:0427/194226.928759:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/bin/sh: 1: chromium-browser: not found
/bin/sh: 1: open: not found
Cannot retrieve auth tokens.
Failure("Error opening URL:https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=r8acnK0bxDoCu5uYj1bpQAwsIb0ecU2ho6ovcK5M9eg")

**Comment by astrada** [comment]
It looks like you are using `su` or `sudo` to mount your drive, but the browser won't start in that case. If you want to authorize on another server/device, you can use the [headless authorization checklist](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization).
