### ISSUE TITLE
authorize in server install 

### ISSUE THREAD

**Issue by sweptr** [astrada/google-drive-ocamlfuse#547]
I installed on a afterburst vps (kvm, centos 7)-but it fails when I come to the authoizationm because I have no gui installed on that machine.  Neither do I own   a 0Auth2 key.

Is there any way to authorize through elinks or on a browser at another machine, for example firefox on android.?

**Comment by astrada** [comment]
Yes, check this wiki [page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization).
