### ISSUE TITLE
Mount doesn't work after reboot

### ISSUE THREAD

**Issue by Waliers** [astrada/google-drive-ocamlfuse#549]
I followed the steps on https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting

And when I type `mount ~/gdrive` it mounts and works.

However after reboot when I go to the folder I get input/output error when I want to go to the folder.

When I type `fusermount -u gdrive` and then `mount ~/gdrive` it works again until I rebooted the machine.

I would really love it to automount the gdrive at boot so I don't have to type this commands after every reboot.

Is there any added step needed on Debian 9 to make the automount work?

**Comment by astrada** [comment]
You should add `-verbose` option to `google-drive-ocamlfuse` in your `gdfuse` script. Then you should check `~/.gdfuse/default/gdfuse.log` to see what kind of error you are getting.
