### ISSUE TITLE
Avoid .Trash

### ISSUE THREAD

**Issue by upline6** [astrada/google-drive-ocamlfuse#550]
Hi,
I really like the program but the issue I have with it is the .Trash folder. No matter what sub folders I select to mount, /.Trash is always in there.
In my case it contains over 1000 files, that I don't need in google-drive anymore but also don't want to throw into the void forever yet. I imagine, connecting this folder takes the most amount of time when trying to access the directory, which is especially noticeable when on a slow connection.
I figured, excluding the .Trash folder would greatly improve the usability and takes away the time to load the many file names and properties.

Now, I've searched a lot but I just cannot figure out how to archive this. There is 'delete_forever_in_trash_folder=true' but turning that on does not stop /.Trash from appearing.

Any ideas?
I am okay with files being gone forever if I delete them when working on the ocamlfuse mount.

**Comment by astrada** [comment]
In version 0.7.4, I've added the option `disable_trash`, to turn off trash bin fetching. I'm publishing this new version to the [beta ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta) and [opam](https://github.com/ocaml/opam-repository/pull/14157).

**Comment by tomchiverton** [comment]
Could you update https://github.com/astrada/google-drive-ocamlfuse/wiki/What%27s-new ?

**Comment by astrada** [comment]
OK!
