### ISSUE TITLE
Wrong available space informed

### ISSUE THREAD

**Issue by loginsistemas** [astrada/google-drive-ocamlfuse#551]
Hi. Thanks for your work, this is a really useful software.

I mounted the _team drive_, added for my company to my personal google account. I can see the _team drive_, containing around 250GB of files. There is no space limitation on these team units, but on mounted folder I can see 15GB of total size and only 1gb left. I can copy small files under the limits, but not files bigger than space left.

I think ocalmfuse is informing about the total and left space in my personal google account, not in my _team drive_. How can I handle it?

**Comment by astrada** [comment]
Unfortunately the TeamDrive's free space is not available to the REST API, so as a workaround, in version 0.7.4, I changed the total space left to the maximum available if `team_drive_id` is specified. I'm publishing this new version to the [beta ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta) and [opam](https://github.com/ocaml/opam-repository/pull/14157).
