### ISSUE TITLE
File Name Error

### ISSUE THREAD

**Issue by Tunglin-Inamin-TW** [astrada/google-drive-ocamlfuse#552]
if I have been open not exist file like 1.png, in feature the file is exist, but I can't open 1.png .

In google drive, the file is normal and republic.

ls can show it, but use any file command always show " No such file or directory"

**Comment by astrada** [comment]
Can you remount with `-verbose` and after you reproduce the error again, send me the log file `gdfuse.log` that you can find in `~/.gdfuse/default`? Thanks!

**Comment by Tunglin-Inamin-TW** [comment]
[gdfuse.log](https://github.com/astrada/google-drive-ocamlfuse/files/3211667/gdfuse.log)

My os is CentOS 7.6.1810

I change filename in google drive and change it back in centos to fix it now.

But it's troublesome.

Thanks for your reply.

**Comment by astrada** [comment]
Thanks! You are using an old version (0.6.23), can you please upgrade to the latest one (0.7.4) and retry? Thank you!

**Comment by Tunglin-Inamin-TW** [comment]
opam always install v0.6.23 for me, your teaching can't use in Centos. Can you teach me how to install latest?

**Comment by astrada** [comment]
If you have opam 2.0 (if not, you should [upgrade it](https://opam.ocaml.org/doc/Install.html)), you can run:

    opam update
    opam switch create 4.07.0
    eval $(opam env)
    opam install google-drive-ocamlfuse

**Comment by Tunglin-Inamin-TW** [comment]
I follow your command and show error report like opam-repository#13491:
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlfuse failed at
        "/root/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse
        -j 1".

#=== ERROR while compiling ocamlfuse.2.7.1-cvs6 ===============================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.07.0 | https://opam.ocaml.org#b878563b
# path        ~/.opam/4.07.0/.opam-switch/build/ocamlfuse.2.7.1-cvs6
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlfuse -j 1
# exit-code   1
# env-file    ~/.opam/log/ocamlfuse-3690-c61e7b.env
# output-file ~/.opam/log/ocamlfuse-3690-c61e7b.out
### output ###
# [...]
# -> stderr:
# run: /usr/bin/pkg-config --cflags fuse
# -> process exited with code 0
# -> stdout:
#  | -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse
# -> stderr:
# run: /usr/bin/pkg-config --libs fuse
# -> process exited with code 0
# -> stdout:
#  | -pthread -lfuse
# -> stderr:
# Error: Could not query camlidl lib path



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlfuse 2.7.1-cvs6
└─
╶─ No changes have been performed

```
`opam config var camlidl:lib` command show this:
`/root/.opam/4.07.0/lib/camlidl`

**Comment by astrada** [comment]
I think the issue is because you are running commands as `root`, and probably this doesn't work well with sandboxing. You can try creating a `/root/.opamrc` with [this content](https://gist.github.com/AltGr/8ec08822361f140d5396bb945fbad185) to disable sandboxing, and then retry installation.

**Comment by Tunglin-Inamin-TW** [comment]
I don't know how to use that, it not a command.
Can I remove sandboxing?
