### ISSUE TITLE
Plex with google drive

### ISSUE THREAD

**Issue by ambigus9** [astrada/google-drive-ocamlfuse#554]
Hi, i'm trying to stream files from my google drive account to plex media server (PMS) on linux ubuntu 16.04. Currently PMS doesn't show me any file that is in my *movies* folder from google drive using google drive ocamlfuse, here are the steps i'm following:

**install plex using snap**
`sudo snap install plexmediaserver
`
**install google Drive Ocamlfuse**
```
sudo add-apt-repository ppa:alessandro-strada/ppa
sudo apt-get update
sudo apt-get install google-drive-ocamlfuse
```
**link to my google drive account**
`google-drive-ocamlfuse`

**create folder and mount it allowing other**
```
mkdir ~/miguel-google-drive
sudo google-drive-ocamlfuse -o allow_other ~/miguel-google-drive
```
Any suggestion? Thanks.

**Comment by ambigus9** [comment]
@meszape  Thanks, Wich command i must use to **configure the drive mount with the plex user**? Do you have plex installed with **snap**?

**Comment by meszape** [comment]
Hi

I installed via apt. You have to run the command as the plex user (the
config and the mount)

Br

**Comment by ambigus9** [comment]
Thanks, that's the problem. Installing using apt works perfect! But by snap I must access data in **/media/** folder.

**Comment by meszape** [comment]
I am not familiar how plex works when you install with snap. But if media
needs to be in /media, than you should mount with /media path

Br
Peter

**Comment by ambigus9** [comment]
thanks
