### ISSUE TITLE
I am using two account, one loaded right away, the other is stuck in loading

### ISSUE THREAD

**Issue by mas192** [astrada/google-drive-ocamlfuse#555]
Hi Astrada,

Thanks so much for this wonderful package. I am currently trying to have two Gmail drives setup. one account worked right off the bat. However, the second account has been stuck loading. Please, any advice would be awesome.

Thanks,
Sam

**Comment by mas192** [comment]
![ocaml_problem](https://user-images.githubusercontent.com/21248222/59151784-f7d9a080-89ed-11e9-80ca-5d6f9d7919f7.png)
This the error after trying to load for a while

**Comment by mas192** [comment]
This is the problem I see
![ocaml_problem](https://user-images.githubusercontent.com/21248222/59151836-c8776380-89ee-11e9-87a2-30c862980f8c.png)

**Comment by mas192** [comment]
Also my drives dont auto mount on restart, I am on Ubuntu 18.04 LTS

**Comment by astrada** [comment]
What kind of authorization are you using? Standard or alternative?

> Also my drives dont auto mount on restart, I am on Ubuntu 18.04 LTS

Have you checked this [wiki page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting)?
