### ISSUE TITLE
0 byte files uploaded

### ISSUE THREAD

**Issue by RJSzynal** [astrada/google-drive-ocamlfuse#557]
When creating or modifying a file, the file created in google drive is 0 bytes. 
Mount command: `/usr/bin/google-drive-ocamlfuse -debug -o allow_root "${HOME}/googledrive-home"` (normally without -debug) executed as my user.
I will email the logs to you. If there's anything else you need, please let me know.

Thanks
Robert

**Comment by astrada** [comment]
You are using an old version that's not compatible with http2. Can you upgrade to version 0.7.4?

**Comment by RJSzynal** [comment]
Ah yes, I can't believe I didn't even check I was on the latest version.
This has solved the issue.
Thank you
