### ISSUE TITLE
Mime type for uploaded .m4a AAC audio files

### ISSUE THREAD

**Issue by Brrrezel** [astrada/google-drive-ocamlfuse#560]
I have uploaded several AAC encoded audio files with `.m4a` extension to Google Drive using google-drive-ocamlfuse on Ubuntu 19.04 LTS. I encountered a problem when playing these files in Safari on a Mac or Safari and Chrome on iOS - they refuse to play in the browser. I discovered the following issue:

### Problem:
Files uploaded with a .m4a extension get `audio/mpeg` as mime type, which lets Safari assume it is a MP3 file. 
Files uploaded via the Google Drive web interface get `audio/x-aac` as mime type, which does not show the described issue.

### Suggested Solution:
Add a file extension match rule to `src/mime.ml` stating
```caml
| "m4a" -> "audio/x-aac"
```

Update:
Maybe it is also `audio/x-m4a`, I don't really know what is the best solution in this case. 

I did not yet consider the case, if the `.m4a` file is ALAC encoded - maybe someone has a better solution for this problem.

**Comment by astrada** [comment]
It looks like the standard mime type is `audio/mp4` (https://www.iana.org/assignments/media-types/media-types.xhtml#audio). I'm publishing v0.7.7 (on the beta ppa) than includes this patch. Let me know if it works for you. Thanks!

**Comment by Brrrezel** [comment]
Small remark, I am asking myself (I was not going into the depths of your code...), why do you have to manually map the mime type? I think the Drive API should somehow provide auto detection...

Short search lead me to another project on Github:
https://github.com/gsuitedevs/drive-zipextractor/commit/01df4a5812e8f5e1532ee66b48f280a810bb5b82

**Comment by astrada** [comment]
You are right, in version 0.7.8 I've added a config option (`autodetect_mime`) that enables Google Drive autodetecting feature. The default is `true` so you don't have to turn it on. But if it doesn't work, you can turn it off.
