### ISSUE TITLE
[Question] Can you exclude certain files from being uploaded?

### ISSUE THREAD

**Issue by xyphos10** [astrada/google-drive-ocamlfuse#561]
Hello 

I would like to know if it is possible to disallow certain file types from being uploaded when using google drive ocamlfuse. Example lets say I mounted by gdrive to /mnt/storage and I have the following directories, 

/mnt/storage/info.db
/mnt/storage/info.db-shm
/mnt/storage/info.db-wal
/mnt/storage/tmp/radfakdfasdf.partial

Is it possible to tell google drive ocamlfuse not to upload any files found on /mnt/storage/tmp and also not to upload /mnt/storage/info.db* whether or not there are any changes. Info.db is an sqlite3 database.

**Comment by astrada** [comment]
No, sorry, it's not possible. If you need to have some local and some remote files in the same directory, you should use a sync tool (like [rclone](https://github.com/ncw/rclone)).
