### ISSUE TITLE
Team drives

### ISSUE THREAD

**Issue by nicoparker** [astrada/google-drive-ocamlfuse#567]
Hello there,

I’ve successfully mounted my main Drive folder (the root folder kind of) on an headless Ubuntu server and was trying to mount another root folder, namely my computer’s backup (which is another root folder as far as I understood). It contains folders such as Downloads, Desktop etc...
After reading the documentation I found out that the URL for that one looks exactly like Team Drives : https://drive.google.com/drive/u/1/folders/xxxxxxx, where the xxx represent the ID, so I’ve used a new label with the same API credentials, edited the config file to use that ID but got an error :

nico@server:~$ ls Drive/mbp/
ls: cannot access 'Drive/mbp/': Input/output error

Whereas the root Folder (My Drive) still works.

I’ve tried also to use the ID of a folder inside that root folder (Downloads) for example but ran into the same problems. Then I thought : ok maybe I need new API for that one, so I repeated the whole process with Google, configured the software and mounted the folder to finally run into the same error.

I wanted to ask you the following questions 
-is it possible to mount those other (personal) root folders following the Team Drives logic?
-if yes, where is my mistake?

Thanks in advance & regards!

**Comment by nicoparker** [comment]
<img width="281" alt="PNG image" src="https://user-images.githubusercontent.com/54425068/63568472-e133f600-c5a7-11e9-86e5-def65dc51a96.png">

The « My Drive » folder that is in blue highlighted works as expected, I cannot sync the mount the one in red.

**Comment by astrada** [comment]
> I wanted to ask you the following questions
> -is it possible to mount those other (personal) root folders following the Team Drives logic?

It should be possible, but it looks like they are read-only (if you access them from the API). If you enable debug logging you should see the error returned by the Drive API.

**Comment by nicoparker** [comment]
Hello, thanks for your answer! I’ve tried with the debug on, it turns out the ressource is not found (curl.log). I don’t understand cause I’m sure about the ID.

[62.382897] curl: header in: Cache-Control: private, max-age=0
[62.382998] curl: header in: X-Content-Type-Options: nosniff
[62.383066] curl: header in: X-Frame-Options: SAMEORIGIN
[62.383132] curl: header in: X-XSS-Protection: 1; mode=block
[62.383203] curl: header in: Server: GSE
[62.383271] curl: header in: Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
[62.390441] curl: header in: Accept-Ranges: none
[62.390492] curl: header in: Vary: Origin,Accept-Encoding
[62.390524] curl: header in: Transfer-Encoding: chunked
[62.390553] curl: header in: 
[62.390582] curl: data in: 141
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Shared drive not found: xxxxxxxxxxx",
    "locationType": "parameter",
    "location": "driveId"
   }
  ],
  "code": 404,
  "message": "Shared drive not found: xxxxxxxxxxx"
 }
}
[62.390835] curl: data in: 0
[62.390917] curl: info: Connection #0 to host www.googleapis.com left intact


Here is the result of the gdfuse.log
[0.020567] TID=0: Setting up mbp filesystem...
[0.020648] TID=0: BEGIN: Saving configuration in /home/nico/.gdfuse/mbp/config
[0.021114] TID=0: END: Saving configuration in /home/nico/.gdfuse/mbp/config
[0.021299] TID=0: Loading application state from /home/nico/.gdfuse/mbp/state...done
Current version: 0.7.6
Docs mode not changed!
Setting up cache db...done
Setting up CURL...done
Refresh token already present.
[0.076322] TID=0: Starting filesystem ./Drive/mbp/
[0.113605] TID=1: init_filesystem
[0.113825] TID=1: Starting flush DB thread (TID=2, interval=30s)
[0.113939] TID=1: BEGIN: Getting root folder id (team drive id=1XsgUnFDBChltJBCsdaHSUARVAKC4xel-, root folder=) from server
[0.114096] TID=1: END: Getting root folder id (id=Xxxxxxxxxx) from server
[27.555809] TID=3: getattr /
[27.555991] TID=3: BEGIN: Loading metadata from db
[27.556180] TID=3: BEGIN: Recalculating cache size (old value=0)
[27.556508] TID=3: END: Recalculating cache size (new value=0)
[27.556622] TID=3: END: Getting metadata: Not valid
[27.556685] TID=3: BEGIN: Refreshing metadata
[28.518265] TID=3: END: Refreshing metadata
[28.518307] TID=3: BEGIN: Getting changes from server
[62.460020] TID=3: ServiceError
[62.460472] TID=3: Exception:Failure("{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"notFound\",\"message\":\"Shared drive not found: xxxxxxxxx
\",\"locationType\":\"parameter\",\"location\":\"driveId\"}],\"code\":404,\"message\":\"Shared drive not found: xxxxxxxxxxxx"}}")
Backtrace:

So it turns out that the Team Drives logic doesn’t work for those “My computer” things.

**Comment by astrada** [comment]
It looks like the Drive API was updated with a generalized concept of Shared Drives that should include Team Drives: https://developers.google.com/drive/api/v3/enable-shareddrives. I will check if, with the modifications required, those other Drives become available.

**Comment by astrada** [comment]
@nicoparker: I made some tests and I found that you have to put the folder id in the `root_folder` config option (you should also let the `team_drive_id` config option blank) to access folders under `Computers`. Then you can read/write your files as those in `My Drive`.

**Comment by nicoparker** [comment]
Hello! I’ve tried for myself and it works just as expected! Thanks for the tip.

Maybe the documentation should be updated to reflect the difference between Team drives and root folders? Regards

**Comment by fl-nishida** [comment]
@astrada Thank you for providing nice tool!
As you mentioned above I  put shared drive folder id  in the root_folder config option and 
blanked team_drive_id but my drive is mounted....

My config is as below, I would appreciate if you suggest me the misses i made, thank you in advance
----
acknowledge_abuse=false
apps_script_format=desktop
apps_script_icon=
cache_directory=
client_id=XXXXXXXXXXXXXXXXXXXX
client_secret=XXXXXXXXXXXXX
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
delete_forever_in_trash_folder=false
desktop_entry_exec=
disable_trash=false
docs_file_extension=true
document_format=desktop
document_icon=
download_docs=true
drawing_format=desktop
drawing_icon=
form_format=desktop
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
metadata_memory_cache=true
metadata_memory_cache_saving_interval=30
presentation_format=desktop
presentation_icon=
read_ahead_buffers=3
read_only=false
root_folder=share_dirve's id I want to mount
shared_with_me=true
spreadsheet_format=desktop
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
team_drive_id=
umask=0o002
verification_code=
write_buffers=false

**Comment by astrada** [comment]
@fl-nishida: to mount shared drives you should use the `team_drive_id` config option. The `root_folder` is used to access backups under the `Computers` node.

**Comment by overthetop78** [comment]
hello, it does not work. Either Google has changed the way it does and has to pay for G Suite, either it's me that hurts things. But please, help me.
