### ISSUE TITLE
How to run this without GUI?

### ISSUE THREAD

**Issue by StealWonders** [astrada/google-drive-ocamlfuse#570]
I'm running an Ubuntu18.04 Server without GUI, it tells me I'm missing these browsers which I ofc. do not have. How do I go about running the software?

**Comment by astrada** [comment]
Please check this [wiki page](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization).

**Comment by StealWonders** [comment]
Thank you!
