### ISSUE TITLE
OAuth2 for Devices

### ISSUE THREAD

**Issue by bmshouse** [astrada/google-drive-ocamlfuse#572]
As an alternative for headless devices, Google's OAuth2 for Devices may be a good alternative. It allows users to go to a simple URL and enter a short verification code. It is intended for TVs or other limited input devices, but I believe it fits well in a headless verification process. 

https://developers.google.com/identity/protocols/OAuth2ForDevices

**Comment by astrada** [comment]
Sorry, but it's available only for one scope: https://www.googleapis.com/auth/drive.file (see https://developers.google.com/identity/protocols/OAuth2ForDevices#allowedscopes). With this scope, the application has access only to files created by the application itself (or the user has explicitly shared with the app).

**Comment by astrada** [comment]
I added that auth flow in version 0.7.13

**Comment by bmshouse** [comment]
@astrada Thank you!  I will test this out this week.
