### ISSUE TITLE
Does ist support incremental diffing?

### ISSUE THREAD

**Issue by vanniktech** [astrada/google-drive-ocamlfuse#573]
I've already got a state of my Google Drive folder on a disk and every now and then I'd like to sync it out from my machine. I was trying to execute:

`google-drive-ocamlfuse -debug -u /mnt/Data/google-drive` but I got: 

```
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
```

I just want to make sure that if I use the `nonempty` flag, my files on `/mnt/Data/google-drive` won't be deleted and new files from Google Drive will be downloaded while newly added local files will be uploaded to the Google Drive.

Also, seems like `nonempty` isn't mentioned in `google-drive-ocamlfuse --help`.

**Comment by astrada** [comment]
No, if you mount your drive on an existing directory, you won't see the local files, but only the remote files. If you need a sync app, you should use something like https://github.com/rclone/rclone.

**Comment by vanniktech** [comment]
Alright, thanks for the answer :)
