### ISSUE TITLE
Device API: error messages unexpected

### ISSUE THREAD

**Issue by bshouse** [astrada/google-drive-ocamlfuse#574]
I was playing with the the Device API and I get the following error message. The HTTP 401 is pretty clear, but I wonder if the 'unexpected leaf's might have useful information to the debugging process. 

```
google-drive-ocamlfuse -device -id [Redacted].apps.googleusercontent.com -secret [Redacted]

Warning: Unexpected leaf: name=error data_type=Scalar in GapiOAuth2Devices.AuthorizationCode.parse_error_response

Warning: Unexpected leaf: name=error_description data_type=Scalar in GapiOAuth2Devices.AuthorizationCode.parse_error_response
Cannot retrieve auth tokens.
Failure("OAuth2 for devices error:  (HTTP response code: 401)")
```

**Comment by bshouse** [comment]
The root cause of this was that I was using Credentials (id & secret) for a Web Application. Using Credentials for "Other" allows the process to complete successfully. 

In addition, it is important to note that the Google OAuth consent must include the API Scope "../auth/drive.file" for this to be successful. 

So, the underlying error messages might be helpful, but not critical.

Thank you again for all your help!

**Comment by astrada** [comment]
OK, thanks for your feedback.
