### ISSUE TITLE
Slow Navigation

### ISSUE THREAD

**Issue by Mensen** [astrada/google-drive-ocamlfuse#58]
Thank you for actually making some software that can make use of my google drive!

However, whenever I explore the drive, either using a GUI or directly in the terminal it takes a long time to even enter a directory. When I try to move files in the directory or rename files/folders it can take up to 20-30s.

This does not happen with any other directory except the gdrive folder.
I've set the cache size to 1GB in the hopes it would basically just download my whole drive locally for fast access but the issue does not change.

Is this just an inherent problem, or is there something I can do?

**Comment by jcward** [comment]
I have the same problem with very slow access, from `ls` to `nautilus`, because I do have a lot of Google Docs in my drive, and this did work for me:

> you can turn your docs into links...

    document_format=desktop
    presentation_format=desktop
    spreadsheet_format=desktop
    drawing_format=desktop
    form_format=desktop

> Then `google-drive-ocamlfuse -cc` to clear cache.

Thanks, @astrada!

One question: While links are a good workaround, is it possible to allow fast directory listing (e.g. `ls` and `find`), and only perform the slow document fetch/conversion later when the file is opened? Maybe report a 1-byte file (or some other special flag, like a symlink or named pipe) until the file is actually opened?

**Comment by astrada** [comment]
> One question: While links are a good workaround, is it possible to allow fast directory listing
> (e.g. ls and find), and only perform the slow document fetch/conversion later when the file is
> opened? Maybe report a 1-byte file (or some other special flag, like a symlink or named pipe)
> until the file is actually opened?

Unfortunately it's not easy because it requires opening files with `O_DIRECT` option, and the FUSE binding I'm using doesn't allow that. I'm keeping this issue open as a reminder.

**Comment by jcward** [comment]
Ok, thanks! The links feature is nice and will work for now.

**Comment by aplund** [comment]
I'm not sure if this is the right place for this comment, but it seems that doing lots of metadata requests (e.g. lstat()) is also extremely slow if the metadata cache expiry has occurred, say when you start up at the beginning of the day.  From my connection, one lstat() request takes anywhere from 500ms-1000ms. If you are getting the sizes of 1000 files, there's 10-20minutes in just checking metadata.

This is particularly a problem when doing an rsync update.  Is there any way to get some kind of bulk metadata update out of the google drive api, or perhaps a more efficient way of asking rsync to check file sizes?

**Comment by astrada** [comment]
The easiest thing that I can think of is running `ls -lR` before rsync to warm the cache. I don't know if it's quicker than running just rsync.

**Comment by Torsten85** [comment]
@astrada couldn't you fetch the whole google drive (`drive.files.list` should do this without many requests and also delivers all the stats needed) and instead of flushing the cache after `metadata_cache_time` simply poll `drive.changes.get` and flush only the parts of the cache that really have changes? This would dramatically speed navigation up.

**Comment by astrada** [comment]
Well, not really. `drive.files.list` without filters can be quite slow if you have many files. You can check it enabling lost+found and querying that folder. The changes are already polled the way you are suggesting. Global cache invalidation occurs only if there are more than 50 changes between 2 calls to `drive.changes.get`.

**Comment by Torsten85** [comment]
@astrada ... and a call to `drive.changes.get` happens every `metadata_cache_time` seconds right? 

Currently the first attempt to navigation after mounting is painfully slow but every following navigation attempt is quite fast... but after some time (maybe an hour or so) navigation is slow again.

**Comment by astrada** [comment]
> ... and a call to drive.changes.get happens every metadata_cache_time seconds right?

Yes, right.

> Currently the first attempt to navigation after mounting is painfully slow but every following navigation attempt is quite fast... but after some time (maybe an hour or so) navigation is slow again.

It can be slow if you have lots of Google Docs. As they are exported, I've have to download them fully to get their size (otherwise the will be shown as zero-bytes). If you don't care about exporting documents, you could switch formats to `desktop`, or turning them off setting `download_docs=false` in the config.

**Comment by msangel** [comment]
>download_docs=false
This helps. Please specify this as a default option.

**Comment by OndraZizka** [comment]
Where is the config? Thx

**Comment by OndraZizka** [comment]
Hi, here's my take on this: to my `mountGdrive` script, I added `tree /gdrive/ &` which caches all the files in the background. I've increased the cache size to 2048 MB (it has to be a geeky number indeed) and the timeout to 3600. That's no big deal, I hav a plenty of space and the caching seems to work fine; besides, I only work with non-doc files over fuse.

**Comment by thmxv** [comment]
Just to summarize my experience. We use a TeamDrive to collaborate on an 'medium sized' asset collection (at the moment 150.000 files totaling 100GB, but destined to grow a lot). We have some custom tools that needs to go over the whole asset repository and get a listing of every directory (using a in house optimized version of python's os.walk() function).
- Getting he first listing is painfully slow, even if not having any Google docs
- Using ls -lR or tree to build a warm cache helps a lot
- Even with a warm cache, listing the whole drive is still 10x slower than on windows running the same python code on a  FileStream mount.

**Comment by FabioPedretti** [comment]
> Do you have many Google Docs (office-like files)? Those files can't be efficiently cached, so they slow down a lot the resource fetching. If you don't need them on your desktop, you can turn them completely off, putting `download_docs=false` in the config file. Otherwise, you can turn your docs into links, putting:
> 
> ```
> document_format=desktop
> presentation_format=desktop
> spreadsheet_format=desktop
> drawing_format=desktop
> form_format=desktop
> ```
> 
> in the config file, and then using `-cc` command line option to clear the cache.

Could you think about making this the default? Or at least have a command line option to force this for all formats?
Thanks.

**Comment by hmaarrfk** [comment]
Would you accept a PR to change the defaults?

**Comment by astrada** [comment]
In version 0.7.5, I added a command line option (`-docsmode`) to quickly set Google Docs config options. See [Usage](https://github.com/astrada/google-drive-ocamlfuse/wiki/Usage).

**Comment by hmaarrfk** [comment]
Nice that should do it!

Would you want to take PRs to add google drive relevant icons from wikipedia to the installed files. That way the desktop stuff gets nice icons

**Comment by astrada** [comment]
OK, thanks, just check that the icon license permits to embed it in another software.

**Comment by astrada** [comment]
Should be fixed in the latest versions.
