### ISSUE TITLE
First run opens a browser but not the GAE auth page

### ISSUE THREAD

**Issue by daparker** [astrada/google-drive-ocamlfuse#580]
Hello,

I installed on Debian 10 (Buster) without any problems, using the instructions for Debian Stretch.  Then, following the instructions on the Authorization page, I ran **google-drive-ocamlfuse** with no arguments.  It opened Firefox but just to my home page, not to the page where I can set up the GAE service application.  I tried this once when I already had Firefox open and was logged into my Google account, and once with the browser closed completely, with the same result both times.  Do I need to do something extra to get the GAE authorization page to come up on the first run?

Thanks.

**Comment by kurdtpage** [comment]
Try running in debug mode first:
`google-drive-ocamlfuse -debug`
Let it run for a bit, then check out what is in the debug log:
`cat ~/.gdfuse/default/gdfuse.log`

**Comment by daparker** [comment]
Thanks for the tip; the debug log revealed that it's calling `xdg-open` to open the browser.  This seems to be some kind of issue with `xdg-open` because it doesn't work when I run it directly, either.  So, not an problem with google-drive-ocamlfuse itself.
