### ISSUE TITLE
Google Drive API doesn't work well with file chunks

### ISSUE THREAD

**Issue by jeff-geoff** [astrada/google-drive-ocamlfuse#583]
No, downloading torrents to the mount-point is not really supported because Google Drive API doesn't work well with file chunks.

_Originally posted by @astrada in https://github.com/astrada/google-drive-ocamlfuse/issues/366#issuecomment-338563608_

Does the API now allow this type of action if the file is pre-allocated prior to running the torrent?

**Comment by astrada** [comment]
No, it doesn't matter what kind of model you have of your local file-system. The Drive API doesn't allow to upload chunks of a file, only the whole file.
