### ISSUE TITLE
How to open desktop files in browser?

### ISSUE THREAD

**Issue by dmusican** [astrada/google-drive-ocamlfuse#587]
I've got google-drive-ocamlfuse working properly, and I'm using desktop as the file type for all Google doc files. I can correctly see these files locally with a .desktop extension, and a file size of 0. How do I actually open them in the browser? Clicking on them in a files browser, or issuing xdg-open on them, just pops up a text editor.

**Comment by astrada** [comment]
It looks like GNOME removed support for .desktop files with Type=Link since Nautilus version 3.30: https://gitlab.gnome.org/GNOME/nautilus/issues/448

Ubuntu 18.04 ships version 3.26.4, so it still works on bionic. I will look for alternatives.

**Comment by dmusican** [comment]
Thanks, much appreciated. I'm not running in GNOME at all, incidentally, I"m currently using MATE; but regardless, whatever alternative you find would likely do the job.

**Comment by astrada** [comment]
In version 0.7.14, I've added `desktop_entry_as_html` that if set to `true` makes the app create `.html` files that redirect you to the edit page.

**Comment by dmusican** [comment]
This is brilliant and works wonderfully. Thank you!
