### ISSUE TITLE
Recommended Docker version of google-drive-ocamlfuse?

### ISSUE THREAD

**Issue by maltokyo** [astrada/google-drive-ocamlfuse#593]
As the title suggests, I find many dockers for google-drive-ocamlfuse.  Is there a recommended one from you @astrada ?  I would be appreciative to know.  If I get a good one running, could we add it here as part of your project to be "official"?

**Comment by astrada** [comment]
> Is there a recommended one from you @astrada ?

No, there isn't. But I think anything based on Ubuntu LTS should work fine. And if you don't want Ubuntu, you should look for an image that includes opam so you can compile from source.

**Comment by maltokyo** [comment]
Ok. Thank you!! It might be good if you endorse one on your site.

**Comment by astrada** [comment]
If you find anything that works well, feel free to add it to the [wiki](https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation). Thanks!

**Comment by maltokyo** [comment]
I made one myself, would you like me to make a pull request, I can maintain it here as a contributor if you like?

**Comment by astrada** [comment]
Thanks! Feel free to open the PR.

**Comment by maltokyo** [comment]
Here we go, it was easier for me to do it all with own repo.

Please link it in your README etc, and any feedback I will fix quickly.  Version numbers will be in sync with yours!

https://hub.docker.com/r/maltokyo/docker-google-drive-ocamlfuse

**Comment by astrada** [comment]
Thanks! I've added a docker badge to the README and the image link to the wiki: https://github.com/astrada/google-drive-ocamlfuse/wiki/Installation#docker
