### ISSUE TITLE
Configure maximum files or size pending upload with async upload [Feature request]

### ISSUE THREAD

**Issue by techsy730** [astrada/google-drive-ocamlfuse#599]
It would be nice to have a configurable maximum number of files or amount of data (whichever would be easier) that can be pending an upload when async_upload_queue is true.

This can be nice for large batches of data to upload where you don't want it to just say "I wrote them all" even though it is actively being uploaded, which increases risk of data loss. Instead when the configured max is hit, then it will block like as is async_upload_queue is false until there is enough room in the queue.

**Comment by astrada** [comment]
In version 0.7.18, I've added config option `async_upload_queue_max_length` that specifies the maximum number of entries of the upload queue before blocking. I'm publishing it on the beta ppa. Let me know if you need it on opam. Thanks!

**Comment by BiatuAutMiahn** [comment]
Once this limit is reached will the upload just stall like with DriveFS?

**Comment by astrada** [comment]
> Once this limit is reached will the upload just stall like with DriveFS?

Once the limit is reached, new uploads will block until the queue length returns below the limit.
