### ISSUE TITLE
What happens if connection is interrupted during upload? 

### ISSUE THREAD

**Issue by dairefagan** [astrada/google-drive-ocamlfuse#602]
Google-drive-ocamlfuse is currently uploading a 16GB directory of 10 files. I can only tell the upload is still going on because I can see it in my gnome top panel network monitor and with the nethogs program. I have async_upload_queue= and write_buffers= both set to true

If there was a powercut to my home or I lost Internet access, whenever my computer was powered back up with Internet access, would google-drive-ocamlfuse resume the upload without any issues or is there a risk of file corruption?

**Comment by astrada** [comment]
The upload is retried `max_retries` (default 8) times. If it still fails, the upload is aborted removed from the upload queue. So, if your connection is not stable, I would not remove the original files, before checking that the upload was completed correctly.
