### ISSUE TITLE
Cannot copy files to Drive due to "Input/Output error"

### ISSUE THREAD

**Issue by TirantRex** [astrada/google-drive-ocamlfuse#606]
I am using a Rasberry Pi 4 with rasbian and am trying to configure crontab tasks to backup the Minecraft server I have running on it. I get a generic "Input/output error" or "I/O error" whenever I try to make a zip file on the mounted drive or when trying to copy files onto it. 

I believe this may be a cache issue because I have had no problem copying very small files but I just don't know what to change.

I start the program with crontab like this: @reboot google-drive-ocamlfuse -o allow_other /home/pi/GDrive

Here is my config file:
`acknowledge_abuse=false
apps_script_format=desktop
apps_script_icon=
async_upload_queue=false
async_upload_threads=10
autodetect_mime=true
cache_directory=
client_id=
client_secret=
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
debug_buffers=false
delete_forever_in_trash_folder=false
desktop_entry_as_html=false
desktop_entry_exec=
disable_trash=false
docs_file_extension=true
document_format=desktop
document_icon=
download_docs=true
drawing_format=desktop
drawing_icon=
form_format=desktop
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
log_to=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=2048
max_download_speed=0
max_memory_cache_size=536870912
max_retries=8
max_upload_chunk_size=805306368
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=3600
metadata_memory_cache=true
metadata_memory_cache_saving_interval=30
mv_keep_target=false
presentation_format=desktop
presentation_icon=
read_ahead_buffers=3
read_only=false
redirect_uri=
root_folder=
scope=
service_account_credentials_path=
service_account_user_to_impersonate=
shared_with_me=false
spreadsheet_format=desktop
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=true
team_drive_id=
umask=0o022
verification_code=
write_buffers=false`

**Comment by astrada** [comment]
Have you tried remounting with `-debug` and checking the log files for errors?

**Comment by TirantRex** [comment]
I was able to find one error in the logs :`Exception:Sys_error("Value too large for defined data type")`

**Comment by astrada** [comment]
Can you please send the logs to my email (alessandro.strada@gmail.com)? Thanks

**Comment by astrada** [comment]
Should be fixed in the release I'm publishing now.
