### ISSUE TITLE
Delete File Permanently

### ISSUE THREAD

**Issue by roxyschram** [astrada/google-drive-ocamlfuse#608]
How do you delete files permanently instead of them going to the trash bin? I see there was a feature request, I see 2 options about trash bins both of which I enabled, but nothing about bypassing the trash bin.

**Comment by astrada** [comment]
There's this command line switch: `-skiptrash`. (Run `google-drive-ocamlfuse -help` to get all command line options.)

**Comment by roxyschram** [comment]
I didn't see that listed but maybe I would have seen it if I wasn't working from a cellphone on it... :/ I'll give that a try. Thank you and thank you for your work.

**Comment by roxyschram** [comment]
Sorry for the delete, working like a champ. Thank you so much!
