### ISSUE TITLE
Can't rsync

### ISSUE THREAD

**Issue by thalesmaoa** [astrada/google-drive-ocamlfuse#612]
Hello, I was able to mount and auto mount my Gdrive. In fact, I can perform any normal system operation. However I scheduled an rsync backup but it seems to be a problem that I have no idea how to diagnose.
I have a folder with 50GB of files which I just clone to GDrive. The rsync is scheduled for every 1st of each month. Every time it start, it send all the files over again. My drive reached 777GB. 

Here is the rsync command:

```
rsync -avzh -P /share/HD/fahren/Administrativo/ /share/GDrive/Backup/fahren/Administrativo/
```

rsync output is normal, but I can see it pushes every single file every time.

**Comment by brancomat** [comment]
There's a couple of caveats in `rsync` use with `google-drive-ocamlfuse`, please take a look at the related wiki page:
https://github.com/astrada/google-drive-ocamlfuse/wiki/rsync

Long story short: in my case I ended up using `--size-only` to speed up things and avoid reuploading files (but I'm aware it's not an optimal solution) and `--inplace` to avoid mimeType issues.

**Comment by thalesmaoa** [comment]
Nice! What about delta (-W) which is mentioned?

**Comment by brancomat** [comment]
> What about delta (-W) which is mentioned?

It's faster. From the `rsync` manpage:
```
      -W, --whole-file
              This option disables  rsync’s  delta-transfer  algorithm,  which
              causes all transferred files to be sent whole.  The transfer may
              be faster if this option is used when the bandwidth between  the
              source  and destination machines is higher than the bandwidth to
              disk  (especially  when  the  "disk"  is  actually  a  networked
              filesystem).
```
(see also: https://github.com/astrada/google-drive-ocamlfuse/issues/48#issuecomment-34549818)

**Comment by thalesmaoa** [comment]
@brancomat thank. That was my question. How can a "copy entire file" be faster. Reading again is says:
```
if this option is used when the bandwidth between  the source  and destination machines is higher than the bandwidth to disk
```

Is there a easy way to erase everything to start over? Google is putting inside trash and a new folder called storage.

**Comment by brancomat** [comment]
Unfortunately a detailed explaination is out of my league.

However, if I understand correctly, since google drive APIs don't allow sequential file access or uploads of single chunks (there's the Google Drive v3 API resumable upload feature but it's useless in this context) not using `-W` forces the client to retrieve informations about the existing file (i.e.: download the whole file in cache to analyze the differences), then it uploads in its entirety anyway.

(but I might be wildly wrong, pinging @astrada on this)

**Comment by astrada** [comment]
@brancomat you're correct! 👍 

(Resumable upload is useful only when the upload is interrupted, then the application can upload only the bytes the server didn't receive.)

**Comment by thalesmaoa** [comment]
Is  the hidden .Trash/ folder Tu é real Drive Trash? I'm erasing everything to start over.
