### ISSUE TITLE
Faster loading folders

### ISSUE THREAD

**Issue by jorpilo** [astrada/google-drive-ocamlfuse#619]
Hello.
I have noticed that the first time you enter the mounted folder it takes a while to load.
Consecutive loads of the same folder (while metadata is still valid, are performed really fast) but after some time, it needs to reload it again.
This behavior is the same for every folder and subfolder in the mounted directory.
While understandable, I find it really slow and it gives the whole application a feeling really unresponsive while loading the metadata
Is there any way to improve the metadata retrieval so the application doesn't feel so unresponsive, specially for simple operations such as ls and navigation of folders?

**Comment by astrada** [comment]
No, sorry, there is no way to make the metadata fetching faster.

**Comment by jorpilo** [comment]
I am just trying to understand the behavior of why sometimes it's really slow and other times really faster.
Could the metadata be fetched in the background when the folder is mounted and then be ready for when any operation is performed?

**Comment by astrada** [comment]
> I am just trying to understand the behavior of why sometimes it's really slow and other times really faster.

I think it depends on the access pattern. Sometimes the OS issues a stat call to a dir or a file (maybe to get completion arguments), so when you actually need the metadata it's already there.

> Could the metadata be fetched in the background when the folder is mounted and then be ready for when any operation is performed?

At the moment it isn't so. But it can be an enhancement.

**Comment by astrada** [comment]
In version 0.7.21 (that I'm publishing right now), I've added `background_folder_fetching` config option to start a background thread that fetches folder data. Let me know is this solve your issue.

**Comment by shpinog** [comment]
Is it possible to cache this metadata somehow?

Each time you access a folder in which there have not even been changes, a rescan takes place, if the folder is large, it takes a long time.

It may be possible to add options with different scenarios such as:

Download a list of all files when mounting - it would be convenient to wait once, and know that the folders will open quickly.

Download lazily (it’s already possible now)

Use cache past scan? (Is this possible?
