### ISSUE TITLE
I/O Error Accessing Drive Shortcut

### ISSUE THREAD

**Issue by just-max** [astrada/google-drive-ocamlfuse#621]
#618 added support for the new Google Drive Shortcuts.
However, accessing shortcuts to shared files doesn't always work properly (it seems). Trying to access (eg. with ls or stat) the created link (symlink?) causes "cannot access '<filename>': Input/output error." After turning on shared_with_me the symlink works fine, however turning the option off again causes the link to point to a non-existent file (in .shared). Accessing the link itself doesn't produce an error any more though.
It seems that the old behaviour (when using Add to my Drive instead of the new Add a shortcut to Drive) was to allow access to those files directly without shared_with_me on, based off of accessing an item added to my drive that old way.
I prefer the old behaviour, not sure if that's still possible though?

**Comment by astrada** [comment]
> I prefer the old behaviour, not sure if that's still possible though?

No, because Drive Shortcuts are a new kind of resource in gdrive and rendering them as symlinks requires pointing to an existing file on the local filesystem. If you want, I can try to treat them as hard links (adding a new option), so that you can access the file directly, though you will not have an indication of the fact that you are accessing a shortcut and not the original file.

**Comment by just-max** [comment]
> If you want, I can try to treat them as hard links
No, I think symlinks most closely resemble Google Drive Shortcuts, since the file is only in one place.
The problem is that without shared_with_me the symlinks themselves can't even be read. The easy fix is turning on shared_with_me but especially since that is off by default having it cause an error doesn't seem desirable.
Rendering them as a symlink to the .shared folder (which then doesn't exist with shared with me off) doesn't seem like the best option either.

**Comment by astrada** [comment]
OK, I didn't know that Drive removed the "Add to My Drive" option. So, I think I fixed the issue in version 0.7.20: I removed the `shared_with_me` option, that's now on by default, and fixed the handling of shortcuts to shared items. Let me know if you still have problems.

**Comment by just-max** [comment]
> OK, I didn't know that Drive removed the "Add to My Drive" option

Yep, but looks like they'll still be around for a bit though, as per https://cloud.google.com/blog/products/g-suite/simplifying-google-drives-folder-structure-and-sharing-models or https://gsuiteupdates.googleblog.com/2020/03/shortcuts-for-google-drive.html

> I removed the shared_with_me option, that's now on by default

Makes sense.

Thanks for getting this sorted!
