### ISSUE TITLE
root_folder is not working

### ISSUE THREAD

**Issue by toml01** [astrada/google-drive-ocamlfuse#622]
Hi, thank you for a great tool!

I run version:
```
➜  ~ google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.7.19
Copyright (C) 2012-2020 Alessandro Strada
License MIT
```

I set `root_folder` as:
```
root_folder=1yGynlq8ri9pEzATckJyWxFd_C87pyLIj
```

and running:
```
➜  ~ google-drive-ocamlfuse -cc -label documents
Clearing cache...done
```

But still, I'm getting the root folder of my drive instead of the specific folder.

unmounting and remounting doesn't help too:
```
➜  ~ fusermount -u ~/drive-docs
➜  ~ google-drive-ocamlfuse -label documents drive-docs
```

any help please?

**Comment by astrada** [comment]
After you changed the `root_folder`, did you unmount the drive before mounting? The problem with the last 2 commands used to remount is that `-cc` is missing.

**Comment by toml01** [comment]
This worked, thanks!
Although, I find it kind of confusing. Why does this work:
```
➜  ~ fusermount -u ~/drive-docs                            
➜  ~ google-drive-ocamlfuse -cc -label documents drive-docs
```

but this doesn't:
```
➜  ~ google-drive-ocamlfuse -cc -label documents
➜  ~ fusermount -u ~/drive-docs                            
➜  ~ google-drive-ocamlfuse -label documents drive-docs
```

**Comment by astrada** [comment]
Yes, I admit that the UX is not the best at all! :D
If you restart the application without unmounting (`fusermount`), there is still a process in memory that saves retains the old config. When that process exits (at unmount), the DB is persisted again with the old settings.

**Comment by toml01** [comment]
Ahh makes sense.
Thanks for the help!
