### ISSUE TITLE
Input/output error with large files

### ISSUE THREAD

**Issue by PROgram52bc** [astrada/google-drive-ocamlfuse#627]
Hi, I have been using google-drive-ocamlfuse for a while, and it mostly behaves as expected. However I noticed that when I was trying to copy some large file from google-drive to my local machine, it stalls for about 30 seconds, and then gives me an error, like the following:
```
$ ls -lh 201902_Spr.tar.gz
-rw-r--r-- 1 xxx xxx 70M Jan  3 10:35 201902_Spr.tar.gz
$ cp 201902_Spr.tar.gz ~/Documents
cp: error reading '201902_Spr.tar.gz': Input/output error
```
With the `-d` flag, I get the (roughly corresponding) debugging output like this:
```
unique: 1282, opcode: LOOKUP (1), nodeid: 10, insize: 58, pid: 12641
LOOKUP /Archieves/201902_Spr.tar.gz
getattr /Archieves/201902_Spr.tar.gz
   NODEID: 33
   unique: 1282, success, outsize: 144
unique: 1283, opcode: OPEN (14), nodeid: 33, insize: 48, pid: 12641
open flags: 0x8000 /Archieves/201902_Spr.tar.gz
   open[0] flags: 0x8000 /Archieves/201902_Spr.tar.gz
   unique: 1283, success, outsize: 32
unique: 1284, opcode: READ (15), nodeid: 33, insize: 80, pid: 12641
unique: 1285, opcode: READ (15), nodeid: 33, insize: 80, pid: 12641
read[0] 131072 bytes from 0 flags: 0x8000
read[0] 131072 bytes from 131072 flags: 0x8000
   unique: 1284, error: -5 (Input/output error), outsize: 16
unique: 1286, opcode: READ (15), nodeid: 33, insize: 80, pid: 12641
read[0] 4096 bytes from 0 flags: 0x8000
   unique: 1286, error: -5 (Input/output error), outsize: 16
unique: 1287, opcode: FLUSH (25), nodeid: 33, insize: 64, pid: 12641
flush[0]
   unique: 1287, success, outsize: 16
   unique: 1285, error: -5 (Input/output error), outsize: 16
unique: 1288, opcode: RELEASE (18), nodeid: 33, insize: 64, pid: 0
release[0] flags: 0x8000
   unique: 1288, success, outsize: 16
```
The file is about 70 MB in size. I verified that with a smaller file of 35 MB, it can be copied over successfully.
Is there possibly a cache-size setting or something that prevents me to copy large files like this?
Thanks in advance!

**Comment by astrada** [comment]
You should enable logs (remounting with -verbose or -debug) then check them after you get the error.

**Comment by PROgram52bc** [comment]
I see.. I get some output saying the file is identified as malware. I think that's the problem.
```
[62.550740] TID=235: Service error: {"error":{"errors":[{"domain":"global","reason":"cannotDownloadAbusiveFile","message":"This file has been identified as malware or spam and cannot be downloaded."}],"code":403,"message":"This file has been identified as malware or spam and cannot be downloaded."}}.
```
But I was able to download directly from the web, with a warning message saying: "[the file] exceeds the maximum file size that Google can scan. This file might harm your computer, so only download this file if you understand the risks."

**Comment by astrada** [comment]
If you want to download it anyway, you can set `acknowledge_abuse=true` in the config file.

**Comment by PROgram52bc** [comment]
Thanks! That worked great!
