### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by arbrebinaire** [astrada/google-drive-ocamlfuse#632]
Hi,

I used to be able to symlink a directory outside a mounted Google Drive directory into it:
`ln -s /home/user/some_dir /home/user/cloud/someone@gmail.com/some_dir`

ln now complains:
`ln: failed to create symbolic link '/home/user/cloud/someone@gmail.com/some_dir': No such file or directory`

google-drive-ocamlfuse log:
`[536.789759] TID=54: File not found: symlink /home/user/some_dir`

Linking from a mounted Google Drive directory into a directory outside of it still works.

It's very useful to be able to link a folder outside a mounted Drive folder (let's say a node_modules dir with a few thousands files that I do not wish to upload to Google Drive).

I'm using version 0.7.21.  I initially installed version 0.7.17, which could handle that type of link.

Thanks much.

**Comment by astrada** [comment]
I broke that feature implementing support for Drive Shortcuts. In version 0.7.22, I partially restored it. It works only if you use an absolute path to create the symlink (otherwise I cannot tell if the target file is inside the mounted filesystem or not).

**Comment by arbrebinaire** [comment]
Really appreciate it.

My use case is rather personal, but I use Google Drive as a simplified JavaScript code repo with utilities I program for my non-coding friends.  It's basically a playground for people learning JavaScript, since they can share code with me too or with others and just correct mistakes on the go (without the fuss of learning the git machinery).

I was using relative links from their Google Drive root to their machine directory structure where logs, private files (credentials, etc.) and node_modules dir is located.  I'll have to find a way to use absolute paths.

Thanks again.

**Comment by WayneD** [comment]
I have some symlinks that are just a nice visible way to store some info, such as `foobar.hash -> git_hash_here`.  I now have to transform those symlinks with a leading slash to be able to mv them into the backup mount.  Can't you just treat any file-not-found error as an indication that the link should not be a drive shortcut?
