### ISSUE TITLE
Is it possible to ignore specific sub-directories?

### ISSUE THREAD

**Issue by meetmangukiya** [astrada/google-drive-ocamlfuse#633]
Something like `.gitignore` that'd prevent mentioned files and folders from being uploaded. 

Edi: checked the configuration wiki and the `config.ml` file, doesn't seem like there is configuration option for this. I have never programmed in OCaml but I will be happy to help anyway I can if this is something you'd like to add.

**Comment by astrada** [comment]
Sorry, it's not possible. You should use something like [rclone](https://github.com/rclone/rclone) or [drive](https://github.com/odeke-em/drive).

**Comment by meetmangukiya** [comment]
Okay, thank you for your suggestions!
