### ISSUE TITLE
Mounting Gives Error

### ISSUE THREAD

**Issue by dragonBall561** [astrada/google-drive-ocamlfuse#637]
I made the directory "Google Drive" in my Home folder. When I run the command ```google-drive-ocamlfuse ~/"Google Drive/"``` (After giving ocmalfuse access, it gives this error:
```
Unix.Unix_error(Unix.EACCES, "mkdir", "/home/angad/.gdfuse/default")
```

**Comment by astrada** [comment]
The user that start the process doesn't have permission to create directories under `/home/angad/`.

**Comment by dragonBall561** [comment]
Ok. I'll do it as root
