### ISSUE TITLE
RFE: offline mode

### ISSUE THREAD

**Issue by fommil** [astrada/google-drive-ocamlfuse#64]
It would be really great if this could be setup to work in offline mode with the cache, so that even without an internet connection I can access all my files.

I'd be happy if doing a full sync was a command that I had to run periodically.

**Comment by muranyia** [comment]
FYI Grive stopped working a few days ago.

**Comment by astrada** [comment]
There is another [project](https://github.com/odeke-em/drive) to access Google Drive that should work offline.
