### ISSUE TITLE
"Key has expired" message

### ISSUE THREAD

**Issue by sjtmbg** [astrada/google-drive-ocamlfuse#640]
Hi,

I recently started using gd-ocamlfuse in anger and have my google drive mounted on two machines, both running ubuntu 18.04.4.  I copy a file (call it "filename.ext") from a local partition to the mounted google-drive directory on Machine A.  When I look at this file on Machine B, it is called "filename (xxxxxxxx).ext", where xxxxxxxx is an 8-digit hex number.  When I move the file to a local partition on Machine B I get the following message:

mv: getting attribute 'system.posix_acl_access' of 'system.posix_acl_access': Key has expired

The contents of the file seem fine - no sign of corruption.  So why the change of filename?

**Comment by astrada** [comment]
>The contents of the file seem fine - no sign of corruption. So why the change of filename?

Google Drive permits to have more than one file with the same name in the same directory. This is not supported by UNIX file-systems, so the name is changed to make sure that is unique in the directory.

**Comment by sjtmbg** [comment]
OK, thanks.  Can you explain the warning message?  Anything to be concerned about?

**Comment by astrada** [comment]
No, sorry, I don't know what that message means (and Google doesn't help).

**Comment by sjtmbg** [comment]
OK, no problem, thanks anyway.

And thanks for your great work on this outstanding project!
