### ISSUE TITLE
Possible to make full background sync / full cache?

### ISSUE THREAD

**Issue by MPNull** [astrada/google-drive-ocamlfuse#641]
I would like to ask is that possible to configure google-drive-ocamlfuse to be fully cached like that the moving in example 1000 files to the folder doesn't show a progress bar for so long time because it waits for every single file to be transferred?

I'm not completely sure I should explain it but I would like to make ocamlfuse to cache the files and make them accessible immediately and transfer them in the background. Like move them to disk and buffer them with the speed that is possible from the disk to drive so moving files would not stutter.

**Comment by astrada** [comment]
If you need a full sync, you should use something like [rclone](https://github.com/rclone/rclone) or [drive](https://github.com/odeke-em/drive).
