### ISSUE TITLE
errors trying to list .ods files

### ISSUE THREAD

**Issue by R-Chandra** [astrada/google-drive-ocamlfuse#644]
It looks like recently any time I try to stat() (indirectly, as in, through ls -l) any file in my Google Drive that ends in .ods, I get input/output error.  Here is an example; find(1) has to stat(2) everything in order to know if there's a directory needing recursing into, and notice it only trips up on .ods files.

1 19:57:33 rchandra@hal9003:~ 1> find GDrive -type f > /dev/null
find: ‘GDrive/gen_match_cals.ods’: Input/output error
ind: ‘GDrive/volleyball-results.d/results_template_w_cal_link.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2013 winter The Y volleyball results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2015-fall-results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2014 winter The Y volleyball results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2014-fall_The_Crew_at_The_Y_results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2012 fall The Y volleyball results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/TheY/2016-winter-results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/results_template.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/match_sched_gen.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/DockAtTheBay/2013_The Crew Dock at the Bay Results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/DockAtTheBay/2014_The_Crew_Dock_at_the_Bay_results.ods’: Input/output error
find: ‘GDrive/volleyball-results.d/DockAtTheBay/2015_The_Crew_Dock_at_the_Bay_results.ods’: Input/output error
find: ‘GDrive/shoppinglist-new.ods’: Input/output error
find: ‘GDrive/non-root/function_testing.ods’: Input/output error
find: ‘GDrive/non-root/2015_Dock_gen.ods’: Input/output error
find: ‘GDrive/My Tracks-driving.ods’: Input/output error
find: ‘GDrive/VolleyballSchedDocs/2016-06-27-gen_match_cals.ods’: Input/output error
find: ‘GDrive/VolleyballSchedDocs/2016-05-28-KAV-gen_match_cals.ods’: Input/output error
1 19:58:53 rchandra@hal9003:~ 1> 

When using -debug, I did not see anything in curl.log which had the string (case insensitive) "error" in it.  Other than that, I wouldn't know what to look for.  I did notice that when it came to any .ods files, there was a whole lot of non-text in the file, the chunk of which started with PK (which IIRC is part of the signature for zipped files, which "Office" documents are).

In gdfuse.log, there doesn't seem to be a whole lot more to go on, other than for example

[91.305682] TID=335: END: Updating resource state in db (id=28)
[91.305701] TID=335: Service error: {}.
[91.312942] TID=335: Input/output error: stat /gen_match_cals.ods
[91.313332] TID=336: getattr /othertest.txt.odt
[91.313368] TID=336: BEGIN: Getting metadata from context
[91.313385] TID=336: END: Getting metadata: Valid

This is on Xubuntu 18.04.4, and it doesn't seem to matter which kernel I boot of the ones I have installed, but I'm usually running 5.4.0-39-generic .  The system has all updates applied.

I notice there is the line spreadsheet_format=ods in my config file, that's probably very relevant.

If all I'm doing is listing the files (ls), I don't see an error, but if I long list (ls -l) then I see input/output error.

0 20:42:11 rchandra@hal9003:~ 0> google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.7.22
Copyright (C) 2012-2020 Alessandro Strada
License MIT
0 20:42:14 rchandra@hal9003:~ 0>

**Comment by astrada** [comment]
There was a related bug that I fixed in the beta version. Can you please try that version? (You can find it [here](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta)).

**Comment by R-Chandra** [comment]
Acknowledged, I could give that a try, just don't know when.  maybe over the US Independence Day holiday.

**Comment by R-Chandra** [comment]
Looking good.  I did dpkg --install of the beta package, and I see stat()s from ls -l OK.  Thank you for your help.
