### ISSUE TITLE
Error: failed to open directory, every time there is a gsheet file to convert to ods

### ISSUE THREAD

**Issue by taxedserf** [astrada/google-drive-ocamlfuse#645]
The attached error from Thunar File manager.  Renders no directory data, so means navigation through file system in Google Drive is now impossible.

![googledriveocamlfuse error on gsheet](https://user-images.githubusercontent.com/43858989/86641330-f7398200-bfd2-11ea-9c97-b0ad5d04bae8.png)

In this screenshot, "postage control" is a gsheet.

Environment: Linux Mint 19 Xfce 32-bit running Thunar file manager 1.6.15.  Recent update included google-drive-ocamlfuse, so presume using the latest version of google-drive-ocamlfuse.

What's the fix?

--- Update, additional observations
1. Doesn't appear to be a similar error for gdoc files.  These are presented as *.ODT, as they should, with no error message.
2. Three files were moved in Google Drive Cloud after the error message.  But the Thunar File Manager still shows the files in their old location.  A related, or shared, root cause?

**Comment by astrada** [comment]
If you were not on the beta channel and didn't update after July 5, please update your package. I've released a bugfix that seems related to your issue. Otherwise, even if updating doesn't resolve, please remount with `-debug` and send the logs to my email (alessandro.strada@gmail.com). Thanks!

**Comment by taxedserf** [comment]
Package updated; issue disappeared; software working normally!   Thanks!
