### ISSUE TITLE
How to access the shared drive in the mounted directory?

### ISSUE THREAD

**Issue by abhipn** [astrada/google-drive-ocamlfuse#647]
I have followed all the instructions from [Headless Usage Doc](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization) and I was able to mount the drive.

But when I changed directory to the mount point. I couldn't find the Shared Drives anywhere. Am I missing any steps here for being able to access the Shared Drives along with shared with me (which is accessible by default)?

Version :- 0.7.22

**Comment by astrada** [comment]
To access Shared Drives you can follow the instructions for [Team Drives](https://github.com/astrada/google-drive-ocamlfuse/wiki/Team-Drives) (that's the old name for Shared Drives).
