### ISSUE TITLE
changing ownership of '/gdrive/': Input/output error

### ISSUE THREAD

**Issue by adukale** [astrada/google-drive-ocamlfuse#651]
I am getting  Input/Output error while chown the mounted directory. Have tried with -o allow other also.

Here is the debug log.
Service error: {"error":{"errors":[{"domain":"global","reason":"fileNeverWritable","message":"This file is never writable."}],"code":403,"message":"This file is never wr$
[13.945173] TID=6: Input/output error: chown /

**Comment by astrada** [comment]
To change ownership of the mountpoint you have to unmount first.

**Comment by adukale** [comment]
Thanks, worked.
