### ISSUE TITLE
Suddenly extremely slow?

### ISSUE THREAD

**Issue by OZ1SEJ** [astrada/google-drive-ocamlfuse#652]
I've been using google-drive-ocamlfuse for more than a year now, and if I have e.g. a file open in a text editor, it usually saves the file within seconds. But since yesterday, everything takes _much_ longer - I now have to wait 2-3 _minutes_ for a save action to complete. Is there any way of troubleshooting this?

**Comment by matejdro** [comment]
Google has some outage today: https://www.google.com/appsstatus#hl=en&v=issue&sid=4&iid=a45de3b26d6c5872f4cfe8e3424d7a82

**Comment by OZ1SEJ** [comment]
That was it! It's fast again - thanks! :-)
