### ISSUE TITLE
Shortcut symlinks remove the last character of the mount folder path, and are thus broken

### ISSUE THREAD

**Issue by TheAllSeeing** [astrada/google-drive-ocamlfuse#660]
All of my shortcuts appear as broken symlinks. Checking when they lead will show that they remove the last character of the mountpoint name - 
So instead of pointing to /path/to/Drive/path/to/file they point to /path/to/Driv/path/to/file.

**Comment by astrada** [comment]
Looks like a bug. Can you please remount with `-verbose` and send `gdfuse.log` to alessandro.strada@gmail.com? Thanks!
