### ISSUE TITLE
invalid_client using OAuth2

### ISSUE THREAD

**Issue by drzraf** [astrada/google-drive-ocamlfuse#664]
Steps to reproduce:
- setup a an app
- create a oauth2 credentials
- `google-drive-ocamlfuse -id foo.apps.googleusercontent.com -secret bar -headless`
- open the url / paste the code

Result:
```
Cannot retrieve auth tokens.
Failure("Unexpected error response: {\n  \"error\": \"invalid_client\",\n  \"error_description\": \"Unauthorized\"\n}")`
```
Documentation about Authorization says:
> You can create OAuth2 credentials from the Google APIs Console. Here you can find how to create a new application and here how to set up OAuth 2.0 credentials. When activating APIs, you must select the Drive API. When creating a new client ID, you must select "Installed applications" as Application type and "Other" as Installed application type (Redirect URI should be urn:ietf:wg:oauth:2.0:oob). Check that Drive API is among the Enabled APIs of your Developers Console.

But when creating oauth2 credentials we are not asked for "Redirect URI" (anymore) nor are we given the choice of "Other" (only "Desktop") + the referenced links of documentation are broken.

Is is still possible to google-drive-ocamlfuse with what is offered by console.developers.google.com nowadays?

**Comment by astrada** [comment]
Have you tried with this [guide](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization)? Sorry that the info are not up to date.

**Comment by drzraf** [comment]
Strangely enough, I was able to make it work on my local machine. Then I synced the `config` & `state` files to the remote server and got it working there too.
Closing for now & sorry for the noise.
