### ISSUE TITLE
Google doc file showing up as .desktop file

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [astrada/google-drive-ocamlfuse#682]
When I mount a google drive storage account using `google-drive-ocamlfuse` the actual document is not mounted, instead a .desktop file shows up at the mount point.

For example, I have the google doc file named Test in my google drive storage account. After mounting this google drive storage account using `google-drive-ocamlfuse`, the google doc Test shows up on my file system as Test.desktop when I navigate to the google drive storage mounted at the mount point, and the content of Tesk.desktop is:

```
[Desktop Entry]
Type=Link
Name=Test
URL=https://docs.google.com/document/d/1ch6yUklaLDETSJDhbwuodSlsIKf56U7cFcsC113ytSU/edit?usp=drivesdk
```

As you can see, the Test google doc shows up as Test.desktop which contains a link to the google doc instead of there being an actual document named Test that I can access (and download) on my file system. The link is opened with the browser.

**Comment by astrada** [comment]
Yes, that's the default. But you can specify google docs format using `-docsmode`. See https://github.com/astrada/google-drive-ocamlfuse/wiki/Usage and https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration#document-export-formats

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada thanks. The documentation for the usage of google-drive-ocamlfuse that you linked says:
> -docsmode: This option can be used to quickly set Google Docs config options. Supported values are:

Do you include the `-docsmode` when you are mounting the google drive storage account using `google-drive-ocamlfuse mountpoint` or when you run `google-drive-ocamlfuse` with no arguments?

Is the default value for the `-docsmode` option `desktop`? And does setting the value of the `-docsmode` option to `libreoffice` or `msoffice` mean that I would be able to access an actual document named Test on my system? That is, would setting `-docsmode` as `libreoffice` or `msoffice` convert the google doc named Test to a Test.odt file that is on the local file system?

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada I was wondering, if I set `-docsmode` option to `libreoffice` or `msoffice` and I modify the `libreoffice` or `msoffice` document on my file system, are changes made to the `libreoffice` or `msoffice` document on the file system synced to the google drive file it maps to?

**Comment by astrada** [comment]
>are changes made to the libreoffice or msoffice document on the file system synced to the google drive file it maps to?

No, Google Docs have an internal format that is not exportable, so there is no way to modify those file reliably without using the web interface, therefore the exported files are read-only (useful for backup purposes).

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada That's great to know, thanks
