### ISSUE TITLE
Mounting multiple google drive accounts using `google-drive-ocamlfuse -label label mountpoint`

### ISSUE THREAD

**Issue by ChukwuemezieChristopherAneke** [astrada/google-drive-ocamlfuse#683]
I don't quite understand how to use `google-drive-ocamlfuse -label label mountpoint` to mount multiple google drive accounts. I have several google drive storage accounts that I want to mount on my file system. So I use the `-label` option to distinguish them when mounting each of them.

I'm not sure whether `google-drive-ocamlfuse -lable myaccount1 mountpoint` needs to be run every time you want to mount a specific google drive storage account, that is, do you need to use the `-label` option the next time you want to mount that same google drive storage account, or do you only need to run `google-drive-ocamlfuse -lable myaccount1 mountpoint` the first time you mount a specific google drive storage account?

Also, just to confirm, does the label identify a specific google drive account?

**Comment by astrada** [comment]
>I'm not sure whether google-drive-ocamlfuse -lable myaccount1 mountpoint needs to be run every time you want to mount a specific google drive storage account, that is, do you need to use the -label option the next time you want to mount that same google drive storage account, or do you only need to run google-drive-ocamlfuse -lable myaccount1 mountpoint the first time you mount a specific google drive storage account?

You need to specify `-label ` every time. Otherwise it defaults to `-label default`.

>Also, just to confirm, does the label identify a specific google drive account?

Not necessarily but it's probably the most common scenario. But, for example, if you need 2 different configurations for the same account (say if you want to access different Shared Drives) you can use 2 labels that use the same google account.

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada thanks. That's very clear. `.gdfuse/label` does not get removed after you unmount the google drive storage account mounted at the mountpoint, so I thought that maybe `.gdfuse/label` remembers which google drive account that label was created for, so that the next time you mount the google drive storage account the label was created for you wouldn't need to specify `-label` again.

So then I'm guessing that `.gdfuse/label` is overwritten each time the same label is specified using the `-label` option, right?

> if you need 2 different configurations for the same account (say if you want to access different Shared Drives) you can use 2 labels that use the same google account.

When you say two different configurations for the same account do you mean something like `google-drive-ocamlfuse -docsmode libreoffice` and `google-drive-ocamlfuse -docsmode msoffice`?

I don't understand the example of wanting to access different Shared Drives, do you mean the "Shared with me" folder in google drive?

**Comment by ChukwuemezieChristopherAneke** [comment]
Say you have four google drive storage accounts you want to mount. Do you create a mount point for each google drive storage account and then mount all four google drive storage accounts on each mount point by using `-label` to identify each google drive storage account you are mounting? Maybe an example to mount multiple google drive storage accounts would be helpful.

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada
> You need to specify -label every time. Otherwise it defaults to -label default.

If I don't specify `-label` when mounting multiple google drive storage accounts and it defaults to -label default, are the contents of `.gdfuse/default` overwritten each time a different google drive storage account is mounted?

**Comment by ChukwuemezieChristopherAneke** [comment]
@astrada I've used `gooogle-drive-ocamlfuse` more and I'm now understanding how it works. The problem was that I wrongly thought that `google-drive-ocamlfuse -label label [mountpoint]` was an alternative command to `google-drive-ocamlfuse ~/GoogleDrive`, now I found out through using google-drive-ocamlfuse that `google-drive-ocamlfuse -label label [mountpoint]` is actually an alternative for `google-drive-ocamlfuse` which implicitly uses `-label default`.

The first time you run the command `google-drive-ocamlfuse -label label [mountpoint]` it configures the google drive storage account you want to mount (i.e. the google drive account you grant access to gdfuse in the webpage that gdfuse opens from the terminal) and then mounts it. The next time you run `google-drive-ocamlfuse -label label [mountpoint]` it (i.e. google-drive-ocamlfuse) uses the existing label (more accurately the configuration) in `.gdf/label` that is specified in the second run of `google-drive-ocamlfuse -label label [mountpoint]` to mount the google drive (storage) account you select using the webpage that gdfuse opens in your browser. Therefore the first run of `google-drive-ocamlfuse -label label [mountpoint]` can be slow because the configuration for the google drive storage account is being set up and then the google drive storage is mounted, but subsequent runs of `google-drive-ocamlfuse -label label [mountpoint]` are fast since the configuration specified by the `-label` option is (re)used which means the google drive storage is mounted straight away without any configuration being performed.

I'm assuming that you can break down the command `google-drive-ocamlfuse -label label [mountpoint]` into two parts:
1) `google-drive-ocamlfuse -label label`
2) `google-drive-ocamlfuse -label label mountpoint`

right? And that after running 1) you can modify the configuration in the config file in `.gdfuse/label` before mounting the google drive storage using 2), right?

**Comment by astrada** [comment]
Yes, it's correct.
