### ISSUE TITLE
On the behavior of local-side caching

### ISSUE THREAD

**Issue by BraINstinct0** [astrada/google-drive-ocamlfuse#689]
(Google) Drive File Stream works by
1) downloading files to local on-demand
2) delete local cache based on time(i.e. expire)
3) free up space if total local space has been used up

Since I'm planning to move from GDFS to gFUSE, which config would probably be the most similar to this?
My local drive storage is <100GB, and my Google Drive is >0.5TB, so I am concerned about this issue.

**Comment by astrada** [comment]
There is the config option `max_cache_size_mb` that should limit the local cache size. Note that the limit is not strict, because the application trims the cache only after operations. Note also that it probably doesn't work well if you have lots of big Google Docs.

**Comment by BraINstinct0** [comment]
Since I do not have much Google Docs(Rather, I'm using it more as a remote server than a Cloud for work), that'd not be much of a problem. So is it correct that I should set the max_cache_size_mb **lower than** the desired spare storage space?

**Comment by astrada** [comment]
Yes, right.

**Comment by BraINstinct0** [comment]
Ok, thanks for the guidance. Closing as resolved
