### ISSUE TITLE
.desktop files empty

### ISSUE THREAD

**Issue by karlberggren** [astrada/google-drive-ocamlfuse#693]
I would like to be able to click on desktop files and have the file open in google docs in my browser.  However, this is not working currently. Instead, my desktop link files are all empty, and clicking on them just results in an error message "There was an error launching this application.".  Would anyone be able to suggest what I could do to fix this?

I am running google-drive-ocamlfuse with option -docsmode desktop, and here is the config file.

[config.txt](https://github.com/astrada/google-drive-ocamlfuse/files/5827282/config.txt)

Not sure what I'm doing wrong.  I am using nemo 4.6.4 on linux mint 20 Cinnamon, v 4.6.6.  Kernel is 5.4.0-26-generic.

**Comment by astrada** [comment]
You can try setting `desktop_entry_as_html=true` and remount with `-cc`. The `.desktop` files should become `.html` files that redirect you to the Google Doc.

**Comment by karlberggren** [comment]
OK, I've tried that and it sort of worked.  It worked for one of the drives I have mounted, but not for the other. The one it worked for was my standard personal google drive.  That seems to be working well now.

However, my work google drive (part of google suites, based on file sync) continues to show the .desktop files, with size 0.

**Comment by karlberggren** [comment]
This problem seems to have resolved itself after my latest system upgrade/update, and a couple reboots.
