### ISSUE TITLE
Cant revoke access to google account

### ISSUE THREAD

**Issue by ncabello0335** [astrada/google-drive-ocamlfuse#698]
I just installed this app and its great but i had problems with another app so i wanted to revoke access just in case.. but i cant find ocamlfuse o gdfuse or anything related to this app in the google security list of third party apps. Any ideas?

**Comment by astrada** [comment]
If there is an active token, you should see something like this (in https://myaccount.google.com/permissions):
![Capture](https://user-images.githubusercontent.com/1190416/107776559-04290b80-6d42-11eb-9101-0ef3b66282a5.PNG)

If not, check that you are using the correct Google Account. If it is and you don't see anything, the token is not active anymore.

**Comment by ncabello0335** [comment]
Thanks for the quick reply!. But I searched the list one by one, its not there.

The app is still working, i can log in  terminal to the mounted and synced  gdrive (its a great app) But since i am having trouble with access to another app (appsheet) i wanted to revoke access to see if it had anything to do.

**Comment by ncabello0335** [comment]
My fault i was on a different account. All is OK
