### ISSUE TITLE
Making mounted directory available via Samba

### ISSUE THREAD

**Issue by Kasogi** [astrada/google-drive-ocamlfuse#70]
Hi!
I succesfully mounted my Google Drive under /googledrive on my Ubuntu 12.04 (headless) server. Now I am trying to make this directory available to the other computers in my LAN via Samba.
Unfortunately this does not work - the other clients in my network simply come back with an error message that the respective network drive was not found (error 0x80070043).
Any idea how to solve this?
Many thanks for this great program anyways.
Regards
Kasogi

**Comment by simonjamain** [comment]
Hi, bumped on the same problem, can you @vikjon0 tell me how exactly what command do you run with ` -o allow_other as per` ? I tried to put this in `/etc/fuse.conf` but did not seemed to work even after reboot. Thanks and sorry for asking on this 2 year old thread.

**Comment by yamaura** [comment]
add just a line `user_allow_other` to /etc/fuse.conf
and add `-o allow_other` option to google-drive-ocamlfuse command

**Comment by michasrichter** [comment]
I'm really sorry for resurrecting this old thread, but I just wanted to thank you guys for the excellent solution to the above. Uncommenting the `user_allow_other` in /etc/fuse.conf and then adding `-o allow_other` to the mount command as such..:

`google-drive-ocamlfuse ~/GoogleDrive -o allow_other`

...worked to allow folders inside the google drive mount on my server to be shared (and accessible) via SMB. In my case that was a "Scans" folder that can then be manually manipulated from a PC.
