### ISSUE TITLE
Cannot retrieve auth tokens

### ISSUE THREAD

**Issue by x80486** [astrada/google-drive-ocamlfuse#715]
I installed `google-drive-ocamlfuse` from Nix packages. I'm currently user Arch Linux (`Linux 5.10.32-1-lts #1 SMP Wed, 21 Apr 2021 12:28:13 +0000 x86_64 GNU/Linux`).

I'm trying to setup the repo doing `google-drive-ocamlfuse -xdgbd ~/Documents/CloudDrive/`, but so far looks like because there are some packages missing the process is unable to finish successfully.

```shell
[x80486@uplink:~/Documents]$ google-drive-ocamlfuse -xdgbd ~/Documents/CloudDrive/ 
/bin/sh: line 1: xdg-open: command not found
/bin/sh: line 1: firefox: command not found
/bin/sh: line 1: google-chrome: command not found
/bin/sh: line 1: chromium-browser: command not found
/bin/sh: line 1: open: command not found
Cannot retrieve auth tokens.
Failure("Error opening URL:https://accounts.google.com/o/oauth2/auth?client_id=5********9.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=J********Y")
```

Like I said, probably having any of those packages installed will make this a success, but I was wondering if there is a way, after pasting the URL manually in the browser and granting `gdfuse` the correct access, to close the loop on the client and retrieve the authorization token(s) in some way.

**Comment by astrada** [comment]
If you are on a headless server, you should check this wiki page: https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization
