### ISSUE TITLE
Adding an option for non empty directory

### ISSUE THREAD

**Issue by hdavy2002** [astrada/google-drive-ocamlfuse#73]
Hello folk,

I have some directories that are not empty and I need to mount them. I get an error and I get an option to add '-o nonempty' to my command, however it does not work for me. 

I checked the options for google-drive-ocamlfuse and there was nothing in there for nonempty dir.

Is there any other way to get around this?

Best

**Comment by vvcares** [comment]
Hi. I used "google-drive-ocamlfuse -label myname /home/gdrive -o nonempty".
But this command deleting my existing files .

Is there a way to not delete but sync all together.?

**Comment by astrada** [comment]
> Hi. I used "google-drive-ocamlfuse -label myname /home/gdrive -o nonempty".
> But this command deleting my existing files .

Not really. Your files are temporarily hidden by the mounted file system. When you unmount it, they will be available again.

> Is there a way to not delete but sync all together.?

No, you cannot merge an existing directory (on your local file system) with a FUSE file system. This is really not a sync application, but it gives you a local view of your remote files on GDrive.
