### ISSUE TITLE
PPA for Ubuntu 21.10

### ISSUE THREAD

**Issue by jonwitts** [astrada/google-drive-ocamlfuse#734]
Hi there,

I have just upgraded my Ubuntu 21.04 install to 21.10 and as part of the distribution upgrade process google-drive-ocamlfuse was uninstalled. Are there any plans for a PPA for Ubuntu 21.10?

Thanks

**Comment by astrada** [comment]
I've just published the packages for impish.

**Comment by jonwitts** [comment]
Perfect, thank you!
