### ISSUE TITLE
Doc suggestion: User systemd

### ISSUE THREAD

**Issue by davad** [astrada/google-drive-ocamlfuse#740]
An alternative to creating a system-wide systemd service for [Automounting](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting) is to create a user-specific unit definition. This method uses SystemD, but doesn't require elevated permissions to set up.

The file is almost identical, but `User` and `Group` are implicit.

Example unit definition:

```
[Unit]
Description=FUSE filesystem over Google Drive
After=network.target

[Service]
ExecStart=google-drive-ocamlfuse -label {label} {mountpoint}
ExecStop=fusermount -u {mountpoint}
Restart=always
Type=forking

[Install]
WantedBy=multi-user.target
```

Create this file as `~/.config/systemd/user/google-drive-ocamlfuse.service`.

Manually start/stop it as a normal user (no root):

```
systemctl start --user google-drive-ocamlfuse.service
systemctl stop --user google-drive-ocamlfuse.service
```

Enabling on-boot works similarly:

```
systemctl stop --user google-drive-ocamlfuse.service
```

**Comment by astrada** [comment]
Cool! Thanks! The wiki is editable by anyone, so feel free to add a section to the Automounting page.

**Comment by davad** [comment]
Thanks, made the change
