### ISSUE TITLE
Sudo has no writing privilege over Googledrive

### ISSUE THREAD

**Issue by laurentftech** [astrada/google-drive-ocamlfuse#753]
Hi. 
I would like to use the tool to automate backup by using systemctl but I notice that sudo user (root) has no writing privilege while regular has. 
Would you know how to fix that?
Thank you.

**Comment by astrada** [comment]
Have you tried mounting with `-o allow_root`?

**Comment by laurentftech** [comment]
No… I just tested it and it works.
  
You can close the issue.   
  
Thank you!
  
  
  
  
  
  
  

  
  
>
