### ISSUE TITLE
Google OAuth oob flow is deprecated

### ISSUE THREAD

**Issue by vmartins** [astrada/google-drive-ocamlfuse#764]
When trying to authenticate [headless](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization):
```
google-drive-ocamlfuse -headless -label me -id MYKEY -secret MYSECRET
```
After opening the given URL in the browser, the error appears
![image](https://user-images.githubusercontent.com/1051065/159488481-2cec2777-24ad-486e-8d15-21b5a4a15fe8.png)

Googling about the error, I verified that OAuth out-of-band (oob) flow will be [deprecated](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob)

**Comment by astrada** [comment]
Yes, in the latest version (0.7.28), I added 2 config options to address this issue: [oauth2_loopback] that can be set to [true] to enable the local server to handle the verification request, and [oauth2_loopback_port] to specify the port of the local server (defaults to 8080).

**Comment by rarrr** [comment]
I came across the same thing today.  if you just chance the oauth_loopback to true it sets the redirect to 127.0.0.1
![image](https://user-images.githubusercontent.com/7687585/159688500-268162f7-cf5b-4e9a-a231-a0c304546cef.png)
I've faffed around using ssh to redirect ports but it doesn't seem to start the tiny_httpd server. gdfuse.log nor -debug has nothing about starting it.

**Comment by vmartins** [comment]
After updating to version 0.7.28 and setting the parameter ```oauth2_loopback=true```, I created a [client](https://console.cloud.google.com/apis/credentials) of type web application with authorized redirect URI ```http://127.0.0.1:8080/oauth2callback``` and got the access token correctly.

Opening the given URL in the browser and authorizing, I was redirected to an address like: ```http://localhost:8080/?code=ACCESSTOKEN&scope=https://www.googleapis.com/auth/drive```, so I copied the ```code``` and used as verification code.

Thanks!

**Comment by eturkes** [comment]
> After updating to version 0.7.28 and setting the parameter `oauth2_loopback=true`, I created a [client](https://console.cloud.google.com/apis/credentials) of type web application with authorized redirect URI `http://127.0.0.1:8080/oauth2callback` and got the access token correctly.
> 
> Opening the given URL in the browser and authorizing, I was redirected to an address like: `http://localhost:8080/?code=ACCESSTOKEN&scope=https://www.googleapis.com/auth/drive`, so I copied the `code` and used as verification code.
> 
> Thanks!

Thanks I was facing the same issue and this worked. Took me a bit to figure out that you have to extract the `code` directly from the address bar in the browser. Assuming you also got "This site can't be reached" upon arrival to the final address.

**Comment by EdgarSedov** [comment]
I was able to retrieve verification token by flow described in [docker repository](https://github.com/maltokyo/docker-google-drive-ocamlfuse#environment-variables), but application shows this error on any call on my machine so i couldn't paste it correctly to the app:
```
edgar@edgar-laptop:~$ google-drive-ocamlfuse -cc -s -verbose -id my_id.apps.googleusercontent.com -secret my_secret
Starting application setup (label=default, base_dir=).
[0.000190] TID=0: Loading configuration from /home/edgar/.gdfuse/default/config...done
Opening log file: /home/edgar/.gdfuse/default/gdfuse.log
Clearing cache...done
Please enter the verification code: [23808:23808:0100/000000.685992:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
TOKEN_PASTED_HERE
Cannot retrieve auth tokens.
Failure("Unexpected error response: {\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Bad Request\"\n}")

edgar@edgar-laptop:~$ rm -rf ~/.gdfuse/default
edgar@edgar-laptop:~$ google-drive-ocamlfuse
[24568:24568:0100/000000.317440:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Had to use integrated flow without my credentials, it worked because it doesn't require you to paste something to console

Would be great to update the docs accordingly, i can describe the process of retrieving verification_token if error can be fixed

**Comment by bwraith** [comment]
> After updating to version 0.7.28 and setting the parameter `oauth2_loopback=true`, I created a [client](https://console.cloud.google.com/apis/credentials) of type web application with authorized redirect URI `http://127.0.0.1:8080/oauth2callback` and got the access token correctly.
> 
> Opening the given URL in the browser and authorizing, I was redirected to an address like: `http://localhost:8080/?code=ACCESSTOKEN&scope=https://www.googleapis.com/auth/drive`, so I copied the `code` and used as verification code.
> 
> Thanks!

Hi, I am sorry if this should all be easily followed, but I'm a little confused. I've received the warning that oob is deprecated, and I believe that the oob method is what I'm using with google-drive-ocamlfuse as of now. Is the google-drive-ocamlfuse application providing a http listener at port 8080 on my local destop? How is the server for http://127.0.0.1:8080/oath2callback created/served? Do I need to create a local web server or is this part of the application's functionality? Sorry it's hard to grasp the flow from this information, as I'm simply using this application and not familiar with the code. I did have a clientid and secret created in an application that I created in the console under api credentials, so I can step through the creation of a new client with type web spplication and with the described URI, as you've described, but I don't understand what's happening on the desktop application and/or http listener on the desktop. Thanks you so much for any additional clarifications or instructions on this.

**Comment by astrada** [comment]
The http listener is provided by the application. You just have to update the configuration and do the authentication flow.

**Comment by bwraith** [comment]
> After updating to version 0.7.28 and setting the parameter `oauth2_loopback=true`, I created a [client](https://console.cloud.google.com/apis/credentials) of type web application with authorized redirect URI `http://127.0.0.1:8080/oauth2callback` and got the access token correctly.
> 
> Opening the given URL in the browser and authorizing, I was redirected to an address like: `http://localhost:8080/?code=ACCESSTOKEN&scope=https://www.googleapis.com/auth/drive`, so I copied the `code` and used as verification code.
> 
In my case, I created the client as described, added the secret, client id, redirect uri, and oauth2_loopback=true parameters to the config file. I then executed google-drive-ocamlfuse (no parameters) and saw nothing happen. However, after removing the "state" file and issuing a clear cache command, the application launched the authentication page in my browser, I authorized, and it did everything else automatically. I saw a verification code retrieved successfuly in the browser window, and the console from which I launched google-drive-ocaml-fuse showed a similar "success" message for retrieving the verification token. I then issued a mount command, and it seems to be working. I'm not sure if this was the intended flow, but I thought I'd report what worked in my case, just in case it helps anyone else. Thanks...

**Comment by BigTimeStats** [comment]
Hello, total noob here, how do I set the oauth2_loopback parameter? I'm not seeing it in my current version on an ubuntu google cloud server. Currently seems to be running 0.7.27 even though I installed it today following the install instructions:

```
sudo add-apt-repository ppa:alessandro-strada/ppa
sudo apt-get update
sudo apt-get install google-drive-ocamlfuse
``` 

Current version

```
$ google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.7.27
Copyright (C) 2012-2021 Alessandro Strada
```

```
sudo apt upgrade google-drive-ocamlfuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
google-drive-ocamlfuse is already the newest version (0.7.27-0ubuntu1~ubuntu18.04.1).
```

I've set the correct credentials in OAuth 2.0 Client IDs including the URI above

**Comment by BigTimeStats** [comment]
Can anyone help me update the `oauth2_loopback=true` parameter? Where do I do this and what code do I submit afterwards? Thanks!

**Comment by BigTimeStats** [comment]
Edit: seemed to work after I logged out and back in and used without sudo 
```
mkdir GoogleDrive
google-drive-ocamlfuse GoogleDrive
```

Old:
Still not working for me after this: 

```
$: cat config | grep oaut
oauth2_loopback=true
oauth2_loopback_port=8080
$: ~/.gdfuse/default$ google-drive-ocamlfuse -headless -id xxx -secret xxx
```

Then I opened up the browser and copied the code from the url and received: `Access token retrieved correctly.`

Code was "4/xxxx&scope=https://www.googleapis.com/auth/drive" -> do I include the full url after code=?

However, then when I run 

```
sudo google-drive-ocamlfuse /GoogleDrive
/usr/bin/xdg-open: 869: www-browser: not found
....
Cannot retrieve auth tokens.
Failure("Error opening URL:https://accounts.google.com/o/oauth2/auth?xxxx
```

```
cat state
access_token_date=2023-03-14T23:18:53.000Z
auth_request_date=2023-03-14T23:18:53.000Z
auth_request_id=xxx
last_access_token=xxx
refresh_token=xxx
saved_version=0.7.30
```

Is this right?

**Comment by GetPsyched** [comment]
> I was able to retrieve verification token by flow described in [docker repository](https://github.com/maltokyo/docker-google-drive-ocamlfuse#environment-variables), but application shows this error on any call on my machine so i couldn't paste it correctly to the app:
> 
> ```
> edgar@edgar-laptop:~$ google-drive-ocamlfuse -cc -s -verbose -id my_id.apps.googleusercontent.com -secret my_secret
> Starting application setup (label=default, base_dir=).
> [0.000190] TID=0: Loading configuration from /home/edgar/.gdfuse/default/config...done
> Opening log file: /home/edgar/.gdfuse/default/gdfuse.log
> Clearing cache...done
> Please enter the verification code: [23808:23808:0100/000000.685992:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> TOKEN_PASTED_HERE
> Cannot retrieve auth tokens.
> Failure("Unexpected error response: {\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Bad Request\"\n}")
> 
> edgar@edgar-laptop:~$ rm -rf ~/.gdfuse/default
> edgar@edgar-laptop:~$ google-drive-ocamlfuse
> [24568:24568:0100/000000.317440:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
> ```
> 
> Had to use integrated flow without my credentials, it worked because it doesn't require you to paste something to console
> 
> Would be great to update the docs accordingly, i can describe the process of retrieving verification_token if error can be fixed

@EdgarSedov can you elaborate more on your solution? I'm running into the same issue and I'm guessing it's due to an outdated refresh token being passed into the console.
