### ISSUE TITLE
Automount with /etc/fstab without password

### ISSUE THREAD

**Issue by zanonmark** [astrada/google-drive-ocamlfuse#770]
Alessandro,

first of all, thanks a lot for Your work.

I'd like to propose a little improvement to the documentation, and specifically the [Automation > Mount using fstab](https://github.com/astrada/google-drive-ocamlfuse/wiki/Automounting#mount-using-fstab) section.

As Linux shell scripts can't be set the SUID flag, while normal application can, I wrote a small C program which a) determines the current username, b) becomes root, c) switches to the current user and mounts the filesystem.

Attached is the C source code. [google-drive-ocamlfuse-mounter.txt](https://github.com/astrada/google-drive-ocamlfuse/files/8599067/google-drive-ocamlfuse-mounter.txt)
After renaming .txt to .c, compile and install with:
```
$ gcc google-drive-ocamlfuse-mounter.c
$ sudo mv a.out /usr/bin/google-drive-ocamlfuse-mounter
$ sudo chown root:root /usr/bin/google-drive-ocamlfuse-mounter
$ sudo chmod 4755 /usr/bin/google-drive-ocamlfuse-mounter
```

Then create a mount directory with rw permissions for a specific user only:
```
$ sudo mkdir /mnt/google-drive-marco
$ sudo chown marco:marco /mnt/google-drive-marco
$ sudo chmod 0700 /mnt/google-drive-marco
```

Then edit /etc/fstab and add:
```
/usr/bin/google-drive-ocamlfuse-mounter#default  /mnt/google-drive-marco  fuse    uid=1000,gid=1000,user,_netdev,comment=x-gvfs-show  0       0
```
Fix the `uid` and `gid` parameters according to yours. The `comment=x-gvfs-show` is there so the Thunar file manager in XFCE can list this fstab entry, and mount / unmount it too.

As far as I can see, there shouldn't be any security issue with such a configuration, as users can only mount directories where they have filesystem permissions (so you could as well have another /etc/fstab entry pointing to /mnt/google-drive-tony with proper permissions, etc.).

Thanks,
MZ

**Comment by astrada** [comment]
Cool! Thanks! Feel free to add it to the wiki, it's freely editable.

**Comment by zanonmark** [comment]
> Cool! Thanks! Feel free to add it to the wiki, it's freely editable.

Interesting, I didn't know that!

Thanks,
MZ
