### ISSUE TITLE
I/O error when accessing gdrive

### ISSUE THREAD

**Issue by scfrank-pri** [astrada/google-drive-ocamlfuse#777]
My files do not show up in the mounted dir (GDRIVE)
I am running ubuntu 22.04 

google-drive-ocamlfuse -debug -o nonempty GRIVE
Starting application setup (label=default, base_dir=).
[0.535828] TID=0: Loading configuration from /home/user/.gdfuse/default/config...done
Opening log file: /home/user/.gdfuse/default/gdfuse.log
fusermount: failed to access mountpoint /home/user/GRIVE: Permission denied

Which is strange enough because it worked until recently. 
$ls -l GRIVE/ 
ls: reading directory 'GRIVE/': Input/output error
total 28
drwxrwxrwx   2 user.user  4096 Jun 23 15:17 ./
drwxr-xr-x 122 user.user 16384 Jun 23 17:34 ../
dr-xr-xr-x   2 user.user  4096 Jun 23 15:17 .shared/
dr-xr-xr-x   2 user.user  4096 Jun 23 15:17 .Trash/

/etc/fuse.conf reads: 
user_allow_other
mount_max = 1000

gdfuse.log reads: 
[0.536802] TID=0: Setting up default filesystem...
[0.536882] TID=0: BEGIN: Saving configuration in /home/.../.gdfuse/default/config
[0.538999] TID=0: END: Saving configuration in /home/.../.gdfuse/default/config
[0.539239] TID=0: Loading application state from /home/.../.gdfuse/default/state...done
Current version: 0.7.30
Docs mode not changed!
Setting up cache db...done
Setting up CURL...done
[0.544833] TID=0: google-drive-ocamlfuse didn't shut down correctly.
Cleaning up cache...done
Setting up cache db...done
...Refresh token already present.
[0.562633] TID=0: Starting filesystem GRIVE
[0.572380] TID=0: Exiting.
[0.572467] TID=0: Flushing cache...
[0.572486] TID=0: Storing clean shutdown flag...done
[0.573427] TID=0: CURL cleanup...done
[0.573457] TID=0: Clearing context...done

~/.gdfuse/default/config reads (only edited options)
acknowledge_abuse=true
stream_large_files=true

I changed these options because, without changing them, it also did NOT work. 

Trying other mount dirs (outside of my home folder) also gives me I/O errors. 
I have no idea what else should I do  - but I desperately need to access my files. 
Thanks for your help.

**Comment by astrada** [comment]
It looks like you probably have a pending google-drive-ocamlfuse instance. Kill it, or if you don't know how, reboot your system. And if it still doesn't work, remove all the files in /home/user/.gdfuse/ (`rm -r /home/user/.gdfuse/`) and reauthorize the access.

**Comment by scfrank-pri** [comment]
I did all this before, and again now. Still the same error, even if I use a new mount dir:
user@X1:~$ google-drive-ocamlfuse TEST
user@X1:~$ ll TEST
ls: reading directory 'TEST': Input/output error
total 28
drwxrwxrwx   2 user users        4096 Jun 23 17:22 ./
drwxr-xr-x 122 user group 16384 Jun 24 07:22 ../
dr-xr-xr-x   2 users users        4096 Jun 23 17:22 .shared/
dr-xr-xr-x   2 users users        4096 Jun 23 17:22 .Trash/

When I look into the log file, everything is OK - it takes info from Trash, and then it stops when a file autorun.inf is missing (no idea what this means). Maybe that helps: 

   unique: 684, success, outsize: 4112
unique: 686, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 27263
   unique: 686, success, outsize: 4112
unique: 688, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 27263
   unique: 688, success, outsize: 4112
unique: 690, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[0] flags: 0x0
unique: 692, opcode: LOOKUP (1), nodeid: 1, insize: 52, pid: 27263
   unique: 690, success, outsize: 16
LOOKUP /autorun.inf
getattr /autorun.inf
   unique: 692, error: -2 (No such file or directory), outsize: 16

**Comment by astrada** [comment]
An `Input/output error` usually means that there is an error returned by the Drive API. Have you checked `curl.log`? Do you see any error there?

**Comment by scfrank-pri** [comment]
I do not identify errors. This is the tail of the log file:

[1.373400] curl: header in: alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
[1.373412] curl: header in: accept-ranges: none
[1.373429] curl: header in: 
[1.373755] curl: data in: {
 "id": "0ANWEt8b-rTpEUk9PVA",
 "name": "My Drive",
 "mimeType": "application/vnd.google-apps.folder",
 "trashed": false,
 "explicitlyTrashed": false,
 "version": "2701",
 "webViewLink": "https://drive.google.com/drive/folders/0ANWEt8b-rTpEUk9PVA",
 "createdTime": "2012-09-02T12:26:23.936Z",
 "modifiedTime": "2016-03-17T09:52:45.640Z",
 "shared": false,
 "capabilities": {
  "canEdit": true
 }
}
[1.373917] curl: info: Connection #0 to host www.googleapis.com left intact

**Comment by astrada** [comment]
I'm sorry, but if there are no errors in the log files, maybe the input/output error is returned by the OS? But if it's so, I don't know how to help you.

**Comment by scfrank-pri** [comment]
Looks like it is a fuse problem 
googling for 
LOOKUP /autorun.inf 
getattr /autorun.inf  
(which is the last entry in gdfuse.log before hanging) gives this: 

[https://stackoverflow.com/questions/54588394/fuse-file-system-looks-for-trash-autorun-inf-and-xdg-volume-info-files](https://stackoverflow.com/questions/54588394/fuse-file-system-looks-for-trash-autorun-inf-and-xdg-volume-info-files)

[https://github.com/gphoto/gphotofs/issues/13](https://github.com/gphoto/gphotofs/issues/13)

Unfortunately, I lack the competencies to know what to fix now.

**Comment by scfrank-pri** [comment]
All I can tell that it works now. No idea why, no idea how. Did not learn anything. But can access my files, again.
