### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by adojaan** [astrada/google-drive-ocamlfuse#78]
Hi, thank you for this initiative, it is very userful piece of software (when I get it working)
Problem: On first launch browser window is opened, I can select one of my multiple Google accounts, then I accept access to drive, then once more I select account on a different page (OAuth2) but then error message is displayed: Error: Bad Request
Your client has issued a malformed or illegal request. 
I noticed that state file in .gdfuse/default has some zero dates:
last_access_token=
access_token_date=1970-01-01T00:00:00.000Z
refresh_token=
auth_request_id=Rw.....Co5w
saved_version=0.5.3
auth_request_date=1970-01-01T00:00:00.000Z
May it affect?

**Comment by astrada** [comment]
I'm closing this issue because there was no follow-up.
