### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by adrianmihalko** [astrada/google-drive-ocamlfuse#789]
Hi,

I exactly followed [authorization guide](https://github.com/astrada/google-drive-ocamlfuse/wiki/Authorization#alternative-authorization-mode) -[ also this guide](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization)-, but for some reason it is not working for me.

$google-drive-ocamlfuse -headless -label me -id 750xxxxxxxxxxxxxxxapps.googleusercontent.com -secret xxxxxxxxxxx_d96GO9D8n
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=xxxxxxxxxxxxxxapps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code:

When I open the URL on another machine:

![SCR-20221017-l8l](https://user-images.githubusercontent.com/733361/196187247-40d0e7a7-c407-4332-834d-4c2a4e419edb.png)

When I click on error details:

_Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)_

**Comment by mrfdrws** [comment]
> Hi,
> 
> I exactly followed [authorization guide](https://github.com/astrada/google-drive-ocamlfuse/wiki/Authorization#alternative-authorization-mode) -[ also this guide](https://github.com/astrada/google-drive-ocamlfuse/wiki/Headless-Usage-&-Authorization)-, but for some reason it is not working for me.
> 
> $google-drive-ocamlfuse -headless -label me -id 750xxxxxxxxxxxxxxxapps.googleusercontent.com -secret xxxxxxxxxxx_d96GO9D8n Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=xxxxxxxxxxxxxxapps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force Please enter the verification code:
> 
> When I open the URL on another machine:
> 
> ![SCR-20221017-l8l](https://user-images.githubusercontent.com/733361/196187247-40d0e7a7-c407-4332-834d-4c2a4e419edb.png)
> 
> When I click on error details:
> 
> _Error 400: invalid_request The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method. Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob [Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)_

same problem, hope this nice app working again

**Comment by smoglica** [comment]
Seems that the [OOB](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration) flow has been deprecated.

Google it's suggesting to [Migrate to a secure alternative]( https://developers.google.com/identity/protocols/oauth2/resources/oob-migration#migrate-to-a-secure-alternative) and seems that for desktop apps should be followed the [loopback IP address](https://developers.google.com/identity/protocols/oauth2/native-app#redirect-uri_loopback) flow.

I tried to replace from the generated URL the `redirect_uri` from `redirect_uri=urn:ietf:wg:oauth:2.0:oob` to `http://localhost`. So I'm able to get redirect to `http://localhost` and finding from the URL the `code` query string param.

Using it as `verification code` I still get:

```
Cannot retrieve auth tokens.
Failure("Unexpected error response: {\n  \"error\": \"invalid_client\",\n  \"error_description\": \"Unauthorized\"\n}")
```

I guess that this is caused by the exchange request that doesn't match the `redirect_uri`

**Comment by astrada** [comment]
Yep, see issue #764 for a solution.

**Comment by adrianmihalko** [comment]
> Yep, see issue #764 for a solution.

For me auth server is not starting:

```
@ubuntu:~/.gdfuse/default$ cat config | grep oaut
oauth2_loopback=true
oauth2_loopback_port=8086
@ubuntu:~/.gdfuse/default$ sudo google-drive-ocamlfuse -headless -id apps.googleusercontent.com -secret GOCSPX-
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A8086%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: 
```

```
$ sudo netstat -tulpn | grep 8086
@ubuntu:~$ curl 'http://127.0.0.1:8086/oauth2callback?code=4/0AWgav&scope=https://www.googleapis.com/auth/drive'
curl: (7) Failed to connect to 127.0.0.1 port 8086 after 0 ms: Connection refused
```

**Comment by adrianmihalko** [comment]
Oh got it, solution was here: https://github.com/astrada/google-drive-ocamlfuse/issues/764#issuecomment-1088153922
