### ISSUE TITLE
Update install instructions in the wiki

### ISSUE THREAD

**Issue by elhusseiniali** [astrada/google-drive-ocamlfuse#802]
Hey, so if someone were to install the package using opam, they no longer have to use depext (it fails when you try to install depext, anyway). Just running `opam install google-drive-ocamlfuse` is enough. Figured you'd want to update the wiki to reflect this. Thanks for the great work!

**Comment by astrada** [comment]
Thanks! Fell free to update it yourself. The wiki is editable.
