### ISSUE TITLE
Choose directory in GD to be mounted ?

### ISSUE THREAD

**Issue by Sylv01H** [astrada/google-drive-ocamlfuse#803]
Hello, I have a lot of directories on my Google Drive, and I want to mount only one in these, is it possible or not ?
I don't find parameters or option to do that...
Thanks !

**Comment by astrada** [comment]
You can try with the `root_folder=` config option (https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration). You have to get the folder id from the web interface, though.

**Comment by Sylv01H** [comment]
Hello, thanks for you reply, I will try this !

**Comment by Sylv01H** [comment]
Ok, working fine !
Many thanks !
