### ISSUE TITLE
Massive memory consumption.

### ISSUE THREAD

**Issue by Phils80** [astrada/google-drive-ocamlfuse#842]
Hi, I'm using google-drive-ocamlfuse with 3 Google accounts on my Ubuntu Server 22.04. Every account is running as separate service. 
I'm using 0.7.30 version of google-drive-ocamlfuse.

I have following problem:
after some time service on one of accounts starts to consume massive percentage of memory (I have 32 GB RAM installed on my server) arriving at over 73% of total memory use, in consequence almost blocking my server:
```

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1466 root      20   0   43,9g  21,5g     20 S   1,7  73,4  27:39.79 google-drive-oc
   1438 root      20   0   13,6g   6,1g   1328 S   2,3  20,9   9:50.00 google-drive-oc
1340765 root      20   0 2652620 434980      0 S  16,7   1,4  18:20.30 mysqld
   1419 root      20   0  608508 228296      0 S   1,7   0,7   1:24.62 google-drive-oc

```
 Restarting service for this account normalize situation, but after some time problem returns. Observing system memory use with `type -o %MEM` I see that memory consumption for this account is slowly, but constantly growing with dynamics about 0,5 GB / 1h. 

It is very strange, because size of whole data is about 26 GB for this account. <s> Additionally other accounts don't have this problem regardless similar size of data. </s>
-----EDIT-----
It seems that other account with lower ammount of files has this problem too, but it grows slower.

 My config file is following:

```
acknowledge_abuse=false
apps_script_format=desktop
apps_script_icon=
async_upload_queue=false
async_upload_queue_max_length=0
async_upload_threads=10
autodetect_mime=true
background_folder_fetching=false
cache_directory=
client_id=HIDDENFORSAFETY.apps.googleusercontent.com
client_secret=HIDDENFORSAFETY
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
debug_buffers=false
delete_forever_in_trash_folder=false
desktop_entry_as_html=false
desktop_entry_exec=
disable_trash=false
docs_file_extension=true
document_format=desktop
document_icon=
download_docs=true
drawing_format=desktop
drawing_icon=
form_format=desktop
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
log_to=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
metadata_memory_cache=true
metadata_memory_cache_saving_interval=30
mv_keep_target=false
oauth2_loopback=true
oauth2_loopback_port=8080
presentation_format=desktop
presentation_icon=
read_ahead_buffers=3
read_only=false
redirect_uri=
root_folder=
scope=
service_account_credentials_path=
service_account_user_to_impersonate=
spreadsheet_format=desktop
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
team_drive_id=
umask=0o022
verification_code=
write_buffers=false
```
I've went through issue #215  , but it seems my version is 0.7.30 which is the latest and there is no clear solution there for me. 
-----EDIT-----
My Google drives are mounted in Nextcloud filesystem - it is allowing me to use Nextcloud also to manage and view our files in Google drive. Doing it forces me to run cron job every 15 minutes to scan (with  `nextcloud.occ files:scan` ) Google drive for changes to keep Google drive and Nextcloud syncronized. After this operation memory consumption increase.
What is important - it is increasing for every account, but **increase is more significant for accounts with bigger ammount of files:**

account 1 has 13018 files in 657 directories - its memory consumption increase about 0,4 GB every scan
account 2 has 5866 files in 335 directories - its memory consumption increase 0,1 GB every scan
account 3 has 72 files in 13 directories and its consumption doesn't grow

I launched google-drive-ocamlfuse with -debug option, and registered logs for over 3 hours and curl.log has almost 300 k lines  and gdfuse.log has over 2 Mln lines. 

Does anyone knows what can be root cause or/and solution ? Is there any way to limit allowed memory consumption level ?

@astrada I can share with you log files if necessary

**Comment by Phils80** [comment]
I don't know if this behavior is a result of linking Google Drive folder with Nextcloud, but the only workaround I've found was to set up cron job and restart google-drive-ocalmfuse service every hour. It protects against blocking my server by consuming whole RAM...

**Comment by gAlleb** [comment]
Hi @Phils80 
I've written about this here https://github.com/astrada/google-drive-ocamlfuse/issues/826#issue-1918120489.

If you've installed via ppa:
Try switching ppa to `deb http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu focal main` and reinstall focal version on your Ubuntu 22.04. 
Go to `/etc/apt/sources.list.d`, find `alessandro-strada-ubuntu-ppa....list` and edit contents to `deb http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu focal main`, then reinstall. It may help. 

You'll have 
```
~$ google-drive-ocamlfuse -version
google-drive-ocamlfuse, version 0.7.30
Copyright (C) 2012-2022 Alessandro Strada
License MIT
```

But it would be from `focal` repo and it usually solves the problem on Ubuntu 22.04. Something wrong in `jammy` version of  0.7.30.

**Comment by Phils80** [comment]
Hi **@gAlleb**, many thanks for your support, your solution works like a charm ! I can close this issue now :)
