### ISSUE TITLE
Google has made access to this f*cking impossible

### ISSUE THREAD

**Issue by Chiarchiaooo** [astrada/google-drive-ocamlfuse#861]
As the title suggests, the whole procedure to set up an application on Google cloud's slow as b*lls ""website"" has now an added layer of bureaucracy since Google now has to validate the app in order to let you use it.

I'm sorry, but i think i'll look for another one.

Edit: Sorry for the delay in an update, but I managed to resolve the issue in the end switching to mega, which has a native app on Linux and gives for free 5 more GB than what Google offers. I'll be marking this issue as solved

**Comment by ljo123** [comment]
I couldn't get it to work either with the new token method. Kept getting "app not verified" errors from google. However if you have a previous working install of google-drive-ocamlfuse you can copy over the ~/.gdfuse directory and get everything working with the existing token.

**Comment by Chiarchiaooo** [comment]
I do not have a previous version. Since i had some problem with my installation and had to reset.
I in the end just ended switching to MEGA since google apparently either doesn't care about linux or are making it hard on purpose.

**Comment by Chiarchiaooo** [comment]
It's a bit of a pity since this software is really good and i've also made a script and .service file in order to load it at boot as a user process. I'll leave it opened in case someone comes with a solution.

gdrive-load.sh: https://hastebin.com/share/uwumumomuc.bash
gdrive-client.service: https://hastebin.com/share/wiginololi.ini

**Comment by gwennlbh** [comment]
It does work, you just have to put your google account's email address in the test users list (at https://console.cloud.google.com/apis/credentials/consent)

**Comment by asanchez75** [comment]
it works and do no forget to select "Desktop" as application type

**Comment by chvainickas** [comment]
> It does work, you just have to put your google account's email address in the test users list (at https://console.cloud.google.com/apis/credentials/consent)

Do you know how this is done? Is there a guide anywhere? @ewen-lbh 

EDIT: Fixed, got it to work by following the instructions [here](https://github.com/astrada/google-drive-ocamlfuse?tab=readme-ov-file#usage)

**Comment by chvainickas** [comment]
@ewen-lbh

**Comment by vicmortelmans** [comment]
I'm trying, but at step 2 "Create an OAuth client ID." it says I must configure the OAuth Consent screen first, and I'm at loss what I have to enter there. If I leave the form incomplete and submit, it won't accept and I get a warning that my request is reported as abusive !?

I don't think this workaround is working...

**Comment by Chiarchiaooo** [comment]
> It does work, you just have to put your google account's email address in the test users list (at https://console.cloud.google.com/apis/credentials/consent)

Still quite convoluted as a method, tbh.
