### ISSUE TITLE
I/O error because OAuth 2.0 token expires

### ISSUE THREAD

**Issue by andrewjdcrow** [astrada/google-drive-ocamlfuse#872]
Now that OAuth 2.0 is required, I've been having the occasional issue where my token expires and Drive fails to mount properly. When it's happened, removing `~/.gdfuse` and reauthenicating works. Below are snippets from the logs.

gdfuse.log
```
[0.378510] TID=4: Error during request: Unexpected error response: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```
curl.lorg
```
[0.201252] curl: data in: {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
```
```
[0.375038] curl: data in: {
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```
I've been reviewing the [Google Cloud docs](https://cloud.google.com/secret-manager/docs/creating-and-managing-expiring-secrets#removing-expiration) and found that this should work:
`gcloud secrets update "SECRET_ID"  --remove-expiration`

However, it turns out I need to set up a billing account; I'd rather not if I can help it.
```
...
ERROR: (gcloud.secrets.update) FAILED_PRECONDITION: Billing account for project 'REDACTED' is not found. Billing must be enabled for activation of service(s) 'secretmanager.googleapis.com' to proceed.
...
  reason: UREQ_PROJECT_BILLING_NOT_FOUND
```
Is there a best method of removing the expiration time or automatically refreshing tokens? Thanks!

**Comment by gAlleb** [comment]
<img width="500" alt="Снимок экрана 2024-06-09 в 16 26 51" src="https://github.com/astrada/google-drive-ocamlfuse/assets/144447266/358b1699-2be9-4715-8a76-092b48a843dd">

> Projects configured with a publishing status of Testing are limited to up to 100 test users listed in the OAuth consent screen. A test user consumes a project's test user quota once added to the project.
Authorizations by a test user will expire seven days from the time of consent. If your OAuth client requests [an offline access type](https://developers.google.com/identity/protocols/oauth2/web-server#offline) and receives a refresh token, that token will also expire.

>

**Comment by xandey** [comment]
Did you figure out a way to solve this? I ended up setting up a script with my secret in it and I run it every week when I can't access the folder. I don't have a billing account either.

**Comment by andrewjdcrow** [comment]
@xandey Yes, @gAlleb suggested that the Publication Status of your project should be set to "In Production."

**Comment by xandey** [comment]
Ok. I added a description of this in the wiki.
