### ISSUE TITLE
Question: Can GDO work with Google One?

### ISSUE THREAD

**Issue by berislavlopac** [astrada/google-drive-ocamlfuse#881]
I use Google Drive via the Google One subscription, so I don't have a GCP project where I could activate the API as per the documentation. I used to be able to use it on a previous laptop; now every time I run `google-drive-ocamlfuse` I get the following error:

> `Error: You should specify a client id (-id) and a client secret (-secret)`

And the documentation all points to the GCP API.

So I would like to confirm: is it possible to use it with the Google One subscription? If so, how you I get the relevant credentials? If not, has something recently changed that prevents me from using it? Thank you!

**Comment by astrada** [comment]
Yes, it works (I have a Google One subscription). But now you have to create your own credentials (https://github.com/astrada/google-drive-ocamlfuse/wiki/Authorization) because of a change of policy by Google to increase privacy/security of your data.

**Comment by berislavlopac** [comment]
But I have to create a GCP project anyway, is that correct? :thinking:

**Comment by astrada** [comment]
Yes, it's correct.

**Comment by berislavlopac-wpp** [comment]
It's working fine, thank you!
