### ISSUE TITLE
Question about using service accounts

### ISSUE THREAD

**Issue by rennsport** [astrada/google-drive-ocamlfuse#884]
Hi, I am part of an org that would like to start using our google drive for some of our applications. It seems a service account would be the most appropriate way to achieve this. The steps I've done so far:

- Created an project on our org's Google Cloud console and enabled the Google Drive API for the project
- Created a service account in said project and saved its json & client ID
- Added the service account's client ID to our org's Google Workspace API section with the google doc and google drive scope
- Installed google-drive-ocamlfuse in our Ubuntu test environment

My question is does the service account need to impersonate a Google Workspace user in order for google-drive-ocamlfuse to work? I know it's mentioned in the docs [here](https://github.com/astrada/google-drive-ocamlfuse/wiki/Service-Accounts) about impersonation so maybe I am misunderstanding Google's APIs, but why would we want to create a service account only for the service account to actually add files to drive under the guise of another user in the org? Or is the more correct way to think about service accounts is that they are a special type of API authentication that is allowed to modify any Workspace user's data within a given scope hence the name "service?"

**Comment by astrada** [comment]
Yes, a service account is tied to an application, and if you enable domain delegation (https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority), your users can access their data as themselves without having to manually authorize access to the Drive scope.

**Comment by rennsport** [comment]
Okay the that makes sense. From a bookkeeping standpoint, if we want a specific application to be the modifier and owner of the files on the shared drive would we create a new user on our org's workspace, say application@domain, and then use that with the service account or would it be "better" from a security standpoint to generate a client ID & client secret and authorize those specifically with the application@domain user as to not lot any application gain access to any user's data?

**Comment by astrada** [comment]
If you want to keep everything segregated, you should create a specific client id/secret. Then you could share single files/folders between actual users and the application. It's more manual work but it's safer.

**Comment by rennsport** [comment]
Thanks for your help, I appreciate it!
