### ISSUE TITLE
Mount a specific folder

### ISSUE THREAD

**Issue by hynese** [astrada/google-drive-ocamlfuse#99]
So I set up google-drive-ocamlfuse on a headless server. I do `google-drive-ocamlfuse /mnt/google_drive/` and I can see all my files at /mnt/google_drive. This is brilliant!

But is it possible to mount just the "data" folder of my Google Drive to /mnt/google_drive?

I'm using Google Drive as a storage area for owncloud.org. The person whose Google Drive account I'm using won't want all his Google Drive files accessible on the server. He only wants one folder to be used for the owncloud storage area.

Would it be possible to add a "root_directory" option for `google-drive-ocamlfuse`? Can I just edit src / drive.ml#30 and change `let root_directory = "/"` to `let root_directory = "/data/"`? Or are there other places in the codebase I'd need to change?

Great project btw. Very useful. Thank you!

**Comment by kilabyte** [comment]
Any plans to specify the mount point subdirectory? I really don't want my whole drive mounted on the server (security). Based on @hynese suggestion where can i find the drive.ml on my install?

**Comment by astrada** [comment]
> Based on @hynese suggestion where can i find the drive.ml on my install?

If you are using opam, you can clone the repository locally, edit the src/drive.ml file (https://github.com/astrada/google-drive-ocamlfuse/blob/master/src/drive.ml#L44) at line 44, instead of "root" you should enter the folder id of the folder you want to mount. To get the folder id, you can open the Drive web interface, go to the said folder and note the id that is the string that is after the last slash in the URL. Then with `opam pin add google-drive-ocamlfuse . -n` (from the directory where you cloned the repository) you can select you local version. `opam update && opam upgrade` should compile and install it. If it doesn't work, `opam remove google-drive-ocamlfuse && opam install google-drive-ocamlfuse` should do.

**Comment by kilabyte** [comment]
hmmm thats the kicker is i don't have root/sudo access to add opam

**Comment by astrada** [comment]
If you want you can install opam in a custom directory (without sudo). Check this [link](http://opam.ocaml.org/doc/Install.html) and replace /usr/local/bin with a directory you have permission to write to.

**Comment by rourke** [comment]
I really don't want to install opam and compile it to be able to mount a subdirectory. Seems like a big hassle over having an option like `root_directory` as an argument. Any plans on adding something like this?

**Comment by astrada** [comment]
> Any plans on adding something like this?

Yes, I just have to find some spare time to add this feature. :-)

**Comment by bayoumedic** [comment]
i am needing this too

**Comment by astrada** [comment]
I just published version 0.6.20 (on the beta channel) where I added a `root_folder` config option where you can specify a folder id or a remote path to the a custom root folder.

**Comment by jmiller0** [comment]
Has anyone gotten this to work, what is the syntax?

**Comment by astrada** [comment]
You can insert a folder id or a path. For example `root_folder=0B-TenPiSMBplOGg4eXR1c3U0RTg` or `root_folder=/folder/f1`.
![folderid](https://user-images.githubusercontent.com/1190416/27259602-d71af5c4-5416-11e7-9d13-a7a8855ed39e.png)

**Comment by felixbrucker** [comment]
This does not seem to work with folder ids from backuped computers like the following:
![image](https://user-images.githubusercontent.com/5189997/28852333-961d35ac-7728-11e7-9bc3-6cd209a08d9a.png)

i assume the regular gdrive api can't reach those?

**Comment by astrada** [comment]
> i assume the regular gdrive api can't reach those?

Yes, right.

**Comment by jeepfanatic** [comment]
I'm trying to use the root_folder option but it's still mounting to the root of my google drive.  Tried using both via command line and by editing the config file.  Any suggestions?

**Comment by soulslicer** [comment]
I tried running this in command line but it doesnt work:

"google-drive-ocamlfuse root_folder=1s-Y... gdrive"

It still tries to pull everything. What do I do?

**Comment by astrada** [comment]
@soulslicer: you should set it in the `config` (file)[https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration].

**Comment by vinkwok** [comment]
Hi astrada, it's a very useful tool. Thanks! 
BTW, I seems cannot get it to work with folder ID or path. Any comments?

**Comment by oliversheridanmethven** [comment]
> @soulslicer: you should set it in the `config` [file](https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration).

If I want to have two mounted folders `foo` and `bar` mounted within some directory `baz`, can this be done. It seems setting the `root_folder` would be global.

**Comment by soulslicer** [comment]
I gave up and switched to in sync almost a year ago

**Comment by google-meet-meat** [comment]
> Hi astrada, it's a very useful tool. Thanks!
> BTW, It seems I cannot get it to work with folder ID or path (it still shows the full drive folder even I denote a specific folder id). Any comments?

I fixed it on headless by running the headless usage and authorization command again @vinkwok

**Comment by shbitsus** [comment]
failed to change root to folder:
Just installed on Debian 11 from 
deb http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu xenial main
Ran google-drive-ocamlfuse so it would create a config file, but killed it before authenticating.
Edited the config changing "root_folder=" to "root_folder=xxxxxxxxxxxxxxxxxxxxx".
Run google-drive-ocamlfuse again, this time authenticating. Oh, and since I might later connect an other account, I gave it a label.  Disappointed it mounted my entire google drive, but, then I see the Label I passed caused it to create a new set of config files under .gdfuse/ label 
I unmount google-drive.  Edit the new config file and mount it again.
Still, it mounts my entire google drive.

**Comment by shbitsus** [comment]
several more tries:  but ultimately  apt-get purge ; delete .gdfuse ; and start over.  I think working now.
I had revoked it's access to my Google Drive.  I was thinking that perhaps the level of access granted was set in stone at the time I approved the access.  Or, I could be wrong, perhaps if I delete the 'root_folder' config, it would again have full access. Anyway, after revoking access, every time I ran google-drive-ocamlfuse it would hang the terminal window, and other file-system related apps like pcmanfm.  Having purged and reinstalled, I think I now have it as I wanted it.
Seems it could use some improved error handling, such as in the case that app access is revoked.

**Comment by pelya** [comment]
There seems to be no way to mount a backup folder created by Google Drive desktop app, such as this:

![Screenshot_20230704_222229](https://github.com/astrada/google-drive-ocamlfuse/assets/155328/a43e8c5b-dc61-4300-8385-87c9d455d964)

When I'm setting `root_folder` option with the folder hashcode from URL in the config file, it just uses Google Drive root folder.
However I have managed to solve this by sharing this backup folder with another Google account, then mounting it from this other account, the folder is present inside `.shared`.
